### ISSUE TITLE
When using pipelines, a bad ID is not easy to understand by the user

### ISSUE THREAD

**Issue by joncodo** [apache/incubator-devlake#1046]
We need a better backend error displayed to the UI to tell the user that the ID was not right and that they should fix it.
![Screen Shot 2022-01-07 at 9 51 35 AM](https://user-images.githubusercontent.com/3011407/148553531-91243a20-1cdd-40c3-b891-09cd4a8543fa.png)

**Comment by joncodo** [comment]
The error handled on the backend should return an error code and the front end should display a friendly error message of "It looks like your Jira Board Id was not found. Are you sure you entered the right id? To see how to find this id, look here :)"

**Comment by e2corporation** [comment]
For specific or fatal errors we could easily pop up a Toast notification directly from the Pipeline Manager Hook so the user can see it right away.

**Comment by klesh** [comment]
I agree that the error message here is not user-friendly.
The thing is the error message can be anything, it is impossible to cover every single case with one shot.
We should/would keep improving it as we go.
Closing the issue, and feel free to open new issues for specific unfriendly error messages
