### ISSUE TITLE
`feat` Pipelines - DELETE Pipeline Run/Log support

### ISSUE THREAD

**Issue by e2corporation** [apache/incubator-devlake#1081]
## Description
As a Developer I need the ability to **Delete** a Run log at my discretion.

- [ ] Implement DELETE API Route
- [ ] Add Delete Action to Pipelines Management Table
- [ ] Test Delete Workflow

**Comment by klesh** [comment]
@Startrekzky Please take a look at this

**Comment by Startrekzky** [comment]
@klesh Do we still need to do this in the new config-ui?

**Comment by klesh** [comment]
@Startrekzky I don't thinkso.
@e2corporation As a developer, I would truncate the pipelines/tasks tables.
Close it now, feel free to re-open
