### ISSUE TITLE
Scrape recent metrics from the server

### ISSUE THREAD

**Issue by warren830** [apache/incubator-devlake#1095]
## Description
According issue #931 , we can add a feature to get recent data since a fix time through plugins

## Describe the solution you'd like
We can use api links as below 
1. github issue api link: https://docs.github.com/en/github-ae@latest/rest/reference/commits
- since:   Only show notifications updated after the given time. This is a timestamp in ISO 8601 format: YYYY-MM-DDTHH:MM:SSZ  
2. gitlab merge request api link: https://docs.gitlab.com/ee/api/merge_requests.html
- created_after: Return merge requests created on or after the given time. Expected in ISO 8601 format (2019-03-15T08:00:00Z)
- updated_after:  Return merge requests updated on or after the given time. Expected in ISO 8601 format (2019-03-15T08:00:00Z)
But still need more work to verify if we can get right data by the params

## Has the Feature been Requested Before?
issue #931

**Comment by klesh** [comment]
@yumengwang03 Aah, I'm starting to feel sorry for u...

**Comment by Startrekzky** [comment]
Close it as it duplicates with #931
