### ISSUE TITLE
When we say "Users" do we mean "Human Users"?

### ISSUE THREAD

**Issue by kevin-kline** [apache/incubator-devlake#1099]
## Question
When we say "Users" do we mean "Human Users"?

When we collect users from Jira, we get two types. 
1. accountType = "app" (non-human)
2. accountType = "atlassian" (human)

In the domain layer, we are converting both types into users, without distinguishing between the two. Is this what we want, or do we want only human users?

## Screenshots
Example 1: users in the domain layer include slack and trello.
![image](https://user-images.githubusercontent.com/27032263/150539474-38536c3a-bcd8-4545-b536-299d84d3648c.png)

Example 2: Users in Jira can be "app" or "atlassian"
![image](https://user-images.githubusercontent.com/27032263/150539881-cd6b4318-48c0-4402-a857-cbb5c1261779.png)

@Startrekzky

**Comment by klesh** [comment]
@Startrekzky Please take a look

**Comment by Startrekzky** [comment]
Please look at the clarification and solution of `accounts`, `users`, `teams` in #2361
