### ISSUE TITLE
API to list out what `subtasks` a plugin can provide

### ISSUE THREAD

**Issue by klesh** [apache/incubator-devlake#1411]
## Description
Currently, users have to learn plugin subtasks by reading source code so they can customize what `subtasks` to run on `config-ui`, this is not very user friendly.

## Describe the solution you'd like
backend to provide an api like `/plugins` which returns all available plugins, and their `subtasks`

## Has the Feature been Requested Before?
No

**Comment by Startrekzky** [comment]
Need design @yumengwang03

**Comment by keon94** [comment]
@klesh I can take this one.

**Comment by keon94** [comment]
bump

**Comment by keon94** [comment]
@klesh is this still slotted for v0.15? I haven't been able to get around to it yet due to my involvement in the Python framework work.

**Comment by klesh** [comment]
@keon94 no problem, this is not a critical task, we can postpone it.

**Comment by keon94** [comment]
@klesh Could you provide a sample JSON of the output body you'd like to see for this API? Should it just be a list of names like ["collectAccounts", "extractAccounts", ...]

**Comment by klesh** [comment]
@keon94 I think we can output more, all meta info should be returned including `enabledByDefault`, `description` and `domainTypes`.

I think it would be helpful if users could see these information in `Advanced Mode`. @hezyin @mintsweet

**Comment by klesh** [comment]
I think it should look like the following:
```
[
    {
        "plugin": "github",
        "subtasks": [
            {
                "name": "collectApiIssues",
                "description": "...",
                ...
            },
            ...
        ],
        ...
    }
]
```

**Comment by hezyin** [comment]
@klesh @keon94 Hey guys, can you help me better understand who are the users of this API and when/how do they use this API?

**Comment by klesh** [comment]
@hezyin , as mentioned in the quoted thread, it would be helpful for Advanced Users if `config-ui` could adopt and display the info accordingly.

Secondly, as we move forward, some users might choose to stay on an older version of devlake, it would be helpful for them to perform some Advanced Tasks without too much digging.

Lastly, users or config-ui can be more flexible with the meta information. i.e. to rerun all `extractors` and `converters` after changing `transformation rule` without `collectors` with scripts or clicks. (select all subtasks that not start with `collect` )

> @keon94 I think we can output more, all meta info should be returned including `enabledByDefault`, `description` and `domainTypes`.
> 
> I think it would be helpful if users could see these information in `Advanced Mode`. @hezyin @mintsweet

**Comment by Startrekzky** [comment]
Tracked in #5920
