### ISSUE TITLE
rename `tasks` field from `pipeline` and move it to higher level

### ISSUE THREAD

**Issue by klesh** [apache/incubator-devlake#1412]
## Description

Currently, we can customize what `subtasks` to run for a particular plugin:

```json
[
  [
    {
      "plugin": "github",
      "options": {
        "repo": "lake",
        "owner": "merico-dev",
        "tasks": ["convertCommits"]
      }
    }
  ]
]
```
and since we had move `subtasks` execution from `plugin`  to `framework`, this schema doesn't make sense anymore

## Describe the solution you'd like

rename `tasks` to `subtasks` and move it to outer level
```json
[
  [
    {
      "plugin": "github",
      "subtasks":  ["convertCommits"]
      "options": {
        "repo": "lake",
        "owner": "merico-dev"
      }
    }
  ]
]
```

## Has the Feature been Requested Before?
No

**Comment by klesh** [comment]
document is also needed

**Comment by abeizn** [comment]
assign to me. thanks

**Comment by abeizn** [comment]
@e2corporation Solved by https://github.com/apache/incubator-devlake/pull/2057, but configure-ui needs to be adapted.
the subtasks is missing.
1. Here you can see the execution parameters
![Uploading image.png…]()

![image](https://user-images.githubusercontent.com/101256042/171552371-e7e033d0-9cb6-4e98-b401-2ffb28726d93.png)

2. into advanced mode, you can see:
![image](https://user-images.githubusercontent.com/101256042/171552501-c5ebdf41-9a1d-46c0-90bf-69cf049174c6.png)
