### ISSUE TITLE
More helpful error message when pipelines fail

### ISSUE THREAD

**Issue by hezyin** [apache/incubator-devlake#1447]
## Description

I created a Github pipeline but misspelled the project name, and got the following error message. The error message is a bit raw and not end-user friendly.

<img width="2534" alt="Screen Shot 2022-04-06 at 4 21 13 PM" src="https://user-images.githubusercontent.com/2908155/162089974-cac70fe5-7266-4e7a-8028-4b84f80a93b4.png">

## Describe the solution you'd like

Ideally, the error message would tell me the project doesn't exist

**Comment by klesh** [comment]
Plan of attack:
1. detect the error message to see if it contained "message not found"
2. wrap it with a more friendly message like "please check if the requested URL exists"

**Comment by yumengwang03** [comment]
Also need to add error message in the new Config UI.

**Comment by likyh** [comment]
OK, I'll add some detail log for it.

**Comment by Startrekzky** [comment]
This issue has been paraphrased and will be resolved in #2724
