### ISSUE TITLE
DevLake support different database systems

### ISSUE THREAD

**Issue by klesh** [apache/incubator-devlake#1547]
## Description
Sometimes, for Advanced Users, they likely want to integrate DevLake to their existing database, it is better for DevLake to support different database systems other than `mysql`.
Theoretically, we don't need to do much since we are using `gorm`, the problem mainly on `testing` and `verification`

The first dbs to be support: `postgres`

## Describe the solution you'd like
Maybe we should implement some automated mechanisim to help us test against different database systems

- [x] devlake framework itself supports postgres #1705 
- [x] dbt plugin supports postgres #1544 

## Has the Feature been Requested Before?
No

**Comment by hezyin** [comment]
Closing now since all subtasks are done.
