### ISSUE TITLE
Config UI Create a Pipeline: GitLab Project ID and Jira Board ID fields should only allow a single input value

### ISSUE THREAD

**Issue by hezyin** [apache/incubator-devlake#1659]
## Describe the bug

We've updated the instructions for these fields (GitLab Project ID and Jira Board ID) but they still allow multiple input values. We should probably switch to a basic text input field for them.

<img width="615" alt="Screen Shot 2022-04-17 at 10 13 55 PM" src="https://user-images.githubusercontent.com/2908155/163760280-ea6ba2de-076a-440a-8f46-ef56bd009ca6.png">

**Comment by Startrekzky** [comment]
Need design @yumengwang03

**Comment by warren830** [comment]
will be designed by @yumengwang03 in another issue

**Comment by klesh** [comment]
Will be addressed by the New ConfigUI flow
