### ISSUE TITLE
Remove outdated fields from `JiraIssue`

### ISSUE THREAD

**Issue by klesh** [apache/incubator-devlake#1711]
## Description
Previous, we added `changelog_update` `remotelink_updated` to `jira_issues` table for differential sync.
This is not elegant, because it creates unneccessary data dependency between tables, plus, with new `api_collector` approach, those fields were actually abandoned

## Describe the solution you'd like
1. Remove those fields
2. Go through related `subtasks` to clean up the references like `jira_changelog_collector` is still refering `changelog_updated` but not actually using it.

## Has the Feature been Requested Before?
No

**Comment by keon94** [comment]
I'll take this one.

**Comment by klesh** [comment]
Happy Coding 👍

**Comment by klesh** [comment]
@keon94 Sorry, should have informed you earlier.
This approach is proven unreliable by @mindlesscloud lately, have to close it for now, feel free to re-open and discuss.
