### ISSUE TITLE
Improve the configuration flow

### ISSUE THREAD

**Issue by Startrekzky** [apache/incubator-devlake#1725]
## Goal
To decrease the drop-off rate of configuration. To help users quickly connect to a data source, set data scope and data transformation rules, and create pipelines to (regularly) collect data, and see pre-built dashboards.

## Describe the solution you'd like
See detailed solutions in [#1700](https://github.com/merico-dev/lake/issues/1700#issuecomment-1107796146)

## Describe alternatives you've considered
An easy way to estimate the drop-off rate is to count the `No. of clicks`, `No. of scenario switching`, `No. of fields to populate` during the flow.
For instance, a user who wants to collect full GitHub data and set up recurring plans by following this [guide](https://github.com/merico-dev/lake/blob/main/docs/github-user-guide-v0.10.0.md) needs about 
- 17 clicks
- 7 scenario switching. Eg. GitHub connection configuration page -> README; GitHub connection configuration page -> Pipeline page; Pipeline page -> a new pipeline page, etc
- 11 required fields and 9 optional fields to populate

**Comment by klesh** [comment]
will be addressed by #1862
