### ISSUE TITLE
Add pr comments and issue comments to the domain layer

### ISSUE THREAD

**Issue by Startrekzky** [apache/incubator-devlake#1746]
## Why
1. 'Issue comments' can be used for metrics such as 'issue response time'
2. 'PR comments' can be used for metrics such as 'PR response time' and 'PR review round'

## Subtasks

- #1758 (v0.11.0)
- #1759
- #1760

## How
Please refer to the [domain layer schema](https://www.devlake.io/docs/DevLakeDomainLayerSchema)

**Comment by klesh** [comment]
According to table from #1500
![image](https://user-images.githubusercontent.com/61080/165259901-f21df327-70fb-4f73-ad06-bc91067222a7.png)

We already have them in our Domain Layer.
Do u mean we ought to collect data from data source and convert them to domain layer?

**Comment by klesh** [comment]
Closed. It will be addressed by sub-issues.
