### ISSUE TITLE
Convert Jira's issue comments to the domain layer

### ISSUE THREAD

**Issue by Startrekzky** [apache/incubator-devlake#1759]
## Describe the solution you'd like
- [ ] Convert Jira issue comments to the domain layer's [issue_comments](https://www.devlake.io/docs/DevLakeDomainLayerSchema)

## Belongs to
#1746

**Comment by moshe** [comment]
Any progress on this one? Seems like JIRA issues collected to `_raw_jira_api_issues`, not not extracted into `issue_comments`

**Comment by Startrekzky** [comment]
> Any progress on this one? Seems like JIRA issues collected to `_raw_jira_api_issues`, not not extracted into `issue_comments`

Hi @moshe, it's not implemented yet. I'm thinking of adding a feature to let users choose what entities to collect, which is tracked in #5920 . Please stay tuned.
