### ISSUE TITLE
Convert GitLab's pr comments to the domain layer

### ISSUE THREAD

**Issue by Startrekzky** [apache/incubator-devlake#1760]
## Describe the solution you'd like
- [ ] Convert Gitlab MR comments to the domain layer's [pull_request_comments](https://www.devlake.io/docs/DevLakeDomainLayerSchema)

## Belongs to
#1746

**Comment by klesh** [comment]
`pr_comments` in Gitlab was named `GitlabMergeRequestNote`, and converted to `Note`

**Comment by warren830** [comment]
> Actual: `pr_comments` in Gitlab was named `GitlabMergeRequestNote`, and converted to `Note` Expected: `GitlabMergeRequestNote` to be converted to `PullRequestComments`

This has been done before:
![image](https://user-images.githubusercontent.com/39366025/173343278-c613ad8c-8463-4bf5-8eae-607e116454aa.png)
