### ISSUE TITLE
A plugin to host enrichers that depend on Domain Layer Data only such as `issue_changelog_enricher`

### ISSUE THREAD

**Issue by klesh** [apache/incubator-devlake#1778]
## Description

Currently, we have `sprint_issues_converter` from `jira` plugin who takes in `jira_changelog` and produces `sprint_issues` `issue_status_history` `issue_assignee_history` and `issues_sprint_history`. In another word, it consumes **Tool Layer Data** and produces **A set of Domain Layer Data to multiple tables**.
It poses following problems:

1. To support TaPD, we have to replicate the logic for TaPD, and we can easily foresee there will be more in the future.
2. The naming `sprint_issues_converter` is confusing, firstly, this is a enricher by our definition. secondly, the name looks like it is converting `sprint_issues` relationship into Domain Layer, but no, not at all.
3. `sprint_issues` looks like a relationship table, but it is not, it contains `removed` relationship. when it was `removed` or `added`

## Describe the solution you'd like
1. Jira/TaPD convert their `changelog` into Domain Layer `changelog`, and create another plugin contains a enricher who would take Domain Layer `changelog`, and produces enriched data accordingly.
2. Name the enricher from previous step `changelog_enricher`, because, the input is single, and the outputs are multiple, and may increase in the future, it makes sense to name enricher by the input.
3. The existing `sprint_issues` table to be renamed to sth like `sprint_issues_history` to avoid confusion. @Startrekzky @narrowizard @hezyin 

## Has the Feature been Requested Before?
No

**Comment by klesh** [comment]
Close this issue since it was taken over by  @narrowizard

**Comment by narrowizard** [comment]
I think we still need to do this one:  
> Jira/TaPD convert their changelog into Domain Layer changelog

**Comment by klesh** [comment]
> 

We had jira changlelog converted to domain layer already, Do you mean TaPD only?
