### ISSUE TITLE
Please offer a normalized completion_time in Issue Tracking Domain to make sure issues from different tools have the same end time

### ISSUE THREAD

**Issue by leglars** [apache/incubator-devlake#1796]
## Description
In Jira, there are two different fields can prove an issue is completed: issue_status and resolution_date. However, resolution_date is NOT an obvious field in the issue view, which is not a form field showing within field list. Also, it is NOT updated automatically when an issue status transfers to "completed", because this transformation only works when the target status is the "END" of workflow. On the contrary, in the real world, all statuses belonged to completed status category seem as completion status. This conflict will cause parts of "completed" issue without resolution_date.

At the same time, different tools have different definition of End. The philosophy of domain layer attempts to normalize this differentiation so that the users don't need to take care of this details.

## Describe the solution you'd like
Therefore, the issue-tracking-domain should have a field, like completion_time, to uniform the definition of issue completion. And the specific calculation for each tool should be handled by each plugin or data transformation process.

**Comment by klesh** [comment]
@narrowizard Seems like this bowl belongs to you, please take it, you are welcome.

**Comment by narrowizard** [comment]
LGTM, I'll try to do it.
