### ISSUE TITLE
Implement a data catalog for easy data exploration

### ISSUE THREAD

**Issue by hezyin** [apache/incubator-devlake#1834]
## Why data catalog

1. Knowing what data is there and its meaning is essential for users to consume/analyze the data
2. Right now, we manually maintain the [domain layer schema](https://www.devlake.io/docs/DataModels/DevLakeDomainLayerSchema) doc, which is challenging to keep all the details up-to-date. Ideally, we should automate this with proper data catalog tooling.

## A Rough Proposal

1. A protocol for a plugin developer to describe the meaning of each column of the data they produce
2. A mechanism to auto-refresh the data catalog whenever a plugin gets updated
3. An easy-to-use interface for users to explore the data

**Comment by Startrekzky** [comment]
@hezyin @klesh @yumengwang03 Here are several open-source data catalogs we can look at:
1. Linkedin's data catalog: [Datahub](https://github.com/datahub-project/datahub.) / [Demo](https://demo.datahubproject.io/). It could manage varieties of data assets, such as DB schema, dashboards, glossary, etc. It supports [MySQL](https://datahubproject.io/docs/metadata-ingestion/#installing-plugins), but it doesn't seem to support Grafana dashboards.
2. Lyft's data catalog: [amundson](https://github.com/amundsen-io/amundsen/). It also supports MySQL, but doesn't support Grafana.
3. [Apache Atlas](https://github.com/apache/atlas)
4. [Low priority, don't research on this if there's no time] [Netflix/metacat](https://github.com/Netflix/metacat)

**Comment by keon94** [comment]
@klesh I can take this one

**Comment by keon94** [comment]
@Startrekzky can you help me understand the "user-consumption" requirement? Do you want something that can for example map column X of table Y to all Grafana dashboards that use it?

**Comment by keon94** [comment]
bump

**Comment by Startrekzky** [comment]
Hi @keon94 
Recently, I received some users' requests to help customize their dashboards. I noticed 2 major obstacles:
1. They didn't know how Grafana works, even though I've added some description here. Thus, they were not aware of the existence of the domain data model, not mentioned to write SQL based on it. 
![image](https://user-images.githubusercontent.com/14050754/204274083-31ce4096-8eb9-4b52-894c-2cba4b526878.png)

2. After I told them how Grafana worked (to query data from DB), they still didn't know how to add a new panel. 
   a. They didn't know how to use Grafana, eg. create a new dashboard or new panel, etc. (I planned to work on this in #2248)
   b. They didn't know where to find the data model. (As a temp approach, I decided to move the data model link to the top of every dashboard)
   c. They were not familiar with writing SQL. This may be related to their positions, as both users are DevOps engineers not backend or data engineers.

Let's see if this data catalog can be helpful to both point 1, 2.b and 2.c

**Comment by keon94** [comment]
@Startrekzky Do you think a tool like SQL Workbench would get the job done? It's open-source, cross platform, easy to use and a GUI for the DB that I personally use all the time (it's vastly helpful as I'm not a SQL expert either). Also, easy to set up. Here're some screenshots of it.
![image](https://user-images.githubusercontent.com/25063936/205215354-fc05dc7a-5526-405f-b1f3-cf4c4021eb69.png)
![image](https://user-images.githubusercontent.com/25063936/205215422-7eb73144-be51-4793-b2b9-4f8fd08293f2.png)
![image](https://user-images.githubusercontent.com/25063936/205215556-b5fe7d37-a436-413b-b1bf-3f7a33ca3fe6.png)

**Comment by Startrekzky** [comment]
@keon94 Yes. I'm using Navicat to do this and I didn't have such problems. My comment was to describe potential problems a user might encounter. These problems could be the use case for reference when we start designing this feature in the future.

**Comment by Startrekzky** [comment]
I don't think this needs to be tackled for now. I'll close it and feel free to reopen if you have valid reason.
