### ISSUE TITLE
Data quality report

### ISSUE THREAD

**Issue by warren830** [apache/incubator-devlake#1840]
## Description
Can we show users their data quality such as below:
1. What percentage of issues/prs have labels to indicate itself is a bug or feature and its component
2. What percentage of prs has ‘closes issue’ in the body

Main idea is to show how their development process obey standard rules

## Describe the solution you'd like
Once users finished tasks for a specific data source, we can calculate the data quality and give some general suggestions

## Has the Feature been Requested Before?
Please link any other

**Comment by klesh** [comment]
Interesting idea, would you like to take a look at this?
