### ISSUE TITLE
Postgres Support: some SQL include functions that are only available in Postgres

### ISSUE THREAD

**Issue by mindlesscloud** [apache/incubator-devlake#1842]
## Describe the bug
The function `GROUP_CONCAT` is not available in Postgres

## Screenshots
![image](https://user-images.githubusercontent.com/8455907/167666518-14e77703-5aef-4b53-8815-a775d0a69bf4.png)
![image](https://user-images.githubusercontent.com/8455907/167666572-44772351-e994-400d-ab0b-54f42c3884c9.png)

**Comment by klesh** [comment]
resolved
