### ISSUE TITLE
config-ui: jira connections modify & delete api errors `v0.11.0`

### ISSUE THREAD

**Issue by e2corporation** [apache/incubator-devlake#1843]
## ⚠️ Config-UI / Data Integrations / JIRA / Configure & Delete Connection
Modifying and Deleting **JIRA** Connection sources functionality on UI has degraded, Backend API may require modifications.

```json
{
  "success": false,
  "message": "invalid encKey"
}
```

## Screenshots
<img width="1229" alt="Screen Shot 2022-05-10 at 12 23 12 PM" src="https://user-images.githubusercontent.com/1742233/167676867-5250ac8e-e6fd-4201-a02a-d0fbd5fc09ee.png">
<img width="1054" alt="Screen Shot 2022-05-10 at 12 22 49 PM" src="https://user-images.githubusercontent.com/1742233/167676878-79134147-6d4e-4f67-984f-df5d32a7a034.png">

**Comment by abeizn** [comment]
i checked too, it works.

![image](https://user-images.githubusercontent.com/101256042/167990981-3e2cb724-8a2c-46aa-a165-9714143f9a57.png)
![image](https://user-images.githubusercontent.com/101256042/167991010-f7877fed-9069-4a2c-a0ba-8fff0b391715.png)
![image](https://user-images.githubusercontent.com/101256042/167991047-2760928d-3bc4-4762-97fb-245d2a1a14a8.png)
![image](https://user-images.githubusercontent.com/101256042/167991074-e9dd5643-61a5-44a0-91bc-4e17997d74c1.png)

**Comment by klesh** [comment]
deletion should not need decryption.

**Comment by klesh** [comment]
@mappjzc
