### ISSUE TITLE
config-ui: pipelines - cancel running pipeline not successful

### ISSUE THREAD

**Issue by e2corporation** [apache/incubator-devlake#1844]
## Config-UI / Pipelines / CANCEL Pipeline Run
The **Cancel** feature of a running pipeline is not operating as expected, when a pipeline run is cancelled it's record `status` should be set to `TASK_FAILED` or a new state `TASK_CANCELLED` so the UI can be updated. 

## Screenshots
<img width="1185" alt="Screen Shot 2022-05-10 at 12 12 09 PM" src="https://user-images.githubusercontent.com/1742233/167678534-cf191b01-c0ef-43c2-a0d6-0774efeb7952.png">

**Comment by mindlesscloud** [comment]
> @klesh @warren830 Please investigate if this is a valid issue on your end and if it's needed for this iteration. Thanks!

@e2corporation  Yes, this is a valid issue. In some cases, DevLake responds very slowly

![image](https://user-images.githubusercontent.com/8455907/167884647-3dd23e62-4892-4b17-906d-c36dc9d7773d.png)

**Comment by warren830** [comment]
> @klesh @warren830 Please investigate if this is a valid issue on your end and if it's needed for this iteration. Thanks!

Ok, will fix it today

**Comment by klesh** [comment]
create a unit-test to cover this case
