### ISSUE TITLE
Several development documents need updated

### ISSUE THREAD

**Issue by skyleaworlder** [apache/incubator-devlake#1848]
## Documentation Scope
Briefly explain what is the documentation is referencing (main README, a specific plugin etc.)

* [refdiff installation (about lack of dependency)](https://github.com/merico-dev/lake/tree/main/plugins/refdiff#development)
* [link label](https://github.com/merico-dev/lake/blob/main/CONTRIBUTING-zh-CN.md)
* [PluginEntry definition position](https://github.com/merico-dev/lake/tree/main/plugins)

## Describe the Change
A clear and concise description of what is being updated in the documentation

### 1. refdiff installation

I got an error when using cmake to build refdiff on my wsl(Ubuntu 20.04). It notices me that libssl-dev is needed for libgit2:

```text
make[2]: *** No rule to make target '/usr/lib/x86_64-linux-gnu/libssl.so', needed by 'libgit2.so.1.3.0'.  Stop.
make[1]: *** [CMakeFiles/Makefile2:204: src/CMakeFiles/git2.dir/all] Error 2
```

And this problem occur due to `libgit2/build/src/CMakeFiles/git2.dir/build.make`:

```makefile
libgit2.so.1.3.0: /usr/lib/x86_64-linux-gnu/libssl.so
```

So I'd like to add the following dependency into [requirements](https://github.com/merico-dev/lake#requirements):

```shell
sudo apt-get install libssl-dev
```

### 2. link label

A simple Markdown syntax mistake.

### 3. PluginEntry definition position

This documentation has been discussed in #1845 . There is still another problem:

```go
func (plugin YourPlugin) Execute(options map[string]interface{}, progress chan<- float32) {
  // ignore some code
  // Export a variable named PluginEntry for Framework to search and load
  var PluginEntry YourPlugin //nolint
}
```

Variable `PluginEntry` should be exported, but it's in `Execute` now. Though `Execute` is going to be deprecated in #1845 , exporting a variable as entry of plugin is still used to enable go plugin when calling Open and LookUp.

**Comment by Startrekzky** [comment]
Thanks @skyleaworlder , we're trying to figure out permission problem and will get it merged asap.
