### ISSUE TITLE
Config UI for v1.0 - stages of development breakdown

### ISSUE THREAD

**Issue by yumengwang03** [apache/incubator-devlake#1862]
### Overview
Now that we have reached an agreement on the new Config UI design, it's time to dissect this big project into doable tasks that could be ideally completed within three sprints. 
Accordingly, there will be three stages to approach the new design:
1. The step-by-step creation of blueprints
2. The blueprint detail page
3. The new Data Connections page
The reason for this dissection is because these three features are relatively isolated and will cause minimum impact on one another or the current Config UI features. The detailed implementation of each stage is unpacked as follows:

### Stage I - The step-by-step creation of blueprints
**Priority: High**
I suggest we start from this feataure because it is the core user flow of the new Config UI, therefore having the most potential to drastically improve user experience. When completed, the step-by-step creation pages should replace the current "Create Pipeline Runs" page.
Except for the brand new UI elements, I think the following parts can be reused for the first iteration:
- In Step 1 - Add Data Connections, use the current "Adding a connection" page (only applicable for Jira for now) for the dialog for creating a new connection.
- In Step 4 - Set Sync Frequency, the entire page can reuse the current "Automate Pipeline" dialog.
- The Advanced Mode can reuse the current version with some minor modifications.
As for the Blueprint Landing page, we can also reuse the "Pipeline Blueprint" page for this iteration with the "Create a New Blueprint" CTA.
In this stage, the menu item "Pipelines" should be renamed to Blueprints. The sub-menu items "Create Pipeline Runs" and "All Pipeline Runs" should be removed. However, the All Pipeline Runs page will remain and be able to be accessed from the Blueprint Landing page.
<img width="937" alt="Screen Shot 2022-05-17 at 2 38 55 PM" src="https://user-images.githubusercontent.com/9535430/168745431-7e06f0bf-5c52-462a-97a5-62a423565c03.png">

### Stage II - The blueprint detail page
**Priority: Medium**
Currently we only have the pipeline detail page, which should be replaced by the blueprint detail page. The blueprint detail page can be further broken down into two sub-stages:
1. Showing basic information, the status of the current run and all historical runs and their logs, without allowing users to modify the blueprint
2. CTAs that allow users to modify the blueprints (this can be optional/for later iterations if our progress is delayed)

Parts that can be reused for this iteration:
- The pipeline activity UI can be inserted for the historical run details.
<img width="1029" alt="Screen Shot 2022-05-17 at 2 42 07 PM" src="https://user-images.githubusercontent.com/9535430/168745878-5da58d94-5b6e-41b3-8e2b-9c2d1c229a0a.png">
(The above screenshot is only for reference and not the final design.)

### Stage III - The new Data Connections page
**Priority: Low**
Based on the actual progress of the previous two stages, I think this stage can be optional for the goal by the end of this bi-month, because it's basically an optimization of the current feature.
<img width="906" alt="Screen Shot 2022-05-17 at 2 40 37 PM" src="https://user-images.githubusercontent.com/9535430/168745787-b3ea1a5e-c345-437a-b030-abc902a342a3.png">

### A few things (especially potential risks) to discuss
- Whether we should add the features of each stage on top of the current Config UI without breaking anything, or we should develop new features in silos first and later ship them altogether, remains as a question for discussion.
- Because quite a substantial amount of features are completely new, we should expect lots of bugs later in the development process, which are likely to delay our planned progress.

**Comment by Startrekzky** [comment]
Done.
