### ISSUE TITLE
PKCS7UnPadding panic with empty origData

### ISSUE THREAD

**Issue by mappjzc** [apache/incubator-devlake#1866]
## Describe the bug
![image](https://user-images.githubusercontent.com/2921251/168048652-458dea8a-ce54-4dcc-833a-42123a460718.png)
![image](https://user-images.githubusercontent.com/2921251/168048850-52a74e06-6eb5-4060-aa64-a900a3843016.png)

If give PKCS7UnPadding an empty data, it will panic because visit the -1 index.

## To Reproduce
1. Set the BaseAuth as empty witch would be Decrypt
2. debug to run it.

## Expected behavior
Don't panic even for empty data.

**Comment by klesh** [comment]
Tolerate empty data. Do not panic.
