### ISSUE TITLE
refdiff (calculateIssuesDiff) is incompatible with postgres

### ISSUE THREAD

**Issue by abeizn** [apache/incubator-devlake#1869]
## To Reproduce
1. run github plugin (wechaty/wechaty)
2. run gitextrator plugin(wechaty)
3. run refdiff (Calculate issues diff)

## Screenshots
![image](https://user-images.githubusercontent.com/101256042/168073222-7e52e08a-f5f3-48a3-98b5-69813be3f053.png)

**Comment by klesh** [comment]
1. clean up data
2. create composite pk
