### ISSUE TITLE
The github plugin failed to collect tidb on postgres.

### ISSUE THREAD

**Issue by abeizn** [apache/incubator-devlake#1870]
## Describe the bug
postgres unsupported Unicode escape sequence.

## To Reproduce
1. run github by (pingcap/tidb) 
2. subtask collectApiIssues error occured

## Screenshots
![image](https://user-images.githubusercontent.com/101256042/168076584-fcb63960-274d-4f5d-9c3d-a2b345f5b2ec.png)

**Comment by klesh** [comment]
change type to `text`
