### ISSUE TITLE
After install devlake,  when I go to ip:4000, but  see nothing

### ISSUE THREAD

**Issue by matthewxuda** [apache/incubator-devlake#1878]
## To Reproduce
1. Go to http://192.168.1.182:4000/
2. See nothing

## Screenshots
![image](https://user-images.githubusercontent.com/5927005/168459505-35b13c7e-effd-4b1e-8620-cfc08bd6257c.png)

![image](https://user-images.githubusercontent.com/5927005/168459452-6e1a9a75-f33c-4be1-b62c-3a30f3061b86.png)

3.  Go to http://192.168.1.182:80/
4. click "[研发环境控制台]",  show 404
![image](https://user-images.githubusercontent.com/5927005/168459690-7e65588c-07fd-4688-80eb-c603c8ebc4bd.png)
![image](https://user-images.githubusercontent.com/5927005/168459712-14164089-f8fa-44c2-ab7d-d88c8bf4c81b.png)

use

**Comment by narrowizard** [comment]
Seems you are visit 4000 port from LAN. Try to change the listening address from `127.0.0.1:4000` to `0.0.0.0:4000`.  

> https://github.com/apache/incubator-devlake/blob/3f950c95e5c48ca463c240c31a8f74a782ecd6fc/docker-compose.yml#L68

**Comment by matthewxuda** [comment]
thanks ，I can see the page :), but can't connect jenkins , can you help me 

![image](https://user-images.githubusercontent.com/5927005/168521264-756c6e36-b685-4a39-944c-bb1cd525c43b.png)

**Comment by Startrekzky** [comment]
> thanks ，I can see the page :), but can't connect jenkins , can you help me
> 
> ![image](https://user-images.githubusercontent.com/5927005/168521264-756c6e36-b685-4a39-944c-bb1cd525c43b.png)
> 
> use username and password can login it ![image](https://user-images.githubusercontent.com/5927005/168524903-fd63269f-84cd-4696-88cf-05a9f3a6bc6e.png)
> 
> and I generate api token with the password, and it still can't connect ![image](https://user-images.githubusercontent.com/5927005/168529407-4d32e941-75d3-4d73-9c2e-f64992d32c02.png)

It doesn't require Jenkins API, the username and password will do. May I have the version of Jenkins?

**Comment by matthewxuda** [comment]
![image](https://user-images.githubusercontent.com/5927005/168573365-7077c6c8-5fb7-4d09-9383-2b5916321da1.png)

**Comment by warren830** [comment]
> ![image](https://user-images.githubusercontent.com/5927005/168573365-7077c6c8-5fb7-4d09-9383-2b5916321da1.png)

Can you send a request to jenkins server using curl like the following:
curl --location --request GET --X GET 'http://192.168.1.181:30180/' \
--header 'Authorization: Basic xxxx' 

`xxxx` should be your username:password encoded by base64

You can use this website to get encoded basic auth token: https://www.base64encode.org/

**Comment by klesh** [comment]
@matthewxuda Looks like your jenkins server is not working...Wild guest, your jetty server is blocking request with unexpected `Authorization` header... You may want to consult your IT or Devops guys to figure out why.

**Comment by matthewxuda** [comment]
can see the jenkins process in docker, is that mean jenkins server is working , right?
![image](https://user-images.githubusercontent.com/5927005/168625252-e6f0213e-3491-42d3-b220-c3256c07e8c4.png)

**Comment by klesh** [comment]
@matthewxuda  this is related to jenkins setup, subject that we dont fully understand, would you mind to join our slack group? Our Devops colleague may provide further help there.

**Comment by matthewxuda** [comment]
thanks a lot, how to join the slack group

**Comment by klesh** [comment]
@matthewxuda Sorry, forgot to mention, it is on the bottom of our project main readme
https://github.com/apache/incubator-devlake
scroll down you should able to see them
![image](https://user-images.githubusercontent.com/61080/168756551-c466a6d6-5640-44d1-add5-9e152b262829.png)

**Comment by matthewxuda** [comment]
![image](https://user-images.githubusercontent.com/5927005/168776658-4b674868-bcac-465d-8991-c6855daa279b.png)
QR code is expired，

i register slack with email , but can't login
![image](https://user-images.githubusercontent.com/5927005/168777755-650edd2b-db85-44a0-b6c7-66ab8615f923.png)

![image](https://user-images.githubusercontent.com/5927005/168777676-072d7134-47b3-4548-8534-566722d3b0e1.png)

**Comment by warren830** [comment]
> ![image](https://user-images.githubusercontent.com/5927005/168776658-4b674868-bcac-465d-8991-c6855daa279b.png) QR code is expired，
> 
> i register slack with email , but can't login ![image](https://user-images.githubusercontent.com/5927005/168777755-650edd2b-db85-44a0-b6c7-66ab8615f923.png)
> 
> ![image](https://user-images.githubusercontent.com/5927005/168777676-072d7134-47b3-4548-8534-566722d3b0e1.png)

I just updated the wechat qr code. Please scan the image below:
![image](https://user-images.githubusercontent.com/39366025/168939667-d6899e08-27e0-4db3-904d-4424a05b31f5.png)
