### ISSUE TITLE
Different reflect.Type use the same Map in batches of BatchSaveDivider. 

### ISSUE THREAD

**Issue by mappjzc** [apache/incubator-devlake#1880]
## Describe the bug
![image](https://user-images.githubusercontent.com/2921251/168609452-dcc3189b-ecae-4942-957d-0c80b6195c59.png)

the struct TestTypeA and the struct TestTypeBv are diffrent reflect.Type
but when we look at the pointer of the Map, we can see it use the same pointer.
so it made different reflect.Type use the same Map in batches of BatchSaveDivider. 

## To Reproduce
1. Go to unit test and debug the code.

## Expected behavior
Different reflect.Type should to use different Map pointer.

**Comment by klesh** [comment]
Were they all `nil` ?
