### ISSUE TITLE
Add a plugin for Trello

### ISSUE THREAD

**Issue by Startrekzky** [apache/incubator-devlake#1881]
## Description
Collect data from Trello(Cloud).

## Pre-requisites
Please make sure you have access to [Trello API](https://developer.atlassian.com/cloud/trello/rest/api-group-actions/#api-actions-id-get). The API response will be stored in the raw data layer. before applying to this issue; otherwise, it's nearly impossible to finish this task.

## Describe the solution you'd like
Add a plugin for `trello`. Please refer to other data source plugins such as [jira](https://github.com/apache/incubator-devlake/tree/main/plugins/jira) and [tapd](https://github.com/apache/incubator-devlake/tree/main/plugins/tapd). 

This plugin performs 3 major tasks:
1. Collect data from [Trello API](https://developer.atlassian.com/cloud/trello/rest/api-group-actions/#api-actions-id-get). The API response will be stored in the raw data layer.
2. 1st ETL: transform the raw data and load it into the tool layer.
3. 2nd ETL: transform the tool layer data and load it into the domain layer. As Trello is an issue tracking tool, the final data to be loaded into the domain layer are mainly [entities from issue tracking domain](https://www.devlake.io/docs/DataModels/DevLakeDomainLayerSchema#domain-1---issue-tracking)

## How to start
Please follow the doc [how to add a plugin](https://devlake.apache.org/docs/DeveloperManuals/PluginImplementation).

## Additional notes
In DevLake, there're 3 layers of storage: 
- raw data layer: tables starting with `_raw_` 
- tool layer: tables starting with `_tool_`
- domain layer: tables with no prefix

You can set up DevLake and see the tables in MySQL.

**Comment by joncodo** [comment]
I would like to tackle this one. Please approve @hezyin @Startrekzky and assign me to it :)

**Comment by hezyin** [comment]
@joncodo Thanks for volunteering for this issue, Jon. If you're interested in adding a new plugin for DevLake, would you be interested in tackling the Bitbucket plugin instead? Seems like there're more users asking for Bitbucket plugin than Trello. The issue is here: https://github.com/apache/incubator-devlake/issues/2100

**Comment by yujng** [comment]
I would like to tackle this one. Please approve @hezyin @Startrekzky and assign me to it

**Comment by klesh** [comment]
Happy coding @yujng

**Comment by warren830** [comment]
Hi @yujng , any update about this issue? I didn't find your email on your personal page, can you please send one to me: warren@apache.org

**Comment by Startrekzky** [comment]
> @hezyin @Startrekzky Hi there! Does it make sense to create a new issue or should this one be reopened? It seems that the assignee has not responded for quite a while now.

Hi @jrezzende , I just reopened it, waiting for someone to adopt it lol

**Comment by jakezhu9** [comment]
I would like to tackle this feature. Assign me plz

**Comment by jakezhu9** [comment]
I would like to tackle this one. Assign me plz

**Comment by klesh** [comment]
@jakezhu9 , happy coding 💪

**Comment by Startrekzky** [comment]
> I would like to tackle this one. Assign me plz

Can you share the 'plan of attack' before you start coding?

**Comment by jakezhu9** [comment]
I plan to finish it in the next two weeks and I'm working on it now💪
