### ISSUE TITLE
Add a plugin for Gitee

### ISSUE THREAD

**Issue by Startrekzky** [apache/incubator-devlake#1883]
## Description
Collect data from Gitee(Cloud).

## Pre-requisites
Please make sure you have access to [Gitee API](https://gitee.com/api/v5/swagger#/getV5ReposOwnerRepoStargazers?ex=no) before applying to this issue; otherwise, it's nearly impossible to finish this task.

## Describe the solution you'd like
Add a plugin for `gitee`. Please refer to other data source plugins such as [github](https://github.com/apache/incubator-devlake/tree/main/plugins/github) and [gitlab](https://github.com/apache/incubator-devlake/tree/main/plugins/gitlab). 

This plugin performs 3 major tasks:
1. Collect data from [Gitee API](https://gitee.com/api/v5/swagger#/getV5ReposOwnerRepoStargazers?ex=no). The API response will be stored in the raw data layer.
2. 1st ETL: transform the raw data and load it into the tool layer.
3. 2nd ETL: transform the tool layer data and load it into the domain layer. As Gitee is a source code management and code review tool, the final data to be loaded into the domain layer are mainly entities from [source code management domain](https://www.devlake.io/docs/DataModels/DevLakeDomainLayerSchema#domain-1---issue-tracking) and [code review domain](https://www.devlake.io/docs/DataModels/DevLakeDomainLayerSchema#domain-3---code-review).

## How to start
Please follow the doc [how to add a plugin(WIP)](url).

## Additional notes
In DevLake, there're 3 layers of storage: 
- raw data layer: tables starting with `_raw_` 
- tool layer: tables starting with `_tool_`
- domain layer: tables with no prefix

You can set up DevLake and see the tables in MySQL.

**Comment by SnowMoon-Dev** [comment]
@warren830 I will finish this feature

**Comment by warren830** [comment]
> @warren830 I will finish this feature

It's yours now, hh!
