### ISSUE TITLE
Add a plugin for Ones

### ISSUE THREAD

**Issue by Startrekzky** [apache/incubator-devlake#1884]
## Description
Collect data from Ones(Cloud).

## Pre-requisites
Please make sure you have access to [Ones API](https://ones.geotmt.com:8443/project/open-api-doc/) before applying to this issue; otherwise, it's nearly impossible to finish this task.

## Describe the solution you'd like
Add a plugin for `ones`. Please refer to other data source plugins such as [jira](https://github.com/apache/incubator-devlake/tree/main/plugins/jira) and [tapd](https://github.com/apache/incubator-devlake/tree/main/plugins/tapd). 

This plugin performs 3 major tasks:
1. Collect data from [Ones API](https://ones.geotmt.com:8443/project/open-api-doc/). The API response will be stored in the raw data layer.
2. 1st ETL: transform the raw data and load it into the tool layer.
3. 2nd ETL: transform the tool layer data and load it into the domain layer. As Ones is an issue tracking tool, the final data to be loaded into the domain layer are mainly [entities from issue tracking domain](https://www.devlake.io/docs/DataModels/DevLakeDomainLayerSchema#domain-1---issue-tracking)

## How to start
Please follow the doc [how to add a plugin](https://devlake.apache.org/docs/DeveloperManuals/PluginImplementation).

## Additional notes
In DevLake, there're 3 layers of storage: 
- raw data layer: tables starting with `_raw_` 
- tool layer: tables starting with `_tool_`
- domain layer: tables with no prefix

You can set up DevLake and see the tables in MySQL.

**Comment by yujng** [comment]
I would like to tackle this one. Please approve @hezyin @Startrekzky and assign me to it : 
最近几次Devlake会议都有进去参加学习

**Comment by yujng** [comment]
WeOpen Star

**Comment by Startrekzky** [comment]
> I would like to tackle this one. Please approve @hezyin @Startrekzky and assign me to it : 最近几次Devlake会议都有进去参加学习

Thanks @yujng so much, I'm looking forward to your PRs.

**Comment by Startrekzky** [comment]
"Ones" only supports on-premise deployment, which means this issue is more suitable for those who already have the access to an "Ones" instance.

**Comment by yumengwang03** [comment]
We still need this.

**Comment by morganchenjp** [comment]
als thumb_up for this feature request.

**Comment by morganchenjp** [comment]
> I would like to tackle this one. Please approve @hezyin @Startrekzky and assign me to it. I went to the recent community meeting for a couple of times.

Any progress on this feature ? @hezyin @Startrekzky
