### ISSUE TITLE
Translate blog `How DevLake is Up and Running` into English

### ISSUE THREAD

**Issue by Startrekzky** [apache/incubator-devlake#1885]
## Documentation Scope
Translate blog [DevLake是怎么跑起来的](https://devlake.apache.org/zh/blog/how-apache-devlake-runs/) into English and published it on the website's [blog page](https://www.devlake.io/blog).

## Solution
1. translate the doc.
2. push it into the [blog](https://github.com/apache/incubator-devlake-website/tree/main/blog) folder of website repo with the name `How DevLake is Up and Running`. 

## How to Submit a Blog?
Please follow the [guide](https://devlake.apache.org/zh/community/make-contribution/BlogSubmission/).

**Comment by klesh** [comment]
Resolved
