### ISSUE TITLE
Translate blog `Deadlock caused by ants` into English

### ISSUE THREAD

**Issue by Startrekzky** [apache/incubator-devlake#1886]
## Documentation Scope
Translate blog [使用ants引发的死锁](https://devlake.apache.org/zh/blog/deadlock-caused-by-using-ants/) into English and published it on the website's [blog page](https://www.devlake.io/blog).

## Solution
1. translate the doc.
2. push it into the [blog](https://github.com/apache/incubator-devlake-website/tree/main/blog) folder of website repo with the name `Deadlock Caused by Ants`.

## How to Submit a Blog?
Please follow the [guide](https://devlake.apache.org/zh/community/make-contribution/BlogSubmission/).

**Comment by SongDunYu** [comment]
I want to do it.

**Comment by warren830** [comment]
> I want to do it.

assigned to you

**Comment by warren830** [comment]
Waiting for pr merge
