### ISSUE TITLE
GitHub API - `IssueTypeIncident` Field breaks Test Case

### ISSUE THREAD

**Issue by e2corporation** [apache/incubator-devlake#1887]
As a side effect of the `camelCase` refactor on the Backend, the `IssueTypeIncident` field for GitHub Connection API was changed to `typeIncident` and was not properly updated elsewhere. Expected BE to respond with `issueTypeIncident` key instead.

<img width="1240" alt="Screen Shot 2022-05-16 at 7 09 08 PM" src="https://user-images.githubusercontent.com/1742233/168696932-abf12c54-0f39-4323-b71d-23cd3d65905e.png">

**Comment by e2corporation** [comment]
@klesh @warren830

**Comment by warren830** [comment]
> @klesh @warren830

Sorry man, I'll look into it
