### ISSUE TITLE
License header update

### ISSUE THREAD

**Issue by WillemJiang** [apache/incubator-devlake#1897]
## Description
Current the source code doesn't have the license header. 
We need to specify the license header as [ASF required](https://www.apache.org/legal/src-headers.html#headers).
Please note, we cannot [change the third party code's license header](https://www.apache.org/legal/src-headers.html#3party).
We also need to add [a NOTICE file](https://www.apache.org/legal/src-headers.html#notice).

**Comment by klesh** [comment]
Should have been addressed, we will wait till v0.11 released successfully and then close this issue.
Thanks for your pointer, very helpful.

**Comment by klesh** [comment]
Resolved
