### ISSUE TITLE
Extract issue(s) in Gitlab merge request

### ISSUE THREAD

**Issue by Startrekzky** [apache/incubator-devlake#1906]
## Description
Extract issue(s) in Gitlab merge request and store them to table.pull_request_issues and table.ref_issues_diff

## Describe the solution you'd like
Similar to Github's logic
1. provide configuration(in 'regex' format) to extract issues in GitLab merge request in `.env`
2. extract the issue number according to the configuration
3. store the data to table.pull_request_issues and table.ref_issues_diff

**Comment by warren830** [comment]
For gitlab, its issues might belong to either jira or gitlab. So I think the best way of this implementation is to do this job on domain layer.
But if we want to do this job on domain layer, one number might belong to two repos. Our prefix of id can solve some problems. But if issues from different repos with the same number, that also can be a problem. 
For now, if fairmarcket wants this feature eagerly, we can simply implement this in tool layer, and generate a table with only two fields(mr_number and issue_number)
