### ISSUE TITLE
Config UI hides the input value for auth token fields

### ISSUE THREAD

**Issue by hezyin** [apache/incubator-devlake#1908]
## Description

In the current implementation of Config UI, the auth tokens fields are shown in plain text when a user types in the credentials. This is problematic when DevLake evangelist demos Config UI during a live stream or community meetup. 

Can we encrypt the input values for those sensitive fields by default and provide an option for users to view the values in plain text?

**Comment by yumengwang03** [comment]
The latest design is updated here: https://github.com/apache/incubator-devlake/issues/2384

**Comment by klesh** [comment]
Already done in v0.12
