### ISSUE TITLE
Add `NOTICE` to our repo

### ISSUE THREAD

**Issue by klesh** [apache/incubator-devlake#1912]
## Description
Subtask of #1909 

## Describe the solution you'd like
Adding ~~`NOTICE.md`~~ `NOTICE` to our repo.
Sample can be found on https://github.com/apache/servicecomb-java-chassis/blob/master/NOTICE

## Has the Feature been Requested Before?
No

**Comment by likyh** [comment]
> Hey, I would like to help you by creating a ` NOTICE.md` file for you so can you describe more about it I mean how do you want it

Maybe we will delete all the file which not belong to apache open source and add a normal `NOTICE.md` ?

**Comment by losier** [comment]
Don't delete all those files let them be here just add a normal `NOTICE.md` so what you want in your md file

**Comment by klesh** [comment]
@losier Yup, that is the problem, we are not very sure what should be put into this `NOTICE.md` file. 😂. Nothing stood up AFAIK.
I think we should create a simple one, and wait for our Mentors to verify.
@losier,  would you like to take this one? just creating a simple plain empty NOTICE file would be sufficient I think.

**Comment by losier** [comment]
@klesh Done

**Comment by klesh** [comment]
@losier I don't see any PR related to this issue.

**Comment by losier** [comment]
@klesh now its their last time I have done some mistake while creating a pr sorry hehe

**Comment by klesh** [comment]
@losier Thanks for your hard work. Could you link the PR you created into this issue by simply adding #1912 in PR description.
And I notice PR #1997 , has a quite different format/content than those I proposed, why is that? I think we need a `NOTICE` that is without `.md` rather than `NOTICE.md` file to comform the ASF standard, it was my fault to say `NOTICE.md` in the description, will update it soon, sorry for that.

**Comment by losier** [comment]
Hey @klesh can you review PR #2006

**Comment by Startrekzky** [comment]
Closed as this issue has already been resolved.

**Comment by warren830** [comment]
fixed by #2070
