### ISSUE TITLE
Refactor `run` to several smaller funcs

### ISSUE THREAD

**Issue by warren830** [apache/incubator-devlake#1914]
## Description
`run` is a huge func, it's hard to do the unit test, usually we have to check if it's ok after collect all the data.

path: plugins/gitextractor/parser/libgit2.go

## Describe the solution you'd like
1. extract every `Foreach` to a single func
2. write unit test for every derived func
3. in the unit test, you should check the data source  on the website first, then compare the result of the funcs

**Comment by keon94** [comment]
I can take this one

**Comment by klesh** [comment]
@keon94  Happy Coding

**Comment by keon94** [comment]
Hi @klesh, I'm not clear on step 3. Do you not want the tests to connect to a mocked git.Repository that returns mocked objects? By the way, to mock the repo, I'll have to wrap it in an interface so we can use something like mockery on it to generate the mock. Please let me know your expectation.

**Comment by klesh** [comment]
@keon94 I'm not very sure what @warren830 meant either, maybe you can submit your PR as a draft, and let's see how can we do unit-test?

**Comment by hezyin** [comment]
@keon94 My guess for what @warren830 meant in step 3 is to verify the data correctness of the git extractor plugin after data collection. Historically, we have been comparing the number of records in the database after running the plugin with the number of records displayed on the data source's website. For example, you can check how many commits/tags are there in a project on GitHub against how many git extractor collected in the database.

**Comment by keon94** [comment]
@hezyin, okay so we'd want to do integration/manual testing for that. I'm just not sure how exactly we want to perform unit testing here as we're hitting a third party API. We'd have to mock the API calls to the repo instance if that's what we want. Do we have any instance of go-mock/mockery usage in our code-base that I can use as reference? At first glance, I couldn't find any.
@warren830 please chime in when you get a chance.

**Comment by klesh** [comment]
> @keon94 My guess for what @warren830 meant in step 3 is to verify the data correctness of the git extractor plugin after data collection. Historically, we have been comparing the number of records in the database after running the plugin with the number of records displayed on the data source's website. For example, you can check how many commits/tags are there in a project on GitHub against how many git extractor collected in the database.

That sounds like an `e2e-test` with actual git repo and database involved and all.



> @hezyin, okay so we'd want to do integration/manual testing for that. I'm just not sure how exactly we want to perform unit testing here as we're hitting a third party API. We'd have to mock the API calls to the repo instance if that's what we want. Do we have any instance of go-mock/mockery usage in our code-base that I can use as reference? At first glance, I couldn't find any. @warren830 please chime in when you get a chance.

I have a PR with mockery setup https://github.com/apache/incubator-devlake/pull/2053, but for what we want to test against this plugin, I think `e2e-test` would be a better fit, that we don't need mockery at all.

**Comment by klesh** [comment]
Closed by #2050
