### ISSUE TITLE
Add more type checks to `DecodeStruct` and `EncodeStruct`

### ISSUE THREAD

**Issue by warren830** [apache/incubator-devlake#1915]
## Description
Right now, in our `DecodeStruct` and `EncodeStruct`, we only check `string`, `int`, `int64`, `float64` inside the `switch`
It works properly for now. But we want to make these two funcs more general.

path: plugins/helper/config_util.go

## Describe the solution you'd like
1. check  all the cases  in `json.literalStore` 
2. supplement the cases we don't have in `DecodeStruct` and `EncodeStruct`
3. you can also use `reflect.string` to replace `case "string"` in `DecodeStruct` and `EncodeStruct`

## Has the Feature been Requested Before?
Please link any other

**Comment by warren830** [comment]
> i check the `DecodeStruct` and `EncodeStruct` method
> 
> * `DecodeStruct` map struct to viper config
> * `EncodeStruct` map viper config to struct
> 
> viper config support data type is:
> 
> * bool
> * int
> * string
> * int slice
> * string slice
> * map[string]interface{}
> * map[string]string
> * float64
> * interface
> 
> so the two method should support
> 
> * int slice
> * string slice
> * map[string]interface{}
> * map[string]string
> * bool

Yes, perfectly right. Do you want to take this one?

**Comment by fatelei** [comment]
ok

**Comment by fatelei** [comment]
assign to me
