### ISSUE TITLE
Lack of documentation for api_collector

### ISSUE THREAD

**Issue by warren830** [apache/incubator-devlake#1922]
## Description
`api_collector` is the core of our collector tasks. Without api_collector, we have to care about apiClient, scheduler, db and so on. Right now, we can implement collector tasks with only consideration of business.
But `api_collector` is hard to understand how to use api_collector

`api_collector` path: plugins/helper/api_collector.go

## Describe the solution you 'd like
1. understand api_collector
2. write a doc to contain the following:
> - describe how api_collector works
> - write a doc to describe how to implement collector with api_collector

**Comment by klesh** [comment]
![image](https://user-images.githubusercontent.com/61080/177673420-93db30ae-f636-41d9-9594-c82722ecdefb.png)
![image](https://user-images.githubusercontent.com/61080/177673653-b43ccf72-d987-4e0a-95e8-cd2c5988c8aa.png)

We have `godoc` for `api_collector` already, I think it is enough at this point.
Close now, feel free to re-open.
