### ISSUE TITLE
Lack of documentation for api_extractor

### ISSUE THREAD

**Issue by warren830** [apache/incubator-devlake#1923]
## Description
`api_extractor` is the core of our extractor tasks. Without api_extractor, we have to care about apiClient, scheduler, db and so on. Right now, we can implement extractor tasks with only consideration of business.
But `api_extractor` is hard to understand how to use api_extractor

`api_extractor` path: plugins/helper/api_extractor.go

## Describe the solution you 'd like
1. understand api_extractor
2. write a doc to contain the following:
> - describe how api_extractor works
> - write a doc to describe how to implement extractor with api_extractor

**Comment by phzbbbbbbbb** [comment]
Hi, @warren830!

Please assign it to me.

**Comment by warren830** [comment]
> Hi, @warren830!
> 
> Please assign it to me.

Great!

**Comment by warren830** [comment]
> Hi, @warren830!
> 
> Please assign it to me.

Hi, are you still working on this issue?
