### ISSUE TITLE
typo of jira from config-ui, maybe backend as well?

### ISSUE THREAD

**Issue by klesh** [apache/incubator-devlake#1930]
## Describe the bug
![image](https://user-images.githubusercontent.com/61080/169075045-f5e05476-2c55-47a9-866c-5379d415af9f.png)

## Expected behavior
It shoud be `endpoint`

**Comment by xgdyp** [comment]
I only find one `endPoing` after searching all files and I think only this one is left. Amazingly how it work before.

**Comment by klesh** [comment]
Aah, I'm feeling a nice vibe here.
But both of you closed your PRs, I have no PR to pick here 😂.
I would suggest @jasendo to re-open his PR because that was his first contribution to the community, Iet's show some welcome gesture for our newcomer. If that was ok for @xgdyp and @e2corporation .

**Comment by xgdyp** [comment]
Sure, no problem. @klesh
