### ISSUE TITLE
Do we need CORS for devlake api server?

### ISSUE THREAD

**Issue by klesh** [apache/incubator-devlake#1946]
## Question
![image](https://user-images.githubusercontent.com/61080/169308088-79f199d7-4d7a-4c31-9f09-d59725f86c08.png)

**Comment by e2corporation** [comment]
@klesh Yes you should need CORS, the API listens on `localhost:8080`, UI will listen on `localhost:4000` which is a different origin. Without CORS, the web browser should (and will) block all api requests to the lake api, unless that browser has cross-origin restrictions disabled, which would be insecure and not all browsers allow this option to be disabled.

**Comment by klesh** [comment]
@e2corporation This is true if config-ui requests api directly to `localhost:8080`, but we do have setup webpack proxy which forwarding api requesting, in this case, CORS is not needed.
![image](https://user-images.githubusercontent.com/61080/169328602-e1b65fa9-702f-4070-a442-afbf96ffa021.png)

and for production mode, we also have `nginx`  forwarding api requests for us, right

**Comment by e2corporation** [comment]
@klesh That is an interesting point, there is no downside to supporting CORS Options, but the best thing to do is disable CORS on your end to see if the API proxy works as expected.

**Comment by klesh** [comment]
Plan: to disable CORS, and verify if `config-ui` working correctly both in developer mode and production mode(docker-compose)

**Comment by sbdtu5498** [comment]
@klesh I am thinking of working on this issue. So for disabling the CORS part we need to put AllowCredentials = false. And then do we manually need to check whether config-ui is working properly or do we need to do automated testing for that as well.

**Comment by sbdtu5498** [comment]
Hi @klesh, I just built Devlake for all the modes after solving the previous issue. I will be taking this one. I just wanted to confirm a few things. To close the CORS functionality, we need to pul AllowCredentials to false, right, or something else. Also, to check whether DevLake is working fine in all the modes, we just need to check it manually after building it correctly.

**Comment by sbdtu5498** [comment]
Oh okay, so we need to comment out the whole CORS Config piece of code and then test it manually.
