### ISSUE TITLE
[Docs] CONTRIBUTING.md link broken on PR Template

### ISSUE THREAD

**Issue by Sync271** [apache/incubator-devlake#1956]
## Documentation Scope
PR Template

## Describe the Change
The link to CONTRIBUTING.md on the PR Template is relative: 
https://github.com/apache/incubator-devlake/blob/eae66d15d70893397c0e66e1710179926aa912e8/.github/pull_request_template.md?plain=1#L5

This works when you open the PR Template as a file but not when you access CONTRIBUTING.md though the PR Template when opening/making a PR, the link takes you to [CONTRIBUTING.md](https://github.com/apache/incubator-devlake/CONTRIBUTING.md)

**Comment by warren830** [comment]
Sorry for late reply. I think we should remove CONTRIBUTING.md and change the link to `https://devlake.apache.org/community/`. Are you interested in fix issue?

**Comment by Sync271** [comment]
Yup, you can assign this to me

**Comment by warren830** [comment]
> Yup, you can assign this to me

Nice!
