### ISSUE TITLE
the ”number“ field in pull_requests table is deprecated.

### ISSUE THREAD

**Issue by abeizn** [apache/incubator-devlake#1959]
## Describe the bug
the "number" field  is same to the "key" field, then we need to delete the number field.

## Screenshots
![image](https://user-images.githubusercontent.com/101256042/169478443-49639c85-6779-4c67-aada-207d8684ec35.png)

**Comment by klesh** [comment]
@abeizn Did we fix this already?

**Comment by abeizn** [comment]
> @abeizn Did we fix this already?

No, i will fix it in v0.12 version.
