### ISSUE TITLE
"Deploy to Kubernates" typo in README.md

### ISSUE THREAD

**Issue by nikitakoselev** [apache/incubator-devlake#1962]
## Documentation Scope
main README.md

## Describe the Change
Deploy to Kubernates => Deploy to Kubernetes

## Screenshots
![image](https://user-images.githubusercontent.com/6383738/169663291-f2fe8e94-740e-40fc-b12c-e31cd464b898.png)

## Additional context
Now let me fix it :)

**Comment by shebuel-oss** [comment]
Can you assign this to me also? @nikitakoselev

**Comment by nikitakoselev** [comment]
Thank you, @shebuel-oss , I have already resolved the issue. Could you please take a look at my pull request to double check it looks fine?

**Comment by klesh** [comment]
Hi everyone, I check #1963 , it looked alright, but I couldn't merge it since it was closed.

**Comment by warren830** [comment]
> Hi everyone, I check #1963 , it looked alright, but I couldn't merge it since it was closed.

I saw he fixed it in #1966, hh

**Comment by warren830** [comment]
fixed by #1966
