### ISSUE TITLE
lines are too long in CONTRIBUTING.md

### ISSUE THREAD

**Issue by nikitakoselev** [apache/incubator-devlake#1964]
## Documentation Scope
Having lines over 80 symbols is not a good idea. 197 characters long lines are hard to read and require some kind of a wrapper.

## Describe the Change
Easy. We will move new sentences to the new line :)

## Screenshots
![image](https://user-images.githubusercontent.com/6383738/169664179-94acec81-90c8-4aac-9f42-810e8490bb41.png)

## Additional context
Humans read in "F" shape (or mirrored F, if we speak of some languages).
OS documentation shall be taken seriously, as we cannot afford demotivating people with such small things

**Comment by shebuel-oss** [comment]
I can fix that @nikitakoselev

**Comment by nikitakoselev** [comment]
Thank you, @shebuel-oss , I have already resolved the issue. Could you please take a look at my pull request to double check it looks fine?

**Comment by warren830** [comment]
> 

Haha, I read your review, nice job! You are welcome to pick up some other issue? Thanks!

**Comment by warren830** [comment]
fixed by #1964

**Comment by shebuel-oss** [comment]
> > 
> 
> Haha, I read your review, nice job! You are welcome to pick up some other issue? Thanks!

Thank you. Sure I will
