### ISSUE TITLE
`creator_ids` in table.issues and pull_requests are empty strings

### ISSUE THREAD

**Issue by Startrekzky** [apache/incubator-devlake#1976]
## Describe the bug
table.Issues and table.pull_requests lack values of `creator_id`.

## To Reproduce
1. collect github data
2. see table.issues

## Expected behavior
Shows the `creator_id`. Now it's empty. The composition rules of `creator_id` are the same as those of `assignee_id`.

## Screenshots
A screenshot of the "issues" table
![image](https://user-images.githubusercontent.com/14050754/169854329-4f69c043-ecc8-466d-809d-d5f577f3b89e.png)

**Comment by likyh** [comment]
Yes, github plugin not extract create user info.
I'll try to fix it.

**Comment by klesh** [comment]
Happy Coding!
