### ISSUE TITLE
Add a field `creator_name` in the issues and pull_requests table

### ISSUE THREAD

**Issue by Startrekzky** [apache/incubator-devlake#1977]
## Description
Add a field `creator_name` in the issues and pull_requests table. Users can easily know who creates an issue or PR.

## Describe the solution you'd like
Please make sure all the following plugins have the right logic to assign value
- [ ] github: issue/pr creator's login
- [ ] gitlab: issue/mr creator's username
- [ ] jira: issue creator's username
- [ ] TAPD: issue creator's username

**Comment by likyh** [comment]
there are `author_name`/`author_id` in `pull_requests`. So just issue need fix.
