### ISSUE TITLE
Config UI for v1.0 - stage 1

### ISSUE THREAD

**Issue by klesh** [apache/incubator-devlake#1979]
## Description
Stage 1 of #1862 

## Describe the solution you'd like

**NOTE: every `connection` should have `ratelimit` field**

### Backend tasks
- #1412
- #1978 
- #636 
- #1980
- #1981
- #2262
- #1983
- Gitlab to accept `transformation rules` from `task.options`
- #1986
- Feishu to accept `transofmration rules ` from `task.options`
- Blueprint Api design upgrade
  1. #1987
  2. #1982

Multi Connection Checklist:
- Replace `GetDb` with `GetDal`
- Configuration like `PrType` `IssueTypeBug` are now grouped as `TransformationRules` and will be passed in `task.options`, no need  to store them with `connection` anymore. and jira connection should be refactor and remove those settings as well.
- Remove `Concurrency` parameter
- One PR for one `entity`
- Write `e2e-test` for each `entity`
- Write `godoc` for every public method/function/struct
- Write `unit-test` for public util function if any
- Close the issue on last PR

### Frontend tasks (to be filled by @e2corporation )
- #1951 

## Has the Feature been Requested Before?
No

**Comment by e2corporation** [comment]
@klesh can you please provide me the latest expected JSON configuration for Blueprint Create / `POST`? I need to make some changes to the request structure so that we send `boards` and `projects` as an array of **Board IDs** and **Repositories**. Backend can then split the string to extract `Owner` and `RepositoryName`.


# Requested Structure Updates
```
{
    "version": "1.0",
    "connections": [
        {
            "plugin": "github",
            "connectionId": 123,
            "scope": [
                {
                    "projects": ["merico-dev/lake", "merico-dev/stream"]
                    "transformation": {
                        "issueTypeBug": "^(bug|failure|error)$"
                    },
                    "entities": [
                        "code",
                        "crossdomain",
                        "devops",
                        "ticket",
                        "user"
                    ]
                }
            ]
        },
        {
            "plugin": "jira",
            "connectionId": 321,
            "scope": [
                {
                    "boards": [123],
                    "options": {
                        "since": "2022-1-2"
                    },
                    "transformation": {
                        "issueTypeBug": "??"
                    },
                    "entities": []
                }
            ]
        }
    ]
}
```


# Current Structure proposed on #1982
Dispatching `owner` and `repo` as 2 separate fields is not ideal, instead we should send an array of `projects`
```
{
    "version": "1.0",
    "connections": [
        {
            "plugin": "github",
            "connectionId": 123,
            "scope": [
                {
                    "owner": "merico-dev",
                    "repo": "devlake",
                    "transformation": {
                        "issueTypeBug": "^(bug|failure|error)$"
                    },
                    "entities": [
                        "code",
                        "crossdomain",
                        "devops",
                        "ticket",
                        "user"
                    ]
                }
            ]
        },
        {
            "plugin": "jira",
            "connectionId": 321,
            "scope": [
                {
                    "boardId": 123,
                    "options": {
                        "since": "2022-1-2"
                    },
                    "transformation": {
                        "issueTypeBug": "??"
                    },
                    "entities": []
                }
            ]
        }
    ]
}
```
