### ISSUE TITLE
 Refdiff to support another set of parameters tag regex and tag limit, and calculate diffs based on these 2 parameters

### ISSUE THREAD

**Issue by klesh** [apache/incubator-devlake#1983]
## Description
Refdiff currently accept only `pairs` and calculate diffs for them, this is not very flexible, because most of the time, user would like to know diffs of latest releases. It's no point to calculate same set of pairs over and over again, especially with `pipelines` that triggered by `blueprint`

## Describe the solution you'd like
Beside `pairs`, refdiff can accept `tagsPattern` and `tagsLimit`, maybe evens `tagsOrder`(alphabetically , semver). and refdiff would filter `tags` by these parameters, sort them, take last `tagsLimit` tags, and calculates diffs for them.

## Has the Feature been Requested Before?
No

**Comment by mappjzc** [comment]
Assignee to me.
