### ISSUE TITLE
Be able to specify what plugins to build

### ISSUE THREAD

**Issue by klesh** [apache/incubator-devlake#1996]
## Description
Currently, we have some plugins which depend on dynamic-library with specific version (like `gitextractor` depends on libgit2 v1.3.0),  which can be hard to satisfy, and, sometimes, user just don't need those plugins at all.
With support for "specifying what plugins to build", user can choose to ignore those plugins, and compile only those he/she wanted.
Plus, this would be convenience for developer when debugging specify plugin

## Describe the solution you'd like
Modify `scripts/compile-plugins.sh` to accept an Environment Variable `PLUGINS` in `pluginA,pluginB` format, and compile only specified plugins if `PLUGINS` was set and NOT empty.
1. `PLUGINS` is given and not empty: keep existing plugin binary files, compile only specified plugin
2. `PLUGINS` is not given or empty: delete all existing plugin binary files, compile all plugins

## Has the Feature been Requested Before?
No

**Comment by sbdtu5498** [comment]
Just revising the bash stuff. I will take the issue.

**Comment by klesh** [comment]
Happy Coding 😃

**Comment by deepto98** [comment]
Can I pick this up?
