### ISSUE TITLE
collect/extractor 's params need some document to help developer.

### ISSUE THREAD

**Issue by likyh** [apache/incubator-devlake#2017]
## Documentation Scope
plugin

## Describe the Change
Such as https://developers.weixin.qq.com/miniprogram/dev/framework/plugin/development.html

**Comment by likyh** [comment]
need go doc and deploy to public go document website.

**Comment by klesh** [comment]
Looks like it is all automatically generated by pkg.go.dev.
All we have to do is to add link onto our website, which will be addressed by https://github.com/apache/incubator-devlake-website/issues/54
Close it for now,  feel free to re-open if I missed anything.
