### ISSUE TITLE
Change the logo for ASF v0.11.0 release

### ISSUE THREAD

**Issue by yumengwang03** [apache/incubator-devlake#2037]
We need to replace the old logo with the new one in Config UI . The "view dashboard" button can be placed under the new logo.

Old:
![middle_img_v2_6989464b-4589-4c93-bed9-0b579da60beg](https://user-images.githubusercontent.com/9535430/170999336-2d0e1b4f-b381-450b-a556-a9bf37239cac.jpg)
New:
![DevLake config ui logo](https://user-images.githubusercontent.com/9535430/170999255-45ef9a67-45ce-4d83-93ad-d31e5d842473.svg)

**Comment by likyh** [comment]
![KQB9TNlKY8](https://user-images.githubusercontent.com/3294100/171160708-54cf67a7-0d47-4f51-9673-bc6f686b7a68.png)
It's also require a favicon. (must .ico)
