### ISSUE TITLE
[BUG][ENV] When debugging the gitlab plugin, it prompts that the env file cannot be found

### ISSUE THREAD

**Issue by SnowMoon-Dev** [apache/incubator-devlake#2055]
## Describe the bug
When debugging the gitlab plugin, it prompts that the env file cannot be found

## To Reproduce
1. cd incubator-devlake/plugins/gitlab
2. go run gitlab.go -p $gitlab_project_id

## Screenshots
<img width="880" alt="image" src="https://user-images.githubusercontent.com/42627702/171469687-3f40edb6-e7cf-4437-9402-ea10425584c0.png">

**Comment by Startrekzky** [comment]
Sorry for the late reply, can @klesh @warren830 take a look at this bug?

**Comment by warren830** [comment]
@SnowMoon-Dev has already provided a better solution, nice job!
