### ISSUE TITLE
gitlab error code 403 with CI/CD options turned off

### ISSUE THREAD

**Issue by mappjzc** [apache/incubator-devlake#2065]
## Describe the bug
At the issue #1937 
There are another user get the same problem.
Through remote assistance, we checked the gitlab repository and the corresponding request API url when the error occurred.
We confirmed that the 403 error was returned when calling the interface 
`projects/{{ .Params.ProjectId }}/pipelines`
to get the list.
This error appears in some gitlab repositories, but not in other gitlab repositories.
After comparing and checking, it was found that the CI/CD configuration was not enabled.
![image](https://user-images.githubusercontent.com/2921251/171598136-42f41875-4eb0-4dc9-ba70-1d2470b6ac7c.png)
In the test environment, after closing the CI/CD settings of the project and performing a reproduction test, the problem can be successfully reproduced.
![image](https://user-images.githubusercontent.com/2921251/171597735-131a67bb-7aac-46e4-bbc3-406aea246b21.png)
![image](https://user-images.githubusercontent.com/2921251/171599396-33e5e184-9845-492e-80e3-f7092f14e475.png)

## To Reproduce
1.Collect a gitlab project repository with CI/CD options turned off

## Expected behavior
Even collecting a gitlab project repository that has CI/CD options turned off, the collection can be done successfully.

**Comment by klesh** [comment]
Plan of Attack:
1. Display a friendly error message like "Please check if Gitlab CI/CD feature is disabled. View details https://devlake.apache.org/docs/Plugins/gitlab/".
2. Add documentation describing the common causes to https://devlake.apache.org/docs/Plugins/gitlab/
