### ISSUE TITLE
[BUG][CI] e2e-mysql CI build fails

### ISSUE THREAD

**Issue by SnowMoon-Dev** [apache/incubator-devlake#2066]
## Describe the bug
e2e-mysql CI build fails

## Expected behavior
remove “apk add --no-cache tar” will not affect CI running
<img width="1346" alt="image" src="https://user-images.githubusercontent.com/42627702/171622128-d322beb9-81ec-491d-a39c-2d11abb0f495.png">

## Screenshots
<img width="1553" alt="image" src="https://user-images.githubusercontent.com/42627702/171621892-ac3a5f9c-54f9-48c4-8af1-23cdb636d2b5.png">

**Comment by klesh** [comment]
I think we should pre-built this package into `lake-builder`

**Comment by SnowMoon-Dev** [comment]
resolved, close issiues
