### ISSUE TITLE
problems when using devlake

### ISSUE THREAD

**Issue by better629** [apache/incubator-devlake#2068]
using latest version

## Describe the bug
1、datasource connection problem
using default datasource failed, but success when creating new datasource using same configuration. (The mysql port used is 33306)

2、gitlab pipeline success with no data
there are data in mysql db but no data in grafana dashboard

3、jira pipeline failed with many issues
pipeline run success when the issues num is small in board id , but failed with large num.
error info is `context deadline exceeded (Client.Timeout exceeded while awaiting headers)\nset Environment Varaible ASYNC_CF=true to enable callframes information Get`

4、git Extractor
error `remote authentication required but no callback set` when using exitest repo id( in successed gitlab pipeline)

## Screenshots
1、datasource connection problem
![image](https://user-images.githubusercontent.com/7869691/171766681-6a8a0b22-cbdd-47dd-aea9-284c1afc4b42.png)

2、gitlab pipeline success with no data
![image](https://user-images.githubusercontent.com/7869691/171767715-f49345a4-3fdb-4719-a32c-3a5bee6f46eb.png)

3、jira pipeline failed
![image](https://user-images.githubusercontent.com/7869691/171767525-f052eb00-99aa-45d9-b061-e6f589008217.png)

**Comment by Startrekzky** [comment]
Thanks for reporting. Can @klesh @warren830 brief the updates for this bug?

**Comment by klesh** [comment]
1. This is needed to be confirmed
2. This is related to problem 1 , I think. The dashboard was working IIRC.
3. Nothing we can do here, seemed like the server was down or network connectivity was no good, and it worked eventually IIRC
4. We need to support private repo on config-ui as I mentioned, we need a design for that @Startrekzky

**Comment by likyh** [comment]
I'll focus on it.

**Comment by likyh** [comment]
1. if you use the other name instead of `lake`, you should fill it at `DB_URL` in file `.env`
2. commit chart needs data not only in the GitHub plugin but also in `gitextractor`
3. It seems to be blocked by the network. Maybe you can add the `proxy`.
4. This is related to problem 2 and it's will be fixed soon.
