### ISSUE TITLE
usage proposal

### ISSUE THREAD

**Issue by better629** [apache/incubator-devlake#2069]
## Description
1、The granularity of operations can be larger
using project-id to import gitlab data is real time-consuming. We want to import all data and show it in a dashboard with high level.
2、pipeline CURD
seems it can't delete pipeline. Managing is time-consuming.
3、grafana bashboard
how to create bashboard with your data easier??

## Describe the solution you'd like
1、gitlab
in  gitlab group_id granularity or else

**Comment by klesh** [comment]
Hi @better629 , Thanks for the advice.
1. The granularity of operations can be larger. This is definitely legitimate. would you take a look at this @Startrekzky 
2. pipeline is a historical record representing a transaction that was carried out at some point, no need to delete a pipeline.
3. Good point, @Startrekzky , I think we need some kind of guide/documentation/blog to help people create their first dashboard,

**Comment by Startrekzky** [comment]
Hi @better629 
1. The 1st problem will be addressed in #2271 , please subscribe this ticket.
2. The 2nd problem will not exist after v0.12.0 released.
3. The 3rd problem will be addressed in #2248 , please subscribe this ticket.

I'll close this issue, as it contains multiple feature requests. Please report the feature request in separate issues in the future. Thanks.
