### ISSUE TITLE
Conversion from collation utf8mb4_0900_ai_ci into utf8_general_ci impossible for parameter

### ISSUE THREAD

**Issue by marcemv90** [apache/incubator-devlake#2073]
## Describe the bug
Running a Github pipeline to register a repository that contains emojis on some of its pull request comments (and probably in other fields) the pipeline fails with the following error:

```
Error 3988: Conversion from collation utf8mb4_0900_ai_ci into utf8_general_ci impossible for parameter
```

## To Reproduce
1. Go to '**Pipelines > Create Pipeline Run**'
2. Click on '**Create Pipeline Run**'
3. Scroll down to until '**Github**' is shown in Data Providers list
4. **Toggle on** GitHub Data provider
5. Enter repository owner and name for a repository **that contains emojis** on some of its comments, titles, etc.
6. Click on '**Run Pipeline**'
7. Wait for the Pipeline to run, in our case it fails at 20%.

## Expected behavior
Github scan succeeds with no errors.

## Screenshots
![image](https://user-images.githubusercontent.com/16705936/171841365-f2c16067-7834-4916-93f1-9d9eeb5e718c.png)

![image](https://user-images.githubusercontent.com/16705936/171843271-72fe5df0-c00b-4554-a6ab-b78a7917329b.png)

## Additional context
Similar errors are shown in the lake container logs:
```shell
time="2022-06-03 10:51:01" level=error msg=" [task service] task failed%!(EXTRA *errors.SubTaskError=Error 3988: Conversion from collation utf8mb4_0900_ai_ci into utf8_general_ci impossible for parameter)"
time="2022-06-03 10:51:01" level=error msg=" [pipeline service] [pipeline #21] run tasks failed: %!w(*errors.errorString=&{Error 3988: Conversion from collation utf8mb4_0900_ai_ci into utf8_general_ci impossible for parameter})"
```

We think it might be related to the emojis  as the log also contains those. Probably is related to the charset used in the Database or some of its tables or fields.

Please let us know if further information is required.

Many thanks!

Regards.

**Comment by Startrekzky** [comment]
@klesh @warren830 Can you look at this bug?

**Comment by warren830** [comment]
@marcemv90 This is wield, I tried many times, it works well. 
<img width="418" alt="image" src="https://user-images.githubusercontent.com/39366025/176817911-ea61011d-4340-4f13-8d1c-1055a00c56fe.png">

**Comment by warren830** [comment]
@marcemv90 can you provide the repo you met the problem?

**Comment by warren830** [comment]
😅

**Comment by warren830** [comment]
> 😅
also tried this one
![image](https://user-images.githubusercontent.com/39366025/176824195-62ece2eb-15d9-4628-b258-ade051007a13.png)

**Comment by marcemv90** [comment]
Hi @warren830 👋 ,

I can't provide the repository where that bug was found as it is a private repository from my company. Emojis becoming the cause of the error was our first thought, but we are not sures about that. That was something that simply made sense for us, but we have no further mechanisms to dig deeper.

What is something that I do can provide are the tags of the docker images that we are using, maybe that's helpful for your for troubleshooting, or maybe it is something that is already fixed in a higher version or something similar.

- **Lake:** [mericodev/lake:20220523](https://hub.docker.com/layers/lake/mericodev/lake/20220523/images/sha256-b2210658d048388e1a0ea0ae55f865c8ad520b628e9a94a76d492045097524bc?context=explore)
- **ConfigUI**: We are using a Docker image built by us because there hasn't been a non-test release since #2238. But it is based on [mericodev/config-ui:20220523](https://hub.docker.com/layers/config-ui/mericodev/config-ui/20220523/images/sha256-7c8c87fa885a1ce9f4065e0cd2334e2be0866845dc0c7566af7c09224b97533f?context=explore).
- **Database**: We are running a MySQL in AWS RDS. Engine version 8.0.27

Hope it can shed some light to help identifying the root cause.

Please let me know if I provide something else that might be helpful as well, like enabling debug traces and upload the logs of a failed scan, or something like that.

Regards!

**Comment by warren830** [comment]
I think the problem might be caused by AWS RDS. What's the collation of your db?

**Comment by marcemv90** [comment]
Hello @warren830 , see following:

```mysql
use lake;
SELECT @@character_set_database, @@collation_database;
```

![image](https://user-images.githubusercontent.com/16705936/177109346-6281003e-2dbf-464b-acf7-07909d38d362.png)

Also our connection string is set to the following, in case it could be helpful:

`mysql://user:pass@devlake.xxxxxxxxx.eu-west-1.rds.amazonaws.com:3306/lake?charset=utf8mb4&parseTime=True`

Thanks for your time!

Regards.

**Comment by warren830** [comment]
> 

Thanks!

**Comment by warren830** [comment]
> Hello @warren830 , see following:
> 
> ```sql
> use lake;
> SELECT @@character_set_database, @@collation_database;
> ```
> 
> ![image](https://user-images.githubusercontent.com/16705936/177109346-6281003e-2dbf-464b-acf7-07909d38d362.png)
> 
> Also our connection string is set to the following, in case it could be helpful:
> 
> `mysql://user:pass@devlake.xxxxxxxxx.eu-west-1.rds.amazonaws.com:3306/lake?charset=utf8mb4&parseTime=True`
> 
> Thanks for your time!
> 
> Regards.

This is so strange, we are using the same character set and collation:
![image](https://user-images.githubusercontent.com/39366025/180117357-529f26c1-4b1e-4042-8f85-d9b9f89e2479.png)

Can you check which task returned error?

**Comment by marcemv90** [comment]
Hi @warren830, the task is using the Github plugin, not sure if that the information that you need. Let me know if I can provide further details.

**Comment by klesh** [comment]
Hi, @marcemv90, what was the name of the failing subtask?
Can you isolate the specific "emoji" that causing the problem?
Thanks in advanced.

**Comment by Startrekzky** [comment]
Hey @marcemv90 , have you found out which specific emojis cause this problem?

**Comment by marcemv90** [comment]
Hello @klesh , @Startrekzky , sorry for the delayed response, I've been trying to reproduce the error, but I've been completely unable. I will let you know if it arises again, so I can provide further details.

Sorry.

**Comment by hezyin** [comment]
@marcemv90 Hi Marcelo, were you able to reproduce the issue?
