### ISSUE TITLE
[Improve][github template] Improve current template and feature template

### ISSUE THREAD

**Issue by SnowMoon-Dev** [apache/incubator-devlake#2075]
## Documentation Scope
Briefly explain what is the documentation is referencing (main README, a specific plugin etc.)

## Describe the Change
 Improve current template and feature template

**Comment by Startrekzky** [comment]
Hi @SnowMoon-Dev , do you mean the template for creating `documentation` issues? 
I'll take a look at it.

**Comment by SnowMoon-Dev** [comment]
> 

yes
