### ISSUE TITLE
golangci-lint header linting doesn't seem to be working

### ISSUE THREAD

**Issue by klesh** [apache/incubator-devlake#2077]
## Describe the bug
File from https://github.com/apache/incubator-devlake/pull/2053/files#diff-f06f45811e3bd67de714c015e0f3efd9aac00b72618df90878a279f33209c090 has no head, but `golangci-lint` passed anyway.

## Expected behavior
`golangci-lint` should fail

## Screenshots
![image](https://user-images.githubusercontent.com/61080/171938048-3dc1f1f5-a228-43bb-b814-ac7b6505499b.png)

**Comment by matrixji** [comment]
Seems failed due to cgo build failed (no libgit2 dev package installed).
I'd like to handle this issue.

**Comment by klesh** [comment]
Happy Coding
