### ISSUE TITLE
Incorrect configuration handling while deploy with helm

### ISSUE THREAD

**Issue by matrixji** [apache/incubator-devlake#2081]
## Describe the bug
Incorrect configuration handling while deploying with helm

## To Reproduce
1. Deploy devlake with helm
2. Configure some settings and Click `[Save Configuration]`
3. The server return error with:
    ```json
    {"success":false,"message":"open .env: no such file or directory"}
    ````

## Expected behavior
Configuration should be saved without error.

## Screenshots
N/A

## Additional context

There should be at least 2 things to be fixed.
1. Need to create an empty `.env` config file if it does not exists while deploying with helm.
2. The `WriteConfig` func in config/config.go need to use the path from ENV_PATH (if have), currently:
    ```go
    // WriteConfig save viper to .env file
    func WriteConfig(v *viper.Viper) error {
            return WriteConfigAs(v, `.env`)
    }
    ```

I'll try to fix it.

**Comment by Startrekzky** [comment]
Hi @matrixji , thanks for the issue and pr.
