### ISSUE TITLE
Review all of our onboarding documentation as a new developer returns

### ISSUE THREAD

**Issue by joncodo** [apache/incubator-devlake#2092]
Use the fresh set of eyes to review the set up process docs

## Documentation Scope
Readmes for setting up the project

## Describe the Change
QA

**Comment by joncodo** [comment]
I will tackle this one :)

**Comment by hezyin** [comment]
@joncodo Hi Jon, this is a good place to start. Could you please list out the docs you're going to proofread so we can better manage this issue?

**Comment by klesh** [comment]
Hey man, how are you doing?

**Comment by klesh** [comment]
hi @joncodo , can we close this one?
