### ISSUE TITLE
There is no way to search our docs at https://devlake.apache.org/docs

### ISSUE THREAD

**Issue by joncodo** [apache/incubator-devlake#2097]
## Documentation Scope
So I am looking for new documentation to add but I want to make sure that the topics are not already covered in our docs. It seems like the only way to do this now is to go to each page individually and search through chrome's search feature.

## Describe the Change
I would like to see us enable search on our apache docs site. I am not sure how we do this now but I will work to figure it out. I think will really improve the usability of our docs.

## Screenshots
<img width="1476" alt="Screen Shot 2022-06-06 at 12 44 37 PM" src="https://user-images.githubusercontent.com/3011407/172196433-6f1e9244-f971-4115-858f-e584d6e9c2d7.png">

**Comment by joncodo** [comment]
I think this would be applicable to solve this problem: https://docusaurus.io/docs/search#using-algolia-docsearch

> The service is free for any open-source project: just make sure to read the [checklist](https://docsearch.algolia.com/docs/who-can-apply/) and [apply to the DocSearch program](https://docsearch.algolia.com/apply).

> DocSearch crawls your website once a week (the schedule is configurable from the web interface) and aggregates all the content in an Algolia index. This content is then queried directly from your front-end using the Algolia API.

**Comment by joncodo** [comment]
It would also be nice to be able to search docs and github issues together.

**Comment by yumengwang03** [comment]
I'll work on this.
