### ISSUE TITLE
Add Contribution Guide to apache docs site

### ISSUE THREAD

**Issue by joncodo** [apache/incubator-devlake#2098]
## Documentation Scope
We have a Contribution.md doc in devlake but that information is not on the apache docs site. I also think I can revisit this guide to provide a smoother new dev experience.

## Describe the Change
Update Contribution.md and move it over to the apache docs site.

**Comment by hezyin** [comment]
@joncodo Good idea, we should migrate `CONTRIBUTING.md` to our official website. 

1. There're some outdated sections in `CONTRIBUTING.md`, for example, the "Maintainer Team @ Merico" section should be removed. DevLake is now led by the Apache DevLake PPMC.
2. As for where would the `CONTRIBUTING.md` live under our website, I thought it can be merged into or replace this page: https://devlake.apache.org/community/make-contribution/fix-or-create-issues

@yumengwang03 What do you think, Yumeng?

**Comment by joncodo** [comment]
I will do this

**Comment by joncodo** [comment]
I see now that this doc exists in a different section of the site: https://devlake.apache.org/community/

Under the community tab at the top. I just looked in docs and assumed community was a forum.
<img width="538" alt="Screen Shot 2022-06-07 at 10 25 15 PM" src="https://user-images.githubusercontent.com/3011407/172511343-3e5b6878-f825-4b2d-9cac-ce95da305be3.png">

**Comment by joncodo** [comment]
But I still need to remove this section in the docs. PR incoming

**Comment by joncodo** [comment]
This was also already done:

> ## Maintainer team 

> Apache DevLake is maintained by apache/devlake committers. We aim to achieve an SLA of 24 hrs for replying to issues.
