### ISSUE TITLE
Fix lint in pipeline so our github actions pass

### ISSUE THREAD

**Issue by joncodo** [apache/incubator-devlake#2099]
## Describe the bug
Main is failing currently

<img width="1005" alt="Screen Shot 2022-06-06 at 1 02 23 PM" src="https://user-images.githubusercontent.com/3011407/172199189-18dbd555-7274-42db-a089-6c9d313373b9.png">

<img width="1038" alt="Screen Shot 2022-06-06 at 1 02 54 PM" src="https://user-images.githubusercontent.com/3011407/172199253-ecb9d0d6-e5d2-49a6-aca7-b990c0f89a7b.png">

**Comment by hezyin** [comment]
@joncodo I believe someone is already working on this. @klesh should have more context, please chime in.

**Comment by joncodo** [comment]
Seems like one of these things was fixed. I recommend that we prevent any merges that break tests. This would be a great open source practice. @hezyin
