### ISSUE TITLE
Add a new plugin for Bitbucket

### ISSUE THREAD

**Issue by hezyin** [apache/incubator-devlake#2100]
## Description

Add a new Bitbucket data source plugin for Bitbucket so DevLake can collect dev data from it.

## Pre-requisites

1. Understand how a DevLake plugin works.
2. Make sure you have access to [Bitbucket API](https://developer.atlassian.com/cloud/bitbucket/rest/intro/). 

## Describe the solution you'd like
Add a plugin for `bitbucket`. Please refer to other data source plugins such as [github](https://github.com/apache/incubator-devlake/tree/main/plugins/github) and [gitlab](https://github.com/apache/incubator-devlake/tree/main/plugins/gitlab). 

This plugin performs 3 major tasks:
1. Collect data from Bitbucket RESTful API. The API responses shall be stored in the raw data layer.
2. 1st ETL: transform the raw data and load it into the tool layer.
3. 2nd ETL: transform the tool layer data and load it into the domain layer.

## How to start
Please follow the doc [how to add a plugin(WIP)](url).

## Additional notes
In DevLake, there're 3 layers of storage: 
- raw data layer: tables starting with `_raw_` 
- tool layer: tables starting with `_tool_`
- domain layer: tables with no prefix

You can set up DevLake and see the tables in MySQL.

**Comment by keon94** [comment]
@hezyin I'll take this one.

**Comment by mindlesscloud** [comment]
@keon94 this issue was assigned to @thenicetgp as an OSPP(Open Source Promotion Plan) project

**Comment by thenicetgp** [comment]
I'll take this one.

**Comment by keon94** [comment]
Hi @Startrekzky. Which release are we targeting this plugin for?
