### ISSUE TITLE
CI: golangci-lint post job fails

### ISSUE THREAD

**Issue by matrixji** [apache/incubator-devlake#2102]
## Describe the bug
golangci-lint post job requires standard tar tools.
It just impacts the post job.

## To Reproduce
N/A

## Expected behavior
Hope ` golangci-lint post` success

## Screenshots
![image](https://user-images.githubusercontent.com/183388/172281446-8ab43ec1-fbb9-40c6-95d8-0fe2a9c45660.png)

## Additional context
We start using `mericodev/lake-builder:latest` as golang lint container after #2084.
But no standalone `tar` in that images, we need to add tar tools in that devel container image.

**Comment by warren830** [comment]
Yes, this is a problem, let me contact our DevOps to fix it
