### ISSUE TITLE
当点击“Grafana”按钮，就跳转到http://localhost:3002/d/0Rjxknc7z/demo-homepage?orgId=1去了

### ISSUE THREAD

**Issue by Doujang** [apache/incubator-devlake#2109]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

![image](https://user-images.githubusercontent.com/20734553/172370609-bf63980b-e511-47bc-bb20-3eec80a7d800.png)

### What you expected to happen

感觉前端应该处理下，获取当前domain然后拼接端口，而不是直接写死localhost

### How to reproduce

感觉前端应该处理下，获取当前domain然后拼接端口，而不是直接写死localhost

### Version

0.10.1

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Startrekzky** [comment]
Hi @Doujang, is that OK for me to translate your issue into English so that the rest community could understand?
