### ISSUE TITLE
[Bug] [config-ui] Connection Save too slowly

### ISSUE THREAD

**Issue by likyh** [apache/incubator-devlake#2111]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

Connection Save too slowly. It's always 2s even thouth it's in local network.

### What you expected to happen

![image](https://user-images.githubusercontent.com/3294100/172426185-9891fd75-92e8-469e-ae7e-fde01df171b7.png)

Save success when api response.

### How to reproduce

1. create a connection and save it.
2. look how long it succeed.

### Version

main

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by likyh** [comment]
I think the reason of this issue is `ToastNotification.clear()` in other network request

**Comment by e2corporation** [comment]
This is not a bug there must be some specific reason this is wrapped in a timeout, most likely for UI latency.

**Comment by likyh** [comment]
The api request function should return when success and only return slowly when timeout?
