### ISSUE TITLE
Scheduled pipeline function does not match the description

### ISSUE THREAD

**Issue by Doujang** [apache/incubator-devlake#2116]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

<img width="535" alt="image" src="https://user-images.githubusercontent.com/20734553/172519472-9bc88b72-f280-4d6a-a7bb-d9a9d9f7b390.png">

The description shows the scheduled task is accurate to second; while the setting function is accurate to minute. 

### What you expected to happen

The description and the function should be consistent.

### How to reproduce
N/A

### Version

0.10.1

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by abeizn** [comment]
second is optional. when you select `Custom` Frequency, you can update the Schedule.
![image](https://user-images.githubusercontent.com/101256042/172522013-0555ce4f-973d-4f53-ab1a-ab4d1a9df800.png)
So i think it is right.

**Comment by Doujang** [comment]
I have tried like that but not working

**Comment by abeizn** [comment]
> I have tried like that but not working

yes, I tried it and it really doesn't work.

**Comment by Startrekzky** [comment]
@e2corporation I think we don't have to modify it in the current version, just make sure it's not appeared in the new config-UI in v0.12.0+ versions and it'll be good.

**Comment by likyh** [comment]
I'll take it and I need a picture to replace it.
