### ISSUE TITLE
[Bug] [Github Plugin] Github users are not appeared in table.users

### ISSUE THREAD

**Issue by Startrekzky** [apache/incubator-devlake#2122]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

I set up DevLake v0.11-test version and imported Github and Jira data. 
When I tried to get Github issue creator's detail by joining table.users. I didn't get the full user info, such as organization. Thus, I couldn't tell if an issue is created by a community member.

![image](https://user-images.githubusercontent.com/14050754/172590466-263cc9bd-fefc-4ee2-b2e1-92e53776b5e8.png)

### What you expected to happen

GitHub users appeared in table.users.

### How to reproduce

1. Set up DevLake main
2. Collected Github data
3. Connected to MySQL
4. Run query
`select distinct i.creator_id, i.creator_name, u.id, u.name FROM issues i
left join users u on i.creator_id = u.id`

### Version

main

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Startrekzky** [comment]
A side note: please make sure that Github users' org appeared in table.users in the domain layer schema.

**Comment by abeizn** [comment]
@likyh

**Comment by likyh** [comment]
I’ll try to fix it.
