### ISSUE TITLE
Add more context to error messages

### ISSUE THREAD

**Issue by keon94** [apache/incubator-devlake#2134]
## What and why to refactor
Many plugin subtasks directly return errors without adding any extra context to the message. This makes troubleshooting difficult. For example, [this](https://github.com/apache/incubator-devlake/blob/0d3aa41e5e3db60e7ddfd3c3835f40e8c1c8eeb4/plugins/github/tasks/pr_commit_extractor.go#L85), which might produce a Json unmarsal error, needs to have a message that additionally tells us something like "unable to get Input while extracting pull request commits".

## Describe the solution you'd like
Identify all such plugin subtasks and wrap the error messages with more context.

## Related issues
Similar to #1447 
## Additional context
n/a

**Comment by keon94** [comment]
For example, at every package level (or even function level) wrap the thrown error like this:
`fmt.Printf("error while doing X: %v")`
and rethrow this new error.

**Comment by yumengwang03** [comment]
Please be aware that @taninghan has attached the UI design in https://github.com/apache/incubator-devlake/issues/1447

**Comment by keon94** [comment]
PR: #2745

**Comment by keon94** [comment]
@Startrekzky @klesh As per our conversation in our weekly meeting, I've increased the scope on this issue to make the backend use a more robust error framework with support for user friendly messages, wrapped errors and stacktraces.
