### ISSUE TITLE
Migration documentation

### ISSUE THREAD

**Issue by keon94** [apache/incubator-devlake#2135]
## Documentation Scope
The DB migration scripts, in [this package](https://github.com/apache/incubator-devlake/tree/main/models/migrationscripts),each contain a snapshot of the datamodel they're transforming. These snapshotted structs are not used anywhere, and this makes it confusing to the reader/user as far as the purpose they serve.

## Describe the Change
Document in code or in a Readme the purpose or usage of these structs to clarify their need.

## Screenshots
n/a

## Additional context
https://github.com/apache/incubator-devlake/issues/1711 is where I encountered this ambiguity.

**Comment by likyh** [comment]
Yeah, It's necessary and should be closed
