### ISSUE TITLE
Devlake cannot support directories when integrating jenkins

### ISSUE THREAD

**Issue by moonlzl** [apache/incubator-devlake#2145]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

When the jenkins job is created in the directory, devlake cannot correctly accept and display the data

### Use case

![image](https://user-images.githubusercontent.com/107170821/172778527-674640e3-8267-4168-8da7-3d341125fe72.png)
![image](https://user-images.githubusercontent.com/107170821/172778817-770c1ebb-cfb7-4ade-a6be-6ac4007092ba.png)

template is a directory, not a job
devlake cannot correctly accept and display the data

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by moonlzl** [comment]
similar question
https://github.com/apache/incubator-devlake/issues/2091

**Comment by Startrekzky** [comment]
Hi @moonlzl, thanks for the issue. I'm trying to put in the v0.13.0
