### ISSUE TITLE
[Bug] [golangci-lint] golangci-lint error messages need to be handled

### ISSUE THREAD

**Issue by SnowMoon-Dev** [apache/incubator-devlake#2152]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

golangci-lint throws error information

### What you expected to happen

golangci-lint error messages need to be handled

### How to reproduce

1. commit PR

### Anything else

<img width="1225" alt="image" src="https://user-images.githubusercontent.com/42627702/172986733-e278c1bb-0eca-4d6a-bb17-a1fe8a2d68ec.png">

### Version

main

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by warren830** [comment]
Will fix it next week

**Comment by SnowMoon-Dev** [comment]
> Will fix it next week

good~

**Comment by likyh** [comment]
fixed
