### ISSUE TITLE
[Bug] [config-ui] Only trigger connection test when multi tokens

### ISSUE THREAD

**Issue by likyh** [apache/incubator-devlake#2155]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

![image](https://user-images.githubusercontent.com/3294100/172996932-71cd0b08-8953-4c45-8318-ecd82f89c427.png)

![image](https://user-images.githubusercontent.com/3294100/172997215-e49e259b-1fec-4406-b6ed-9d9c7ba8a7e0.png)

### What you expected to happen

Trigger connection test whenever saving connections.

### How to reproduce

1. save a GitHub connection when only using 1 token;
2. save the same connection with 2 tokens.
3. Look at the difference between these.

### Version

main

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by klesh** [comment]
@e2corporation I feel like this issue has been brought up many times,  I used to believe it is better to separate Save and Test, but seems like most people prefer Test & Save. So, maybe we can do that? the connection can be saved IFF Test succeeded.

**Comment by e2corporation** [comment]
It may even be more practical to test `onChange` so when all credentials are completed, run a test and display failure, but still allow the user to save the record.

**Comment by klesh** [comment]
Will be addressed by New ConfigUI flow
