### ISSUE TITLE
Help！Jenkins pipeline 50% completed with error.

### ISSUE THREAD

**Issue by yizhixiaotaozi** [apache/incubator-devlake#2158]
## Question
just set up a default project,
run a pipeline with 
"Plugin": "jenkins",
 "Options": {}

## Screenshots
![企业微信截图_20220610153405](https://user-images.githubusercontent.com/7123892/173014586-6ac0f6f6-f404-4c13-b07b-b441a8b9f0cf.png)

## Additional context
run task failed with panic (github.com/merico-dev/lake/plugins/jenkins/tasks.ExtractApiBuilds.func1:62): runtime error: index out of range [0] with length 0

**Comment by abeizn** [comment]
which version? v10.1 or main?

**Comment by warren830** [comment]
@yizhixiaotaozi Hi, sorry for the bug, already fixed, can you try it again?
