### ISSUE TITLE
[Feature][config-ui] JIRA Authentication Tooltip for Password field

### ISSUE THREAD

**Issue by e2corporation** [apache/incubator-devlake#2188]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Internal feature request by @klesh to add a tooltip to JIRA's password field to indicate what type of value should be used if JIRA Cloud or JIRA Server is used.

### Use case

The Connection Form parameters for JIRA's password field should be enhanced with a Tooltip Icon and text (see Token field for reference)

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by tanninghan** [comment]
Design for creating Jira data connection
![image](https://user-images.githubusercontent.com/102040651/174627059-4b457194-2050-4dc6-9d90-5d945c36b27b.png)

**Comment by e2corporation** [comment]
Resolved w/ `v0.12.0` release, a tooltip was added.
