### ISSUE TITLE
[Bug] [config-ui] GitExtractor Pipeline Activity 0% Progress after 2minutes

### ISSUE THREAD

**Issue by e2corporation** [apache/incubator-devlake#2197]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

When using the **GitExtractor** Plugin, task progress is not accurately calculated after 2 minutes of activity. We should be using `progressDetail` to infer percentage completed if `progress` value is always 0 or not able to be updated.

![20220615-012136](https://user-images.githubusercontent.com/1742233/173743562-26214fb7-5af9-49bf-bedd-f54c29f0c040.jpeg)

### What you expected to happen

The (sub)task progress percentage for tasks on the pipeline should use the progressDetail data if available to calculate percentage completed.

### How to reproduce

Run a Pipeline with GitExtractor.

### Version

`main`

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by e2corporation** [comment]
Could be addressed on either Backend or Frontend, awaiting further feedback.

**Comment by klesh** [comment]
We discussed this on https://github.com/apache/incubator-devlake/issues/822
Please check the "Final Decision" section, BE can not provide a reliable Percentage Progress.

**Comment by klesh** [comment]
@yumengwang03

**Comment by Startrekzky** [comment]
This has been covered by #2249
