### ISSUE TITLE
[Bug] [jira] Task failed with error 404

### ISSUE THREAD

**Issue by narrowizard** [apache/incubator-devlake#2226]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

It report an error "Issue does not exist or you do not have permission to see it" when I am running jira plugin. And I'm confirmed that I have permission to all jira issues.

### What you expected to happen

It shouldn't report error.

### How to reproduce

Not sure.

## Snapshots
![origin_img_v2_08aaa3bf-6483-4f18-8acd-bb07539fa26g](https://user-images.githubusercontent.com/11383928/174071253-5ee4ddab-7277-4c0d-be33-6d360499ef77.png)

## Logs
![5dgvVlALFi](https://user-images.githubusercontent.com/11383928/174071350-3d9a716a-b3b3-4eee-a6c4-1fe965eadd8d.jpg)

### Version

main

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by narrowizard** [comment]
Maybe the issue has been deleted when syncing jira data.

**Comment by klesh** [comment]
I'm not sure if we could fix this.
Especially when it is unreproducible.

**Comment by narrowizard** [comment]
I have exported the `_devlake_pipelines` table's data.  
[tasks.csv](https://github.com/apache/incubator-devlake/files/8924076/tasks.csv)
