### ISSUE TITLE
[Bug] [Init] Developer Setup on OSX: `make dev` Run Error

### ISSUE THREAD

**Issue by e2corporation** [apache/incubator-devlake#2233]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

Upon rebasing the latest Changes on `main` branch, upgrading to Go v1.17 using Homebrew on OSX, and following the developer setup guide as outlined on the Apache DevLake wiki, `make dev` throws a panic and results in a `make` `Error`. See below for developer log.

```
shogun@z06 lake % make dev
Usage: 
  build all plugins:              scripts/compile-plugins.sh [golang build flags...]
  build and keep one plugin only: PLUGIN=jira scripts/compile-plugins.sh [golang build flags...]
Building plugin ae to bin/plugins/ae/ae.so
Building plugin dbt to bin/plugins/dbt/dbt.so
Building plugin feishu to bin/plugins/feishu/feishu.so
Building plugin gitextractor to bin/plugins/gitextractor/gitextractor.so
Building plugin github to bin/plugins/github/github.so
Building plugin gitlab to bin/plugins/gitlab/gitlab.so
Building plugin icla to bin/plugins/icla/icla.so
Building plugin jenkins to bin/plugins/jenkins/jenkins.so
Building plugin jira to bin/plugins/jira/jira.so
Building plugin refdiff to bin/plugins/refdiff/refdiff.so
Building plugin tapd to bin/plugins/tapd/tapd.so
go run main.go
[2022-06-16 12:04:03]  INFO failed to create dir logs: mkdir logs: file exists
[2022-06-16 12:04:04]  INFO  [plugin] plugin loaded ae
[2022-06-16 12:04:04]  INFO  [plugin] plugin loaded dbt
[2022-06-16 12:04:04]  INFO  [plugin] plugin loaded feishu
[2022-06-16 12:04:04]  INFO  [plugin] plugin loaded gitextractor
[2022-06-16 12:04:05]  INFO  [plugin] plugin loaded github
[2022-06-16 12:04:05]  INFO  [plugin] plugin loaded gitlab
[2022-06-16 12:04:05]  INFO  [plugin] plugin loaded icla
[2022-06-16 12:04:05]  INFO  [plugin] plugin loaded jenkins
[2022-06-16 12:04:05]  INFO  [plugin] plugin loaded jira
[2022-06-16 12:04:06]  INFO  [plugin] plugin loaded refdiff
[2022-06-16 12:04:06]  INFO  [plugin] plugin loaded tapd
panic: encKey is required

goroutine 1 [running]:
github.com/apache/incubator-devlake/services.init.0()
	/Users/shogun/public_html/lake/services/init.go:63 +0x42b
exit status 2
make: *** [run] Error 1
```

### What you expected to happen

DevLake API should startup successfully and accept connections.

### How to reproduce

Run `make dev` under OSX Environment with an brand new Devlake MySQL Container Instance.

### Anything else

This may impact OSX Developer workflow on `main` branch. This could be environment related but it has to be ruled out by other OSX users.

### Version

main

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by e2corporation** [comment]
This appears to be related to `ENCODE_KEY` env var setting and the Decrypt call not able to find `encKey`

**Comment by abeizn** [comment]
I executed the process a few times and it worked, maybe someone updated it in the middle and then the issue stopped recurring. Can you pull down the latest code and re-execute it? If there are still questions, please contact me promptly.

**Comment by e2corporation** [comment]
@abeizn Did you have a chance to try this on a brand new docker mysql container? (ie new developer setup)

**Comment by abeizn** [comment]
> @abeizn Did you have a chance to try this on a brand new docker mysql container? (ie new developer setup)

of course,  I delete the mysql image, and docker image pull mysql ,  and git clone new repo, and docker-compose up -d mysql grafana, and copy env.exemple .env (mysql->127.0.0.1),  then retry(make dev).   it worked.

1. detele mysql image
2. docker image pull mysql 
![image](https://user-images.githubusercontent.com/101256042/174311512-426a0145-8d86-4a44-9c09-3cfc0cc7c2c1.png)
3. git clone new repo
![image](https://user-images.githubusercontent.com/101256042/174312513-f5b28ff0-b5e0-4467-aacb-b33b552068bc.png)

4. make dev
![image](https://user-images.githubusercontent.com/101256042/174312590-5e7458f3-9700-415e-9c72-8d64313ecca7.png)

**Comment by e2corporation** [comment]
@abeizn Also can you try from our forked repo? I am working on a feature branch rebased from `main` branch on `merico-dev/lake`. I wonder if our fork is out of date which is causing the issue?

**Comment by abeizn** [comment]
> @abeizn Interesting thanks for double checking, I will destroy all containers and try again but I'm also curious as to what `.env` file you are using? Have you tried this using the `.env.example` file as a reference? What is the initial value for `ENCODE_KEY` for new users? Is this value set by the user initially?

yes, i used the .env.example file as a reference. and the ENCODE_KEY has no value.

**Comment by abeizn** [comment]
> @abeizn Also can you try from our forked repo? I am working on a feature branch rebased from `main` branch on `merico-dev/lake`. I wonder if our fork is out of date which is causing the issue?
I will try it now.

**Comment by abeizn** [comment]
> @abeizn Also can you try from our forked repo? I am working on a feature branch rebased from `main` branch on `merico-dev/lake`. I wonder if our fork is out of date which is causing the issue?

i try it ,and it worked.
![image](https://user-images.githubusercontent.com/101256042/174321105-f5f23bef-470a-4936-99f5-423061be8f44.png)

![image](https://user-images.githubusercontent.com/101256042/174321337-86784596-c545-4ca8-98d0-9f28d0df5a16.png)

**Comment by e2corporation** [comment]
Always this result for me....

```
make dev
Usage: 
  build all plugins:              scripts/compile-plugins.sh [golang build flags...]
  build and keep one plugin only: PLUGIN=jira scripts/compile-plugins.sh [golang build flags...]
Building plugin ae to bin/plugins/ae/ae.so
Building plugin dbt to bin/plugins/dbt/dbt.so
Building plugin feishu to bin/plugins/feishu/feishu.so
Building plugin gitextractor to bin/plugins/gitextractor/gitextractor.so
Building plugin github to bin/plugins/github/github.so
Building plugin gitlab to bin/plugins/gitlab/gitlab.so
Building plugin icla to bin/plugins/icla/icla.so
Building plugin jenkins to bin/plugins/jenkins/jenkins.so
Building plugin jira to bin/plugins/jira/jira.so
Building plugin refdiff to bin/plugins/refdiff/refdiff.so
Building plugin starrocks to bin/plugins/starrocks/starrocks.so
Building plugin tapd to bin/plugins/tapd/tapd.so
go run main.go
[2022-06-17 11:12:00]  INFO failed to create dir logs: mkdir logs: file exists
[2022-06-17 11:12:00]  INFO  [plugin] plugin loaded ae
[2022-06-17 11:12:00]  INFO  [plugin] plugin loaded dbt
[2022-06-17 11:12:01]  INFO  [plugin] plugin loaded feishu
[2022-06-17 11:12:01]  INFO  [plugin] plugin loaded gitextractor
[2022-06-17 11:12:01]  INFO  [plugin] plugin loaded github
[2022-06-17 11:12:01]  INFO  [plugin] plugin loaded gitlab
[2022-06-17 11:12:02]  INFO  [plugin] plugin loaded icla
[2022-06-17 11:12:02]  INFO  [plugin] plugin loaded jenkins
[2022-06-17 11:12:02]  INFO  [plugin] plugin loaded jira
[2022-06-17 11:12:02]  INFO  [plugin] plugin loaded refdiff
[2022-06-17 11:12:02]  INFO  [plugin] plugin loaded starrocks
[2022-06-17 11:12:03]  INFO  [plugin] plugin loaded tapd
panic: encKey is required

goroutine 1 [running]:
github.com/apache/incubator-devlake/services.init.0()
	/Users/shogun/public_html/lake/services/init.go:63 +0x42b
exit status 2
make: *** [run] Error 1

```

**Comment by abeizn** [comment]
https://github.com/apache/incubator-devlake/pull/2239 this PR may help to solve the above problem.

**Comment by abeizn** [comment]
@e2corporation it is ok now? Can the issue be closed?
