### ISSUE TITLE
[Bug] [config-ui] subtask is missing

### ISSUE THREAD

**Issue by abeizn** [apache/incubator-devlake#2234]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

when i finished issue #1412 "rename tasks to subtasks and move it to outer level."  the configure-ui needs to be adapted. because the subtasks is missing.
`[
  [
    {
      "plugin": "github",
      "subtasks":  ["convertCommits"]
      "options": {
        "repo": "lake",
        "owner": "merico-dev"
      }
    }
  ]
]`

1. when i run pipeline at config-ui. Here you can see the execution parameters.
![image](https://user-images.githubusercontent.com/101256042/174212939-df1260b1-5366-48ac-9238-af34614b56d9.png)
![image](https://user-images.githubusercontent.com/101256042/174212972-620fd5f3-9649-4656-92cc-544008d072d3.png)

2. but, re-into advanced mode, you can see
![image](https://user-images.githubusercontent.com/101256042/174213048-fd3d90a0-8433-497c-9507-937dc6758b3e.png)

so i think the config-ui need to adapt the  issue #1412.

### What you expected to happen

the subtask parameter Should not be missing.

### How to reproduce

run main branch in advanced mode. 

### Version

main

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by klesh** [comment]
No longer needed
