### ISSUE TITLE
[Feature][config-ui] embeddable config-ui

### ISSUE THREAD

**Issue by GerilLeto** [apache/incubator-devlake#2241]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

config-ui is currently a standalone website service.
In most cases, users have to visit config-ui to get lake running properly.

However, some users might prefer or need to integrate lake's config-ui into their own systems, and possibly only integrate parts that they need.

In our team, a work-around solution is building an alternative config-ui(form parts), which is seamlessly integrated with other configuration forms of our system, and has highly similar functionalities to lake's config-ui.

But this work-around won't last, since lake's config-ui is constantly growing with more features and our team cannot keep our mimic work always up-to-date

### Use case

A standalone package of config-ui's forms, without router or any other website functionalities

Systems that use lake could integrate config-ui's form as a react component.

no more mimicking, and one less service to deploy

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by e2corporation** [comment]
@GerilLeto While this can be useful I think the effort to reward ratio is low, and costly to maintain. In theory, users can already create their own user interface for DevLake by following the API documentation and understanding what API resources are provided. They could also use their own own toolstack with Angular or React or any framework and build a proprietary interface to suit their own needs.

**Comment by mintsweet** [comment]
I think it's very important to be able to nest config-ui, users don't need to maintain two sets of configuration pages, so I will start a PR to do this.
