### ISSUE TITLE
[Doc][Dashboard] Add a 'How to Create a Dashboard' doc

### ISSUE THREAD

**Issue by Startrekzky** [apache/incubator-devlake#2248]
## Documentation Scope
Add a 'How to Create a Dashboard' doc to replace  https://devlake.apache.org/docs/UserManuals/GRAFANA in the website.

## Content of the doc
![image](https://user-images.githubusercontent.com/14050754/174328508-f6966def-f103-4929-bdd9-f4503f934167.png)

**Comment by yumengwang03** [comment]
We still need to work on this.
