### ISSUE TITLE
[Feature][Config UI] Showing notifications in browser when a blueprint finishes running

### ISSUE THREAD

**Issue by yumengwang03** [apache/incubator-devlake#2251]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

It's better to show notifications in browser when a blueprint finishes running since users might not be waiting on the blueprint detail page.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by yumengwang03** [comment]
We will keep this.

**Comment by e2corporation** [comment]
There was a previously developed **Pipeline Indicator Widget** that displayed on UI if a running pipeline was detected. This will be restored in order to accommodate this feature.

**Comment by e2corporation** [comment]
<img width="969" alt="Screen Shot 2022-08-26 at 9 37 09 PM" src="https://user-images.githubusercontent.com/1742233/187009204-03fd9265-2a6f-4ca1-89ac-dae6c089591d.png">
<img width="912" alt="Screen Shot 2022-08-26 at 9 37 04 PM" src="https://user-images.githubusercontent.com/1742233/187009205-ede9094f-f437-41d3-b4e5-2012f7fdd407.png">

**Comment by mintsweet** [comment]
> @mintsweet This is another feature you can work on next, the Pipeline Indicator widget as active on V11 Release, we'll need to restore it on the "**Blueprints**" Page and "_Blueprint Status_" Page and potentially other areas of the app where we'd want the user to be aware that there is a running pipeline.
> 
> Essentially, if there is a Running pipeline detected (filter all pipelines results), the **Pipeline Indicator** Widget will be activated so users are aware that there is a running pipeline. See Component `src/components/widgets/PipelineIndicator.jsx`.
> 
> The Widget will likely need updating as the schema of the Pipeline and related Task structure may have changed.
> 
> * [ ]  Re-Implement `src/components/widgets/PipelineIndicator.jsx`
> * [ ]  Apply Styling & UX Updates

OK, I'll take a closer look at this task later.

**Comment by mintsweet** [comment]
hi @yumengwang03, I'm not sure if this issue is still going to be done.
