### ISSUE TITLE
[Doc][Metrics] Update the structure of 'Engineering Metrics' doc for better display

### ISSUE THREAD

**Issue by Startrekzky** [apache/incubator-devlake#2252]
## Documentation Scope
https://devlake.apache.org/docs/EngineeringMetrics

## Describe the Change

- [x] Change the table to small sections  
- [x] Each section contains 
        - Metric definition/value/use case
        - Queries
        - Panel settings
        - Screenshots

## Screenshots
![image](https://user-images.githubusercontent.com/14050754/174329809-00f01be6-20d6-400d-8567-6ae2f1b97d3c.png)

**Comment by aggmoulik** [comment]
Hey @Startrekzky If you are not working on this, I would love to work on it.

**Comment by Startrekzky** [comment]
> Hey @Startrekzky If you are not working on this, I would love to work on it.

Thanks @aggmoulik . Sorry for the late reply. I've already started on this.

**Comment by Startrekzky** [comment]
Closed. The content for these metrics will be updated via issue #2756 #2729
