### ISSUE TITLE
[GitLab] table.issues and pull_requests lack creator_id, author_id, etc.

### ISSUE THREAD

**Issue by Startrekzky** [apache/incubator-devlake#2268]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

After the collection of GitLab data, the domain layer seemed not so 

- [x] table.issues lacks the values of `creator_id`, `creator_name`, and `assignee_id` resolved by #2396 
- [ ] table.pull_requests lacks the values of `author_id`
- [ ] mr_notes in the tool layer doesn't show in the domain layer table pull_request_comments

### What you expected to happen

- [ ] `creator_id`, `creator_name`, and `assignee_id` have values in table.issues. `creator_id` is the FK to table.accounts  (table.users before v0.12)
- [ ] `author_id` has value, and is the FK  to table.accounts (table.users before v0.12)
- [ ] mr_notes from GitLab appeared in table.pull_request_comments
- [ ] add a column `type` in domain layer's table.pull_request_comments, please see the value assignment logic in the section 'Definition of GitLab comments'.

### How to reproduce

1. setup DevLake v0.11
2. collect any GitLab repo

### Definition of GitLab comments
1. Gitlab consists of 2 types of comments:
   a. normal comments: type = null, system = false 
     ![image](https://user-images.githubusercontent.com/14050754/175992626-a21aaac5-7035-46c2-beda-bfc0badbf6f0.png)
   b. diff comments: type = diffNote, system = false
     ![image](https://user-images.githubusercontent.com/14050754/175992767-16d842f0-8507-402a-9573-0b3fb136ab50.png)

2. For values of the `type` field in table.pull_request_comments
   a. for normal comments: if it can't be set to null then empty string
   b. for diff comments: DIFF
   c. for review comments (exist in GitHub but not GitLab, see pic below): REVIEW
     ![image](https://user-images.githubusercontent.com/14050754/175993786-7e61c226-e288-4d82-b00a-bb29829a4022.png)

### Anything else

related to #2126

### Version

main

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by warren830** [comment]
This is a test @warren830

**Comment by klesh** [comment]
@warren830 can u receive the notification email from githbub

**Comment by thenicetgp** [comment]
I will take this one
