### ISSUE TITLE
[Jira] issues.creator_name is empty

### ISSUE THREAD

**Issue by Startrekzky** [apache/incubator-devlake#2269]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

issues.creator_name is empty when issues are collected and transformed from the Jira plugin.

### What you expected to happen

issues.creator_name is populated with jira issue creator's name.

### How to reproduce

1. setup DevLake v0.11
2. collect any Jira scrum board

### Version

main

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by abeizn** [comment]
Fixed and verified in v0.12.0.
![image](https://user-images.githubusercontent.com/101256042/175898060-dcc5fa71-6fcc-4ed7-8b07-e7f329f79f0d.png)
