### ISSUE TITLE
[Jira] Part of Jira cloud users' emails are not shown in the table.users (the future table.accounts)

### ISSUE THREAD

**Issue by Startrekzky** [apache/incubator-devlake#2270]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

After collecting data from Jira(cloud), only part of users' emails is shown in the table.users (the future table.accounts). It might have something to do with the domain of user emails.

In my case, users with emails like 'xxx@meri.co' have no emails in table.users; 
while users with emails like 'xxx@merico.com' have emails in table.users.

### What you expected to happen

All users from Jira(cloud) have email info in the table.users (the future table.accounts).

### How to reproduce

1. setup DevLake v0.11
2. collect Jira data
3. see table.users

### Version

main

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by mindlesscloud** [comment]
To address this problem:
1. the involved user should set `Profile and visibility` properly (https://id.atlassian.com/manage-profile/profile-and-visibility)
2. recollect data
