### ISSUE TITLE
[GitLab] Collect a large number of data scope easier in the config-UI

### ISSUE THREAD

**Issue by Startrekzky** [apache/incubator-devlake#2271]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Copied from #2069 

"The granularity of operations can be larger
using project-id to import gitlab data is real time-consuming. We want to import all data and show it in a dashboard with high level."

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Startrekzky** [comment]
@e2corporation  Can you take a look at the GitLab API to see how can we get the full Gitlab project list? Thanks.

**Comment by klesh** [comment]
> @Startrekzky @klesh Backend would have to first implement an **API Proxy** for Gitlab (like we currently do with JIRA) to provide api access to the list of projects, then frontend can access this information via `GET /api/proxy/gitlab/projects` to provide support on UI.

We may have to do so type-to-search for this, gitlab is an open-source hosting platform, so the total number of projects would be huge.

**Comment by yumengwang03** [comment]
I'll work on this

**Comment by yumengwang03** [comment]
The design is here: https://www.figma.com/file/Eux4Dhorxp7M0TwzOnL6Yh/Config-UI-for-V1.0?node-id=1567%3A15498
However, it needs to be reviewed.

**Comment by yumengwang03** [comment]
Here's the figma link. This feature is reviewed and ready for front end.

https://www.figma.com/file/Eux4Dhorxp7M0TwzOnL6Yh/Config-UI-for-V1.0?node-id=1978%3A9305

**Comment by yumengwang03** [comment]
I've divided this issue into two: #3670 #3671 , and will post progress in these two issues instead of here.

**Comment by Startrekzky** [comment]
This will be implemented in #3670
