### ISSUE TITLE
[Bug][grafana] The customized icon not showing, while visit grafana dashboard with the url /prefix

### ISSUE THREAD

**Issue by matrixji** [apache/incubator-devlake#2279]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

1. Install/deploy devlake with helm chart. (Enable ingress)
2. And when ingress is enabled, the grafana dashboard will use a /grafana prefix for the URL.
3. Configure some pipelines to collect some data.
4. Some icon's URL is not visible(Grafana), see the below screenshot.

![image](https://user-images.githubusercontent.com/183388/174710216-45f372ed-ffc8-4bfa-b68f-ded207fb6b91.png)

And I'm trying to modify the URL to a relative path(remove the leading /), and it seems to work, I'm not an expert on the frontend, so some frontend exports to fix it.
![image](https://user-images.githubusercontent.com/183388/174710493-e7c40ec7-9030-4b0a-8d64-b0036c110850.png)

### What you expected to happen

The icons should be visible while deploying with helm as well as with NodePort.

### How to reproduce

See above

### Anything else

N/A

### Version

main

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Startrekzky** [comment]
Thanks for issuing the bug @matrixji

**Comment by abeizn** [comment]
@matrixji 
1. "image: mericodev/grafana:latest" ,  when user push the latest tag(https://hub.docker.com/r/mericodev/grafana/tags)，the image will be updated. same is apache images and some is devlake images, so the problem is coming. 
2. update " /public/img/lake/*.png " to " public/img/lake/*.png ", i try it. But it does not work. maybe it's due to cookie.

**Comment by matrixji** [comment]
I have some try deploying with 3 different methods by this weekend.

- Deploy with helm using ingress, and in such case, grafana will be published at https://domain/grafana/
- Deploy with helm using NodePort, and in such case grafana will be published at http://domain:port/
- Deploy local with docker-compose, and grafana will be published at http://127.0.0.1:3002/

For case 1 (helm with ingress), the grafana will finally have the below code in head.
```html
<base href="/grafana/">
```

And for case 2/3, the code will be:
```html
<base href="/">
```

So for my understanding change to `/public/img/lake/.png` to `public/img/lake/.png` should be OK for all cases.

**Comment by abeizn** [comment]
> I have some try deploying with 3 different methods by this weekend.
> 
> * Deploy with helm using ingress, and in such case, grafana will be published at https://domain/grafana/
> * Deploy with helm using NodePort, and in such case grafana will be published at http://domain:port/
> * Deploy local with docker-compose, and grafana will be published at http://127.0.0.1:3002/
> 
> For case 1 (helm with ingress), the grafana will finally have the below code in head.
> 
> ```
> <base href="/grafana/">
> ```
> 
> And for case 2/3, the code will be:
> 
> ```
> <base href="/">
> ```
> 
> So for my understanding change to `/public/img/lake/.png` to `public/img/lake/.png` should be OK for all cases.

I will try it, if "public/img/lake/.png" work, I will fix it,  By the way, what OS are you？

**Comment by abeizn** [comment]
Unfortunately, it doesn't work after I remove prefix "/" by "Deploy local with docker-compose"
This is my operation steps. my os is MacOs M1.
1. update /public/img/lake/.png to public/img/lake/.png 
2. make dev, and make configure-dev
3. open grafana, import updated `DemoHomepage.json`, This is to make sure grafana is in effect.
![image](https://user-images.githubusercontent.com/101256042/177073931-33470940-cced-4d85-9281-a2ea96ceadae.png)
4. I updated  
         "/public/img/lake/customer.png" to "public/img/lake/customer.png" 
    and 
         "/public/img/lake/demo_quality.png" to "public/img/lake/demo_quality.png"
   in DemoHomePage.json.

![image](https://user-images.githubusercontent.com/101256042/177074510-5b3a7a23-a306-4184-bd12-863227b881d4.png)

6. results screenshots: customer and demo_quality do not work.
![image](https://user-images.githubusercontent.com/101256042/177074265-6033f7a9-b95e-44dc-a3d4-03947681c689.png)

Can you make sure that the DemoHomePage.json in your grafana  is up to date or correct?

**Comment by matrixji** [comment]
I'm using a Linux server to deploy for it, I have an M1 based Macbook, I'll try using `make configure-dev` on it to have more investigation.

**Comment by klesh** [comment]
Note that in `config-ui/nginx.conf`, we have the following section:

```
  location /grafana {
    rewrite /grafana(.*)$ ${GRAFANA_ENDPOINT}$1;
  }
```

which effectively redirect URL path starts with `/grafana` to another
host defined by `GRAFANA_ENDPOINT` environment variable of the
container, and the prefix `/grafana` would be trimmed. i.e.

let say, for `config-ui` container, the `GRAFANA_ENDPOINT` is set to
`http://grafana`.
when a user try to access `http://config-ui/grafana/hello_world`, he/she
would be redirected to `http://grafana/hello_world`

**Comment by matrixji** [comment]
Information updates. Retry with import JSON on grafana. After importing the modified JSON, the HTML element tree is shown below in devtool.
![image](https://user-images.githubusercontent.com/183388/177494799-a362ad9f-b263-4c16-8647-76c09c6ebb34.png)

**Comment by abeizn** [comment]
>  @matrixji  which method？
1. Deploy with helm using ingress, and in such case, grafana will be published at https://domain/grafana/
2. Deploy with helm using NodePort, and in such case grafana will be published at http://domain:port/
3. Deploy local with docker-compose, and grafana will be published at http://127.0.0.1:3002/

**Comment by matrixji** [comment]
> > @matrixji  which method？
> 
> 1. Deploy with helm using ingress, and in such case, grafana will be published at https://domain/grafana/
> 2. Deploy with helm using NodePort, and in such case grafana will be published at http://domain:port/
> 3. Deploy local with docker-compose, and grafana will be published at http://127.0.0.1:3002/

I'm using helm with ingress, it' seems grafana could not support import JSON with the relative path in `src` here.
So maybe simply changing `/path` -> `path` in JSON is not a good solution.

**Comment by abeizn** [comment]
> > > @matrixji  which method？
> > 
> > 
> > 
> > 1. Deploy with helm using ingress, and in such case, grafana will be published at https://domain/grafana/
> > 2. Deploy with helm using NodePort, and in such case grafana will be published at http://domain:port/
> > 3. Deploy local with docker-compose, and grafana will be published at http://127.0.0.1:3002/
> 
> I'm using helm with ingress, it' seems grafana could not support import JSON with the relative path in `src` here. So maybe simply changing `/path` -> `path` in JSON is not a good solution.

Okey, so do you think the helm installation method is not compatible with grafana? 
Need to change some configuration in helm to fix it or other?

**Comment by matrixji** [comment]
> > > > @matrixji  which method？
> > > 
> > > 
> > > 
> > > 1. Deploy with helm using ingress, and in such case, grafana will be published at https://domain/grafana/
> > > 2. Deploy with helm using NodePort, and in such case grafana will be published at http://domain:port/
> > > 3. Deploy local with docker-compose, and grafana will be published at http://127.0.0.1:3002/
> > 
> > 
> > I'm using helm with ingress, it' seems grafana could not support import JSON with the relative path in `src` here. So maybe simply changing `/path` -> `path` in JSON is not a good solution.
> 
> Okey, so do you think the helm installation method is not compatible with grafana? Need to change some configuration in helm to fix it or other?

Maybe, I'm not sure, I'd like to have some investigation on it to find a suitable solution, will be updated here later.

**Comment by klesh** [comment]
Looking forward to the solution 😃

**Comment by matrixji** [comment]
Similar to this issue: https://github.com/grafana/grafana/issues/21400
So my suggestion is proxy `http://domain/public/.*` -> `http://domain/grafana/public/.*`, and `http://domain/d/.*` -> `http://domain/grafana/d/.*`. Currently seems /public and /d are not used for config-ui.

I've tested success with my demo site: https://devlake-0.jibin.net:8443/grafana/d/0Rjxknc7z/demo-homepage?orgId=1 (Not always available)

**Comment by abeizn** [comment]
Currently, seems /public and /d are not used for config-ui. 
----------------------------------------------------------
Thank you for your suggestions. I don't quite understand what this sentence means? Does it mean that config-ui cannot be used after the change?

**Comment by klesh** [comment]
Thanks for your work, very valuable.
I would discuss with others on Monday since it would affect the other
parts of the system.

**Comment by klesh** [comment]
One more thing, would you mind summing up the whole situation and send a
mail to ***@***.*** for open discussion?
It would help a lot, Thanks in advance.

**Comment by klesh** [comment]
> ## Currently, seems /public and /d are not used for config-ui.
> Thank you for your suggestions. I don't quite understand what this sentence means? Does it mean that config-ui cannot be used after the change?

I think the whole point is to use `reverse proxying for grafana` instead of `redirecting to grafana`.

**Comment by matrixji** [comment]
Information for helm deployment:

Tested with master helm chart, it shows the Icons in default grafana's Home. So no adaptation is needed for the helm chart.

The screen shot for deploy with helm and grafana in latest master:

<img width="1048" alt="截屏2022-07-15 17 13 53" src="https://user-images.githubusercontent.com/183388/179193382-38810b5b-98ec-439f-a82c-e076f6a1bede.png">

Great thanks for all guys handling this issue.
