### ISSUE TITLE
[Feature][SonarQube] Integration SonarQube

### ISSUE THREAD

**Issue by summergan** [apache/incubator-devlake#2305]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

I hope to integrate Sonarqube into Devlake.
The following data can be obtained:
1. The rating of individual code
2. The issues(Bugs/Code Smells/Vulnerabilities) of individual code
3. The duplications lines of individual code

### Use case

The following data can be obtained:
1. The rating of individual code
2. The issues(Bugs/Code Smells/Vulnerabilities) of individual code
3. The duplications lines of individual code

### Related issues

N/O

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Startrekzky** [comment]
Thanks @summergan , this is on our [roadmap](https://devlake.apache.org/docs/Overview/Roadmap). Thanks for the proposal.

**Comment by aggmoulik** [comment]
Hey @Startrekzky I would love to work on a plugin for this, I just have same questions about this.

> What kind of metrics do you want to see from SonarQube?
How would you plan to use it after SonarQube is supported?

**Comment by summergan** [comment]
![image](https://user-images.githubusercontent.com/38934767/177237678-bb728aad-74da-4d46-9bc8-2f821159ab40.png)
hi, I can get overall code metrics including Bugs, Vulnerabilities, and so on in SonarQube Dashboard. I hope I can get each developer's data。
e.g. Developer A, development of two projects. Here hope can get the total bugs, Bugs, Vulnerabilities, and so on (Maybe can follow up on Dashboard data)

**Comment by Startrekzky** [comment]
Thanks @summergan , this is super helpful. Please take a look. @aggmoulik

**Comment by Startrekzky** [comment]
Hi @aggmoulik ,  I've collected requirements from the community members and most of the requirements are similar to what @summergan commented above. 

Have you started on this ticket? If not, I suggest coming up with the data schema for SonorQube first, since DevLake doesn't have the data schema for a quality-domain tool like SonarQube. You can draw a diagram for SonarQube and put it in the comment section so that we can discuss. This is [Apache DevLake's current domain layer schema](https://devlake.apache.org/docs/DataModels/DevLakeDomainLayerSchema) for your reference.

**Comment by ganeshcpote** [comment]
is there any update on this plug-in?

**Comment by mindlesscloud** [comment]
@aggmoulik hi, how things are going?

**Comment by klesh** [comment]
@Startrekzky FYI

**Comment by Startrekzky** [comment]
> is there any update on this plug-in?

I guess the answer is no, so this might be the one plugin we're going to support in the following season.

**Comment by klesh** [comment]
This issue had been added to milestone v0.16,  someone else will be working on it soon since @aggmoulik hasn't responded for quite a while.

**Comment by Startrekzky** [comment]
Hi @summergan @aggmoulik @ganeshcpote , SonarQube v8.2+ has been supported in v0.16+, please check the [latest tag](https://github.com/apache/incubator-devlake/releases).
