### ISSUE TITLE
[Bug][runner] DirectRun failed to generate `encKey` automatically 

### ISSUE THREAD

**Issue by klesh** [apache/incubator-devlake#2332]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

According to @keon94 , when he tried to launch Github with DirectRun, it failed due to `encKey` being empty.

### What you expected to happen

`encKey` should be generated automatically when it was empty in DirectRun mode.

### How to reproduce

Not sure.

### Version

main

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by mappjzc** [comment]
@keon94 
I try to generate encKey automatically on DirectRun,but there is a contradiction:
As follows
![image](https://user-images.githubusercontent.com/2921251/175931105-d2b1e8a6-9a2d-4366-9f7b-e971cf42e7e7.png)
We can see that connectionId was required if you want DirectRun on github plugin.
So it means you have to set at least one connection before do DirectRun.
If you had already create one conntion,that must have a enckey.And if you lost the enckey,It is useless to generate encKey automatically.
So you have to post an connection at first before you try DirectRun.
I created an issue  #2362 For if you want create connection by DirectRun on feature.
