### ISSUE TITLE
[Feature][gitee] add config-ui for gitee plugin 

### ISSUE THREAD

**Issue by SnowMoon-Dev** [apache/incubator-devlake#2342]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

add config-ui for gitee plugin 

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by warren830** [comment]
Great！
