### ISSUE TITLE
[Refactor][plugin helper] rename `connection.RateLimit` to `connection.RateLimitPerHour`

### ISSUE THREAD

**Issue by klesh** [apache/incubator-devlake#2360]
## What and why to refactor
![image](https://user-images.githubusercontent.com/61080/175897878-6f043483-0605-4a4c-8852-20e5d618788d.png)
Without `unit`, the `RateLimit` itself is ambiguous

## Describe the solution you'd like
rename `connection.RateLimit` to `connection.RateLimitPerHour`

## Related issues
#931

**Comment by phzbbbbbbbb** [comment]
Please assign it to me.

**Comment by warren830** [comment]
> Please assign it to me.

Happy coding!
