### ISSUE TITLE
[Feature][team] Team feature solution (stage 1)

### ISSUE THREAD

**Issue by klesh** [apache/incubator-devlake#2361]
### Description

As we discussed on #1680 and https://lists.apache.org/thread/qx6r0pdq5x9jt099ljk1p91dh763ov84
The final conclusion were:

## Table Solution (framework)

1. Existing `users` is to be renamed to `accounts` and moved to `domainlayer/crossdomain` package, it contains registration records from different platforms
2. Add a new table `users` (id varchar,name,email) in `domainlayer/crossdomain`, it contains unique identities, each identity may have multiple `accounts`
3. Add a new table `user_accounts` in `domainlayer/crossdomain`, it contains the relationship between `users` and `accounts`, note that `user_accounts` is a One-To-Many relationship, the PK should be `account_id`
4. Add a new table `teams` in `domainlayer/crossdomain`.
5. Add a new table `team_users` in `domainlayer/crossdomain`, it contains the Many2Many relationship between `users` and `teams`.

Check [Final Data Schema](https://github.com/apache/incubator-devlake/issues/2361#issuecomment-1169616747) for detail

## Plugin Solution (named `org`)

1. API `GET /pulgins/org/users.csv?fake_data=true|false` return a CSV file, when `fake_data=true` return a prebuilt file contains some example data (should be reviewed by @Startrekzky), otherwise, it should contains all records from `users` table with an extra field named `team_ids` (semicolon-separated).
2. API `PUT /plugins/org/users.csv` accepts a CSV file, it should contain all the fields from the `users` table, along with an extra field `team_ids` which is a comma-separated list of the names of teams the `user` belongs to. API should valid the file, and reset `users` and `team_users` table accordingly.
3. API `GET /plugins/org/accounts.csv` renders `accounts`(all fields) + `user_accounts`(user_id) table in CSV format. the API should take care of the escaping, uses UTF-encoding, and set up the header respectively.
4. API `PUT /plugins/org/accounts.csv` accepts a CSV file that has the same construct from the previous API. API should validate the uploaded file, then reset `accounts` and `user_accounts` tables accordingly.
5. API `GET /plugins/org/teams.csv?fake_data=true|false` acts the same way as the 1st API but for `teams`  table.
6. API `PUT /plugins/org/teams.csv` acts the same way as the 2nd API, but for `teams` table.
7. Subtask `connectUserAccountsExact`, which would create `user_accounts` records based on `email` `name` information.

## ConfigUI Solution

No config-ui support at this point according to @Startrekzky and @yumengwang03

### Related issues
1. #1680
2. #2426 
3. #2427 
4. #2428 
5. #2429 
6. #2430 
7. #2431 
8. #2477
9. #2445

**Comment by yumengwang03** [comment]
We don't need UI for the first iteration, so design will wait until it's needed.

**Comment by Startrekzky** [comment]
## Pre-mapping logic for generating `account.csv`
I suggest that we implement 'exact match' in v0.12.0, and fuzzy match according to user feedback in the following releases. What do you think? @klesh @yumengwang03 @hezyin 

1. Based on all the `emails` in table.users, find the records under table.accounts that match the `email` field exactly.
   a) relate accounts.id to users.email, and write the relationship between accounts.id and users.id to table.user_accounts, i.e. (U001, a1), (U001, a2), (U002, a3), (U004, a4), (U005, a5), ( U005, a6) in the following pic.
   b) the accounts.id not associated to users.email will be the next matching range, i.e. (a7, a8, a9, a10).
2. Based on all the `names` in table.users, find the exact match of the `full_name` field under table.accounts for the remaining table.accounts in step 1
   a) write the relationship between accounts.id and users.id to table.user_accounts, i.e. (U005, a7), (U008, a8)
   b) the accounts.id not associated to users.name will be the next matching range, i.e. (a9, a10).
3. Based on all the names in table.users, find the exact match of the `user_name` field under the remaining table.accounts in step 2.
   a) associate accounts.id to users.name, and relate accounts.id to users.id to table.user_accounts, i.e. (U010, a10)
   b) accounts.id not associated to users.name, i.e. a9, is not associated to any existing users. in addition, (U003, U006, U007) in table.users is also not associated to any accounts.id.

An example:<br/>
![image](https://user-images.githubusercontent.com/14050754/176224502-6db9d0f8-daa2-4338-a05f-ddd8fce8a149.png)

**Comment by Startrekzky** [comment]
## Final Data Schema
Please take a look. @klesh @yumengwang03 @hezyin @liangjingyang 

1. **table.accounts** 
    | field                    | type       | length     | description | key |
    | ----------------| -------- | --------- | ----------- | ------ |
    | `id`                    | varchar  | 255          | a user's `id` is composed of "< Plugin >:< Entity >:< PK0 >[:PK1]..."<br/>For example, a Github user's id is composed of "< github >:< GithubUsers >< GithubUserId)". Eg. 'github:GithubUsers:14050754' | PK       |
    | `email`               | varchar  | 255         | email of the account  |         |
    | `full_name`         | varchar  | 255       | full name  |         |
    | `user_name`     | varchar  | 255         | username/nickname or Github login of an account |         |
    | `avatar_url`       | varchar  | 255         |            |   |
    | `organization`   | varchar  | 255         | organization or company name                           |         |
    | `created_date` | datetime | 3             | account creation time                   |         |
    | `deleted`           | tinyint     |                 | 0: default. The user is active 1: the user is no longer active |         |

2. **table.users**
    | field      | type | length | description | key|                                                                                                                                              
    | ------------- | ------- | --------- | ----------- | ------ |
    | `id`  | varchar | 255        | id of a person | PK  |
    | `email`  | varchar | 255       | the primary email of a person | PK  |
    | `name`  | varchar | 255       | name of a person | PK  |

3. Output-3: a **table.user_accounts**
    | field                | type       | length    | description | key  |                                                                                                                                              
    | ------------- | -------- | -------- | ----------- | -----|
    | `user_id`       | varchar  | 255        | users.id    | FK    |
    | `acccount_id`       |  varchar | 255        | accounts.id      | FK    |
  
4. **table.teams**
    | field              | type          | length      | description  | key     |                                                                                                                                              
    | ------------ | ---------  | --------- | -----------  | ------ |
    | `id`               | varchar    | 255          | id from the data sources, decided by DevLake users | PK  |
    | `name`         | varchar     | 255         | name of the team. Eg. team A, team B, etc. | PK  |
    | `alias`          | varchar    | 255          | alias or abbreviation of a team |   |
    | `parent_id` |  varchar    | 255         | teams.id, default to null           | FK |
    | `org_id`      |  varchar    | 255         | the id of org_id, empty for now. Would be used in the future |  |
    | `sorting_index` |  int     | 255         | the field to sort team | FK |    

5. **table.team_users**
    | field                | type       | length    | description | key      |                                                                                                                                              
    | ------------- | -------- | -------- | -----------  | ------ |
    | `team_id`      | varchar  | 255        | Full name of the team. Eg. team A, team B, etc. | PK  |
    | `user_id`       | varchar  | 255        | users.id | FK |

**Comment by Startrekzky** [comment]
Thanks @klesh . The solution in the main thread looks good to me.

**Comment by Startrekzky** [comment]
Done.
