### ISSUE TITLE
DirectRun for plugin api like create connction.

### ISSUE THREAD

**Issue by mappjzc** [apache/incubator-devlake#2362]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

API related methods must be called using HTTP. This requires the devlake program to run completely, which is not conducive to debugging.
Enable directrun support APIs to debug various APIs more conveniently.

### Use case

DirectRun the http api for debug it.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by abeizn** [comment]
unsolved
