### ISSUE TITLE
[Bug][Github] data too long for column 'title'

### ISSUE THREAD

**Issue by asterix314** [apache/incubator-devlake#2363]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

when importing https://github.com/BVLC/caffe to devlake v0.11, the following error occurs:

<img width="369" alt="image" src="https://user-images.githubusercontent.com/10952409/175934721-693f040e-ee60-48a2-9298-a6f7be16239c.png">

### What you expected to happen

Apparently the "title" column in some recipient table (PR? issues?) is defined too short.

### How to reproduce

just use the Github plugin to import https://github.com/BVLC/caffe 

```json
[
  [
    {
      "Plugin": "github",
      "Options": {
        "repo": "caffe",
        "owner": "BVLC"
      }
    }
  ]
]
```

### Version

v0.11.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by warren830** [comment]
Thanks man! We will fix it ASAP
