### ISSUE TITLE
[Feature][config-ui] config-ui new user flow stage 2

### ISSUE THREAD

**Issue by klesh** [apache/incubator-devlake#2367]
## Hide passwords/tokens from connection settings pages (BE/FE)

1. #2423  @warren830 
2. #2384 
3. #1908 
   `config-ui` github connection would call `TestConnection` for each token and print out `username` for them if succeeded, or an error message in red. For other plugins, making the input field to `password` type would be sufficient. @yumengwang03 will finish the design before 1st July, @e2corporation 

## Displaying links to available dashboards based on `blueprint.settings` (Frontend only)

- #2255 
  Create a JSON file like the following in config-ui to indicate the requirement of each dashboard, and display links to those dashboards for a specific `blueprint` 
  ```json
  {
      "dashboards": [
          {
              "name": "Demo-Average Requirement Lead Time By Assignee",
              "url": "/d/kB0IbH37k/demo-average-requirement-lead-time-by-assignee",
              "dependencies": [
                  {
                      "plugin": "github",
                      "entities": [
                          "CODE",
                          "TICKET"
                      ]
                  }
              ]
          }
      ]
  }
  ```

## Pipeline progress (Frontend only)

- #2197 
  note: the `name` and `finishedRecords` of subtask are missing from the current design, @yumengwang03 will work on it and fix the design first. the `finishedRecords` IS VERY VERY VERY SUPER EXTREMELY IMPORTANT because subtask can run for a LONG LONG LONG time causing the PROGRESS to seemingly dead to the user, we HAVE to show it off to prevent anyone from killing DevLake. And I have kept bringing it up countless times. Give me the `finishedRecord` unless you have a better solution.

## User be able to download pipeline log for debugging(BE/FE)

- API endpoint `GET /pipeline/:id/logs.tar.gz` downloads logs of pipelines in compressed format
- Config-ui shows the link to `logs.tar.gz` for finished pipelines

**Comment by e2corporation** [comment]
@klesh Why is #2229 being listed here for a ticket regarding Test Connection? That ticket is not a true description of what's happening on the Pipeline activity page, nor does it reflect the need for usage of `progressDetail`. I have already logged a ticket to address this issue regarding how Activity progress is calculated, it has not been added to any milestone as yet. 

https://github.com/apache/incubator-devlake/issues/2197.

**Comment by e2corporation** [comment]
@klesh @klesh What is the business value in revealing a username associated with a secure token and displaying it on the UI in the first place? Is backend going to discern username information from the token and provide that information in the connection object for each token? Is username going to be present in the API test response only? GitHub automatically emails users regarding expired tokens or tokens that are about to expire.

**Comment by klesh** [comment]
> @klesh Why is #2249 being listed here for a ticket regarding Test Connection? That ticket is not a true description of what's happening on the Pipeline activity page, nor does it reflect the need for usage of `progressDetail`. I have already logged a ticket to address this issue regarding how Activity progress is calculated, it has not been added to any milestone as yet.
> 
> **Config-UI / Pipeline Activity / Progress Detail** #2197.

Not sure, I didn't create any of it... We can close one if you think they are duplicated.
And I have to mention once more: percentage progress is a big NO NO, NOT all subtasks return `progressDetail.totalRecords`, as a matter of fact, many of them return `-1` when it is unavailable. And even if we have only one subtask which can not return this information, it breaks the percentage progress.

**Comment by e2corporation** [comment]
> > @klesh Why is #2249 being listed here for a ticket regarding Test Connection? That ticket is not a true description of what's happening on the Pipeline activity page, nor does it reflect the need for usage of `progressDetail`. I have already logged a ticket to address this issue regarding how Activity progress is calculated, it has not been added to any milestone as yet.
> > **Config-UI / Pipeline Activity / Progress Detail** #2197.
> 
> Not sure, I didn't create any of it... We can close one if you think they are duplicated. And I have to mention once more: percentage progress is a big NO NO, NOT all subtasks return `progressDetail.totalRecords`, as a matter of fact, many of them return `-1` when it is unavailable. And even if we have only one subtask which can not return this information, it breaks the percentage progress.

I understand the need for showing this information, I'm not against making any of these changes, if it was a true priority like you stated it would have been added to a milestone and brought up at weekly standup as a priority ticket that needs to be implemented. I've been busy with feature development.

**Comment by klesh** [comment]
> > > @klesh Why is #2249 being listed here for a ticket regarding Test Connection? That ticket is not a true description of what's happening on the Pipeline activity page, nor does it reflect the need for usage of `progressDetail`. I have already logged a ticket to address this issue regarding how Activity progress is calculated, it has not been added to any milestone as yet.
> > > **Config-UI / Pipeline Activity / Progress Detail** #2197.
> > 
> > 
> > Not sure, I didn't create any of it... We can close one if you think they are duplicated. And I have to mention once more: percentage progress is a big NO NO, NOT all subtasks return `progressDetail.totalRecords`, as a matter of fact, many of them return `-1` when it is unavailable. And even if we have only one subtask which can not return this information, it breaks the percentage progress.
> 
> I understand the need for showing this information, I'm not against making any of these changes, if it was a true priority like you stated it would have been added to a milestone and brought up at weekly standup as a priority ticket that needs to be implemented. I've been busy with feature development.

Aah, sorry, it is for next month... I should have said that before everything

**Comment by e2corporation** [comment]
> > @klesh @Startrekzky What is the business value in revealing a username associated with a secure token and displaying it on the UI in the first place? Is backend going to discern username information from the token and provide that information in the connection object for each token? Is username going to be present in the API test response only? GitHub automatically emails users regarding expired tokens or tokens that are about to expire.
> 
> No, it has nothing to do with the BE.
> 
> Yes, the `username` is going to be present in API test response only.
> 
> Email notification for github token, maybe, I'm not sure. But it has nothing to do with the design AFAIK, from what I learned from @yumengwang03, it is for the user who has multiple tokens from different colleagues, so the user could identify which ones are expired, and reach out to the owner easily, plus, the user can find out if there are duplicate `username` from these seemingly different tokens, and we can also check that for them as well.

If API is providing this information with the API response, we can get this information displayed.

**Comment by Startrekzky** [comment]
Closed
