### ISSUE TITLE
[Bug][runner] steps total nums is wrong under certain circumstances

### ISSUE THREAD

**Issue by abeizn** [apache/incubator-devlake#2368]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

when I run gitlab plugin, I find the total steps is 21, but it has 22 subtasks.
![image](https://user-images.githubusercontent.com/101256042/176162515-a1c33db7-249b-47e3-8ed4-d01fc5fe81fd.png)

### What you expected to happen

the total tasks num is equal to the finish step.

### How to reproduce

run gitlab plugin in main branch.
and when a plugin has same subtask. such as:
![image](https://user-images.githubusercontent.com/101256042/176164367-f0d88b29-aebc-4a6d-ba99-c2746f1ad680.png)

### Version

main

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by klesh** [comment]
OK... but why? why on earth does it need to be executed multiple times?
