### ISSUE TITLE
[Feature][gitlab] API to list all `projects` for gitlab 

### ISSUE THREAD

**Issue by klesh** [apache/incubator-devlake#2376]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

In order to support #2271. We need a new API

## Solution
Add API `GET /api/proxy/gitlab/projects?keyword=&page=2&size=10`, searching and pagination are critical since the total number of projects is likely to be huge.

### Use case

To support #2271

### Related issues

#2271

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by warren830** [comment]
I checked gitlab api: https://docs.gitlab.com/ee/api/projects.html#list-user-projects
we can use the following param:
search(string): Return list of projects matching the search criteria.
starred(boolean): Limit by projects starred by the current user. 
visibility(string): Limit by visibility public, internal, or private. -- using private will return only our company's private projects

**Comment by warren830** [comment]
according to #2705 , I added a proxy to allow config-ui to request gitlab projects
