### ISSUE TITLE
[Doc][GitHub Readme] Unit test badge failing

### ISSUE THREAD

**Issue by hezyin** [apache/incubator-devlake#2377]
<img width="993" alt="Screen Shot 2022-06-28 at 7 15 29 PM" src="https://user-images.githubusercontent.com/2908155/176336793-3dd6e565-e8ac-427b-9d37-9deacfa51507.png">

The unit test badge on the main readme has been failing for a while. Seems like a configuration issue. Not a super high-priority issue, but would be nice if someone can fix this when convenient.

**Comment by klesh** [comment]
I check the Badge Link and the related Github Action, they seem alright to me:

Badge: https://github.com/apache/incubator-devlake/actions/workflows/test.yml/badge.svg
Action Page: https://github.com/apache/incubator-devlake/actions/workflows/test.yml

I had posted a thread on https://github.community/ , and it is waiting for Approval from Moderator, interesting...  Moderated Community...

**Comment by klesh** [comment]
Alright, it was approved, https://github.community/t/github-action-badge-always-show-failing/259290

**Comment by likyh** [comment]
The reason for failing is ci haven't run in branch `main`.
Echarts will run ci when merge master to release.

we don't have a release branch so I will try to run ci in the main branch every night.
