### ISSUE TITLE
[Feature][Config UI] Help users identify and replace expired tokens for GitHub

### ISSUE THREAD

**Issue by yumengwang03** [apache/incubator-devlake#2384]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Either when adding a new connection or edit an existing connection, we want to help users identify and replace expired tokens for GitHub connections, so that it's easier to know which token belongs to whom and replace the expired ones accordingly.

We also should hide the tokens once they are entered for privacy protection.

### Related issues

https://github.com/apache/incubator-devlake/issues/1908

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by yumengwang03** [comment]
Please see the design in Figma and the screenshots, and follow the exactly UI and user flow as designed:
Figma: https://www.figma.com/file/Eux4Dhorxp7M0TwzOnL6Yh/Config-UI-for-V1.0?node-id=291%3A7778
<img width="930" alt="Screen Shot 2022-06-29 at 6 06 08 PM" src="https://user-images.githubusercontent.com/9535430/176412186-f547d73e-d644-422e-b080-b85d566071e5.png">
<img width="916" alt="Screen Shot 2022-06-29 at 6 06 22 PM" src="https://user-images.githubusercontent.com/9535430/176412201-3254f69b-882c-4242-bde7-185795d8f1b7.png">
<img width="931" alt="Screen Shot 2022-06-29 at 6 06 30 PM" src="https://user-images.githubusercontent.com/9535430/176412221-c491f2d5-cbda-4d92-b8af-c9992cdfdd36.png">
<img width="1224" alt="Screen Shot 2022-06-29 at 6 06 50 PM" src="https://user-images.githubusercontent.com/9535430/176412235-b4d38a6b-13d7-4cc0-91c6-790cd3dfc194.png">
<img width="842" alt="Screen Shot 2022-06-29 at 6 09 36 PM" src="https://user-images.githubusercontent.com/9535430/176412279-bf474f04-faf0-4fb9-ac7b-a9a315ff08a7.png">
<img width="1441" alt="Screen Shot 2022-06-29 at 6 07 05 PM" src="https://user-images.githubusercontent.com/9535430/176412317-36293412-6b00-4dbf-9a1c-d00b1cf28cf7.png">

**Comment by e2corporation** [comment]
This feature ticket will be bundled with PR #2026

**Comment by Startrekzky** [comment]
Done.
