### ISSUE TITLE
[Question][Module Name] Is the devlake can CI with CODING(https://coding.net/) info

### ISSUE THREAD

**Issue by matthewxuda** [apache/incubator-devlake#2403]
## Question
Is the devlake can CI with CODING(https://coding.net/) info?

**Comment by abeizn** [comment]
Thanks for reporting the issue, Do you mean that devlake can support this data source（https://coding.net/ )？

devlake currently does not support this data source, but devlake can support, we currently do not have the manpower, you can refer to "https://github.com/apache/incubator-devlake/tree/main/generator" to create a plugin, very welcome to provide PRs to us, and welcome to become a contributor to the apache project.
