### ISSUE TITLE
[Doc][Developer] How to generating `mocks` for Developer setup

### ISSUE THREAD

**Issue by klesh** [apache/incubator-devlake#2409]
## Documentation Scope
Developer setup

## Describe the Change
[mockery](http://github.com/vektra/mockery) was introduced to `main`(milestone v0.12), in order for developers to successfully fire up DevLake, the following instruction must be added to step 7:

1. install [mockery](http://github.com/vektra/mockery) 
2. generate mocking stubs by `make mock`

## Screenshots
![image](https://user-images.githubusercontent.com/61080/177125908-73529145-16ea-4037-8d10-3fb08dcb7180.png)

**Comment by nicoabie** [comment]
@klesh the instruction to install mockery are not recommended according to their repo
https://github.com/vektra/mockery#go-install

was that considered?

**Comment by klesh** [comment]
@nicoabie No, not really. It was chosen simply because it worked :joy:. Maybe we should put a link to https://github.com/vektra/mockery#installation instead of giving the `go install` method directly.
What do you think?
