### ISSUE TITLE
[Feature][Config UI] Allowing users to download the full log of the pipeline

### ISSUE THREAD

**Issue by yumengwang03** [apache/incubator-devlake#2413]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

On the blueprint detail page, there should be a button to allow users to download the full log of a particular pipeline run, for debugging purposes.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by yumengwang03** [comment]
See design here: https://www.figma.com/file/Eux4Dhorxp7M0TwzOnL6Yh/Config-UI-for-V1.0?node-id=300%3A8354

**Comment by klesh** [comment]
Finished
