### ISSUE TITLE
[Feature][Github] Modify test connection to verify one token per time

### ISSUE THREAD

**Issue by warren830** [apache/incubator-devlake#2423]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Change api TestConnection of github plugin to validate exactly 1 token, and return username for the token if succeeded.

Related issues
https://github.com/apache/incubator-devlake/issues/2367

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by warren830** [comment]
We can use the following api to test if a token is valid
`curl --location --request GET --X GET 'https://api.github.com/user' \
--header 'User-Agent: Apipost client Runtime/+https://www.apipost.cn/' \
--header 'Authorization: Bearer ghp_xxx' \
--form 'Authorization=Bearer dfsd'`

**Comment by Startrekzky** [comment]
Fixed.
