### ISSUE TITLE
[Feature][framework] record subtask execution time

### ISSUE THREAD

**Issue by klesh** [apache/incubator-devlake#2433]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Currently, we have `task.spendSeconds` to record the execution time of a `task`.
However, the execution time of `subtask` is missing. It would be beneficial to have this information recorded.

### Use case

This information can help identify the bottleneck of a pipeline
1. For developers: to improve the performance
2. For users: to skip some unneeded subtasks

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by keon94** [comment]
@klesh how do you want the duration recorded? 
1. A new table for subtasks - i.e. _devlake_subtasks (I think this is what you want)
2. Reuse the tasks table, and just write the time info into the subtasks Json
3. Just simply log the elapsed time after a subtask is done (write nothing to DB)

**Comment by klesh** [comment]
Yes, you are correct.
I would prefer the First option because it would be easier for us to
analyze in the future. Say we like to know which subtasks ran slower
than others.
