### ISSUE TITLE
[Feature][jira] Skip collecting `changelog` of `epic issue`

### ISSUE THREAD

**Issue by klesh** [apache/incubator-devlake#2434]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

I notice that some issues may have tens of thousand `changelogs`, turns out these issues are `epic`.
According to what @leglars suggested, we should skip the changelog collection for these epic issues.

### Use case

Reduce the collection time for JIRA plugin

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by warren830** [comment]
Not sure about how to decide if an issue is epic?
