### ISSUE TITLE
What is the  commond for devlake  installation

### ISSUE THREAD

**Issue by matthewxuda** [apache/incubator-devlake#2460]
What is the  commond for devlake  installation

**Comment by shubham-cmyk** [comment]
You can follow the Installation from the Readme.md 
Follow up link : https://devlake.apache.org/docs/QuickStart/LocalSetup/

**Comment by likyh** [comment]
Yes, it's run in docker. Or you can add our WeChat group to get enthusiastic help.

**Comment by SnowMoon-Dev** [comment]
suggest docker deploy @matthewxuda
