### ISSUE TITLE
[Bug][Jira & GitHub] No `full_name` is collected from these two plugins

### ISSUE THREAD

**Issue by Startrekzky** [apache/incubator-devlake#2476]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

![UeFkimkr5C](https://user-images.githubusercontent.com/14050754/178500968-504da324-1fd5-4ea7-a750-4a34aed3e328.jpg)

### What you expected to happen

1. Get full_name of Jira users and GitHub users
2. Convert full_name to the `full_name` of table.accounts in the domain layer.

### How to reproduce

1. collect Jira and GitHub data
2. connect to MySQL, and query 'SELECT * FROM accounts'
3. check the `full_name` field

### Version

main

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by likyh** [comment]
I'll take it with https://github.com/apache/incubator-devlake/issues/2478
