### ISSUE TITLE
[Feature][Config UI] Skipping Failed/Stalled Stages

### ISSUE THREAD

**Issue by asterix314** [apache/incubator-devlake#2499]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

The requested feature is an option to skip failed stages and carry on with the following stages in the pipeline, for those who have a long list of repos to run and want to make as much progress as possible in one go.

In "advanced mode", one can list tens or hundreds of stages(repos) in the "2D list" of the API, to run in sequence. But when one stage fails for whatever reason, the whole pipeline halts, missing the opportunity to run the following stages and just wasting time for human intervention.

Better still, a timeout (say 4 hours) setting can also be useful, for those stages that don't actually fail but still are not making any progress due to rate limiting etc.

### Use case

Add a global option "skip stage when stalled", and a sub-setting for a timeout.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by klesh** [comment]
@asterix314 Thanks for the feedback, it makes sense to me, @Startrekzky  what do you think?

**Comment by Startrekzky** [comment]
> @asterix314 Thanks for the feedback, it makes sense to me, @Startrekzky what do you think?

I'm not sure, may I know what specific problem happened while you were collecting data from multiple GitHub repos? Thanks. @asterix314

**Comment by asterix314** [comment]
> > @asterix314 Thanks for the feedback, it makes sense to me, @Startrekzky what do you think?
> 
> I'm not sure, may I know what specific problem happened while you were collecting data from multiple GitHub repos? Thanks. @asterix314

I used the "2D list" API to collect a few hundred GitHub projects into DevLake. The stages ran in sequence. But when one stage fails, the whole pipeline stalls. There are many reasons for one stage to fail/stall:
- miss-spelt project names
- rate limit exceeded
- etc.
As a result, during the few days of the pipeline's execution, I found myself having to repeatedly return to the config-ui page to check if any stage failed and resume the pipeline manually. It would be much more efficient to automatically skip failed stages, and let the user intervene only at the end, when no executable stages are left unprocessed.

**Comment by Startrekzky** [comment]
> > > @asterix314 Thanks for the feedback, it makes sense to me, @Startrekzky what do you think?
> > 
> > 
> > I'm not sure, may I know what specific problem happened while you were collecting data from multiple GitHub repos? Thanks. @asterix314
> 
> @Startrekzky I used the "2D list" API to collect a few hundred GitHub projects into DevLake. The stages ran in sequence. But when one stage fails, the whole pipeline stalls. There are many reasons for one stage to fail/stall:
> 
> * miss-spelt project names
> * rate limit exceeded
> * etc.
> 
> As a result, during the few days of the pipeline's execution, I found myself having to repeatedly return to the config-ui page to check if any stage failed and resume the pipeline manually. It would be much more efficient to automatically skip failed stages, and let the user intervene only at the end, when no executable stages are left unprocessed.

Thanks for the use case, I'll think about it.

**Comment by klesh** [comment]
1. allow users to skip failed tasks
2. allow users to rerun failed/succeeded tasks

**Comment by yumengwang03** [comment]
Figma link: https://www.figma.com/file/Eux4Dhorxp7M0TwzOnL6Yh/Config-UI-for-V1.0?node-id=2610%3A21361

**Comment by mintsweet** [comment]
@yumengwang03 what does this retry-like button do?
![screenshot-20221104-123850](https://user-images.githubusercontent.com/37237996/199888821-7130a42d-b62a-47de-a228-54b63fd247c7.png)

**Comment by Startrekzky** [comment]
@mintsweet  To rerun the subtask @mindlesscloud

**Comment by mintsweet** [comment]
@Startrekzky if I set up no skip failed task, can the task be rerun? (Does the rerun button show?)

**Comment by Startrekzky** [comment]
> @Startrekzky if I set up no skip failed task, can the task be rerun? (Does the rerun button show?)

I think it's a `No`. What do you think? @mindlesscloud @klesh
