### ISSUE TITLE
[Bug][Pipeline] Fail to create pipeline for the github 

### ISSUE THREAD

**Issue by SimFG** [apache/incubator-devlake#2509]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

I'm just starting to learn about this repository. According to the documentation, the following errors were found.
![image](https://user-images.githubusercontent.com/21985684/179342032-0a9e7984-c94e-4d22-bd00-61444428d7c9.png)

### What you expected to happen

success to create the github pipeline.

### How to reproduce

Use the latest code from the current repository, including `.env.example` and `docker-compose.yml`.
Follow the steps in the documentation.
https://devlake.apache.org/docs/QuickStart/LocalSetup
https://devlake.apache.org/docs/UserManuals/GitHubUserGuide
When creating the pipeline for the github, I fail to be redirected to newly created pipeline and stay the current page. Opening the browser console, I find a front error.

### Version

v0.11.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by likyh** [comment]
Hi, would you like to show us what the connection config is?

**Comment by SimFG** [comment]
Is this page?
![image](https://user-images.githubusercontent.com/21985684/179347183-d942522f-6cdb-49b2-9332-24d3166c0ca6.png)
![image](https://user-images.githubusercontent.com/21985684/179347215-657d9a55-b728-47e5-8c6e-c7670691e17b.png)

**Comment by likyh** [comment]
It seems that you are using `main` instead of `v0.10.1`? now the main branch is in development. You can download `docker-compose.yml` from [here](https://github.com/apache/incubator-devlake/releases/tag/v0.10.1). Or maybe we can help you by wechat meeting.

**Comment by SimFG** [comment]
Thanks your answer. Yes, I use the `docker-compose.yml` file in the `main`  brach. Because I am interesting in this product, and want to join the development of this product.
