### ISSUE TITLE
In the text field of newly created pull request "&nbsp;" is mentioned in plain text

### ISSUE THREAD

**Issue by nikitakoselev** [apache/incubator-devlake#2511]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

In the text field of the newly created pull request "&nbsp;" is mentioned in plain text.

Check the attachment for more details.
I think that some "GitHub flow templates" might have an error.
![image](https://user-images.githubusercontent.com/6383738/179348053-b8e2b37a-8719-4285-b059-1c8cd5e4d1c2.png)

### What you expected to happen

It's doesn't look nice 

### How to reproduce

Create a fork from DevLake
Create a branch with a fix
Create a pull request from your repo to devlake repo, like here
![image](https://user-images.githubusercontent.com/6383738/179348265-52dd3c7d-6b14-4e4a-bf5c-b6aaa2d672e2.png)

Check the text message. It containst "nbsp;" in plain text. not nice

### Anything else

Smile, you are being recorded as a part of our stream at https://www.meetup.com/twosseng/

8 participants are benefitting from learning how high quality project work and how they can contribute to these project.

### Version

main

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by abeizn** [comment]
happy coding

**Comment by klesh** [comment]
Hi, @nikitakoselev, Are you working on it?

**Comment by nikitakoselev** [comment]
No, I've left it as a good first time issue

**Comment by klesh** [comment]
I see, thanks
