### ISSUE TITLE
[Bug][gitextractor] gitextractor can't finish my task in standalone mode

### ISSUE THREAD

**Issue by xgdyp** [apache/incubator-devlake#2513]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

I try to use standalone mode to run `gitextractor` plugin.
My command is 
```
go run plugins/gitextractor/*.go  -url https://github.com/datawhalechina/wonderful-sql.git -id github:GithubRepo:1:382057179 -db "merico:merico@tcp(127.0.0.1:3306)/lake?charset=utf8mb4&parseTime=True" -proxy "http://127.0.0.1:8889/"
```
and something goes wrong like
<img width="1383" alt="image" src="https://user-images.githubusercontent.com/37795442/179359158-3211d5d1-7637-46b0-a0da-72b5d606b919.png">
and the code in repo_creator.go is
<img width="1026" alt="image" src="https://user-images.githubusercontent.com/37795442/179359186-e58bd742-7aa1-440e-baef-a872b7cfe6a4.png">

I don't know it is caused by my wrong running command or gitextractor plugin itself.

### What you expected to happen

normally finish gitextractor task

### How to reproduce

run gitextractor plugin with command like:
```
go run plugins/gitextractor/*.go  -url https://github.com/datawhalechina/wonderful-sql.git -id github:GithubRepo:1:382057179 -db "merico:merico@tcp(127.0.0.1:3306)/lake?charset=utf8mb4&parseTime=True" -proxy "http://127.0.0.1:8889/"
```
and changed the url and id to other repo.

### Version

v0.11.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Startrekzky** [comment]
Thanks @xgdyp. @mindlesscloud could you please take a look?

**Comment by keon94** [comment]
@xgdyp does this only happen in standalone? Have you tried running it from config-ui to see if it also happens?

**Comment by xgdyp** [comment]
> @xgdyp does this only happen in standalone? Have you tried running it from config-ui to see if it also happens?

Yes, this only happen in standalone mode. It has no problems when running from config-ui

**Comment by xgdyp** [comment]
Thanks!
