### ISSUE TITLE
[Bug][config-ui] sent invalid username or password when shift to grafana from config-ui

### ISSUE THREAD

**Issue by mappjzc** [apache/incubator-devlake#2531]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

![image](https://user-images.githubusercontent.com/2921251/179551881-20c0c85a-7427-4f23-986e-53d51a96945f.png)

sent invalid username or password when shift to grafana from config-ui.

we have to flush once to into the grafana..

But after into grafana, when we need to visit config-ui again, we have to write username and password once again.

![image](https://user-images.githubusercontent.com/2921251/179552868-bfe91086-48ff-43eb-95df-b946e326b390.png)

and if we set it. the grafana will send invalid once again.

It seems that grafana try to use username and password of config-ui, and clean it after failed.

### What you expected to happen

Don't interfere between config-ui and grafana.

### How to reproduce

1.set config-ui login username and password.
2.visit grafana by /grafana/.
3.flush grafana.
4.visit config-ui and login again.
5.visit grafana by /grafana/. again.

### Version

main

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by keon94** [comment]
@mappjzc with #2547 merged, are we good to close this one?

**Comment by mappjzc** [comment]
> @mappjzc with #2547 merged, are we good to close this one?

Ok, it can be closed.
