### ISSUE TITLE
[Bug][config-ui] gitlab add connection can not set token

### ISSUE THREAD

**Issue by mappjzc** [apache/incubator-devlake#2554]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

When we try to setting the token for gitlab . we can not input anything
And if we try to set it by chrome console, it will be clean after focus on it.
As follow gif
![settoken](https://user-images.githubusercontent.com/2921251/179959107-6782eaad-8fdf-496d-8874-86fe3ae1ff7d.gif)

try to debug it and handle the focus.
At the second times to run the handleElementFocus, before setElementIsFocused, the value still have.
![image](https://user-images.githubusercontent.com/2921251/179958830-761eb428-711a-4f41-a1be-1d33220524f1.png)
But after this code,We lost input value.
![image](https://user-images.githubusercontent.com/2921251/179959632-de00015b-cc36-4f2b-a340-5431b6a6f865.png)
And also it skip the line of breakpoint.

### What you expected to happen

We can set the token by input.

### How to reproduce

1.Add gitlab connection
2.try to set token.

### Version

main

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by e2corporation** [comment]
@mappjzc This is not ideal and unfortunate, will get this GitLab token issue resolved.

**Comment by e2corporation** [comment]
@Startrekzky I'm actively working on my current PR #2534 and will flag as merge ready as soon as I've completed all my tasks.
