### ISSUE TITLE
[Refactor][gitlab,jira,jenkins,tapd] Missing error handling

### ISSUE THREAD

**Issue by Pranshu-Raj** [apache/incubator-devlake#2561]
Missing error handling in GET GET /plugins/gitlab/connections/connectionId
Missing error handling in GET GET /plugins/jenkins/connections/connectionId
Missing error handling in GET GET /plugins/jira/connections/connectionId
Missing error handling in GET GET /plugins/tapd/connections/connectionId

To fix the error handling part {missing: if err != nil {
return nil, err
}}

**Comment by mappjzc** [comment]
Thanks for reporting the issue. I'm looking forward to your PR.
