### ISSUE TITLE
[Bug][config-ui] Blueprint step 2 validation works partially

### ISSUE THREAD

**Issue by klesh** [apache/incubator-devlake#2572]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

When Jira is invalid, the Next Step gets disabled, which is correct
![image](https://user-images.githubusercontent.com/61080/180211645-f220c776-c10c-4972-aaea-d52d560ae804.png)
However, if I switch to Github while Jira is still invalid, it gets enabled, and I can proceed to the Next Step
![image](https://user-images.githubusercontent.com/61080/180211929-5354c309-f388-46fd-9be0-cffd0614957a.png)

### What you expected to happen

the "Next Step" button should be disabled if any Invalid Connection in play.

### How to reproduce

1. create new blueprint
2. add multiple connections
3. invalidate one connection, and switch to any valid connection
4. see error

### Version

main

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by e2corporation** [comment]
@klesh  I left this behavior intentionally. I could scan all connections I think that's a bit overkill, I think this is acceptable for now given the current behavior is only worse in that we have no validation in place. We could patch this under another PR or if its a blocker we can address it on this one.
