### ISSUE TITLE
[Bug][config-ui] Create blueprint page gets blank out

### ISSUE THREAD

**Issue by klesh** [apache/incubator-devlake#2580]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

![1-1](https://user-images.githubusercontent.com/61080/180393929-29e5be63-6d8f-48c0-bf91-179cd9e1768b.png)
![1-2](https://user-images.githubusercontent.com/61080/180393941-3776cc94-103e-4180-b1e3-ed23ab8f1724.png)
![1-3](https://user-images.githubusercontent.com/61080/180393945-87c5859f-6cc0-4d5b-af52-46b901e0cecf.png)
![1-4](https://user-images.githubusercontent.com/61080/180393950-411fe588-69c6-4d88-b306-a93a21e48974.png)
![blank](https://user-images.githubusercontent.com/61080/180393955-415d1c41-b35c-4bc3-8576-220f3634066f.png)

### What you expected to happen

should be seeing Jira scope page

### How to reproduce

follow the screen-shots:
1. create a new blueprint
2. pick 2 connections, one Jira and one GitHub in my case, both were "Online"
3. continue to step 3, click "add transformation rules" for the GitHub scope
4. click the Jira connection on the top left corner
5. see a blank page

### Version

19aa62d80f6813bd4f66f3c1e271fe55ebffcebd from #2534 

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by e2corporation** [comment]
@klesh Will investigate and resolve.

**Comment by e2corporation** [comment]
@klesh Fixed with #2586
