### ISSUE TITLE
[Bug][config-ui] Github transformation rules is missing

### ISSUE THREAD

**Issue by klesh** [apache/incubator-devlake#2582]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

code review setting is showing while it was unchecked
![image](https://user-images.githubusercontent.com/61080/180398605-f0e49459-5eb2-4f4c-a89a-e9a1b96bbdbd.png)
however, it disappeared while it was checked...
![Uploading image.png…]()

### What you expected to happen

code review transformation rules should be displayed while it was checked, vice-versa

### How to reproduce

check/unchecked the "Data Entities" in step 2, and see error on step 3

### Version

main

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by e2corporation** [comment]
@klesh Fixed with #2586
