### ISSUE TITLE
[Feature][GitLabCI] Investigate and implement GitLabCI Action

### ISSUE THREAD

**Issue by warren830** [apache/incubator-devlake#2583]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar feature requirement.

### Description
![image](https://user-images.githubusercontent.com/2921251/182597524-83c13037-2426-4446-a508-bcc95e1e9f60.png)
![image](https://user-images.githubusercontent.com/2921251/182597578-97f088cd-75d2-4c48-a3a5-7cff0028d7f9.png)

According to issue #2537 , we will implement CI/CD Domain Layer. Before this, we need to investigate GitLabCI and write a table schema in this issue. 

### Use case

We need to investigate GitLabCI first, and try to implement collector and extractor.
Then we can compare several CI/CD plugins' tool layers and go back to work on #2537 
After domain layer design, we can continue to finish this issue

### Related issues

#2537 

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by warren830** [comment]
@mappjzc Please read #2537 carefully before investigating gitlabCI

**Comment by mappjzc** [comment]
closed by #2633
