### ISSUE TITLE
[Bug][config-ui] Blueprint detail page keep showing Pending

### ISSUE THREAD

**Issue by klesh** [apache/incubator-devlake#2593]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

![image](https://user-images.githubusercontent.com/61080/180739320-5c3bcbb1-2b48-4515-be74-d98e4a35a75d.png)

### What you expected to happen

Status should be changing after a while

### How to reproduce

1. go into blueprint detail page
2. click the "run now" button on the top right corner
3. status would never change

### Version

main

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by e2corporation** [comment]
@klesh This should be a relatively minor problem to fix, `TASK_CREATED` may have been excluded from status array(s) that allows auto-polling, not sure why this is only happening now unless the task is Stuck in a created state. What happens when you hit refresh manually?
