### ISSUE TITLE
[Feature][CircleCI] Investigate CircleCI plugin 

### ISSUE THREAD

**Issue by keon94** [apache/incubator-devlake#2596]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

According to issue https://github.com/apache/incubator-devlake/issues/2537 , we will implement CI/CD Domain Layer. Before this, we need to implement raw and tool layer of CircleCI.

### Use case

We need to investigate CircleCI first, and try to implement collector and extractor.
Then we can compare several CI/CD plugins' tool layers and go back to work on https://github.com/apache/incubator-devlake/issues/2537

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Startrekzky** [comment]
Can I rename this issue to 'Investigate CircleCI plugin' and close it?

**Comment by keon94** [comment]
> Can I rename this issue to 'Investigate CircleCI plugin' and close it?

Sure. You can create another issue for the implementation work.
