### ISSUE TITLE
[Bug][config-ui] blueprint add connection modal - auto-testing and proxy field

### ISSUE THREAD

**Issue by e2corporation** [apache/incubator-devlake#2599]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

When adding a New Connection using the Connection Dialog/Modal, proxy field is a key dependency when executing a connection test. This seems to have an undesired effect of testing a connection as the proxy value is being changed.

Alter the test logic so that proxy url's value change does not trigger a repeated test until after.

### What you expected to happen

Chrome user can type into **Proxy URL** field without keyboard interruption

### How to reproduce

Add a connection using Connection Dialog/Modal

### Version

main

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by klesh** [comment]
Same thing goes to the "Endpoint URL"
