### ISSUE TITLE
[Doc][deployment] Move helm deployment document to Official website

### ISSUE THREAD

**Issue by klesh** [apache/incubator-devlake#2606]
## Documentation Scope
deployment/heml/READEME.md

## Describe the Change
The `helm deployment` contributed by @matrixji is the most mature way of deploying Apache DevLake to the Production Environment so far.
However, many new users won't notice it because the document is only available inside a subfolder of our main repo.
I suggest that we move the document to our Office website, aka apache/incubator-devlake-website repo.

**Comment by matrixji** [comment]
I'll take it, pls /assign it to me.

**Comment by matrixji** [comment]
PR raised in website repo: https://github.com/apache/incubator-devlake-website/pull/134

**Comment by warren830** [comment]
> 

Nice job, Bin!

**Comment by klesh** [comment]
Job well done, thanks Bin.
