### ISSUE TITLE
[Doc][main] Add a link to Official Website repo

### ISSUE THREAD

**Issue by klesh** [apache/incubator-devlake#2607]
## Documentation Scope
main readme

## Describe the Change
We move all our document from main repo to Office Website Repo a while ago.
However, some contributors from community never know about this.
We should add a description of how to contribute documentation to our main README, along with a link to the Office Website Repo

**Comment by ppborah** [comment]
Hey @klesh, isn't `How to Contribute` already mentioned in the README ?
I guess you are asking about mentioning docs being on devlake.apache.org and not on the README ?
I would like to work on this, please assign :)

**Comment by klesh** [comment]
@ppborah Thanks!
Here are the things we should do for developers who want to work on new features when reading main README:
1. Developer should know Documentation is hosting on devlake.apache.org
2. Developer should know How to contribute to the devlake.apache.org, in terms of which repo to submit documentation PR. (I ran into a situation where the contributor didn't know about `apache/incubator-devlake-website` repo at all)

**Comment by ppborah** [comment]
I got you! Working on it

**Comment by klesh** [comment]
Hi, @ppborah, would you like to share the progress? Thanks

**Comment by ppborah** [comment]
Working on it @klesh, PR soon

**Comment by ppborah** [comment]
Hey @klesh, do you think we should be more descriptive or this would work ?
Please let me know :)

PS: Initially, I thought of adding "Creating a PR using GitHub UI from `Edit this page` link, but then I felt it's better if we mention that on devLake-website repo's README.md
