### ISSUE TITLE
[Feature][ Config-UI ] Allow the both the column to expand simultaneously. 

### ISSUE THREAD

**Issue by shubham-cmyk** [apache/incubator-devlake#2611]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

When we click to expand on the Github and try to expand the gitExtractor the expanded column closes. 
The same happens vice-versa. 

![dashboard_issue](https://user-images.githubusercontent.com/69793468/180988099-cddc0fc1-151f-482f-9636-ed0aadb09575.gif)
The same

### Use case

Allowing Expanding both columns could be helpful to compare the underneath data. 

### Related issues

Not Found. 

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by e2corporation** [comment]
@shubham-cmyk Thank you for noticing this behavior and reporting an issue with our `V.0.11.0` version's Pipeline Activity, this in fact is actually the intended behavior, as only 1 task row is allowed to be expanded at any given time.

**Comment by shubham-cmyk** [comment]
Got that!
