### ISSUE TITLE
[Bug][Data Schema] Field `user_id` should be `account_id` in table pull_request_comments and issue_comments 

### ISSUE THREAD

**Issue by Startrekzky** [apache/incubator-devlake#2620]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

![origin_img_v2_18d635f4-90ce-4eea-a5ae-324e76a9de7g](https://user-images.githubusercontent.com/14050754/181255076-36fb7f28-711c-4056-8a1f-5e82927f759e.jpg)

![Zn4ah4No8A](https://user-images.githubusercontent.com/14050754/181255130-bbcbc44c-b406-48fc-b785-7854e36e940c.jpg)

### What you expected to happen

Field `user_id` should be `account_id` in table pull_request_comments and issue_comments as it is the FK to table accounts.

### How to reproduce

Collect to MySQL and check the fields in table pull_request_comments and issue_comments

### Version

main

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by thenicetgp** [comment]
I am willing to submit a PR

**Comment by klesh** [comment]
Hi, @thenicetgp , do we have a PR now?

**Comment by thenicetgp** [comment]
yeah，but have some bug to fix

发自我的iPhone

**Comment by thenicetgp** [comment]
> Hi, @thenicetgp , do we have a PR now?

pr will coming soon.
