### ISSUE TITLE
[Feature][config-ui] blueprints service pack 2.0

### ISSUE THREAD

**Issue by e2corporation** [apache/incubator-devlake#2621]
### Description

Apply post-development tasks, bugfixes and outstanding features to the Blueprints V.0.12.0 Release.

- **Feature** #2578 
- **Bug** #2549 
- **Feature** Setup & Enable **All Connections** Section (`ON-HOLD` Stage III ?)
- Add/Update Blueprint Workflow Validation Rules
- Update Data Entity Type Associations
- CSS & Styling Updates
- Code Cleanups & Linting

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by klesh** [comment]
hi @e2corporation , can we close this issue now ?

**Comment by e2corporation** [comment]
Closing already resolved @klesh
