### ISSUE TITLE
[Bug][mericodev dockerhub] "mericodev/devlake-dashboard:latest" throws error

### ISSUE THREAD

**Issue by ppborah** [apache/incubator-devlake#2627]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

**Docker Pull Command used:** 
`docker pull mericodev/devlake-dashboard:latest`

**Response:** 
`Error response from daemon: manifest for mericodev/devlake-dashboard:latest not found: manifest unknown: manifest unknown`

### What you expected to happen

Docker should have pulled the `mericodev/devlake-dashboard:latest` image
- `latest` tag missing in the image
- Works fine if version is specified explicitly (ex: `v0.12.0-beta3`, which is the latest version)

### How to reproduce

`docker pull mericodev/devlake-dashboard` OR
`docker pull mericodev/devlake-dashboard:latest`

### Version:
NA

### Are you willing to submit PR?
NA

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by klesh** [comment]
Which docker-compose file were you using?

**Comment by ppborah** [comment]
docker-compose.yml [from this repo(latest one), NOT v0.11.0]

**Comment by klesh** [comment]
Hi, the `latest` tag is available now. Feel free to re-open if any problems
