### ISSUE TITLE
[Feature][Dashboard] Add text to dashboards for users to understand how to use the pre-built dashboards and panels 

### ISSUE THREAD

**Issue by Startrekzky** [apache/incubator-devlake#2628]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

The existing dashboards are mainly composed of charts. A user may have little knowledge about how to use those charts, what they mean, or what can be improved.

### Use case

1. As an OSS maintainer, when I am looking at the `weekly community retro` dashboard, I want to know what's the meaning of each panel. What does it mean if the **issue response time** gets lower? What can I do about it?
2. As a tech/QA manager, when I am looking at the `weekly bug retro` dashboard, I want to know what's the meaning of each panel. What does it mean if the **bug response time** gets lower? What can I do about it?
etc.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Startrekzky** [comment]
Compared to adding text to the dashboard to explain panels, it's better to just add links to the metric definition page for now, as the metric definition keeps changing. In the future, we should find a way to automatically get metric definition from the [metrics page](https://devlake.apache.org/docs/category/metrics/).

**Comment by yumengwang03** [comment]
It's still work-in-progress.

**Comment by Startrekzky** [comment]
This is partly done and we can improve it later. For example:

![image](https://user-images.githubusercontent.com/14050754/215486062-5bc32b1e-a4ff-4429-bf66-1517d7f1f931.png)
![image](https://user-images.githubusercontent.com/14050754/215486136-910b8ad7-ebb9-441d-9409-258fc63ab49c.png)
