### ISSUE TITLE
[Bug][Framework] Report `panic: interface conversion: interface {} is nil, not *helper.ListBaseNode` 

### ISSUE THREAD

**Issue by warren830** [apache/incubator-devlake#2632]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

When I tried to use jenkins to collect jobs, it reported `panic: interface conversion: interface {} is nil, not *helper.ListBaseNode`
I found this is caused by pr #2401 
@keon94 Please take a look at that, thanks

### What you expected to happen

It should collect successfully

### How to reproduce

just collect jenkins jobs

### Version

main

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by keon94** [comment]
@warren830 please run a quick test again and let me know if PR #2634 fixed it.
