### ISSUE TITLE
[Doc][operation] Add Release SOP(Standard Operating Procedure) Document

### ISSUE THREAD

**Issue by klesh** [apache/incubator-devlake#2649]
## Documentation Scope
Add a Release SOP document to Official Website (apache/incubator-devlake-website)

## Describe the Change
1. Describe what to expect for a Formal Release (From User Perspective): 
   1. Where to download source code
   2. Where to download docker-compose / helm deployment, and links to User Guides
2. Describe how to produce those artifacts (From Release Manager Perspective):
   1. How to build
   2. How to pack (including signing etc)
   5. How to vote
   6. How to create Release on Github

**Comment by klesh** [comment]
Copy `swagger` document to website/doc when releasing

**Comment by mindlesscloud** [comment]
PR: https://github.com/apache/incubator-devlake-website/pull/179
