### ISSUE TITLE
[Doc][DevLake repo] About section of DevLake repo

### ISSUE THREAD

**Issue by ppborah** [apache/incubator-devlake#2671]
## Documentation Scope
About section of DevLake repo

## Describe the Change
There's double whitespace characters (highlighted below👇), please fix the typo

## Screenshots
![Typo](https://user-images.githubusercontent.com/96339995/182606899-d163dfe9-d9af-4140-bd5b-540534627bba.jpg)

**Comment by Startrekzky** [comment]
Thanks @ppborah .

**Comment by yumengwang03** [comment]
I'll work on this

**Comment by ppborah** [comment]
**Update:** This is fixed by @Startrekzky #2773
