### ISSUE TITLE
[Feature][Config-UI] Support TAPD configuration in the config-ui

### ISSUE THREAD

**Issue by Startrekzky** [apache/incubator-devlake#2673]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

TAPD plugin has been supported for a while, but the config-ui hasn't been designed and developed.

Similar to Jira, there should be transformation rules to transform
- TAPD issue types
- issue statuses
- story points
- epic
- the regex to parse commits from issues

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by tanninghan** [comment]
Design of TAPD configuration in the blueprint is ready

![image](https://user-images.githubusercontent.com/102040651/184622302-f67f4e1b-8fa7-4bdc-a85b-5cce6b9fe5d0.png)

See Figma file here: https://www.figma.com/file/Eux4Dhorxp7M0TwzOnL6Yh/Config-UI-for-V1.0?node-id=1254%3A10719

**Comment by Startrekzky** [comment]
To be tracked in #4566
