### ISSUE TITLE
[Doc][license] Add ASF header to *.svg files

### ISSUE THREAD

**Issue by klesh** [apache/incubator-devlake#2713]
## Documentation Scope
*.svg

## Describe the Change
During v0.12 release voting, one of ASF member suggested that we could add ASF header to our *.svg files.
https://lists.apache.org/thread/t3q7oz1hfk7xn7cw9bfdop8dc592sck6

I think it is a good idea, that can solve many doubt and concerns.

SVGs are plain-text files, we can certainly add ASF header as comment into them.

## Screenshots
![image](https://user-images.githubusercontent.com/61080/183584802-8cdd6f82-fad3-4738-81d8-e91395ce9b6d.png)

**Comment by klesh** [comment]
Copying ASF header from `config-ui/src/index.html` to these *.svg files should be sufficient

**Comment by likyh** [comment]
Ok, I'll add it.
