### ISSUE TITLE
[Question][GitHub] Scope for the GitHub personal access token

### ISSUE THREAD

**Issue by ss892714028** [apache/incubator-devlake#2721]
## Question
I am trying to connect Devlake w/ Github. I am wondering what scope I should select for the personal access token?

## Screenshots
If applicable, add screenshots to help explain.
![image](https://user-images.githubusercontent.com/34635663/183824388-7de158bf-183a-485d-90d7-88c039b55356.png)

## Additional context
Add any other context here.

**Comment by klesh** [comment]
Hi, are you trying to connect to private repo? 
For Public Repo, you don't need to grant any permission at all.
For Private Repo, the `repo` section must be checked.

**Comment by ss892714028** [comment]
> Hi, are you trying to connect to private repo? For Public Repo, you don't need to grant any permission at all. For Private Repo, the `repo` section must be checked.

Thank you for the reply, this makes sense to me.
I have another question, what exactly is the `endpoint url`? Where should I go to find this link? Can you give me an example?

**Comment by klesh** [comment]
Hi, for Github Cloud it is `https://api.github.com/`. The same value of from the place holder
![image](https://user-images.githubusercontent.com/61080/183835333-b9cf8c07-948c-4c5f-976d-e897b3363d28.png)
Maybe we should mention it in our Document 😃

**Comment by ss892714028** [comment]
> 

This explains it, thanks. Looks like this field reserved for GitHub on-premise haha

**Comment by ppborah** [comment]
Thanks for raising this issue @ss892714028 :)
We would love to have you in our [Slack](https://join.slack.com/t/devlake-io/shared_invite/zt-17b6vuvps-x98pqseoUagM7EAmKC82xQ) community :)

**Comment by ppborah** [comment]
> Hi, are you trying to connect to private repo? For Public Repo, you don't need to grant any permission at all. For Private Repo, the `repo` section must be checked.

We can improve our docs by adding the above, @klesh your thoughts ?

**Comment by klesh** [comment]
@ppborah I totally agree, we should add this to the Github related document.

**Comment by ppborah** [comment]
@klesh, thanks for acknowledging, I would like to work on this.

**Comment by likyh** [comment]
Notice: github graphql need `read:user` and `read:org` in future.
