### ISSUE TITLE
[Bug][Jenkins] ERROR: column "has_stages" of relation "_tool_jenkins_builds" does not exist (SQLSTATE 42703)

### ISSUE THREAD

**Issue by long2ice** [apache/incubator-devlake#2723]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

<img width="1559" alt="image" src="https://user-images.githubusercontent.com/13377178/183860837-829f5995-9a45-43be-b2e0-c62813394efe.png">

### What you expected to happen

Collect jenkins success

### How to reproduce

Create jenkins blueprints and run it

### Version

main

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by warren830** [comment]
sorry~~let me have a check
