### ISSUE TITLE
[Feature][Config UI] Blueprint detail page - Improve error message tone and voice consistency

### ISSUE THREAD

**Issue by yumengwang03** [apache/incubator-devlake#2724]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

This is an improvement for user experience. We need to show helpful and consistent messages on the UI when a Blueprint fails, so that users can fix the problem more easily. For this feature, we need a list of all known errors that cause the failure of Blueprints, and then work on the copywriting for these messages.

### Related issues

#1447 

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Startrekzky** [comment]
Bump

**Comment by yumengwang03** [comment]
Closing this because it's an ongoing improvements and will be addressed along the way of Config UI iterations.
