### ISSUE TITLE
add new PR metrics to engineering metrics

### ISSUE THREAD

**Issue by Startrekzky** [apache/incubator-devlake#2729]
- [x] [PR Cycle Time](https://devlake.apache.org/docs/Metrics/CycleTime)
- [x] [Coding Time](https://devlake.apache.org/docs/Metrics/CodingTime)
- [x] [PR/MR Size](https://devlake.apache.org/docs/Metrics/PRSize)
- [x] [PR Pickup Time](https://devlake.apache.org/docs/Metrics/PickupTime)
- [x] [PR Deploy Time](https://devlake.apache.org/docs/Metrics/DeployTime)
- [x] [PR Review Time](https://devlake.apache.org/docs/Metrics/ReviewTime)
- [x] [Time To Merge](https://devlake.apache.org/docs/Metrics/TimeToMerge)
- [x] [Review Depth](https://devlake.apache.org/docs/Metrics/ReviewDepth)

**Comment by yumengwang03** [comment]
I'll take this.
