### ISSUE TITLE
[Doc][Installation] Update Docs for new version with some minor fix

### ISSUE THREAD

**Issue by JoshuaPoddoku** [apache/incubator-devlake#2743]
## Documentation Scope
For v0.12.0, we can provide improved docs to avoid errors.

## Describe the Change
Wherever necessary, installation guides can be updated
Slack conversion thread: https://devlake-io.slack.com/archives/C03APJ20VM4/p1660281081774489

**Comment by ppborah** [comment]
Update: @Palanikannan1437 has completed the setup without installing MySQL locally, this might not be necessary.

**Comment by JoshuaPoddoku** [comment]
@ppborah let's rename this issue. It would be great to update necessary docs based on today's resolution by @Palanikannan1437

**Comment by ppborah** [comment]
Me and @Palanikannan1437 would like to work on this. Please assign both of us :)

**Comment by Palanikannan1437** [comment]
> Me and @Palanikannan1437 would like to work on this. Please assign both of us :)

Yes, that would be great! Please assign it to both of us!

**Comment by JoshuaPoddoku** [comment]
The issue is being followed here: https://github.com/apache/incubator-devlake-website/issues/160
