### ISSUE TITLE
[Bug][Api] advanced blueprint json response has pascal-case options

### ISSUE THREAD

**Issue by e2corporation** [apache/incubator-devlake#2762]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

Our current API contract in place has agreed to using `camelCase` for all API Response properties instead of `PascalCase`. [`GET`] for and Advanced Blueprint however certain properties **Plugin** and **Options** for instance, still returns in `PascalCase`. These and possibly other properties need to be changed to `camelCase` for consistency.

`Plugin ---> plugin`
`Options ---> options`

```
Summary
URL: http://localhost:4000/api/blueprints/7
Status: 200 OK
Source: Network
Address: 127.0.0.1:4000
Initiator: 
xhr.js:187


Request
GET /api/blueprints/7 HTTP/1.1
```
```
{
  "name": "ADVANCED BLUEPRINT DevLake",
  "mode": "ADVANCED",
  "plan": [
    [
      {
        "Plugin": "github",
        "Options": {
          "repo": "lake",
          "owner": "merico-dev",
          "connectionId": 1
        }
      }
    ]
  ],
  "enable": true,
  "cronConfig": "0 0 1 * *",
  "isManual": false,
  "settings": {
    "version": "1.0.0",
    "connections": []
  },
  "id": 7,
  "createdAt": "2022-08-02T21:57:42.744Z",
  "updatedAt": "2022-08-17T16:59:25.791Z"
}
```

### What you expected to happen

Full API response in `camelCase` for Advanced Blueprints.

### How to reproduce

Fetch and Advanced Blueprint over API.

### Version

main

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by mappjzc** [comment]
It seems that I can not reappearance the problem.
My api/blueprint return me this.
![image](https://user-images.githubusercontent.com/2921251/185617643-bd6b42a3-84a2-482d-a15f-e4a15820110a.png)

**Comment by mappjzc** [comment]
The plugin and the option been saved at the field plan.
And the paln was json.RawMessage
![YV0nkQov4Y](https://user-images.githubusercontent.com/2921251/185619966-f42e5e88-7828-46dc-89df-738a48a87fec.jpg)
It storages as is.

**Comment by e2corporation** [comment]
@klesh @mappjzc I think I see part of the problem, our old pipeline config samples are using pascal case (Loading Templates in Advanced Mode). I will have to update the advanced pipeline sample configs to use `camelCase`.
