### ISSUE TITLE
[Bug][config-ui] log download path error

### ISSUE THREAD

**Issue by likyh** [apache/incubator-devlake#2765]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

![image](https://user-images.githubusercontent.com/3294100/185337861-a6c9536f-b2d9-4449-b6fc-a0333a6b53e1.png)
when downloading the log, it requests a wrong path.

### What you expected to happen

The requested URL should be filled with pipelineId.

### How to reproduce

download log in any pipeline.

### Version

main

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by e2corporation** [comment]
@likyh This logic was previously working when it was first merged to main (in regards to Pipeline ID being correct). API path has a pipeline id of 0 which is only the default value (for orphaned pipelines), so that's the first thing to look into is why would the pipeline ID still be 0. 

I'll look into this after my next PR.

**Comment by tk103331** [comment]
I think it should be the problem of the following line of code, the 'pipeline' parameter is not passed in.
`checkDownloadStatus()`

https://github.com/apache/incubator-devlake/blob/b81b98d4f039c44ed3dd70b8e76a51a0b06432b2/config-ui/src/pages/blueprints/blueprint-detail.jsx#L228

![image](https://user-images.githubusercontent.com/4404609/186079667-c3867d3e-14d8-4b67-b07a-689863a61c8d.png)

I changed it to `checkDownloadStatus(pipeline)` and it worked

![image](https://user-images.githubusercontent.com/4404609/186080214-cc773829-b217-4c46-af5f-410466645930.png)

**Comment by e2corporation** [comment]
@keon94 Are there any pending logfile fixes to be merged to `main`? After testing the download on OSX I'm noticing an issue where the request to `GET` the logfile (using valid pipeline id) results in an a process hangup with main executable and a file (logging.tar.gz) is never served for download.

**Comment by e2corporation** [comment]
> I think it should be the problem of the following line of code, the 'pipeline' parameter is not passed in. `checkDownloadStatus()`
> 
> https://github.com/apache/incubator-devlake/blob/b81b98d4f039c44ed3dd70b8e76a51a0b06432b2/config-ui/src/pages/blueprints/blueprint-detail.jsx#L228
> 
> ![image](https://user-images.githubusercontent.com/4404609/186079667-c3867d3e-14d8-4b67-b07a-689863a61c8d.png)
> 
> I changed it to `checkDownloadStatus(pipeline)` and it works.
> 
> ![image](https://user-images.githubusercontent.com/4404609/186080214-cc773829-b217-4c46-af5f-410466645930.png)

Thanks for the reply and for noticing this -- yes this is the main issue `pipeline` var was not injected. This logic is also being slightly re-worked and the variable will be passed as expected.
