### ISSUE TITLE
[Bug][Config-ui] Can't proceed with no reason 

### ISSUE THREAD

**Issue by warren830** [apache/incubator-devlake#2784]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

![image](https://user-images.githubusercontent.com/39366025/185741780-cdd01ab8-a943-47a7-ade1-792786468e61.png)
I can not click next step. Or I should be given some info?

One more thing, if we don't fill these inputs, can we use the default values?

<img width="558" alt="image" src="https://user-images.githubusercontent.com/39366025/185795355-533b0081-20e4-4aa1-ade0-a93ecd7fb8ab.png">

### What you expected to happen

The page should tell me which part I must fill

### How to reproduce

run github tasks with refdiff

### Version

main

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by e2corporation** [comment]
@warren830 You most exit/close "Edit"Transformation mode before allowing to go "Next". Please click **Go Back** first and see if the next button is re-activated.

**Comment by warren830** [comment]
> @warren830 You must exit/close "Edit"Transformation mode before allowing to go "Next". Please click **Go Back** first and see if the next button is re-activated.

Thanks Julien, right now it works. But I think this might mislead users..

**Comment by e2corporation** [comment]
@warren830 This functionality has been the same since V12, also the behavior was requested by the Product team which makes sense since we want the user to complete editing before proceeding next.  Normally you would see all the projects listed before getting to the edit screen. Maybe we can put a help tooltip to let the user know that the next button is disabled while they are editing.

**Comment by klesh** [comment]
I agree with both of you.
Can we add some animation to the "Go Back" button to draw Users' attention?

**Comment by e2corporation** [comment]
@klesh I'll look into making some adjustments.

**Comment by e2corporation** [comment]
Closed with #2799
