### ISSUE TITLE
[Bug][gitee] gitee requests too many duplicated rows when  there are more than 1 page of commits in pr

### ISSUE THREAD

**Issue by likyh** [apache/incubator-devlake#2785]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

gitee requests too many duplicated rows when there are more than 1 page of commits in pr.

Such as this: `https://gitee.com/api/v5/repos/Apache-ShenYu/shenyu/pulls/3/commits?access_token=……&page=1` and `https://gitee.com/api/v5/repos/Apache-ShenYu/shenyu/pulls/3/commits?access_token=……&page=2` have same data and failed to page. So it can not finish.

Collect this repo and it is just 5 pr. https://gitee.com/Apache-ShenYu/shenyu

### What you expected to happen

Collect success and not collect duplicatedly.

### How to reproduce

use plugin gitee and collect this: https://gitee.com/Apache-ShenYu/shenyu

### Version

main

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by likyh** [comment]
Also, we should check all the request to see if paging work.

**Comment by thenicetgp** [comment]
I am willing to submit a PR
