### ISSUE TITLE
[Feature][config-ui] Supports `db migration confirmation`

### ISSUE THREAD

**Issue by klesh** [apache/incubator-devlake#2788]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Currently, users have to `curl /api/proceed-db-migration` if there were pending migration scripts manually.

![image](https://user-images.githubusercontent.com/61080/185833787-04e7e738-f455-4590-8fb1-cd2febc3b3ae.png)

We should offer a flow in to allow users to confirm the operation `config-ui`.
For example: 
redirect to a page which describe the risk of applying db-migration-scripts, telling them they could switch back to the previous version if they will. offer a button "confirm and proceed" on the page if they would like to upgrade.

### Use case

Users could finish the upgrade in `config-ui`

### Related issues

https://github.com/apache/incubator-devlake/issues/2816

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by tanninghan** [comment]
![image](https://user-images.githubusercontent.com/102040651/186367544-c0d64347-2459-4ab6-8cb8-23a1fef0a81b.png)
See design here: https://www.figma.com/file/Eux4Dhorxp7M0TwzOnL6Yh/Config-UI-for-V1.0?node-id=1291%3A10778

**Comment by e2corporation** [comment]
@klesh What happens when Downgrade option is selected?

**Comment by klesh** [comment]
@e2corporation Nothing... One would have to revert the docker-compose / k8s-deployment and then restart the containers. We don't need the Downgrade button, and the Error Message has to be Rephased in config-ui, do NOT use the original error message from the API response directly.

**Comment by yumengwang03** [comment]
<img width="1011" alt="Screen Shot 2022-08-29 at 10 12 22 PM" src="https://user-images.githubusercontent.com/9535430/187221528-8aca23cd-1811-4525-987e-7dd7750480db.png">

Just updated based on feedback. Does this look right? @klesh @e2corporation

**Comment by e2corporation** [comment]
@yumengwang03 Please see screenshots on this development PR for Migration feature, https://github.com/apache/incubator-devlake/pull/2859.

It looks like additional information on how to manually approve the migration was removed from the initial notice?
