### ISSUE TITLE
[Bug][bitbucket] Unused Models

### ISSUE THREAD

**Issue by likyh** [apache/incubator-devlake#2790]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

These model haven't used.
bitbucket/models/issue_event.go
bitbucket/models/issue_label.go
bitbucket/models/user.go

### What you expected to happen

delete them.

### How to reproduce

it saved in https://github.com/apache/incubator-devlake/tree/main/plugins/bitbucket/models.

### Version

main

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by thenicetgp** [comment]
I will take this one.
