### ISSUE TITLE
[Bug][gitlab] CollectApiCommitsMeta never use anymore 

### ISSUE THREAD

**Issue by mappjzc** [apache/incubator-devlake#2797]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

CollectApiCommitsMeta not use on SubTaskMetas anymore.
DOMAIN_TYPE_CODE not use on config-ui anymore.
![image](https://user-images.githubusercontent.com/2921251/185965227-e0c7178a-972f-4d00-91a4-047250857aac.png)
![image](https://user-images.githubusercontent.com/2921251/185965323-088f1faf-6663-4e62-88ca-c2e354b8d294.png)
![Uploading image.png…]()

### What you expected to happen

remove unuse code.

### How to reproduce

run and read the code

### Version

main

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by klesh** [comment]
No, keep them, as long as the `EnableByDefault=false`, then we are good. do NOT remove them at this point.
