### ISSUE TITLE
[Feature][Issue Tracking] Allow users to add their customized issue fields into domain schema

### ISSUE THREAD

**Issue by leglars** [apache/incubator-devlake#2802]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Comprehensive issue tracking tools, like Jira and TAPD, have a great ability to extend issue fields for users. Therefore, we should allow users to add these customized fields into domain schema, so that they can easily aggregate and analyze data by these fields without hassle.

### Use case

In my Jira practice, I create many customized fields to manage and categorize issues. For example, our development team have several sub-team to take responsibility for different sub-system or components in our product. I create a field called "team" to help me allocate issues to each sub-team. And each sub-team only need to focus on their sub-backlog.

Obviously, the "team" field is not covered by domain layer and won't considered as a universal practice. But, when I dig in my issue data, "team" is an important dimensions to aggregate data and find the problem.

"team" is just an example. It could be "group", "issue reason", "importance", etc. 

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by klesh** [comment]
# Requirement (from @leglars)

1. A set of APIs to manage customize-jira-issue-fields on the fly, including list/add/delete
2. The `field name` should be customizable at table level.
3. User should be able to specify the mapping between `raw issue json` and `jira issue table`

# Solution

This is an advanced feature, we don't know if it would thrive or not, we keep it minimal and see how it goes.

## Points

- All customize-jira-issue-fields (hereafter this text will be abbreviated as CJIF) should be prefixed with `x_`, so we could distinguish them from normal fields.
- `varchar255` is the only supported type at the moment.
- no indexing or any other complicated features.


## Plan of attack

1. `GET /plugins/jira/customize/issues/fields` to return a list of all CJIF, that is fields with prefix `x_`
   ```json
   [
     { "name": "<FIELD_NAME>", "columnName": "x_<FIELD_NAME>", "columnType": "varchar(255)" },
     ...
   ]
   ```
2. `POST /plugins/jira/customize/issues/fields` to create a new CJIF, the name of the field must be verified, and a field named `x_<FIELD_NAME>` should be created in `jira issues` table with type `varchar(255)`.
   REQUEST
   ```json
   { "name": "<FIELD_NAME>" }
   ```
   RESPONSE
   ```json
   { "name": "<FIELD_NAME>", "columnName": "x_<FIELD_NAME>", "columnType": "varchar(255)" }
   ```
3. `DELETE /plugins/jira/customize/issues/fields/<FIELD_NAME>` to delete the specified CJIF.
4. Update `jira transformation rules` to accept a `map[string][string]` as the mapping between `raw json` and `jira issue`
   NEW TRANSFORMATION RULES
   ```json
   {
     ...,
     "customizeFields": {
       "<JSON_PATH_FOR_RAW_JSON>": "<FIELD_NAME>",  // "fields.customfield_10020.0.id": "sprint_id"
       ...
     }
   }
   ```
5. Define a new interface named `DynamicFields` under `core/dal` with methods `GetDynamicFields` and `SetDynamicFields` with type `map[string]interface{}`
6. `jira issue` implement the `DynamicFields` interface, 
7. Update the `jira issue extractor`, ADD new logic to handle the CJIF extraction, and call `SetDynamicFields`
8. Update the `BatchSave.Flush`, check if the entity implemented `DynamicFields`, and do an extra UPDATE operation accordingly https://gorm.io/docs/update.html#Updates-multiple-columns
9. Update swagger document
10. Update office document

**Comment by narrowizard** [comment]
Sounds it will update domain layer's table (like `issues`) schema, then how can we handle the db migration stuffs?  eg: 
- conflicted custom fields
- schema update in `customize` tasks

**Comment by klesh** [comment]
@narrowizard  all custom fields will be prefixed with `x_`, these fields will not be managed by `migration`.
@mindlesscloud we should throw an error if migration contains columns with the prefix.
