### ISSUE TITLE
[Bug][k8s-deploy] The image tag should be using apache/xxx instead of mericodev

### ISSUE THREAD

**Issue by klesh** [apache/incubator-devlake#2811]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

![image](https://user-images.githubusercontent.com/61080/186298742-3c3b671b-427b-4601-861d-5d3ce2d86b82.png)

### What you expected to happen

The `mericodev` should be replaced with `apache`

### How to reproduce

See https://github.com/apache/incubator-devlake/blob/main/k8s-deploy.yaml

### Version

main

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by thenicetgp** [comment]
I am willing to submit a PR
