### ISSUE TITLE
[Doc][db migration] Improve db-migration-confirmation message for Production Mode

### ISSUE THREAD

**Issue by klesh** [apache/incubator-devlake#2816]
## Documentation Scope
db migration confirmation error message

## Describe the Change
Currently, the db-migration-confirmation message tells users to request `/proceed-db-migration` OR `/api/proceed-db-migration` from config-ui, which is confusing for End Users: It suggests both URLs could work, but, in reality, only the latter one would work since we don't expose `devlake` directly.
We should improve the message for the time being:
```
send a request to `/api/proceed-db-migration` (`/proceed-db-migration` if you were running `devlake` alone) if it is ok, 
```

## Screenshots
![image](https://user-images.githubusercontent.com/61080/185833787-04e7e738-f455-4590-8fb1-cd2febc3b3ae.png)

**Comment by hezyin** [comment]
@klesh How about the following version:

> New migration scripts detected. Database migration is required to launch DevLake.
> WARNING: Performing migration may wipe collected data for consistency and re-collecting data may be required.
> To proceed, please send a request to `<config-ui-endpoint>/api/proceed-db-migration` (or `<devlake-endpoint>/proceed-db-migration`).
> Alternatively, you may downgrade back to the previous DevLake version.
