### ISSUE TITLE
[Refactor][config-ui] delete the use of `switch` in connection manager to prepare for dynamic connection 

### ISSUE THREAD

**Issue by likyh** [apache/incubator-devlake#2826]
## What and why to refactor
delete the use of `switch` in connection manager to prepare for dynamic connection.
Now the use of `switch` blocks us from adding more types of connections quickly.
So we need to refactor it to more commonly check.

## Describe the solution you'd like
add `columns` in `integrationsData` to generate inputs.

**Comment by e2corporation** [comment]
@likyh There are only 2 switch blocks in this file... mainly controlling what active properties are needed to be defined from API for the active connection object, which there are ways to consolidate this. Generating dynamic inputs is another matter altogether.

**Comment by likyh** [comment]
Not only 2:
https://github.com/apache/incubator-devlake/blob/main/config-ui/src/pages/configure/connections/ConnectionForm.jsx#L710
https://github.com/apache/incubator-devlake/blob/main/config-ui/src/hooks/useConnectionManager.jsx#L145
https://github.com/apache/incubator-devlake/blob/main/config-ui/src/hooks/useConnectionValidation.jsx#L82

This is the main block.

**Comment by e2corporation** [comment]
@likyh I don't feel that we need some complex auto-generated "dynamic connection" form. All providers are already sharing the same connection form with a few business rule surrounding which providers have access to that field. There are other ways to optimize the switch statements without refactoring everything. Why was this item created?

**Comment by likyh** [comment]
> @likyh I don't feel that we need some complex auto-generated "dynamic connection" form. All providers are already sharing the same connection form with a few business rule surrounding which providers have access to that field. There are other ways to optimize the switch statements without refactoring everything. Why was this item created?

For add more types of connections edit. https://github.com/apache/incubator-devlake/tree/main/plugins
Which other way is?

**Comment by e2corporation** [comment]
@likyh Before getting carried away with "Dynamic" everything, lets look at the problem you're trying to solve for. It sounds like the backend team as a whole has this anxiety of not knowing what needs to be done on Frontend's Config-UI when a new provider is added. You continue to make it sound like it's difficult to configure a Provider on UI when there's way more work in actually writing a backend plugin. The connection form is **already dynamic.** and it's a single unified form for All providers, it's driven by frontend's Integrations configuration as you are already aware of. If we wanted to use a completely separate connection form design for a provider type we already have the flexibility to do that.

1) Identify and Document Provider Registration Steps on UI (I will draft notes on this)
2) Optimize and Streamline the current Configuration Process
3) Evaluate the need for API Driven Dynamic Form controls

The switch statements you mentioned I plan to consolidate into one callback that sets all unified connection props regardless of provider type.

Let's look at the last TAPD PR 2675 for UI by @warren830 to get an idea of configuration changes needed on UI,
https://github.com/apache/incubator-devlake/pull/2675
