### ISSUE TITLE
[Bug][config-ui] Wording for log downloading button

### ISSUE THREAD

**Issue by klesh** [apache/incubator-devlake#2830]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

![image](https://user-images.githubusercontent.com/61080/186566044-9713eea3-ce54-4e1b-8e47-c333b0b4b161.png)

### What you expected to happen

the tooltip text should be "Download full log"

### How to reproduce

goto blueprint detail page
hover on pipeline log downloading button

### Version

main

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by tk103331** [comment]
OK，please assign to me.
