### ISSUE TITLE
[Feature][config-ui] generate plugin configuration page based on plugin metadata

### ISSUE THREAD

**Issue by tk103331** [apache/incubator-devlake#2846]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Using the plugin mode is flexible. The same goes for the plugin's configuration parameters.
I found that the configuration page of the current plugin is defined by the front-end project. It cannot be automatically generated based on the plugins supported by the backend.

If I develop a new custom plugin myself, but the front-end does not have its configuration page. Front-end engineers must design new configuration pages.

I have an idea, I don't know if it will work or not.
**Customize the configuration page metadata in the plugin, and the front end generates page elements based on these metadata.**

The configuration parameters of the plugin need to be abstracted here. For example, parameters may have these properties: dataType, showType, validation, datasource, etc.
- **dataType**: Indicates the data type, such as number, string, array
- **showType**: Indicates the display type, such as input, select
- **validation**: used for form validation, such as required validation, regular validation, range validation
- **datasource**: the option data source for the 'select' component, which can be a simple dictionary, or the data returned by the interface provided by the plugin
- and other properties: **placeholder**, **helpText**, etc.

### Use case

generate plugin configuration page based on plugin metadata

![image](https://user-images.githubusercontent.com/4404609/186806234-bb250b52-0d6b-4efc-9db8-411cc3a1ea02.png)

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by tk103331** [comment]
Configuring metadata based on plugins can also solve this problem： https://github.com/apache/incubator-devlake/issues/2800。 

For example, add a 'security' attribute to the PAT parameter of the GitHub plugin.
The front-end configuration page generates a password input box.
The backend can store PAT parameters encrypted.

**Comment by klesh** [comment]
Nice, this is exactly what we had in our mind for quite a while, we have been tweaking our system bit by bit toward this goal!
But, this is big, it may take a couple of iterations for things to work.
So, I created #2847 to track the overall progress regarding this matter.
I'm glad that we share the same vision, please keep a tab on #2847 if you are interested.

@likyh FYI

**Comment by Startrekzky** [comment]
Bump
