### ISSUE TITLE
[Feature][config-ui] Dynamic UI

### ISSUE THREAD

**Issue by klesh** [apache/incubator-devlake#2847]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

1. #1411
2. config-ui to utilize this api, and provide a checkbox list on `create pipeline` page for user to select what they wanted to run.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by e2corporation** [comment]
@klesh "Dyanmic UI" is a misleading title, this ticket should be better titled "Add Subtasks Selector to Blueprint Normal Mode UI".

**Comment by klesh** [comment]
@e2corporation This epic is not only about "Add Subtasks Selector to Blueprint Normal Mode UI". In long term, we want "Data Integration"
![image](https://user-images.githubusercontent.com/61080/187106254-e5b4e8dd-4bbe-4386-ad00-6b6bd99a76b8.png)
and 
![image](https://user-images.githubusercontent.com/61080/187106285-fe88ba56-a637-4fd2-903a-544b30725155.png)
Places like that to be generated dynamically based on Server-Side information.
It is important because someday people would have private plugins which we can't predefine in config-ui, and we would like users to be able to manage these private plugins via config-ui.
In contrast, users may also delete/disable existing plugins, and the interface should act accordingly to avoid confusion.
This is a long-term epic issue, my plan is to do it in multiple iterations.
What do you think?

**Comment by e2corporation** [comment]
@klesh I understand the concept of having Dynamic Connections, I know what needs to be done to achieve this and I have my own plans optimizing the configuration. My problem is that this knowledge of "People have private plugins which need to be defined in UI" has not been mentioned by Louis our Product manager, nor has the feature has not been requested in a formal ticket with accurate details. Instead, the backend team is opening "refactor" tickets on their own to change core functionality on UI without me having any input. It's also making it difficult to focus on feature development when other developers are refactoring the system while I am trying to get features built for this milestone. This is not proper coordination. "users may also delete/disable existing plugins" has also never been mentioned in team meetings or logged issues as a normal use case of the application.
