### ISSUE TITLE
[Feature][framework] Encrypting `blueprint.settings` `blueprint.plan` and `pipeline.plan` in the database

### ISSUE THREAD

**Issue by klesh** [apache/incubator-devlake#2868]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

According to the discussion in #2800.
It is totally legit to encrypt those fields in the database since they might contain sensitive information like git repo password/token.

### Use case

enhance the security in case of Database Leaks

### Related issues

#2800

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by yuqiangabab** [comment]
I am willing to submit a PR
