### ISSUE TITLE
[Feature][Config-UI] Create Plugin Registry

### ISSUE THREAD

**Issue by e2corporation** [apache/incubator-devlake#2882]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Create a configurable Plugin Registry for Config-UI that will optimize the use and configuration of Data Providers.

### Use cases

As Developers build new Plugins for DevLake, we want to streamline the process of how those plugins are integrated with Configuration-UI.

- [x] Create a Defined Plugin Registration Schema (JSON Registration Files)
- [x] Create Local Plugin Registry Configuration
- [x] Minimize the amount of Configuration Scopes

### Advanced Use Cases
- [ ] Allow Plugins to Define Transformation Settings Fields
- [ ] Allow Dynamic "API" Plugins to be Loaded (Live Plugin Registry)

### Related issues

- #2847 
- #2826 

_No response_

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by likyh** [comment]
I don't think #2862 contradicts this issue. #2862 is the base of it.

**Comment by e2corporation** [comment]
@likyh I had previously requested that you halt changes on refactoring key areas of the code when that ticket was opened, I don't agree with your approach on this, I would appreciate if you follow my lead instead of refactoring the whole ui codebase. Your changes are unnecessarily creating hours of code review and re-testing.

**Comment by e2corporation** [comment]
Not so fast @github-actions
