### ISSUE TITLE
[Bug][Jira] Wrong jira api version

### ISSUE THREAD

**Issue by warren830** [apache/incubator-devlake#2883]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

jira plugin use api/3/issuetype to collect issue types.

### What you expected to happen

we should use api/2/issuetype as jira server doesnt support api/3

### How to reproduce

run jira plugin

### Version

main

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhangzhenyu2** [comment]
I will fix that as soon as possible, thanks
