### ISSUE TITLE
[Refactor][config] get `connectionsList` in the wrong way when requesting all plugin connections.

### ISSUE THREAD

**Issue by likyh** [apache/incubator-devlake#2888]
## What and why to refactor
get `connectionsList` in the wrong way when requesting all plugin connections.

https://github.com/apache/incubator-devlake/blob/main/config-ui/src/hooks/useConnectionManager.jsx#L402-L422

c is not set when requesting allSources.

## Describe the solution you'd like
move it to the right statement.

**Comment by Startrekzky** [comment]
Will it be refactored in v0.15? @likyh
