### ISSUE TITLE
[Bug][config-ui] proxy in jenkins cannot be saved

### ISSUE THREAD

**Issue by likyh** [apache/incubator-devlake#2897]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

![image](https://user-images.githubusercontent.com/3294100/187614626-73dcd875-d428-46b1-88cc-53d4a76d9a8d.png)
![image](https://user-images.githubusercontent.com/3294100/187615165-64e36a83-7474-424e-a758-a9cef92e92e4.png)

### What you expected to happen

save proxy correctly.

### How to reproduce

Modify a Jenkins connection and open it again, and you'll see the proxy is empty and not saved.

### Version

main

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by e2corporation** [comment]
@likyh If this is a bug its as nothing to do with refactoring, please open a separate PR fix to main for this issue.

**Comment by e2corporation** [comment]
Resolved with PR #2903
