### ISSUE TITLE
[Bug][config-ui] "Go Back" always keep loading

### ISSUE THREAD

**Issue by likyh** [apache/incubator-devlake#2905]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

![image](https://user-images.githubusercontent.com/3294100/187820758-90f24bf4-5f3b-4012-a789-3c9706024a97.png)
![image](https://user-images.githubusercontent.com/3294100/187820341-37b18f60-2f21-406b-bca8-f92bece6a319.png)
It always loading but can be clicked.

### What you expected to happen

don't show loading if I haven't click it.

### How to reproduce

1. create blueprint
2. choose jira and github repo
3. edit transfomation rules
4. look at save button

### Version

main

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by e2corporation** [comment]
@likyh This doesn't look like a bug. Did you name your connection "111" If so this is Normal Behavior? The Connection Name appears in the Tab Selector, not the Provide Name. In most cases the names entered are "JIRA" or "GitHub" but user defines whatever connection name. Additionally, if you selected 2 jira instances and we displayed only the connection provider id, we would see "JIRA" twice which would be more confusing.

**Comment by e2corporation** [comment]
@likyh This is not a bug, Klesh requested that The "Go Back" Button have an animation added to it so users are aware they should click it, otherwise "Next" is disabled. If you hover over the Go Back button spinner it will show a tooltip instructing the same.

**Comment by likyh** [comment]
> @likyh This is not a bug, Klesh requested that The "Go Back" Button have an animation added to it so users are aware they should click it, otherwise "Next" is disabled. If you hover over the Go Back button spinner it will show a tooltip instructing the same.

"Go Back" should always keep loading??????

**Comment by e2corporation** [comment]
It's just a spinner it's not loading anything...

**Comment by e2corporation** [comment]
It's indicating activity. This behavior is subject to change in the future, for now that behavior was already approved.
