### ISSUE TITLE
[Bug][Config-UI] Refactor PR 2887 causing duplicate PATCH+POST for Save/Modify

### ISSUE THREAD

**Issue by e2corporation** [apache/incubator-devlake#2915]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

The Refactor PR https://github.com/apache/incubator-devlake/pull/2887 has introduced a new bug where connections are modified and saved twice. Please see comments starting on `Ln 260`.

### What you expected to happen

`saveConfiguration` and `modifyConfiguration` should not be triggered twice. Either the original flow needs to be reverted, or only the new `savePromise` should be executed. Only 1 `POST` request dispatched for **Save** and 1 `PATCH` request should be dispatched for **Modify**

### How to reproduce

Save or Modify any connection and Check XHR Log. 2 `PATCH` and 2 `POST` requests are dispatched.

### Version

main

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by e2corporation** [comment]
@likyh Can you take a look and resolve accordingly? The easiest fix would be to comment out the extra calls to modify and save.

**Comment by likyh** [comment]
ok, rebase bug.

**Comment by e2corporation** [comment]
@likyh Nice, did you test and check XHR log to verify that only 1 event gets dispatched?

**Comment by likyh** [comment]
> @likyh Nice, did you test and check XHR log to verify that only 1 event gets dispatched?

@e2corporation No, promise.then and setTimeout will both run but they have the different conditions.
