### ISSUE TITLE
[Bug][Config-UI] Data Integrations - Toast Notifications odd behavior on Add Connections

### ISSUE THREAD

**Issue by e2corporation** [apache/incubator-devlake#2923]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

**Unable to add a New Connection** for any provider. Users are redirected to the Manage Connections Screen without the connection successfully saving.

### What you expected to happen

A New Connection is Added successfully. User receives a successful Toast warning Stating as such.

### How to reproduce

Try adding a NEW Connection for Any Provider.

### Version

main

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by e2corporation** [comment]
The only Provider that seems to partially work is Jenkins.

**Comment by likyh** [comment]
![image](https://user-images.githubusercontent.com/3294100/187946662-2deb68ad-3c5f-40c7-b3ad-c2decb7efbbe.png)
![image](https://user-images.githubusercontent.com/3294100/187946783-41e3d664-9bd5-48c6-9fdc-3af132eab5ec.png)
I create success. Would you add more info for what situation?

**Comment by e2corporation** [comment]
@likyh Try Adding more than 1 connection to an existing provider

**Comment by e2corporation** [comment]
Previously if there's any failure in the Add process user is kept on the Add Connection page, no redirection happens.

**Comment by likyh** [comment]
> @likyh我认为这与添加同名连接有关，用户没有错误并立即重定向到管理连接页面。感觉有些不对劲，将继续测试以找出问题所在并添加详细信息。

![image](https://user-images.githubusercontent.com/3294100/187948291-76bd15e0-7124-47df-a479-1d541bb21aac.png)
Yes, It show error when duplicate name. Any other idea?

**Comment by e2corporation** [comment]
@likyh Will keep testing, something is still off with regards to the ToastNotifications and changes in timeout behavior. User never gets to see a success Toast anymore.

**Comment by e2corporation** [comment]
If I go to "Add New Connection" for any provider, enter a Connection Name that already exists and click Save. I get redirected to Manage Connections with no error or a new connection added.

**Comment by e2corporation** [comment]
Partially relates to #2892

**Comment by likyh** [comment]
> If I go to "Add New Connection" for any provider, enter a Connection Name that already exists and click Save. I get redirected to Manage Connections with no error or a new connection added.

Would you like to record a video of your actions? I try it but not get your error.

**Comment by e2corporation** [comment]
I am trying to Screen record it GiFox not capturing correctly. Part of the problem with ToastNotifications is that since the savePromise was added you need to move the setTimeout to inside the promise. This is causing conflicts with Toast behavior.

Lines 300 - 302 should get deleted, the timeout should not be calling these setters since it's now being handled in the promise. setShowError, setIsSaving, setSaveComplete shouldnt be in the Timeout anymore.

```
    setTimeout(() => {
      if (!saveResponse.success || errors.length !== 0) {
        ToastNotification.show({
          message: 'Connection failed to save, please try again.',
          intent: 'danger',
          icon: 'error',
        })
       // DELETE These 3 lines
        setShowError(true)
        setIsSaving(false)
        setSaveComplete(false)
      }
    }, 2000)
```

<img width="748" alt="Screen Shot 2022-09-01 at 11 20 19 AM" src="https://user-images.githubusercontent.com/1742233/187951210-e8041438-1243-43c7-bc13-ad16a9b62d1c.png">

**Comment by e2corporation** [comment]
I have to do more refactoring to this area this new logic is not behaving correctly.

**Comment by likyh** [comment]
> I have to do more refactoring to this area this new logic is not behaving correctly.

Ok, If you find out why it is, please record here.

**Comment by e2corporation** [comment]
I am going to get rid of this timeout completely and replace it with an effect which is what I originally planned to do.

**Comment by e2corporation** [comment]
I also want to remove the need for Testing a connection inside the save operation, if anything we need to test before save happens.

**Comment by likyh** [comment]
> I am going to get rid of this timeout completely and replace it with an effect which is what I originally planned to do. In which case I can remove the promise at this layer and use the original code flow. Will keep you posted.

Of course, I also think we should not use setTimeout here. I think it uses setTimeout only because it cannot display tips correctly. Toast is cleared by fetch or other requests.

**Comment by e2corporation** [comment]
Partially relates to #2892 (BE returning false positives when adding a connection of the same name, and during connection add a POST of the same named connection overwrites the original connection)
