### ISSUE TITLE
[Doc][README] The link to the Metrics page is wrong

### ISSUE THREAD

**Issue by Startrekzky** [apache/incubator-devlake#2924]
## Documentation Scope
main README

## Describe the Change
The link to the Metrics page is wrong. The expected URL should be https://devlake.apache.org/docs/Metrics

## Screenshots
![image](https://user-images.githubusercontent.com/14050754/187946045-a1411cf1-4be4-41e8-970e-55e5a0d67a63.png)

**Comment by meeraj257** [comment]
I  will work on this issue.
