### ISSUE TITLE
Link is not working 

### ISSUE THREAD

**Issue by lavakush07** [apache/incubator-devlake#2937]
## Documentation Scope
- In **Installation via Kubernetes** section k8-deploy.yaml link is not working.

## Describe the Change
- Link should be working properly instead of showing 404.

**Comment by abeizn** [comment]
Thanks for the docs, we will take a look at it.

**Comment by Startrekzky** [comment]
Doc Address: https://devlake.apache.org/docs/GettingStarted/KubernetesSetup

![image](https://user-images.githubusercontent.com/14050754/188106108-a42182cc-cd3f-42d4-a21c-2c4515ec7fae.png)
