### ISSUE TITLE
[Bug][plugin-helper] the timeout of ApiClient is incorrectly overridden

### ISSUE THREAD

**Issue by tk103331** [apache/incubator-devlake#2938]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

I create ApiClient with a timeout value. But, the timeout value of ApiClient is incorrectly overridden by `helper.CreateAsyncApiClient()`.
I don't think this should be overridden when API_TIMEOUT is empty, especially since I've set a timeout value.

https://github.com/apache/incubator-devlake/blob/cb25f65384bd4608b29c48587084be42cb8bbe4e/plugins/helper/api_async_client.go#L59-L63

### What you expected to happen

I think the timeout value should'n be overridden when API_TIMEOUT is empty, especially since I've set a timeout value.

### How to reproduce

1. Create ApiClient with a timeout value.
2. Use helper.CreateAsyncApiClient() to create AsyncApiClient.

### Version

main

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by abeizn** [comment]
@tk103331 Thanks for reporting the issue. I'm looking forward to your PR.
