### ISSUE TITLE
[Bug][Core] Database Migration Required uses Wrong Status Code 500 

### ISSUE THREAD

**Issue by e2corporation** [apache/incubator-devlake#2940]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

As part of the assumptions for a required DevLake Database Migration, the Backend should return with a HTTP Status Code `428`, instead it using Internal Server `500`.

### What you expected to happen

API should always return with Status Code `428` If DB Migration is Required

### How to reproduce

N/A - UI will not show migration alert if api responds with internal server error 500

### Version

main

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by klesh** [comment]
@keon94 I think this might be related to the PR #2763 
Would you like to take a look?

**Comment by keon94** [comment]
> @keon94 I think this might be related to the PR #2763 Would you like to take a look?

Yeah, it's a minor issue. I can fix it.
