### ISSUE TITLE
[Bug][devlake] git extractor

### ISSUE THREAD

**Issue by nicoabie** [apache/incubator-devlake#2942]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

Connected devlake to github, created the blueprint and the git extractor task failed.

### What you expected to happen

I would expect it to fetch the GH information
Also have a better log of what happened

this is the json: I cannot share the PAT for security.
if a permission is missing let me know and I can create a new PAT with that.
there is no mention of which permissions are needed, it would be nice to have that list
```json
{
  "id": 3,
  "createdAt": "2022-09-04T03:08:20.845Z",
  "updatedAt": "2022-09-04T03:10:14.092Z",
  "name": "ReMatter 1662260496518",
  "blueprintId": 2,
  "plan": [
    [
      {
        "plugin": "github",
        "options": {
          "repo": "Universe",
          "owner": "ReMatter",
          "connectionId": 2,
          "transformationRules": {
            "prType": "",
            "refdiff": null,
            "prComponent": "",
            "issueTypeBug": "",
            "issuePriority": "",
            "issueSeverity": "",
            "issueComponent": "",
            "issueTypeIncident": "",
            "issueTypeRequirement": ""
          }
        },
        "subtasks": [
          "collectApiIssues",
          "extractApiIssues",
          "collectApiPullRequests",
          "extractApiPullRequests",
          "collectApiComments",
          "extractApiComments",
          "collectApiEvents",
          "extractApiEvents",
          "collectApiPullRequestCommits",
          "extractApiPullRequestCommits",
          "collectApiPullRequestReviews",
          "extractApiPullRequestReviews",
          "CollectApiPrReviewCommentsMeta",
          "extractApiPrReviewComments",
          "collectApiMilestones",
          "extractMilestones",
          "collectAccounts",
          "extractAccounts",
          "collectAccountOrg",
          "ExtractAccountOrg",
          "enrichPullRequestIssues",
          "convertRepo",
          "convertIssues",
          "convertIssueLabels",
          "convertPullRequestCommits",
          "convertPullRequests",
          "convertPullRequestReviews",
          "convertPullRequestLabels",
          "convertPullRequestIssues",
          "convertIssueComments",
          "convertPullRequestComments",
          "convertMilestones",
          "convertAccounts"
        ]
      },
      {
        "plugin": "gitextractor",
        "options": {
          "url": "",
          "repoId": "github:GithubRepo:2:222375197"
        },
        "subtasks": null
      }
    ]
  ],
  "totalTasks": 2,
  "finishedTasks": 0,
  "beganAt": "2022-09-04T03:08:21.377Z",
  "finishedAt": null,
  "status": "TASK_FAILED",
  "message": "",
  "spentSeconds": 0,
  "stage": 1,
  "ID": 3
}
```

[task-7-1-1-github.log](https://github.com/apache/incubator-devlake/files/9483793/task-7-1-1-github.log)

### How to reproduce

Connect devlake to github
Create custom blueprint
Run

### Anything else

I tried it twice.
It started and ran for a while

### Version

v0.12.0
Also tested with mericodev/devlake:latest
image id: 00ed45e2097f

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by likyh** [comment]
Is your project private?

**Comment by nicoabie** [comment]
yes it is

**Comment by klesh** [comment]
@nicoabie Sorry for your inconvenience. The `repo` permission is required for private repo.
We should add it to the document, thanks for the reminder.
Related to #2721

**Comment by nicoabie** [comment]
there are all the repo permissions @klesh  
all of those are required?
![image](https://user-images.githubusercontent.com/2797992/188494505-156cf1bf-2244-497c-9ba3-cbc0a9401f72.png)

the task that pulls from github is been running for 4 hours with no issues
![image](https://user-images.githubusercontent.com/2797992/188495331-c9230bfd-7e24-41a4-99d5-80c7c24949bf.png)

**Comment by klesh** [comment]
> there are all the repo permissions @klesh all of those are required? ![image](https://user-images.githubusercontent.com/2797992/188494505-156cf1bf-2244-497c-9ba3-cbc0a9401f72.png)
> 
> the task that pulls from github is been running for 4 hours with no issues ![image](https://user-images.githubusercontent.com/2797992/188495331-c9230bfd-7e24-41a4-99d5-80c7c24949bf.png)

I have no idea which ones are required... Apache DevLake needs access to repo,issues,pr,comments,events... However, none of them are displayed in this section...

**Comment by nicoabie** [comment]
A private repo needs the repo permission to work. 
I think it would be nice to add an explanation of why devlake needs full control or remove that and only ask for repo:status and repo_deployment

**Comment by klesh** [comment]
@nicoabie I think `repo:user` and `repo:org` are also needed for data collection. Will update the document ASAP. Thanks.
