### ISSUE TITLE
[Bug][Config-UI] Pagination Buttons and Blueprint Activity CSS / Render Issue

### ISSUE THREAD

**Issue by e2corporation** [apache/incubator-devlake#2944]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

There are some rendering glitches on Config-UI that maybe related to recent refactoring changes.

- [ ] Pagination Buttons Improper Scaling

<img width="436" alt="Screen Shot 2022-09-02 at 3 41 44 PM" src="https://user-images.githubusercontent.com/1742233/188311996-d603461e-37a7-4bc0-b1d4-393f19a02b51.png">

- [ ] Multi-stage Pipeline Stage Task Lanes not Vertically Oriented
<img width="1584" alt="Screen Shot 2022-09-02 at 3 44 06 PM" src="https://user-images.githubusercontent.com/1742233/188312001-ab88678d-0a6c-4c70-a1b5-95687650bbdd.png">
<img width="1580" alt="Screen Shot 2022-09-02 at 3 44 18 PM" src="https://user-images.githubusercontent.com/1742233/188312004-7fbea841-32d8-47b2-9e52-87f652f93169.png">

### What you expected to happen

- Pagination Buttons should render normally as when feature was implemented.
- For a Multi-stage Pipeline, StageTask Lanes should be vertically oriented in columns not rows.

### How to reproduce

- Visit Blueprints Grid or Blueprint Historical Runs and notice Pagination Buttons.
- Create a Multi-stage Pipeline with more than 1 stage and notice that render is not as expected.

### Version

main

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by likyh** [comment]
https://github.com/apache/incubator-devlake/pull/2859/files#diff-caa16990188809788eedad74006be8b54a38f2dab997dede7ca3c4ec7be72177R40-R52

It is because of deleting import on `App.js`.

`pipelines.scss` is imported in `import CreatePipeline from '@/pages/pipelines/create'` and it add some global CSS. Now the importer has been deleted, so some other page cannot display correctly without these global CSS.

We should import the global CSS file in App.js or add page prefix in the page CSS file which imported by page component.

**Comment by e2corporation** [comment]
@likyh For now I will be adding the missing import will be added to the blueprint detail component. These styles will be consolidated later, there is an app-level import already it may get migrated there.

**Comment by e2corporation** [comment]
Already fixed on PR #2928, a separate Hotfix PR will be issued for this.

**Comment by e2corporation** [comment]
Resolved with PR #2928
