### ISSUE TITLE
[Bug][devlake] mysql image with M1 arm64 chip 

### ISSUE THREAD

**Issue by nicoabie** [apache/incubator-devlake#2945]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

run `docker-compose up -d mysql grafana` and got
`
ERROR: The Compose file './docker-compose.yml' is invalid because:
Unsupported config option for services.mysql: 'platform'
`

### What you expected to happen

mysql service will start

### How to reproduce

run `docker-compose up -d mysql grafana`

### Anything else

seems this was introduced here https://github.com/apache/incubator-devlake/pull/2263 which was to solve precisely that issue.
seems platform is not always supported, probably matter of docker versions

### Version

main

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by klesh** [comment]
Thanks for the contribution, @abeizn @warren830 please take a look at the PR, I think a better solution would be to change the MySQL tag to `mysql:8` without specific `minor verion`.
and @abeizn , please explain the `platform`, I remember that it has been removed and added back multiple times.
