### ISSUE TITLE
[Feature][kubernetes] Kubernetes operator

### ISSUE THREAD

**Issue by AdheipSingh** [apache/incubator-devlake#2947]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

- Can we have kubernetes operator for dev lake.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by AdheipSingh** [comment]
@thenicetgp i would like to contribute too, can we collaborate ?

**Comment by thenicetgp** [comment]
> 

Sorry didn't know you wanted to submit a PR, happy to collaborate with you！

**Comment by thenicetgp** [comment]
> > 
> 
> Sorry didn't know you wanted to submit a PR, happy to collaborate with you！

How can I help you?

**Comment by thenicetgp** [comment]
@AdheipSingh How can I help you?

**Comment by thenicetgp** [comment]
@AdheipSingh ,Hi,Have you started this?If you have any help, you can contact with me.

**Comment by shubham-cmyk** [comment]
@warren830  Is the Issue Still alive.

**Comment by mindlesscloud** [comment]
hi @thenicetgp , how are things going?

**Comment by thenicetgp** [comment]
> hi @thenicetgp , how are things going?

If this feature is not necessary, I think this issue could be closed temporarily, because I have researched it and found that it is not easy to implement for me.

**Comment by thenicetgp** [comment]
> @thenicetgp You could work with me I have experienced in creating the k8s opetrator.

Very happy to work with you.

**Comment by shubham-cmyk** [comment]
Let me confirm it with @hezyin . What do you expect the k8s operator to do.

**Comment by Startrekzky** [comment]
> Let me confirm it with @hezyin . What do you expect the k8s operator to do.

I noticed that this feature was proposed by @AdheipSingh . Can you share your use case with k8s operator with @shubham-cmyk ? 
Also, @thenicetgp are you still going to do it?

**Comment by thenicetgp** [comment]
sorry ，i have no idea about this，it is difficult for me发自我的 iPhone在 2022年11月7日，22:39，Louis.z ***@***.***> 写道：﻿

Let me confirm it with @hezyin . What do you expect the k8s operator to do.

I noticed that this feature was proposed by @AdheipSingh . Can you share your use case with k8s operator with @shubham-cmyk ?
Also, @thenicetgp are you still going to do it?

**Comment by hezyin** [comment]
Since it's not clear what's needed to be done for this issue. I'm going to close it for now. Feel free to create a new issue with a clearer proposal. Thanks to everybody involved in this thread.
