### ISSUE TITLE
[Feature][zentao] Collect&Extract&Convert stories

### ISSUE THREAD

**Issue by warren830** [apache/incubator-devlake#2964]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Collect&Extract&Convert stories

### Use case

Collect&Extract&Convert stories

### Related issues

#2961

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by yuqiangabab** [comment]
I am willing to submit a PR

**Comment by warren830** [comment]
resolved by #3181
