### ISSUE TITLE
[Bug][Build] Branch: release-v0.13 build failed for undefined: errors.xxx 

### ISSUE THREAD

**Issue by lshmouse** [apache/incubator-devlake#2972]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened
```
$ make all
...
# github.com/apache/incubator-devlake/plugins/jira/models/migrationscripts
plugins/jira/models/migrationscripts/20220716_add_init_tables.go:144:18: undefined: errors.BadInput
plugins/jira/models/migrationscripts/20220716_add_init_tables.go:144:67: undefined: errors.AsUserMessage
plugins/jira/models/migrationscripts/20220716_add_init_tables.go:164:19: undefined: errors.Default
note: module requires Go 1.19
Makefile:33: recipe for target 'build-plugin' failed
make: *** [build-plugin] Error 2
```

### What you expected to happen

The build of branch release-v0.13 will pass~

### How to reproduce

Make all in branch release-v0.13

### Version

v0.13.0

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by klesh** [comment]
@keon94 Would you like to take a look at this?

**Comment by mindlesscloud** [comment]
@lshmouse have you tried running `go mod vendor`?

**Comment by keon94** [comment]
The new error interface is not part of v0.13. This [commit](https://github.com/apache/incubator-devlake/commit/b483c20f60a867bf631a191a1789d00718484dde) to this branch added calls to the new error functions in the migration file though. They should be removed. cc @abeizn

**Comment by abeizn** [comment]
Sorry @lshmouse @keon94. my fault, It has been fixed, everything is running fine now.
