### ISSUE TITLE
[Feature][Plugin] New plugin for Gitea

### ISSUE THREAD

**Issue by tk103331** [apache/incubator-devlake#2992]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

[Gitea](https://gitea.io/) is an open-source software package for hosting software development version control using Git as well as other collaborative features like bug tracking, code review, kanban boards, tickets, and wikis.

### Use case

Gitea plugin

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by warren830** [comment]
Thanks for your contribution!

**Comment by Startrekzky** [comment]
It seems it's still under development
