### ISSUE TITLE
[Refactor][ci] golang ci not run

### ISSUE THREAD

**Issue by likyh** [apache/incubator-devlake#3013]
## What and why to refactor
![image](https://user-images.githubusercontent.com/3294100/189018753-561d7ad5-a1b9-4e37-ad46-68cfcc8e4684.png)
![image](https://user-images.githubusercontent.com/3294100/189019205-0ba41675-98e2-436c-adb2-301e23820d2b.png)

golang ci not work actually or failed.

## Describe the solution you'd like
try to fix it.

**Comment by keon94** [comment]
#3012 has fixed this.
