### ISSUE TITLE
[Bug][bitbucket] failed to decrypt when start `bitbucket` plugin

### ISSUE THREAD

**Issue by thenicetgp** [apache/incubator-devlake#3028]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

when start `bitbucket` plugin, there is an error, `failed to decrypt`
<img width="1244" alt="Screen Shot 2022-09-08 at 23 36 23" src="https://user-images.githubusercontent.com/47466847/189164758-a5e8a392-73e8-4fb2-8434-ef3891b48df7.png">

### What you expected to happen

fix this bug，correct encryption and decryption

### How to reproduce

nothing

### Anything else

nothing

### Version

main

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Startrekzky** [comment]
Hey @thenicetgp , can you link the PR to this issue?

**Comment by thenicetgp** [comment]
> Hey @thenicetgp , can you link the PR to this issue?
At present, the error mentioned in this issue is not a problem. Because bitbucket does not currently have config-ui, the stored data is not encrypted, and naturally there is no decryption process.

**Comment by thenicetgp** [comment]
@Startrekzky If anything needs to be changed, I think it's the log level. maybe `log.warning` is better than `log.error` when the data is raw data rather than encrypted data.
