### ISSUE TITLE
[Bug][GitHub Action] The workflow `check-Apache-license-header` doesn't work

### ISSUE THREAD

**Issue by mindlesscloud** [apache/incubator-devlake#3036]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

The `skywalking-eyes` could not find the config file `.licenserc.yaml `.
the following files with missing ASF header were not detected:
  - errors/errors_test.go
  - generator/template/migrationscripts/archived/connection.go-template
  - models/domainlayer/devops/cicd_pipeline.go
  - models/domainlayer/devops/cicd_pipeline_repo.go
  - models/domainlayer/devops/cicd_task.go
  - models/migrationscripts/20220711_add_subtasks_table.go
  - plugins/azure/impl/impl.go
  - plugins/azure/models/build.go
  - plugins/azure/models/build_definition.go
  - plugins/azure/models/migrationscripts/archived/build.go
  - plugins/azure/models/migrationscripts/archived/build_definition.go
  - plugins/jenkins/models/build_repo.go
  - plugins/jenkins/models/job_dag.go
  - plugins/jenkins/models/pipeline.go
  - plugins/jenkins/models/task.go
  - plugins/jira/models/migrationscripts/20220407_add_source_table.go 
  
![image](https://user-images.githubusercontent.com/8455907/189340266-a8552af6-d6d6-4e58-8c1e-62a5749c80e7.png)

### What you expected to happen

all the files with missing ASF header should be detected

### How to reproduce

please refer to https://github.com/apache/incubator-devlake/runs/7650275133?check_suite_focus=true

### Version

main

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by thenicetgp** [comment]
I will take this one

**Comment by thenicetgp** [comment]
This issue had been dealt with by PR #3040 , I am so sorry to say that I have not closed this issue in PR #3040.
