### ISSUE TITLE
[Bug][config-ui] cannot create my plugin by advance mode in config-ui

### ISSUE THREAD

**Issue by likyh** [apache/incubator-devlake#3055]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

![image](https://user-images.githubusercontent.com/3294100/189803860-88d714b7-8a65-4ad7-b429-066661c567fc.png)

### What you expected to happen

I think config-ui should allow me add any plugin 

### How to reproduce

1. create blueprint
2. click advance mode
3. try to edit plugin in json

### Version

v0.13.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by e2corporation** [comment]
@likyh For the moment, "bitbucket" is new plugin and needs to be added to the list of "Allowed Providers" In Advanced mode. This validation is there to prevent invalid plugins from being manually entered via json.

**Comment by likyh** [comment]
> @likyh For the moment, "bitbucket" is new plugin and needs to be added to the list of "Allowed Providers" In Advanced mode. This validation is there to prevent invalid plugins from being manually entered via json.

I think we should allow all name in here. Because maybe user will load his private plugin.

**Comment by e2corporation** [comment]
> > @likyh For the moment, "bitbucket" is new plugin and needs to be added to the list of "Allowed Providers" In Advanced mode. This validation is there to prevent invalid plugins from being manually entered via json.
> 
> I think we should allow all name in here. Because maybe user will load his private plugin.

I'll get bitbucket added.

**Comment by likyh** [comment]
> > > @likyh For the moment, "bitbucket" is new plugin and needs to be added to the list of "Allowed Providers" In Advanced mode. This validation is there to prevent invalid plugins from being manually entered via json.
> > 
> > 
> > I think we should allow all name in here. Because maybe user will load his private plugin.
> 
> I'll get bitbucket added.

at least, all plugins that exist should allow here. https://github.com/apache/incubator-devlake/tree/main/plugins
But I think we needn't validate the plugin name in advance mode. Users will check it themselves.

**Comment by e2corporation** [comment]
Will turn off validation for now (advanced mode)

**Comment by e2corporation** [comment]
Re-assigned to @mintsweet, Will be resolved by #3209
