### ISSUE TITLE
[Bug][Framework] error getting pipelines

### ISSUE THREAD

**Issue by warren830** [apache/incubator-devlake#3067]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

We cannot get pipelines and blueprints on config-ui
[2022-09-14 16:25:30] ERROR HTTP 500 error
        caused by: error getting pipelines
        Wraps: (2) illegal base64 data at input byte 0
        Wraps: (3) illegal base64 data at input byte 0
        Error types: (1) *hintdetail.withDetail (2) *hintdetail.withDetail (3) base64.CorruptInputError

### What you expected to happen

should get them  as usual

### How to reproduce

![image](https://user-images.githubusercontent.com/39366025/190103888-ec0986a6-5397-4acb-81dc-37c18b9751b4.png)

### Version

main

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by keon94** [comment]
Ah, actually I think it may be because of the migration error code. It's supposed to come back as 428, but it's 500. #2940 is fixing that.

**Comment by keon94** [comment]
At the meantime, as a workaround, just hit the backend with CURL to change the migration status.

**Comment by keon94** [comment]
I take it back about being related to 2940. That error message wouldn't relate to migrations.

**Comment by warren830** [comment]
Finally I found that if you encrpt data when your golang version is 1.17, then after you upgraded to golang 1.19, this will happen
