### ISSUE TITLE
[Bug][framework] status code 500 returned from the server

### ISSUE THREAD

**Issue by mindlesscloud** [apache/incubator-devlake#3072]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

status code 500 returned from the  endpoint `/pipelines`
```
$ curl -i 127.0.0.1:8080/pipelines
HTTP/1.1 500 Internal Server Error
Content-Type: application/json; charset=utf-8
Date: Wed, 14 Sep 2022 14:13:05 GMT
Content-Length: 0
```

### What you expected to happen

The status code should be 200. The response body should be a valid JSON

### How to reproduce

1. setup DevLake
2. request for pipelines curl -i 127.0.0.1:8080/pipelines

### Version

main

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by keon94** [comment]
@mindlesscloud can you try again? I think my latest merged PR will have fixed this. I just setup an env and got a 428 as expected, and after running migrations got 200 with the full JSON.
