### ISSUE TITLE
[why.md][documentation] why.md

### ISSUE THREAD

**Issue by nikitakoselev** [apache/incubator-devlake#3078]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

The project might benefit from having a "why.md" file, similar to https://github.com/quii/learn-go-with-tests/blob/main/why.md

People don't start contributing because of "how amazing this readme.md" is. 
We start contributing because the project's story relates to us.

"why.md" is the place to answer that story.

Potential content:
- Why the project was created
- What were the alternatives
- Why we didn't like the alternatives

### Use case

I want to be able to open the "why.md" of the project and read a story, which will tell me what we are trying to achieve here.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by mappjzc** [comment]
Thank you for your suggestions.
@Startrekzky can you help with this issue?

**Comment by nikitakoselev** [comment]
An example of a story: 
Helen is a DevOps who likes doing RaspberryPi coding in her free time.
Unfortunately she had less and less free time as she spent more and more time doing X manual task.
One day she heard about @DevLake. She managed to use DL's product to create solution Y, so now she can finally do more of RaspberryPi.

I understand it is an oversimplified example, but something like this could be nice.
