### ISSUE TITLE
[Bug][Github] Pr in domain does not have head_repo_id

### ISSUE THREAD

**Issue by warren830** [apache/incubator-devlake#3080]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

 Pr in domain does not have head_repo_id, base_repo_id used head_repo_id

### What you expected to happen

as gitlab

### How to reproduce

collect github

### Version

main

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by thenicetgp** [comment]
I will take this one
