### ISSUE TITLE
[Bug][github] some /pulls/comments of repo get servers error

### ISSUE THREAD

**Issue by mappjzc** [apache/incubator-devlake#3092]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened
![image](https://user-images.githubusercontent.com/2921251/190539905-b1493d84-e338-4292-a430-238d97fc87c6.png)

![image](https://user-images.githubusercontent.com/2921251/190413850-962c4964-31c1-4b76-9dc4-c136b23f4790.png)
![image](https://user-images.githubusercontent.com/2921251/190413874-fa23c5dd-4888-478d-a383-3c5542d18244.png)
![image](https://user-images.githubusercontent.com/2921251/190413924-e1f65014-8c6f-45b7-b152-08fae775f4cb.png)
![image](https://user-images.githubusercontent.com/2921251/190414060-bf9f987b-51ab-4431-b19a-447054643aee.png)

the api request /pulls/comments of apache/incubator-devlake can get the data
but the same api for trinodb/trino get the error

It can be succees when we set the since 
![image](https://user-images.githubusercontent.com/2921251/190415709-404fb821-bbf5-4ffe-92e7-821ad79df29b.png)
But if we use long time ago to set the since like then years ago, it will also sent the fail.
![image](https://user-images.githubusercontent.com/2921251/190416298-291c045f-8767-4007-a20b-0fa3425f52c3.png)

### What you expected to happen

Collect data correctly

### How to reproduce

collect  trinodb/trino suceess.

### Version

main

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by mappjzc** [comment]
@keon94 In config ui, we may need more friendly error messages.

**Comment by klesh** [comment]
Hi, @keon94 , seems like the trino project has some corrupted data in it. We don't have a plan to accommodate the problem at this point. But the message we are seeing doesn't seem friendly,  I think you might be interested in taking a look at the issue.

**Comment by keon94** [comment]
@mappjzc @klesh  That UI error message you're seeing is the format from before we merged #2940. Could you try again on newest code? It shouldn't look like that anymore. Also, you might want to open your browser inspector to see the error json that comes back because config-ui hasn't adapted the changes yet
