### ISSUE TITLE
[Bug][Config-UI] Create Blueprint Github Transformation Settings Degraded

### ISSUE THREAD

**Issue by e2corporation** [apache/incubator-devlake#3094]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

Recent changes have impacted **GitHub's Transformation** Settings. When creating a new Blueprint, GitHub's transformation settings are not written properly to the transformations map. This appears to be a result of upgrading `configuredProject` to an object, however the transformations init line was not updated to reflect this change causing github transformations to not be initialized. This will likely affect modification of Github blueprint as well.

<img width="792" alt="Screen Shot 2022-09-15 at 3 13 55 PM" src="https://user-images.githubusercontent.com/1742233/190490939-f411ef4e-13c5-4b5e-8868-ac83e88a2f34.png">

<img width="1203" alt="Screen Shot 2022-09-15 at 3 14 07 PM" src="https://user-images.githubusercontent.com/1742233/190490969-9c0c074e-3786-468a-950f-8a1d986d57b9.png">
 
<img width="1199" alt="Screen Shot 2022-09-15 at 3 14 16 PM" src="https://user-images.githubusercontent.com/1742233/190491202-dff4d37e-9885-41f9-a41f-29a4b200b09b.png">

### What you expected to happen

When creating a new Blueprint for Github connection, transformation settings should be written to the map configuration as expected.

### How to reproduce

Create a New Blueprint for Github Provider.

### Version

main and v0.13.0

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by e2corporation** [comment]
To FIX this, Data Scopes Manager needs to be patched.

<img width="865" alt="Screen Shot 2022-09-15 at 3 21 47 PM" src="https://user-images.githubusercontent.com/1742233/190491516-98e6fb21-f82b-4c2c-a5b7-4c955cfa11c2.png">

**Comment by e2corporation** [comment]
Affects `v0.13.0`, this fix would also need to be applied to that release tag. @klesh @likyh

**Comment by e2corporation** [comment]
Resolved on PR #3093
- `Fix`: restore missing github transform settings https://github.com/apache/incubator-devlake/pull/3093/commits/268f5a55b3ba083567635e52075e2b0e7882c002

**Comment by likyh** [comment]
Yeah, I can find it in the main branch. and it's OK on branch `prepare-for-v0.13.0`.
