### ISSUE TITLE
[Doc][Documentation] Use hyperlinks to link unlinked Readme.md content to Website

### ISSUE THREAD

**Issue by keon94** [apache/incubator-devlake#3095]
## Documentation Scope
Readme.md

## Describe the Change
The Readme contains duplicated content from the [website](https://github.com/apache/incubator-devlake-website) (Introduction, Datasources, Create Blueprint, etc). This makes managing it cumbersome (we have to track both places). I suggest we simply link these sections to the website as well, like we have with "Getting Started", to make the Readme content minimal. If we want the Readme to contain actual text content we should look into embedding doc pages from the website rather than duplicating content.

**Comment by Startrekzky** [comment]
How about putting a PR for it lol @keon94
