### ISSUE TITLE
[Bug][Module Name] commit_file migration script is not idempotent

### ISSUE THREAD

**Issue by klesh** [apache/incubator-devlake#3108]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

`20220913_commitfile_add_length.go` depends on  gitlab api `dal` instance.
the script would fail if gitlab plugin is missing.
however, the script won't work anymore even if I bring gitlab plugin back
![image](https://user-images.githubusercontent.com/61080/190862441-db19a6ba-6898-4f99-a9cd-cf32055e0f8f.png)

### What you expected to happen

migration script should be working when gitlab became available.

### How to reproduce

1. make sure the script is in pending status
2. fire up devlake with `PLUGIN=github make dev`
3. call /procced-db-migraion, fail
4. restart devlake with `make dev`
5. call /process-db-migration
6. see error

### Version

main

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by mappjzc** [comment]
The import of gitlab will changed to be framework after finished #3097 .
