### ISSUE TITLE
[Bug][Config-UI] database migration failed warning after successful mgration

### ISSUE THREAD

**Issue by e2corporation** [apache/incubator-devlake#3109]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

After a successful DB Migration the UI Warning does not go away.

### What you expected to happen

If Migration was successful the DB Migration Warning dialog should not remain.

### How to reproduce

Test a new DB Migration.

### Version

main

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by likyh** [comment]
it haven't been fixed.
