### ISSUE TITLE
[Bug][config-ui] migrate success but config-ui tell me it failed.

### ISSUE THREAD

**Issue by likyh** [apache/incubator-devlake#3113]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

![image](https://user-images.githubusercontent.com/3294100/190915562-ce9a3c56-8ac0-488d-824f-cbb8a1ddbf30.png)
migrate success but config-ui tell me it failed.

### What you expected to happen

tell me it success.

### How to reproduce

1. upgrade version until migration needed
2. open config-ui
3. start migration

### Version

main

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by e2corporation** [comment]
This issue also tracked in #3109
