### ISSUE TITLE
[Bug][jira] Jira account collector failed to accommodate disabled accounts

### ISSUE THREAD

**Issue by klesh** [apache/incubator-devlake#3125]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

When jira server trying to fetch disabled user information:
![image](https://user-images.githubusercontent.com/61080/190985376-2dcacd66-34f8-4260-8a7b-dfdcae77cc56.png)

### What you expected to happen

skip for 404

### How to reproduce

...

### Version

v0.12.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by mindlesscloud** [comment]
related to #2550 
resolved by #2587
