### ISSUE TITLE
[Feature][frame] transformationRules has set default value.

### ISSUE THREAD

**Issue by abeizn** [apache/incubator-devlake#3150]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar feature requirement.

### Description
when users use devlake, such as the github plugin, the user doesn't set the transformationRules, but the final data results have converted by the default transformationRules, Is this reasonable? Should the backend remove these default handling？

The main focus I think is that the values displayed in the front-end interface are for user reference or are they intended to be used as default values?

1. Front-end  transformationRules show:
![image](https://user-images.githubusercontent.com/101256042/191277354-7fe96edb-02a5-4440-ad01-4a15c522e1b1.png)

2. Backend transformationRules show:
![image](https://user-images.githubusercontent.com/101256042/191277491-45313dba-933f-4d0e-90a6-6af4b12deef7.png)

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by warren830** [comment]
No, I think backend should keep them as most of them are common case

**Comment by klesh** [comment]
However, it is quite confusing for users, they would get an unexpected result when they set the options to empty.

**Comment by klesh** [comment]
I added this to v0.15 and we should discuss this matter.
@Startrekzky @yumengwang03

**Comment by hezyin** [comment]
@warren830 I'm not against providing reasonable default values to users. But I think the key issue here is that the current frontend presentation would lead users to believe those values are just placeholders, instead of default values, thus resulting in the mismatch of the frontend and backend behavior.

If we keep the frontend unchanged, I will vote for removing those default values in the backend as well.

**Comment by Startrekzky** [comment]
I agree with @hezyin  and I created issue #3675  for providing reasonable default values. I need some time to finish the default values for each plugin though, and the default values should be shown in the Config UI form fields.
