### ISSUE TITLE
[Feature][Config UI] Redesign of the Integration/Connections page

### ISSUE THREAD

**Issue by yumengwang03** [apache/incubator-devlake#3160]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

We will redesign the current Integration/Connections page for better user experience.

<img width="1543" alt="Screen Shot 2022-09-22 at 10 43 28 AM" src="https://user-images.githubusercontent.com/9535430/191646624-2cb79b72-555c-4786-852d-111ccfec315c.png">

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by jinxinhe** [comment]
ok
