### ISSUE TITLE
[Feature][Github/Gitlab] pull_request_commits do not have merge_commit

### ISSUE THREAD

**Issue by warren830** [apache/incubator-devlake#3179]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

pull_request_commits do not have merge_commit

### Use case

I suggest to add merge_commit to pr_commits

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by klesh** [comment]
The merge commit sha is stored into `pr.merge_commit_sha`, I don't think storing it to `pr_commits` is the right call.

**Comment by warren830** [comment]
> The merge commit sha is stored into `pr.merge_commit_sha`, I don't think storing it to `pr_commits` is the right call.

Get, will colse this issue
