### ISSUE TITLE
[Bug][quality] Some subtasks do not filter input data by scope

### ISSUE THREAD

**Issue by warren830** [apache/incubator-devlake#3182]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

<img width="1063" alt="image" src="https://user-images.githubusercontent.com/39366025/192145132-2972d4fa-6750-4bca-b626-3cf71dc1a82c.png">
will collect jobs for all runs in db(maybe different repos)

After check, we found there are more subtasks do not have scope

### What you expected to happen

should collect jobs for runs within current repo

### How to reproduce

collect jobs

### Version

main

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by klesh** [comment]
no a urgent problem, move to next milestone

**Comment by likyh** [comment]
because of importing scope to Jenkins, this is out-of-date.
