### ISSUE TITLE
[Bug][Jira] the transformation rule doesn't  work 

### ISSUE THREAD

**Issue by mindlesscloud** [apache/incubator-devlake#3198]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

the type `DORA Incident` should be mapping to `Incident`, however, we got `DORA INCIDENT` in the database.
![image](https://user-images.githubusercontent.com/8455907/192256994-4a4b17c5-2035-46a1-b198-51577136f137.png)

![image](https://user-images.githubusercontent.com/8455907/192224678-993c76fb-000b-42f8-aca9-ce9c6bdf71fa.png)

### What you expected to happen

the transformation rules should be applied to the issues correctly

### How to reproduce

1. create a new type, say, `DORA Incident` in your `Jira`
2. create an issue with type `DORA Incident` in `Jira`
3. create a blueprint for plugin `Jira`
4. add a transformation rule to the blueprint which is mapping `DORA Incident` to `Incident`
5. run the blueprint
6. check the table `issues`, the type of the issue would be `DORA INCIDENT` instead of `INCIDENT`

### Version

main

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by likyh** [comment]
I'll take it. I'll add a checker in the frontend to limit choosing the same tag in different selecter.  And I will add a converter in backend to convert id to tag to avoid tag match miss.
