### ISSUE TITLE
[Feature][Config-UI] Responsive Sidebar + Dock Feature Mode

### ISSUE THREAD

**Issue by e2corporation** [apache/incubator-devlake#3201]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

This feature ticket is to continue extending on a previously submitted Community feature for **Responsive Sidebar** by adding Docked Mode support. 

- [ ] Design "Docked" Mode UX for Sidebar
- [ ] Implement Docked Sidebar Mode

### Use case

Instead of just hiding the Sidebar, a Docked mode for the sidebar would offer minimal functionality for applicable viewports. Having a docked sidebar is also keeping inline with current conventions for how modern sidebars operate.

### Design Concepts (by Henit Chobisa @henit-chobisa)
![Iteration 1](https://user-images.githubusercontent.com/1742233/192299427-e7ef949b-ec04-4715-8f6c-609befbd8dbe.png)
![Iteration 2](https://user-images.githubusercontent.com/1742233/192299434-be8df680-e01d-4d84-b52f-c2c77683ecf2.png)
![Iteration 3](https://user-images.githubusercontent.com/1742233/192299440-0d393b16-a748-485a-91c3-86abebce7110.png)
![Iteration 4](https://user-images.githubusercontent.com/1742233/192299443-c6738fb7-ccc9-4693-aadf-ac29a9ec0c6b.png)

### Related issues

#3106

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by e2corporation** [comment]
@yumengwang03 @Startrekzky Henit (@henit-chobisa) is very interested in further extending our DevLake Sidebar to be more modern by implementing a feature I had in mind called "Docked" mode.  He has created some design drafts that we'd like to get your Input and approval on.

**Comment by yumengwang03** [comment]
@henit-chobisa 
Hi Henit, thank you for the contribution! I think the second one (of your design in the screenshots) looks great! I put a few comments in the following screenshot and let me know if you have other thoughts :)

![192299434-be8df680-e01d-4d84-b52f-c2c77683ecf2](https://user-images.githubusercontent.com/9535430/194711526-9cae8494-c60e-4c47-a54f-5c09a5d0e694.png)

**Comment by henit-chobisa** [comment]
Thank you for your input @yumengwang03, I will try to do all the necessary changes within the design, confirm with you once again and then start working on the same.

**Comment by Startrekzky** [comment]
I think this issue doesn't exist anymore.
