### ISSUE TITLE
[Question][config-ui] why the rate limit of Jira defaults to 0

### ISSUE THREAD

**Issue by Startrekzky** [apache/incubator-devlake#3229]
## Question
Why the rate limit of Jira defaults to 0? I understand that there might be a default rate limit there, but it can't be 0?

## Screenshots
![image](https://user-images.githubusercontent.com/14050754/192787443-2ac1ecc5-1004-4d73-b1c6-68c0b3a553b3.png)

## Additional context
Add any other context here.

**Comment by e2corporation** [comment]
@Startrekzky This Input component is a numeric input so it must have a Number value at all times. 0 Is the default value that implies "Unrated" or "No Rate Limit", the backend to my knowledge also uses 0 to indicate that rate limit is not set. We could add a Tooltip that states "0 = unlimited" or "0 = rate limit disabled".

**Comment by Startrekzky** [comment]
> @Startrekzky This Input component is a numeric input so it must have a Number value at all times. 0 Is the default value that implies "Unrated" or "No Rate Limit", the backend to my knowledge also uses 0 to indicate that rate limit is not set. We could add a Tooltip that states "0 = unlimited" or "0 = rate limit disabled". (It defaults to 0 for all providers)

Can we make the default NULL value and remove 0 from the dropdown list? 
Also, can you add a description under this configuration? I don't know what 1,2,3... mean in the dropdown list. @e2corporation A short sentence will do at this stage.

**Comment by e2corporation** [comment]
@Startrekzky We cannot use NULL value here for this input component, What can happen is a Radio selector be added (similar to how deployment tag is enabled/disabled). If User chooses to "Enable Rate Limit", the input will be displayed as 0 for initial value. If user chooses to "Disable Rate Limit", the input will be hidden though 0 will still be in use internally to reflect that.

**Comment by e2corporation** [comment]
@Startrekzky @klesh Utilize Toggle **Switch** to enable/disable rate limit options + tooltip help & requests per hour display.

<img width="1225" alt="Screen Shot 2022-09-30 at 10 07 33 PM" src="https://user-images.githubusercontent.com/1742233/193378994-180f88f8-dd3b-4ed2-967f-098824619a9c.png">
<img width="1188" alt="Screen Shot 2022-09-30 at 10 09 43 PM" src="https://user-images.githubusercontent.com/1742233/193378997-24360828-1d38-49ba-b887-22e0b62293ea.png">

<img width="1267" alt="Screen Shot 2022-09-30 at 10 13 38 PM" src="https://user-images.githubusercontent.com/1742233/193379111-d620390c-400a-4ec3-9924-daacfd408477.png">
<img width="1268" alt="Screen Shot 2022-09-30 at 10 15 11 PM" src="https://user-images.githubusercontent.com/1742233/193379149-53e0c94f-4427-4f0c-904d-54861e41ac08.png">
