### ISSUE TITLE
[Refactor][pipeline] pipeline need a mode with higher controllability than PIPELINE_MAX_PARALLEL

### ISSUE THREAD

**Issue by likyh** [apache/incubator-devlake#3234]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

The pipeline now supports PIPELINE_MAX_PARALLEL to limit running parallel. But it's controllability is not enough. I'll use the following example to support my argument:

there are 2 blueprints:
1. blueprint 1: [ [jira], [customJiraPlugin], [starrocks] ]
2. blueprint 2: [ [github(repo1), gitextractor(repo1)], [github(repo2), gitextractor(repo2)], [starrocks] ]

Now, if I set PIPELINE_MAX_PARALLEL=1, sometimes the blueprint cannot run immediately. If I set PIPELINE_MAX_PARALLEL >= 2, the plugin startrocks may run parallel and it will cause some errors.

So I think we can add a label in plugins to solve this problem.

```go
func (plugin Refdiff) PapallelLabels() map[string]string {
        return string[]{
            "file" // it means all plugin with the label "file" cannot run parallel
        }
}
func (plugin Icla) PapallelLabels() map[string]string {
        return string[]{
            "$pluginName" // it means this plugin cannot run parallel
        }
}
func (plugin Jira) PapallelLabels() map[string]string {
        return string[]{
            "$connectionId" // it means the plugin have the pluginName and same connection id cannot run parallel
        }
}
```
The plugins with the same label are controlled by the same lock.

If we add this, we will avoid another case.

The blueprint is like the following example:
`[ [jira1, jira2], [starrocks] ]`

```go
func (plugin Jira) PapallelLabels() map[string]string {
        return string[]{
            "$connectionId" // it means the plugin have the pluginName and same connection id cannot run parallel
        }
}
```
We can add magic labels like the above one to prevent jira1 and jira2 from using the same rate limit at the same time. 

The env `PIPELINE_MAX_PARALLEL` will use keep and it means how many pipelines can run parallel.
A new env `TASK_MAX_PARALLEL` will be added for how many tasks can run parallel.

Example:
```env
PIPELINE_MAX_PARALLEL=1
TASK_MAX_PARALLEL=2
```
It means 1 pipeline can run together and at most 2 tasks at the same stage in the running pipeline can be started.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by klesh** [comment]
I think we should keep the `PIPELINE_MAX_PARALLEL` unchanged and create another SET of EnvVars to control the maximum number of parallel pipelines for a specific label.

The labels are defined in Plugin, which is `task` level, how does it work?
