### ISSUE TITLE
[Bug][gitextractor]  gitextractor received early EOF and failed

### ISSUE THREAD

**Issue by mappjzc** [apache/incubator-devlake#3242]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

![image](https://user-images.githubusercontent.com/2921251/192830154-9f586cc4-7067-42ae-9c1e-19abcf3efa09.png)

### What you expected to happen

gitextractor suceess.

### How to reproduce

gitlab collect https://gitlab.com/merico-dev/data-code/lake

### Version

main

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by klesh** [comment]
This might be caused by the NETWORK restriction, can you reproduce it in a restriction-free environment?

**Comment by mappjzc** [comment]
It is temporarily unable to reproduce continuously. It is speculated that it is caused by the instability of the network.
