### ISSUE TITLE
[Bug][config-ui] Wording should be changed when configuring deployment for a github connection

### ISSUE THREAD

**Issue by Startrekzky** [apache/incubator-devlake#3245]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

![5QzzLLSeXh](https://user-images.githubusercontent.com/14050754/192834115-48e0df92-54dc-4717-bd77-c03090cc702b.jpg)

### What you expected to happen

Update it based on the annotation.

### How to reproduce

N/A

### Version

main

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by mintsweet** [comment]
@e2corporation Of course, no problem.
