### ISSUE TITLE
[Question][Blueprints] Can't get all Jira Boards

### ISSUE THREAD

**Issue by greenpean** [apache/incubator-devlake#3254]
## Question
When setting the jira data scope，I can only get 50 jira boards to choose, actually we have more than 50 boards.How can I get the others?

**Comment by klesh** [comment]
Good question, I don't think this is possible currently. @e2corporation @Startrekzky  can you take a look at this?

**Comment by Startrekzky** [comment]
Yeah, I think it's a bug, perhaps we should add pagination here to show all boards.

**Comment by klesh** [comment]
@mintsweet
