### ISSUE TITLE
[Bug][Config-UI] The pipeline does not automatically update state.

### ISSUE THREAD

**Issue by mintsweet** [apache/incubator-devlake#3262]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

Execute it after creating blueprints, and observe that the pipeline has been in the state of **in progress,** and cannot enter the next state without refreshing the page.

![ede2ffac-dafe-4d98-8d29-7bd3b020988a](https://user-images.githubusercontent.com/37237996/193049203-4b35847f-9285-43e6-82a8-38771ce03f8b.png)

### What you expected to happen

After clicking **Run Now**, the status can be updated automatically.

### How to reproduce

1. Create a blueprint.
2. Execute this blueprint.
3. Observe the status of the pipeline.

### Version

main

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by e2corporation** [comment]
@mintsweet We have Polling enabled at 5second intervals, how is your page not refreshed?

**Comment by mintsweet** [comment]
@e2corporation It seems that the interface of tasks has been pending, it will fail after some time, and then no interface will be requested.

![screenshot-20220929-220118](https://user-images.githubusercontent.com/37237996/193052698-9a825dc7-4c49-4435-908f-c92f2916dc5a.png)

**Comment by e2corporation** [comment]
Refreshing/Activity logic has been operational for quite some time, user should not have to manually reload if they don't want to they can just leave this page open. If anything we could lower the `pollTimer` from 5000ms to 3000ms instead.

**Comment by e2corporation** [comment]
Yes the refresh is only enabled for a RUNNING pipeline, once a pipeline has failed or completed polling is turned off.

**Comment by mintsweet** [comment]
So do you think this is a problem? It looks like the first task has failed and the second task has been progressing.

**Comment by e2corporation** [comment]
The 504's you are seeing is related to another issue of Tasks not being fetched, See this ticket: https://github.com/apache/incubator-devlake/issues/3239 which is impacting status behavior and maybe causing the problems you are experiencing.

**Comment by e2corporation** [comment]
If there is indeed another problem of pipeline state not being updated, identify the exact breakage and outline a fix as needed.

**Comment by mintsweet** [comment]
Re-tested, it is indeed caused by a problem with #3239.
