### ISSUE TITLE
[Bug][config-ui] can not save successfully by editing jira transformation rules.

### ISSUE THREAD

**Issue by abeizn** [apache/incubator-devlake#3273]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

invalid plan (400)", "invalid boardId:0 (400)

![image](https://user-images.githubusercontent.com/101256042/193089890-90fe18d1-a83b-4bd5-b928-8f5864c35958.png)

### What you expected to happen

can work

### How to reproduce

firstly, create jira blueprint.
then update jira blueprint setting.
you can see the error.

### Version

main

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by likyh** [comment]
https://github.com/apache/incubator-devlake/issues/3257
