### ISSUE TITLE
[Bug][Jira] test connection api return success with a pair of any username and a valid token

### ISSUE THREAD

**Issue by narrowizard** [apache/incubator-devlake#3277]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

I am using test connection api to check jira integration info before synchronizing.It always return success if the token is valid, even if the username is not exists.  
But the jira tasks will fail with the wrong username.

### What you expected to happen

Test connection api should keep consistent behaviour with sync tasks.  
I mean, if test connection api is passed, sync tasks should not failed for authentication reason.

### How to reproduce

Call test connection api with right endpoint, password but wrong username. 

### Anything else

This issue occurs both in jira server and jira cloud version.

### Version

v0.12.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by mappjzc** [comment]
related #2400

**Comment by mappjzc** [comment]
this issue not only happend on v0.12.0
this happend on all branch if it merged #2748

**Comment by narrowizard** [comment]
please cherry-pick the fix to v0.12, thanks @mindlesscloud
