### ISSUE TITLE
[Question][Integration] Will MS365 and TestLink / Kiwi be supported?

### ISSUE THREAD

**Issue by zhicwu** [apache/incubator-devlake#3279]
## Question
Will MS365 and [TestLink](https://testlink.org) / [Kiwi](https://kiwitcms.org) be supported? The idea is to measure communication, case design and case execution etc.

## Screenshots

* MS365 to measure communications(and maybe documents as needed)
  - Mails
  - IM Chats
  - Meetings
  - (Audio/Video) Calls
* TestLink / Kiwi to measure case design and execution
   - Test Case (total, auto%, manual%)
   - Test Case Revision (total, new%, updated%)
   - Test Results (success rate, auto%, manual%, plans, builds, cases, revisions)

## Additional context
N/A

**Comment by mappjzc** [comment]
thanks for your mind.
@Startrekzky can you help to have a look?

**Comment by Startrekzky** [comment]
Thanks for your proposal @zhicwu. Those 3 tools won't be supported in a short time as they're not in this year's [roadmap](https://devlake.apache.org/docs/Overview/Roadmap/). 
However, we might change the plan if there're more users who want these features and comment under this ticket...
