### ISSUE TITLE
[Feature][framework] Prevent concurrent pipelines for a specific blueprint

### ISSUE THREAD

**Issue by klesh** [apache/incubator-devlake#3286]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

It is pointless to run multiple pipeline for the same blueprint at the same time, and it is likely to cause RateLimit error or Race Condition

### Use case

1. When user click "Run now" on config-ui, api would return error
2. We can also prevent 3rd app trigger blueprint execution via api

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by likyh** [comment]
let's fix by this way https://github.com/apache/incubator-devlake/issues/3234 ?

**Comment by klesh** [comment]
It is a different problem than #3234.
For any blueprint, no matter if it has a particular `label`, why would anyone want to run a blueprint multiple times in parallel?
#3234 is mainly to prevent DIFFERENT blueprints being run in parallel, this is for A blueprint itself alone.

The same underlying mechanism could resolve them, but I think a better way is to deal with them separately, because preventing pipelines for a specific blueprint would always stand, but not so much for the label-control-mechanism.

**Comment by narrowizard** [comment]
Another use case, the triggered cron job for blueprints that is of running status should be prevented as well.  
You can ignore it If this case is covered by the api trigger.
