### ISSUE TITLE
[Bug][config-ui] board transfomation match wrong when edit jira blueprint

### ISSUE THREAD

**Issue by likyh** [apache/incubator-devlake#3294]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

When I delete a board or adjust the order of the boards, the transformation of the second page will not match. For example, the original requirement of board1 is tagA, and the requirement of board2 is tagB. After 1 is deleted, board2 becomes tagA

### What you expected to happen

After 1 is deleted, board2 keep tagB

### How to reproduce

![image](https://user-images.githubusercontent.com/3294100/193201534-1631b9a2-add6-4a2b-b70b-ea7de46482b2.png)
![image](https://user-images.githubusercontent.com/3294100/193201503-dd4f866b-9b94-4045-bb6c-4635752cc232.png)
![image](https://user-images.githubusercontent.com/3294100/193201636-c4516c3b-07bb-4a10-a919-87d505898412.png)
----
![image](https://user-images.githubusercontent.com/3294100/193201757-e32f0b2f-02d5-46bd-b973-1f0d9a9c9668.png)
![image](https://user-images.githubusercontent.com/3294100/193202353-977724fe-5537-4364-a40f-bd8c041945d1.png)

### Version

main

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by e2corporation** [comment]
@likyh This was already resolved with #3275

**Comment by likyh** [comment]
> @likyh This was already resolved with #3275

No, I test on latest main. Please do a test yourself.
