### ISSUE TITLE
[Bug][config-ui] add board but type mapping is wrong when edit jira blueprint

### ISSUE THREAD

**Issue by likyh** [apache/incubator-devlake#3295]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

![image](https://user-images.githubusercontent.com/3294100/193202724-ec0df1da-7a42-4621-92cc-bd0ae4b05b00.png)

### What you expected to happen

new boards have correct type mapping. It should equal user select.

### How to reproduce

1. find an existing blueprint with jira.
2. add a board in jira
3. select an issue type for bugs
4. save
5. look at the body of request

### Version

main

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by mintsweet** [comment]
I'll fix it.

**Comment by e2corporation** [comment]
@likyh I think you just refactored JIRA mappings and ID keys with https://github.com/apache/incubator-devlake/pull/3202

**Comment by likyh** [comment]
> @likyh I think you just refactored JIRA mappings and ID keys with #3202

Do you mean this issue was caused by #3202?

**Comment by e2corporation** [comment]
> > @likyh I think you just refactored JIRA mappings and ID keys with #3202
> 
> Do you mean this issue was caused by #3202?

JIRA Mappings have been working well for a while, in Both Multi-board and single-board scenarios.

**Comment by e2corporation** [comment]
@mintsweet Please be careful with this logic, you are moving a bit too fast and have refactored and introduced breaking issues on this already Merged PR https://github.com/apache/incubator-devlake/pull/3191.

Please be mindful of your usage of Effects and necessary dependencies. That PR 3191 ignored exhaustive dep warnings, now when the dependency is added to DataTransformations it causes a circular loop as outlined in that screenshot.
