### ISSUE TITLE
[Bug][config-ui] Update wording on the connection list page

### ISSUE THREAD

**Issue by Startrekzky** [apache/incubator-devlake#3299]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

 ![image](https://user-images.githubusercontent.com/14050754/193240655-fdb42f14-0830-41f3-9ad2-48f8719b32a7.png)

### What you expected to happen

For all data sources' connection list page, update wordings from 'integration' to 'connection' to make it consistent.

### How to reproduce

N/A

### Version

main

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by likyh** [comment]
I'll take it.
