### ISSUE TITLE
[Refactor][Backend] Re-evaluate Golang "panic" logic

### ISSUE THREAD

**Issue by keon94** [apache/incubator-devlake#3305]
## What and why to refactor
We have many spots in our Golang code where we simply panic with an error for no obvious reason. Panicking in general should be reserved only for when error handling is not an option.

## Describe the solution you'd like
Go over these [search results](https://github.com/apache/incubator-devlake/search?l=Go&q=panic%28) and identify the places where a panic could be replaced with a simple error return.

## Related issues
n/a

## Additional context
n/a

**Comment by keon94** [comment]
Probably a good first issue.

**Comment by shubham-cmyk** [comment]
I would like to try it.

**Comment by keon94** [comment]
@hezyin Could you assign this to @shubham-cmyk ?

**Comment by Palanikannan1437** [comment]
Hey @keon94, I'd love to work on this issue after I'm done with the Gitpod PR, could you please assign this to me?

**Comment by keon94** [comment]
@Palanikannan1437 Sure! Happy coding.

**Comment by keon94** [comment]
bump

**Comment by Palanikannan1437** [comment]
bump

**Comment by shubham-cmyk** [comment]
bump

**Comment by Palanikannan1437** [comment]
Hey @keon94, could you please give a brief overview of how you'd like the errors to be handled according to different scenarios?

I understand "it depends", but what would you prefer over the panic, thank you

**Comment by shubham-cmyk** [comment]
You must remove the panic and make it simple return.
@Palanikannan1437

**Comment by Dev79844** [comment]
Hey @shubham-cmyk! Can I work on this issue?

**Comment by Palanikannan1437** [comment]
> You must remove the panic and make it simple return.

@keon94 is that all or there's more to it?

**Comment by keon94** [comment]
Yes, remove panics and return errors.Error where possible

**Comment by Palanikannan1437** [comment]
Sure, thanks @keon94 and @shubham-cmyk
