### ISSUE TITLE
[Bug][generator] Extractor Not able to detect the Collector Name. 

### ISSUE THREAD

**Issue by shubham-cmyk** [apache/incubator-devlake#3307]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

When you try to generate an extractor. the CLI is not able to find the source file of the Collector. 

![Screenshot from 2022-10-05 05-37-14](https://user-images.githubusercontent.com/69793468/193952420-81d9f341-6c40-49a0-ace2-fddee6f7435f.png)

### What you expected to happen

Extractor should able to detect the src file of the Collector. 

### How to reproduce

`go run generator/main.go create-plugin randomPlugin`
`go run generator/main.go create-collector randomPlugin random`
`go run generator/main.go create-extractor shubham randomPlugin randomExtractor`

### Version

main

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by mindlesscloud** [comment]
Thanks for your feedback, we will try to reproduce and fix it

**Comment by shubham-cmyk** [comment]
@mindlesscloud I have followed the docs for creating the extractor, the `go run generator/main.go create-extractor` is not able to find the src file of the collector.

**Comment by keon94** [comment]
It's because of this line:
https://github.com/apache/incubator-devlake/blob/6893518460793f3e7baa3750367ba09793e267f7/generator/cmd/create_collector.go#L64

Either we need a nil check on the err there or inside the Wrap method.

**Comment by shubham-cmyk** [comment]
Reference #3311
