### ISSUE TITLE
[Bug][API] GET /blueprints 500 Internal Server Error

### ISSUE THREAD

**Issue by hezyin** [apache/incubator-devlake#3314]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

After I successfully created a blueprint with advanced mode, Config UI started to get 500 internal server errors from the backend.

I tried deleting that newly created blueprint, and everything went back to normal.

<img width="2299" alt="Screen Shot 2022-10-07 at 5 46 20 PM" src="https://user-images.githubusercontent.com/2908155/194679125-dfa4b2dc-8786-47af-9151-2cd65918d5a5.png">

The error message from the backend:

<img width="669" alt="Screen Shot 2022-10-07 at 5 45 51 PM" src="https://user-images.githubusercontent.com/2908155/194679132-10dbdd93-047f-43e6-8dde-895faad088c1.png">

### What you expected to happen

GET /blueprints returns successfully.

### How to reproduce

**Version: v0.14.0-alpha1**
Installation method: docker-compose

I created the blueprint with the following curl command:

```
{
    "enabled": true,
    "mode": "ADVANCED",
    "name": "My Bitbucket Blueprint",
    "cronConfig": "",
    "isManual": true,
    "plan": 
        [
            [
                {
                    "plugin": "bitbucket",
                    "options": {
                        "repo": "incubator-devlake",
                        "owner": "yinhezheng",
                        "connectionId": 2
                    }
                }
            ]
        ]
}
```

### Version

main

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by likyh** [comment]
"unexpected end of JSON input" means curl body is not a json. Maybe "]" or other char miss in POST body. So it is not a bug.

**Comment by likyh** [comment]
You need use this json to create blueprint.
```json
{
  "enabled": true,
  "mode": "ADVANCED",
  "name": "My Bitbucket Blueprint",
  "cronConfig": "",
  "isManual": true,
  "plan": [
    [
      {
        "plugin": "bitbucket",
        "options": {
          "repo": "incubator-devlake",
          "owner": "yinhezheng",
          "connectionId": 2
        }
      }
    ]
  ],
  "settings": {
    "version": "1.0.0",
    "connections": []
  }
}
```

```  "settings": {
    "version": "1.0.0",
    "connections": []
  }``` added.

**Comment by likyh** [comment]
settings decode separately now. I'll add a check when added to tell users this column is needed. Now you can add it to use it.

**Comment by hezyin** [comment]
@likyh Thanks. I've verified that adding the `settings` section solved the issue. Closing the issue.
