### ISSUE TITLE
[Doc][README] Typo in supported data sources

### ISSUE THREAD

**Issue by Startrekzky** [apache/incubator-devlake#3318]
## Documentation Scope
main README

## Screenshots
![image](https://user-images.githubusercontent.com/14050754/194707698-c3fe1ade-d303-4203-8f20-88b9015a33e0.png)

**Comment by ankan792** [comment]
Hey @Startrekzky, I am a new contributor and I tried to fix the typo in #3326 . Please review and make sure if it is okay or not. Thanks!

**Comment by klesh** [comment]
Hi, @ankan792 , your PR was valid, it should be merged. I think @Startrekzky didn't see your PR at all, sorry for that.

**Comment by ankan792** [comment]
@klesh That's odd but its alright not a big deal !

**Comment by Startrekzky** [comment]
> @klesh That's odd but its alright not a big deal ! I appreciate your comment.

Sorry @ankan792 , I fixed the typo when adding a `collection mode` column to this table. I really appreciate for your contribution, and these're other GFIs you can work on if you're interested. https://github.com/apache/incubator-devlake-website/labels/hacktoberfest

**Comment by ankan792** [comment]
@Startrekzky It's alright not a big deal! Thanks for commenting :D. I will try to contribute in future issues
