### ISSUE TITLE
[Feature][Config UI] Config UI needs to support BitBucket

### ISSUE THREAD

**Issue by yumengwang03** [apache/incubator-devlake#3319]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Like other data sources that Config UI already supports, we need to design the Connetion page and the Blueprint transformation page for BitBucket.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by jinxinhe** [comment]
![Uploading image.png…]()
[https://www.figma.com/file/Eux4Dhorxp7M0TwzOnL6Yh/Config-UI-for-V1.0?node-id=1999%3A10071](url)

**Comment by mintsweet** [comment]
I'll take it.

**Comment by likyh** [comment]
https://www.figma.com/file/Eux4Dhorxp7M0TwzOnL6Yh/New-Config-UI-(wym)?node-id=3828%3A25209&t=ZJNsNfLDEZ60IBLa-1 
![image](https://user-images.githubusercontent.com/3294100/218025438-eb8fcf44-1ac0-455e-aff8-209d445a8ddf.png)

<img width="999" alt="img_v2_1918a56d-b280-471d-92c1-26d4945d2e3g" src="https://user-images.githubusercontent.com/3294100/218025271-7b58b122-160c-4d65-96ea-0c98c2d80b4d.png">
