### ISSUE TITLE
[Feature][Config UI] Config UI needs to support Azure DevOps

### ISSUE THREAD

**Issue by yumengwang03** [apache/incubator-devlake#3321]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Like other data sources that Config UI already supports, we need to design the Connetion page and the Blueprint transformation page for Azure DevOps.

### Related issues

Related to #2604 

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by jinxinhe** [comment]
![image](https://user-images.githubusercontent.com/114125035/195109536-e4ef47ce-3f39-428a-af39-31334fcb2e1a.png)
[https://www.figma.com/file/Eux4Dhorxp7M0TwzOnL6Yh/Config-UI-for-V1.0?node-id=1999%3A10071](url)

**Comment by Startrekzky** [comment]
@yumengwang03 @jinxinhe This design needs to expand to Azure DevOps, not limited to Azure CI (Azure Pipelines), which means we have to add configuration to the current prototype.

**Comment by keon94** [comment]
Is there a PR for this?

**Comment by keon94** [comment]
We're also going to need some sample JSON schemas/payloads for all the azure endpoints that you are hitting so we can make sure we're returning the correct data.

**Comment by keon94** [comment]
PR: https://github.com/apache/incubator-devlake/pull/4504
