### ISSUE TITLE
[Refactor][config-ui] delete unused params in `usePipelineValidation.jsx`

### ISSUE THREAD

**Issue by likyh** [apache/incubator-devlake#3330]
## What and why to refactor
https://github.com/apache/incubator-devlake/blob/7b0199a6d8557d4f18b73200d619a96d10df0163/config-ui/src/hooks/usePipelineValidation.jsx#L22-L45

<img width="610" alt="image" src="https://user-images.githubusercontent.com/3294100/194715800-b5b793cf-1267-4ea2-b480-4df88638efa3.png">

We rarely use params here and I don't think we will use `projectId/boardId/...` in validation in the future.

## Describe the solution you'd like
Delete them.

Deleting unnecessary params will help us read code without worrying about where the vars are used.

**Comment by e2corporation** [comment]
This is fine to cleanup, A majority of the validation rules was removed from the Pipeline Validator and moved to Blueprint Validator as a consequence of v0.12.0 changes.

**Comment by yumengwang03** [comment]
@likyh

**Comment by mintsweet** [comment]
**usePipelineValidation** has been deleted, so close this issue.
