### ISSUE TITLE
[Doc][Plugin] Add plugins' collection mode info to readmes

### ISSUE THREAD

**Issue by Startrekzky** [apache/incubator-devlake#3338]
## Documentation Scope
- Main README
- Website: https://devlake.apache.org/docs/SupportedDataSources

## Describe the Change
Add data collection mode to the plugin table, as many users asked if a plugin supported incremental sync or not.
Please fill in the the `collection mode` in this table, some examples:
- Full Refresh
- Incremental Sync
- Full Refresh, Incremental Sync (for `issues`, `builds`, etc.)

| Data Source                           | Domain(s)                                                  |Supported Versions                    | Triggered Plugins                      | Collection Mode       |
|---------------------------------------|------------------------------------------------------------|--------------------------------------|--------------------------------------- | --------------------- |
| GitHub (including GitHub Action)      | Source Code Management, Code Review, Issue Tracking, CI/CD | Cloud                                |`github`, `gitextractor`, `refdiff`     | @mappjzc           |
| GitLab (including GitLabCI)           | Source Code Management, Code Review, Issue Tracking, CI/CD | Cloud, Community Edition 13.x+       |`gitlab`, `gitextractor`, `refdiff`     | @mappjzc  |
| Gitee                                 | Source Code Management, Code Review, Issue Tracking        | Cloud                                |`gitee`, `gitextractor`, `refdiff`      | @thenicetgp   |
| BitBucket                             | Source Code Management, Code Review                        | Cloud                                |`bitbucket`, `gitextractor`, `refdiff`  | @mindlesscloud           |
| Jira                                  | Issue Tracking                                             | Cloud, Server 8.x+, Data Center 8.x+ |`jira`                                  | @mindlesscloud       |
| TAPD                                  | Issue Tracking                                             | Cloud                                |`tapd`                                  | @warren830           |
| Jenkins                               | CI/CD                                                      | 2.263.x+                             |`jenkins`                               | @likyh           |
| Feishu                                | Calendar                                                   | Cloud                                |`feishu`                                | @likyh           |
| AE                                    | Source Code Management                                     |                                      | `ae`                                   | @klesh          |

## Screenshots
The doc will look like this:
![image](https://user-images.githubusercontent.com/14050754/194734560-b86dabd3-6b0f-46e8-9c3c-6c9193270f27.png)

**Comment by klesh** [comment]
AE is full refresh

**Comment by likyh** [comment]
Jenkins and Feishu is full refresh

**Comment by mappjzc** [comment]
github  Full Refresh, Incremental Sync (for issues,pr)
gitlab Full Refresh, Incremental Sync (for issues)

**Comment by warren830** [comment]
TAPD: Incremental Sync (for stories, bugs, tasks), others are full refresh
