### ISSUE TITLE
[Feature][Dashboard] Robot removal

### ISSUE THREAD

**Issue by asterix314** [apache/incubator-devlake#3339]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Pull requests issued by automated robots do not indicate real development activity and distort the metrics. Therefore they should be removed. [CNCF/devstats](https://github.com/cncf/devstats) uses pattern-matching to detect bots. We can shamelessly snatch their pattern-list (see [here](https://github.com/cncf/devstats/blob/master/util_sql/exclude_bots.sql)) and use it in something like:

```sql
select *
from pull_requests
where select *
from pull_requests
where --  not the full list but covers 99+% of the cases
    author_name not rlike  '^robot-|-robot$|\\[bot\\]|-bot$|-ci$|-testing$'
```

If performance becomes an issue, then a table of robot IDs can be prepared beforehand and then joined with the target table.

### Use case

How many PRs are attributable to bots? Apply the filter above to get some results.

- For [clickhouse](https://github.com/ClickHouse/ClickHouse), bot activity is rampant:

|created_year|PRs|bots contribution|
|------------|---|----|
|2020|7161|36.7%|
|2021|11015|53.3%|
|2022|4019|19.4%|

- Overall ([oss.demo](https://grafana-oss.demo.devlake.io), 346 repos), not so much, but still significant, and rising:

|created_year|PRs   |bots contribution  |
|------------|------|------|
2020  |218558|4.0%|
2021  |215863|6.2%|
2022  |116016|7.7%|

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Startrekzky** [comment]
Cool. I think we can start by adding this info to the docs of the metrics affected by bot users, e.g. [PR coding time](https://devlake.apache.org/docs/Metrics/CodingTime), to teach users to filter out bot users by customizing SQL in the built-in dashboards.

**Comment by asterix314** [comment]
Great!

**Comment by Startrekzky** [comment]
I've added the logic to some PR metric docs. We can add it to the pre-built dashboards if more users want it in the future
