### ISSUE TITLE
[Feature][Jira] Return more info when proxy api failed

### ISSUE THREAD

**Issue by narrowizard** [apache/incubator-devlake#3340]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

I'm using jira proxy api to get jira board list. It works well if everything is configed correctly.  
But it will return an 500 internal server error when my authentication info is outdated.  
![lVSKeiSRPz](https://user-images.githubusercontent.com/11383928/194740414-e2753383-4855-49ef-9765-27c90aac7307.jpg)

I have tested the jira api, it will return 401 if something wrong with auth info.  
![2b2Wb5V2Iz](https://user-images.githubusercontent.com/11383928/194740420-4de6c784-958c-4521-80f4-0b3a03abe060.jpg)

It will be better if the proxy api return original jira response info(at least the response status code) so that I can expose an exact error info for users.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by mindlesscloud** [comment]
fixed by #3342
