### ISSUE TITLE
[Refactor][config-ui] add a specific manager to read and set transformations If there are specific encode way.

### ISSUE THREAD

**Issue by likyh** [apache/incubator-devlake#3355]
## What and why to refactor
https://github.com/apache/incubator-devlake/blob/24804f67423a726d955003589cc93bb773db16b2/config-ui/src/hooks/useDataScopesManager.jsx#L60-L75

https://github.com/apache/incubator-devlake/blob/24804f67423a726d955003589cc93bb773db16b2/config-ui/src/hooks/useDataScopesManager.jsx#L262

https://github.com/apache/incubator-devlake/blob/24804f67423a726d955003589cc93bb773db16b2/config-ui/src/hooks/useDataScopesManager.jsx#L691-L694

https://github.com/apache/incubator-devlake/blob/24804f67423a726d955003589cc93bb773db16b2/config-ui/src/hooks/useDataScopesManager.jsx#L734-L736

## Describe the solution you'd like

I think we need to add a specific manager to read and set transformations to avoid causing problems.

**Comment by e2corporation** [comment]
@likyh I think this is a duplicate and already resolved with #3371?
