### ISSUE TITLE
[Feature][TAPD] Provide an API to get workspaces by company id

### ISSUE THREAD

**Issue by Startrekzky** [apache/incubator-devlake#3367]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

![image](https://user-images.githubusercontent.com/14050754/195104827-37d5196c-f5c7-42bc-ba01-e7404dbb88d5.png)

### Use case

Users can select TAPD workspaces rather than 'type in'.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by warren830** [comment]
This process should be finished by frontend sending a request to http://localhost:4000/api/plugins/tapd/connections/1/proxy/rest/workspaces/projects?company_id=xxxxx

**Comment by Startrekzky** [comment]
Any updates? Will this request be sent by FE or BE?

**Comment by warren830** [comment]
> Any updates? Will this request be sent by FE or BE?

workspaces id can be get by api.proxy
