### ISSUE TITLE
[Feature][Config-UI] Create Provider Configurations TAPD, BitBucket, Azure, GitEE

### ISSUE THREAD

**Issue by e2corporation** [apache/incubator-devlake#3373]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

This PR is to setup the **Configuration** Entries for the upcoming new **Providers** to be registered on Config-UI

- [ ] TAPD (Already setup configuration-wise)
- [ ] BitBucket
- [ ] Azure
- [ ] Gitee

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by mintsweet** [comment]
Hi @e2corporation, the name **GitEE** should be **Gitee**.
