### ISSUE TITLE
[Feature][Webhook] Simplify incoming `deployment` webhook to reduce configuration

### ISSUE THREAD

**Issue by Startrekzky** [apache/incubator-devlake#3377]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

1. Instead of providing 2 deployment webhooks, it's better just to provide ONE deployment webhook
![20221011-230825](https://user-images.githubusercontent.com/14050754/195245911-b1b84a07-4ef4-4191-9520-92e2d9a1e94a.jpeg)

2. Also, the payload of the existing webhooks contains too many fields. Fields such as `result`, `status`, `type` can be reduced.
![image](https://user-images.githubusercontent.com/14050754/195246272-48a40a62-3777-4615-a52f-7489a709bb17.png)

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by likyh** [comment]
RepoUrl *required

CommitSha *required

Name is optional, and it must be unique once filled in. The name saved to the database is' RepoId/CommitSha/Name ', so is the corresponding pipeline name created

StartedDate is optional. If it is not filled in, it is now

FinishedDate is optional, and the end time must be filled in together with StartedDate. If it is not filled, it is empty

Environment is optional, one of=Production Standing Testing, default is Production
