### ISSUE TITLE
[Feature][Coding] add Merge Request subtasks

### ISSUE THREAD

**Issue by warren830** [apache/incubator-devlake#3381]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

we need to add Merge Request subtasks for `coding`

### Use case

please refer to coding depot collector&extractor
also please refer to github pr collector&extractor

the api we need to use: https://coding.net/help/openapi#78b8a78701eb60f1cbba7c2f3d1cc2c3

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Startrekzky** [comment]
@warren830 Does this issue still exist?
