### ISSUE TITLE
[Refactor][CI] Add Yamllint tool for lint yaml files

### ISSUE THREAD

**Issue by matrixji** [apache/incubator-devlake#3388]
## What and why to refactor
CI and quality enhancement

## Describe the solution you'd like
Add yamllint to check all yaml files if valid.

## Related issues
Bug like #3387 should be found at early stage with Yaml lint tools. 

## Additional context
N/A

**Comment by Startrekzky** [comment]
Any progress? @mindlesscloud

**Comment by mindlesscloud** [comment]
> Any progress? @mindlesscloud

Not so well, so I reassigned it to @matrixji
