### ISSUE TITLE
[Bug][starrocks] failed when run starrocks tasks: cached plan must not change result type

### ISSUE THREAD

**Issue by narrowizard** [apache/incubator-devlake#3407]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

It report an error of `cached plan must not change result type (SQLSTATE 0A000)` when I using starrocks plugin to sync data from pg to starrocks.  

### What you expected to happen

Should not cause an error.

### How to reproduce

1. Setup devlake with a **new** postgres database and a starrocks service.  
2. Create pipeline with following plans:  
```json
{
    "name": "sync to starrocks",
    "plan": [
        [
            {
                "plugin": "starrocks",
                "options": {
                    "host": "starrocks-fe",
                    "port": 9030,
                    "user": "root",
                    "be_port": 8040,
                    "be_host": "starrocks-be",
                    "database": "lake",
                    "password": "password",
                    "batch_size": 10000,
                    "tables": [
                        "^[a-zA-Z].+$"
                    ]
                }
            }
        ]
    ]
}
```

### Anything else

[log](https://github.com/apache/incubator-devlake/files/9769536/devlake.4.log)

### Version

- Build based on release-v0.14 branch

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by abeizn** [comment]
starrocks the way of alter table need to update at func loadData().
such as the way of jira plugin:
https://github.com/apache/incubator-devlake/blob/main/plugins/jira/models/migrationscripts/20220716_add_init_tables.go
starrocks the way of alter table need to update at func loadData().
such as the way of jira plugin:
https://github.com/apache/incubator-devlake/blob/main/plugins/jira/models/migrationscripts/20220716_add_init_tables.go
