### ISSUE TITLE
[Bug][Config-ui] Update the description for GitHub, GitLab, and Jenkins' CI/CD setting

### ISSUE THREAD

**Issue by Startrekzky** [apache/incubator-devlake#3412]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

Update the description for GitHub and GitLab, and Jenkin's CI/CD `production` setting

### What you expected to happen

![image](https://user-images.githubusercontent.com/14050754/195491233-875f054f-cbea-4b5a-8a63-b49853c50cbd.png)

![image](https://user-images.githubusercontent.com/14050754/195490803-44e6070b-eb43-41ec-8eef-68652499d5dd.png)

![image](https://user-images.githubusercontent.com/14050754/195490586-01aa4917-126b-46bd-a630-78717d022a6d.png)

### How to reproduce

-

### Version

v0.14.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by mintsweet** [comment]
I'll take it.
