### ISSUE TITLE
[Feature][Config UI] Show task names of `dora` plugin

### ISSUE THREAD

**Issue by Startrekzky** [apache/incubator-devlake#3438]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

When executing dora tasks, the task names are not shown on the blueprint status page.

![image](https://user-images.githubusercontent.com/14050754/195745453-a08e84bf-2a66-44fe-b6f0-c68324232930.png)

### Use case

Users want to know which tasks are running, so task names should be added.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by mintsweet** [comment]
I'll take it.

**Comment by mintsweet** [comment]
Hi @Startrekzky, Do you think this will meet your needs? 
The backend partner needs to return more content if it can't be achieved.

![screenshot-20221014-154932](https://user-images.githubusercontent.com/37237996/195792517-ad8ad1c0-67a3-4825-815f-a30c1c9fc590.png)
