### ISSUE TITLE
Add a new plugin for Coder

### ISSUE THREAD

**Issue by ankitmalakar7** [apache/incubator-devlake#3447]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Add a new Coder data source plugin for Coder so that DevLake can collect dev data from it.

### Use case

This plugin performs 3 major tasks:

- Collect data from Coder RESTful API. The API responses shall be stored in the raw data layer.
- 1st ETL: transform the raw data and load it into the tool layer.
- 2nd ETL: transform the tool layer data and load it into the domain layer.

### Related issues

No

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Startrekzky** [comment]
Thanks for the feature request.

**Comment by Startrekzky** [comment]
Collecting votes
