### ISSUE TITLE
[Bug][TAPD] Should standardize sprints' status field when convert to domain layer

### ISSUE THREAD

**Issue by narrowizard** [apache/incubator-devlake#3453]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

In jira, we got sprints' status of three possibility: CLOSED, ACTIVE, FUTURE.  
But in tapd, we got OPEN status.  
I think we should standardize these statuses so that we could reuse metrics query between different data sources.

### What you expected to happen

Maybe convert tapd's status to CLOSED, ACTIVE, FUTURE, or convert both jira and tapd status other predefined standard statuses.

### How to reproduce

No steps.

### Version

v0.14.1

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Startrekzky** [comment]
How to convert TAPD iteration statuses to standard statuses: 
- open -> ACTIVE
- done -> CLOSED
