### ISSUE TITLE
[Feature][ClickUp] Add plugin for ClickUp as an issue tracking tool

### ISSUE THREAD

**Issue by hezyin** [apache/incubator-devlake#3458]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar feature requirement.

## Background

[ClickUp](clickup.com) is a [fast-growing](https://techcrunch.com/2021/10/27/clickup-raises-400m-at-a-4b-valuation-to-expand-its-all-in-one-workplace-productivity-platform-to-europe/) project management tool and we have community members requesting this plugin. 

Now that we have the singer-spec framework ready, we could test out the framework by implementing a ClickUp plugin using the new framework.

The singer tap for ClickUp is here (its quality needs verification): https://github.com/AutoIDM/tap-clickup

## Goal 

The goal is to implement a ClickUp plugin that:

1. Covers major entities in the issue-tracking domain and their associations. Major entities include issues, boards, sprints, issue labels, issue changelogs, and issue comments.
2. Support ClickUp as a data source for calculating DORA metrics. Similar to other issue-tracking system, ClickUp can provide incident data for calculating the Change Failure Rate (CFR) and Mean Time to Recover (MTTR) metrics within DORA.
3. Provide a ClickUp dashboard for users to verify and explore data.

## Known Challenges

1. ClickUp's hierarchy
ClickUp has a relatively complicated hierarchy for managing tasks, please see the screenshot below:

<img width="803" alt="Screen Shot 2022-10-17 at 10 40 48 PM" src="https://user-images.githubusercontent.com/2908155/196345109-11e4f9ca-0cc1-4ab4-99d4-61bd21689b2d.png">

* Space: a team or a department
* List: a container for tasks. Users can use lists to organize work for a specific timeframe such as [sprints](https://help.clickup.com/hc/en-us/articles/6311468482455-Getting-Started-Guide/how-to-setup-an-agile-scrum-workflow-in-clickup), by geographic location, or as phases of complex projects.
* Task: maps to issues in DevLake's domain layer. A task always has a parent list.
* Folder: optional, it's a group of lists. 

It's obvious that tasks should map to issues in the domain layer, but how to map other entities require some research.

For more details, please see [ClickUp's hierarchy doc](https://help.clickup.com/hc/en-us/articles/6311525171223-Hierarchy-structure-in-ClickUp).

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by keon94** [comment]
@hezyin I can take this one.

**Comment by dantleech** [comment]
I've started implementing a clickup integration for our company, probably we can contribute it back or share when/if I finish, but just wanted to see if anybdoy has worked on this before I go to far in?

**Comment by klesh** [comment]
> I've started implementing a clickup integration for our company, probably we can contribute it back or share when/if I finish, but just wanted to see if anybdoy has worked on this before I go to far in?

Nice, I don't remember anyone else working on it, not that I know of.
It would be great if you are willing to contribute the plugin to the community.

**Comment by klesh** [comment]
@keon94  FYI, I added @dantleech as assignee. @dantleech feel free to ask questions if you need help on github or slack.

**Comment by dantleech** [comment]
thanks! I can't see any links to the Slack channel, where do I find it?

**Comment by klesh** [comment]
Hi, @dantleech, any update?

**Comment by klesh** [comment]
> yeah, we've got working (slightly opinionated and poorly tested) integration, planning to move it to Github and could share it from there

Good to know, take your time, FYI, the next merging window would be the 21st of this month. Feel free to ping me when ready.

**Comment by dantleech** [comment]
I've opened a PR: https://github.com/apache/incubator-devlake/pull/6153 note however that it is based on 0.17.

**Comment by klesh** [comment]
@dantleech I see, I think it is fine to develop and test it based on v0.17. and we can rebase it to the main before merging. I can help with the rebasing.
