### ISSUE TITLE
[Feature][dora] Support DORA metrics stage 2

### ISSUE THREAD

**Issue by klesh** [apache/incubator-devlake#3468]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar feature requirement.

#### Documentation

1. apache/incubator-devlake-website#298 @klesh 
2. Update [DORA manuals](https://devlake.apache.org/docs/UserManuals/DORA#how-to-implement-dora-metrics-with-apache-devlake ) based on the `Project` design in DORA stage II @Startrekzky 
3. Update [Webhook](https://devlake.apache.org/docs/Plugins/webhook#add-a-new-webhook) manuals for reference @Startrekzky 
4. Update [Config UI tutorial](https://devlake.apache.org/docs/UserManuals/ConfigUI/Tutorial) to be based on new user flow, eg. project, transformation rules, etc. @yumengwang03 
5. Add interface doc to [development doc](https://devlake.apache.org/docs/DeveloperManuals/PluginImplementation) 
6. Update `options` for all plugins, eg. scope_id, transformation_rule_id, etc.
7. Update Jenkins doc. Use Jenkins Job as the data scope.
8. Update the old interface in the [migration scripts](https://devlake.apache.org/docs/DeveloperManuals/DBMigration)
9. Update the [domain layer schema](https://devlake.apache.org/docs/DataModels/DevLakeDomainLayerSchema)
10. Add a doc `Blueprint Plan Generation Version v2.0.0`
11.  Update the calculation logic in [Change Lead Time](https://devlake.apache.org/docs/Metrics/LeadTimeForChanges)https://github.com/apache/incubator-devlake-website/pull/310
12. Update the [refdiff](https://devlake.apache.org/docs/Plugins/refdiff) to support `project`

#### Implementation

1. `project` support on the framework level: project is a set of `scopes` @mappjzc 
   1. Define an interface named `PluginMetric` with methods:
      a. `RequiredDataEntities` returns a list of required data entities and expected features. i.e. DORA should return sth like `[{ "model": "cicd_tasks", "requiredFields": {"column": "type", "execptedValue": "Deployment"}}, ...]` (no concreate usage at this point, can be used in config-ui to describe dependency in the future.)
      b. `IsProjectMetric` returns if the metric depends on Project for calculation. Currently, only `dora` would return true.
      c. `RunAfter` indicates which plugins must be executed before executing this one. (no concreate usage at this point)
      c. `Settings` returns an empty pointer of the plugin setting struct. (no concrete usage at this point)
   3. All metric plugins should implement the `PluginMetric` including `dora` `refdiff`
   4. Implement the long overdue PluginsList #1411, so config-ui can filter out what PluginMetric we currently support. `[{"plugin": "jira", "metric": {"requiredDataEntities": ..., "isProjectMetric": true}}]` 
   5. Create model `projects(name, created_at, updated_at)` table including `models` and related migration script
   6. Create model `project_metrics(project_name, plugin_name, plugin_options)` table to indicate what metric plugins have been enabled by the project
   7. Add `GET/POST/UPDATE` APIs for projects management, the request/response body should include records from `project_metrics` table.
   8. Add `project_name` to `blueprints` table, and update API/Service accordingly. Should we allow `project_name` to be updated? #3754
   9. https://github.com/apache/incubator-devlake-website/pull/308
   10. #3679 
   11. #3833 
2. Storing `scope` and `transformationRule` into database @mindlesscloud 
   1. Define an interface named `PluginSource` with methods:
      a. `Connection` returns an empty connection pointer. i.e. `&JiraConnection{}`
      b. `Scope` returns an empty scope pointer. i.e. `&JiraBoard{}`, the `Scope` model should contain a field `name` for ConfigUI to display for users to distinguish different scopes.
      c. `TransformationRule` returns an empty transformation rules pointer `JiraTransformationRules`
   2. All data-source plugins should implement this interface including `jira`, `github`, `jenkins` etc...
      a. Defining `Scope(id varchar255 uniq, name varchar255 uniq, connection_id idx, transformation_rule_id, created_at, updated_at)` and its migration script. note that the `id` and `name` should derive from the data source, i.e., for `Gitlab` it should be the `project_id` and `owner/repo`, for data source without `id`, use the same value as the `name` is acceptable, say if `jenkins.job` may not has `id` at all.
      b. Defining `TransformationRule(id, name, ...data_source_dependant_fields)` and its migration script
      c. Update all existing subtasks to accept `scope_id` and `transformation_rule_id` and process accordingly while keeping the existing behavior, that is, we add `scope_id` and `transformationRuleId` to existing `options` and treat the `scope_id` and `transformationRuleId` as fallback options: to load the default options from db first, and then override with `options`
      d. Add API endpoints for `Scope` and `TransformationRule` just like `Connection`(Don't forget to write swagger doc first)
      f. Add API endpoint `connections/:id/remote/scopes` to list out all available remote scopes for all plugins
      g. `incoming webhook` implement `PluginSource` and `PluginBlueprintV200` to return `[]*ProjectMapping`, and update the API endpoints to create `domain layer scope` based on `webhook connection` instead of the **actual scope** posted by the client.
   3. the PluginList API should contain the information of the above structs as well `[{"plugin": "jira", "dataSource": {"connectionMeta": {"id": {"type":"uint64"}, "name": {"type": "string", "length": ...}}}}]`
   4. [ConfigUI] would adopt these 2 APIs accordingly
   5. [ConfigUI] with `scope` and `transformationRule` being standardize, we should be able to address #3528 in a unified way.
3. Blueprint Plan Generation Version v2.0.0 @klesh 
   1. https://github.com/apache/incubator-devlake-website/pull/300
   2. #3613:
      a. Defining `Scope` interface with methods `ScopeId()/ScopeName()/TableName()`, and update `repos` `boards` `cicd_scopes` to implement the interface.
      b. PluginBlueprintV200 takes only `ScopeIds`(`connectionId`/`transformationRuleId` can be inferred) as input, and returns `PipelinePlan` and `[]Scope` to indicate the scopes belonging to the project.
   3. #3677 GeneratePlanJsonV200 does whatever has to be done as V100, then handles the []Scope returned by all Data Source plugins, it would check if blueprint has project_name and updating the project_mapping table accordingly by delete+insert technique. And then, it would start calling Metric Plugins like dora and merge all the pipeline plans into the final result.
   4. Update all data source plugins to support PluginBlueprintV200，each one of them should return `[]Scope` based on the given information, i.e. `[&Repo{Id: "github:GithubRepo:1:123"}, &Board{Id: "github:GithubRepo:1:123"}]` 
   5. Update `services/blueprint.go:250` add `case` for `GeneratePlanJsonV100`
6. Update `dora` plugin to utilize the `project_name` information @warren830 
   1. The `dora` is to implement `PluginBlueprintV200` interface and returns a `refdiff` task to produce the `refs_commits_diffs` for deployments under the same `project_name` https://github.com/apache/incubator-devlake/pull/3791
   3. The `dora` would accept `project_name` from `options` in its `PrepareTaskData` callback. And store the information in `taskData` https://github.com/apache/incubator-devlake/pull/3742
   4. Update `calculateChangeLeadTime` to take `project_name` into consideration, namely, reduce the data scope by `project_mapping` table. On top of that, the algorithm must be updated to connect the PR to deployment only when the PR.commit_sha appears in the `refs_commits_diffs` since the previous deployment. #3516 . The result metric should be stored in another independent table i.e. `project_pr_metrics(project_name, pr_id, deployment_id, deploy_time, ...)` https://github.com/apache/incubator-devlake/pull/3742
   7. Rename `ConnectIssueDeploy` to `connectIncidentToDeployment`, and update the algo to take `project_name` into consideration. The `incident` would connect to `deployment` with in the same `project`,  The result metric should be stored in another independent table i.e. `project_issue_metrics` https://github.com/apache/incubator-devlake/pull/3768
12. Jenkins uses `job` as its scope @likyh @warren830 
    1. [Jenkins collects only `builds` belonging to specified `job`](https://github.com/apache/incubator-devlake/issues/3296) pr #3700 
    2. [Jenkins stores the `job` as the scope and converts them to `cicd_scopes`](https://github.com/apache/incubator-devlake/issues/3639) pr: https://github.com/apache/incubator-devlake/pull/3707
13. [Enhance `refdiff` to support `project`: refdiff should take the `project_name` from taskOptions, and offer the ability to calculate `refs_commits_diffs` between 2 consecutive deployments under the same scope, namely `cicd_scopes` ](https://github.com/apache/incubator-devlake/issues/3685)@abeizn 
14. Remove hardcoded dora tasks
15. Update SQL query from grafana dashboards, including **DORA Dashboard** and **Jenkins** and other related dashboards
16. Group grafana dashboards into different folders

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Startrekzky** [comment]
What will be the relation between the `data scope` and `connection` entity?

**Comment by klesh** [comment]
> What will be the relation between the `data scope` and `connection` entity?

Good question, their relationship is N vs 1

**Comment by klesh** [comment]
https://www.figma.com/file/Eux4Dhorxp7M0TwzOnL6Yh/Config-UI-for-V1.0?node-id=2002%3A12997

**Comment by yumengwang03** [comment]
Figma link: https://www.figma.com/file/Eux4Dhorxp7M0TwzOnL6Yh/Config-UI-for-V1.0?node-id=1996%3A11140
This probably needs to be broken down to several front-end issues.

**Comment by Startrekzky** [comment]
@leglars asked if DevLake provided the following APIs:

- CURD of `connection`, `data scope`, `transformation`
- list data scope by connection
- get transformation by data scope
- get blueprint by data scope (low priority)
- get data scope by project
- get connection by data scope

**Comment by pratiyush05** [comment]
Hi @klesh , we have a use case .In our organisation , each team has single JIRA board where they keep their issues and INCIDENTS .So one JIRA board has INCIDENTS of multiple projects at the same time . Looks it has been addressed as scalability problem - [here](https://devlake.apache.org/docs/v0.19/GettingStarted/HowToOrganizeDevlakeProjects#:~:text=A%20board%20contains%20incidents%20of%20multiple%20teams%20or%20projects).

So when we are adding same JIRA board so different Devlake projects , INCIDENTS are getting wrongly associated to multiple project's deployments .So can you please guide us through this problem . 
I know that "Devlake project" is the linking point between an INCIDENT and Deployment .Any extra field that we can add in our JIRA INCIDENTS which can be used to link to correct project ?

**Comment by klesh** [comment]
@pratiyush05 In your case, I think the best way is to create multiple boards for reporting incidents to different projects. isn't it?

**Comment by pratiyush05** [comment]
Appreciate your speedy reply .
So each lake project requires independent board for reporting their respective project's incidents .

I have another query related to incidents only -
in [here](https://devlake.apache.org/assets/images/cfr-definition-94d92cc75f857f183443ad5390d31d65.png) , lets say INCIDENT 3 needs to be linked with Deployment 2 . INCIDENT is more like a microservice in a project which started malfunctioning due to a deployment . Is this understanding of INCIDENT applicable with Devlake ?
If yes , then is it possible to relate INCIDENTS with previous deloyments in Devlake ?

**Comment by klesh** [comment]
@pratiyush05 If I understand [it](https://devlake.apache.org/assets/images/cfr-definition-94d92cc75f857f183443ad5390d31d65.png) correctly, INCIDENT 2 and 3 should be linked to Deployment 3, while Deployment 2 is a success without any incidents linked to it.

**Comment by pratiyush05** [comment]
> @pratiyush05 In your case, I think the best way is to create multiple boards for reporting incidents to different projects. isn't it?

Is there any other way possible to create incidents properly ? As creating a separate JIRA boards for each project can affect  our teams coordination .

**Comment by klesh** [comment]
@pratiyush05 You may create incidents/issues by the webhook plugin as well https://devlake.apache.org/docs/Plugins/webhook#incident--issue
