### ISSUE TITLE
[Feature][wording] entity to domain on blueprint

### ISSUE THREAD

**Issue by likyh** [apache/incubator-devlake#3476]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

![image](https://user-images.githubusercontent.com/3294100/196442086-437a380f-f23f-4fc6-a9ea-5a5245ca284f.png)
It looks like not 「entity」 because it means a set of models. Maybe we can change it to 「domain」 or some other word.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by e2corporation** [comment]
**Domain Entities** would be a more appropriate label, I will be refactoring related state var to `domainEntities` on UI on ticket #3478.

**Comment by yumengwang03** [comment]
> **Domain Entities** would be a more appropriate label, I will be refactoring related state var to `domainEntities` on UI on ticket #3478.

Actually it was intentionally called "data entities" because we didn't add extra burdens for users to understand what domains are. But this section, the data entities selector, is planned to be removed in the future, but it's of low priority right now.
