### ISSUE TITLE
[Refactor][Config-UI] DSM Hook Change `Entities` to `DataEntities`

### ISSUE THREAD

**Issue by e2corporation** [apache/incubator-devlake#3478]
## Config-UI / **Data Scopes Manager** (`DSM Hook`)
Cleanup DSM Hook

- [x] Refactor `entities` to `dataEntities` to prevent collision with future refactor for `boards` and `projects` merging to `entities`
- [x] Restore Logging Output for Selected `Boards` and `Projects` for Debugging
- [ ] Remove duplicate check & change handlers in DataTransformations

<img width="656" alt="Screen Shot 2022-10-18 at 4 14 25 PM" src="https://user-images.githubusercontent.com/1742233/196534610-e27a2111-4be2-4c33-bf43-b8dd9ec4536b.png">

<img width="835" alt="Screen Shot 2022-10-18 at 4 47 24 PM" src="https://user-images.githubusercontent.com/1742233/196541600-d12bcc69-9e9d-4eb5-9832-a5d86f673379.png">

**Comment by likyh** [comment]
I have do a part of this.

**Comment by Startrekzky** [comment]
Will be refactored in v0.15
