### ISSUE TITLE
[Feature]Need config for gitExtractor when creating blueprints

### ISSUE THREAD

**Issue by FrankCheungCN** [apache/incubator-devlake#3484]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

I wish I could edit git extractor's config in normal mode.

### Use case

![image](https://user-images.githubusercontent.com/22819074/196624959-e5e6d59e-4b9a-4088-9361-15613a332cd4.png)

I need to edit git extractor's config, something like adding a proxy. I had to change to advanced mode to edit with the raw JSON, which is not so convenient. 

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Startrekzky** [comment]
Hi @FrankCheungCN GitExtractor will be auto-triggered after creating a blueprint to collect GitLab data. You can add the proxy when creating the GitLab connection.
![image](https://user-images.githubusercontent.com/14050754/197665741-67ebc71d-042d-4d68-a71e-098705efdaa2.png)

**Comment by FrankCheungCN** [comment]
> Hi @FrankCheungCN GitExtractor will be auto-triggered after creating a blueprint to collect GitLab data. You can add the proxy when creating the GitLab connection. ![image](https://user-images.githubusercontent.com/14050754/197665741-67ebc71d-042d-4d68-a71e-098705efdaa2.png)

I have tried it. I think this proxy url won't be added to GitExtractor.

**Comment by warren830** [comment]
hmm, seems like this has been fixed in v0.14
![image](https://user-images.githubusercontent.com/39366025/197767406-12d25168-103d-4c5d-8378-b118679c2d9c.png)

**Comment by FrankCheungCN** [comment]
> hmm, seems like this has been fixed in v0.14 ![image](https://user-images.githubusercontent.com/39366025/197767406-12d25168-103d-4c5d-8378-b118679c2d9c.png)

Cool!
