### ISSUE TITLE
[Feature][Plugin] add a new data sync mode to allow setup a "start_from" or "since" time for data scope to reduce volume of data-syncing

### ISSUE THREAD

**Issue by leglars** [apache/incubator-devlake#3492]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

when setup a data scope for collecting data, I want to a "sync start from" or "sync since" field, so I don't spend time to collect legacy data which I don't care. 

### Use case

I have a 5-year project which uses Jira to manage requirements and incidents from very beginning. So my project has more than 30k issues, and my scrum board has more than 100 sprints. I don't care issues completed or created more than 2 years ago. To sync all 30k issues is time consuming and unnecessary.
However, existing jira plugin just provide two sync mode:
full sync mode, which support incremental syncing after first data sync;
date range sync mode, which support syncing data from an exact date, but this mode doesn't support incremental syncing in subsequent syncing process.

Both mode can't support my idea sufficiently.
I want to only collect my recent 1-2 years issues in the beginning and keep incremental syncing subsequently.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by klesh** [comment]
This ought to be cherry-picked to v0.14.

**Comment by likyh** [comment]
I'll look at this these days.

**Comment by Startrekzky** [comment]
This issue will be implemented in #3492 (for Jira) and #3688 (for GitHub)
