### ISSUE TITLE
[Question][Config-UI] JIRA Provider missing CI/CD Data Entity

### ISSUE THREAD

**Issue by e2corporation** [apache/incubator-devlake#3495]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

It appears **JIRA** no longer has the CI/CD Data Entity scoped to it's Available Entity List, possibly due to recent refactor changes. JIRA needs CI/CD in order to access **Deployment Options**?

<img width="902" alt="Screen Shot 2022-10-19 at 2 09 14 PM" src="https://user-images.githubusercontent.com/1742233/196771279-125d33b7-7368-4619-8665-453ca4ec6fec.png">

### What you expected to happen

Users should be able to select CI/CD Data Entity for JIRA Provider.

### How to reproduce

1. Create a New Blueprint for JIRA
2. Observe that "CI/CD" is Not available for Data Entities

### Version

main

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by e2corporation** [comment]
@likyh @mintsweet Can one of you take this one?

**Comment by e2corporation** [comment]
@likyh @mintsweet Or is JIRA exempt from Deployment Options?

**Comment by likyh** [comment]
![image](https://user-images.githubusercontent.com/3294100/196835031-e050932c-bed9-486d-9e89-6c737e0f78f8.png)
Jira has no CI/CD. Because we can not get build info or deploy info from Jira. It never did.
