### ISSUE TITLE
[Feature][PagerDuty] Support PagerDuty as an incident management system

### ISSUE THREAD

**Issue by hezyin** [apache/incubator-devlake#3498]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

[PagerDuty](https://www.pagerduty.com/) is one of the most popular issue management tools in the industry. DevLake would help more teams implement the DORA framework if it has a plugin that can pull incident data from PagerDuty.

![image](https://user-images.githubusercontent.com/2908155/196837137-227da1ca-5c78-4d68-8af2-d8ec7a2c8a3f.png)

## Incident

The most important entity from PagerDuty is incident. A PagerDuty incident can be triggered automatically via integration with monitoring service and API, or manually via web app and mobile app. See below for an incomprehensive list of incident attributes we're interested in:

1. Status: can be one of Triggered, Acknowledged, Resolved
2. Impacted Service
3. Assignee
4. Title
5. Urgency
6. Priority: for the difference between urgency and priority, see here: https://community.pagerduty.com/forum/t/whats-the-difference-between-urgency-severity-and-priority/153
7. Duration
8. Description
9. When an incident is triggered, when it's acknowledged, and when it's resolved

See PagerDuty's doc on incidents for details: https://support.pagerduty.com/docs/incidents

See below for some screenshots of creating a new incident on web app:

<img width="599" alt="Screen Shot 2022-10-19 at 5 40 21 PM" src="https://user-images.githubusercontent.com/2908155/196838052-0c8ed240-846d-4e95-999b-8077afd0576c.png">
<img width="2489" alt="Screen Shot 2022-10-19 at 5 40 47 PM" src="https://user-images.githubusercontent.com/2908155/196838066-52639d45-e3d5-4a37-925e-998f9068fe07.png">

### DORA Support

IIRC, DevLake's DORA plugin uses issues of incident type to calculate DORA metrics, so let's see if we can map PagerDuty 's incident to the issue entity in DevLake's domain layer.

## Alert

Alert is another important entity in PagerDuty's data. It's not strictly required for calculating DORA, but would be a nice addition to our database.

### Use case

A PagerDuty plugin is most useful for DevLake's support for DORA metrics.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by keon94** [comment]
I'll take this one.

**Comment by Startrekzky** [comment]
@hezyin @klesh @keon94 Will PagerDuty's incidents be transformed into an issue in type "INCIDENT" in the domain layer table.issues?

**Comment by hezyin** [comment]
@Startrekzky I think that's the current plan. What do you think?

**Comment by keon94** [comment]
@hezyin @Startrekzky Going by [this doc](https://devlake.apache.org/docs/Plugins/webhook#incident--issue), are the required fields in that table the minimum we'll need to create a domain Issue object from PagerDuty's data?

**Comment by Startrekzky** [comment]
> @hezyin @Startrekzky Going by [this doc](https://devlake.apache.org/docs/Plugins/webhook#incident--issue), are the required fields in that table the minimum we'll need to create a domain Issue object from PagerDuty's data?

Yes, but we want to collect as much information as possible. Below is the mapping logic between the schema of DevLake issues and PagerDuty incidents in Singer.

| [DevLake issues](https://devlake.apache.org/docs/DataModels/DevLakeDomainLayerSchema#issues) | [PagerDuty incidents](https://github.com/goodeggs/tap-pagerduty/blob/master/tap_pagerduty/schemas/incidents.json) | 
| ------------------------- | ----------------------------- |
| board_key | service_id, make sure a board is created in table.boards. A board is a collection of issues, if there's no `project` or `board` entity in PagerDuty, then service might be a good choice to be abstracted to a `DevLake board` here. |
| url               | html_url |
| issue_key   | incident_number |
| title  | title |
| description  | summary |
| type  | a constant 'INCIDENT' |
| status  | PagerDuty incident URL |
| original_status  | status. Must be one of `TODO` `DONE` `IN_PROGRESS` |
| created_date  | created_at |
| resolution_date  | I didn't find a field called `duration` in Singer's schema. Maybe we can transform it from field `last_status_change_at` of an incident whose status is DONE |
| priority | priority.properties.id or another key in priority.properties  |
| lead_time_minutes  | an incident's resolution_date - created_ at, convert to `minutes` |
| assignee_id  | assignments.items.assignee.id |
| assignee_name  | I didn't see an assignment name here, but please convert it if it exists |


Please note that this mapping logic is based on the names of PagerDuty's incident schema. You can modify it if the real data doesn't look like this.

Also, please note that entity `boards` and `accounts` also need to be implemented if `service name` and `incident assignee` are wanted here.

**Comment by keon94** [comment]
There's a bug in the incidents tap stream which prevents incremental data collection. I've filed an issue to their repo [here](https://github.com/singer-io/tap-pagerduty/issues/7). For now, this plugin will be implemented using the non-incremental collection scheme. cc @hezyin

**Comment by hezyin** [comment]
@keon94 Thanks for the update. Please proceed with the non-incremental version for now.

**Comment by keon94** [comment]
@hezyin @Startrekzky 
Here's an example of the issues tables after mapping the Pagerduty fields

![image](https://user-images.githubusercontent.com/25063936/199322513-3198f371-2092-4ada-b029-b8a0f2aae432.png)

**Comment by keon94** [comment]
@hezyin @Startrekzky @klesh Pagerduty allows multiple assignees for a given issue (incident). How do you guys suggest we approach this? Our domain model only supports having a single one.

**Comment by keon94** [comment]
Domain issues table + Grafana:
![image](https://user-images.githubusercontent.com/25063936/199675172-60971e28-4fd5-4595-8e6b-6e6e9a0f58ff.png)
![image](https://user-images.githubusercontent.com/25063936/199674402-680b7459-8eb7-4830-8f5d-69a4bbc02416.png)

**Comment by keon94** [comment]
PR: #3641

**Comment by Startrekzky** [comment]
> @hezyin @Startrekzky @klesh Pagerduty allows multiple assignees for a given issue (incident). How do you guys suggest we approach this? Our domain model only supports having a single one.
> 
> I was thinking, as a workaround, to use the assigned_at field, and pick the latest assignee.

I agree with using the latest one. GitHub issue has the same problem actually.

**Comment by Startrekzky** [comment]
@keon94 @hezyin Do you think we should reopen this or create a new issue for PagerDuty?
