### ISSUE TITLE
[Bug][migration] Pipeline ids changed after upgrade to v0.14

### ISSUE THREAD

**Issue by klesh** [apache/incubator-devlake#3508]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

When users upgrade existing Apache DevLake deploy to v0.14
The value of `pipeline.id` and `blueprint.id` got reordered.

Beside, the pipeline stop working and report the following error:
![image](https://user-images.githubusercontent.com/61080/196888078-caf5d166-837a-4b75-a224-554b0ed2c19e.png)

And the old table got deleted:
![image](https://user-images.githubusercontent.com/61080/196891475-1788d0c8-bc91-4465-832d-a705f70cf8aa.png)
![image](https://user-images.githubusercontent.com/61080/196898576-71672e7f-e8cd-4395-90e1-7181c8135ea9.png)

### What you expected to happen

`pipeline.id` and `blueprint.id` should stay the same after upgrade.

### How to reproduce

deploy v0.12/v0.13 , launch some pipelines, upgrade to v0.14

### Version

v0.14.1

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by klesh** [comment]
The devlake was deployed to a k8s cluster.
So, I'm guessing when upgrading the k8s cluster, there were multiple `devlake` containers running simultaneously due to k8s would bring up new containers before killing the old ones, which caused the migration to be `partially completed`

**Comment by warren830** [comment]
fixed by #3727
