### ISSUE TITLE
[Feature][github_graphql] Display repo name in blueprint running status

### ISSUE THREAD

**Issue by asterix314** [apache/incubator-devlake#3528]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

The running status of the github_graphql plugin only displays the task ID:
 
![image](https://user-images.githubusercontent.com/10952409/197105436-b671e9ec-8154-41dc-8fa3-ce7f82128bd9.png)

However, repo and owner names are also needed, as in the github plugin:

![image](https://user-images.githubusercontent.com/10952409/197106557-aa43cb4e-1c8c-4e67-8f0d-daa10516618a.png)

Please consider adding the repo / owner names to github_graphql to make the status page more informative and consistent.

version: v0.14

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by klesh** [comment]
Good advise. Thanks.
