### ISSUE TITLE
[Bug][backend-framework] lake crushed when pipeline.beginAt is nil

### ISSUE THREAD

**Issue by likyh** [apache/incubator-devlake#3531]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

![Isdxz6O9WV](https://user-images.githubusercontent.com/3294100/197122822-db7f717e-a6f4-400a-a9dd-f8d140db6a34.jpg)
![PUtBV7uqfG](https://user-images.githubusercontent.com/3294100/197122836-5e7eae1c-c822-4baa-81f1-83ff00984e46.jpg)

### What you expected to happen

don't crushed and log/save original error

### How to reproduce
@narrowizard 
![img_v2_e9cd6024-47f0-449c-8475-771ae615b33g](https://user-images.githubusercontent.com/3294100/197123020-3db45449-3646-4af3-8e3e-4afec7a023bf.jpg)
1. run EE's pipeline

### Version

main

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by narrowizard** [comment]
relates to #3537
