### ISSUE TITLE
[Feature][Deployment] Helm chart support postgres as an option

### ISSUE THREAD

**Issue by matrixji** [apache/incubator-devlake#3544]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

From my understanding devlake already supports both MySQL and PostgreSQL

When the helm chart was first initialed, the support for deployment with PostgreSQL was not supported by the chart's implementation.

Let's ship it to support Postgres as an optional database backend.

Planned to introduce below parameter in helm chart:

- `option.database` for identity which database to use, by default will use `mysql`, valid options: `mysql`, `postgresql`
- `postgresql.*` options for configure Postgres, similar as `mysql.*` for MySQL

### Use case

For guys who want's to deploy devlake with PostgreSQL or use external PostgreSQL database

### Related issues

N/A

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Startrekzky** [comment]
Happy coding.

**Comment by warren830** [comment]
fixed by https://github.com/apache/incubator-devlake-helm-chart/pull/45
