### ISSUE TITLE
[Bug][config-ui] Wrong value is shown while changing "Sync Frequency"

### ISSUE THREAD

**Issue by likyh** [apache/incubator-devlake#3546]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

![image](https://user-images.githubusercontent.com/3294100/197399359-09c1b20c-67c5-4c8c-a7c1-82c85492f164.png)

### What you expected to happen

choose manual as default when a blueprint is manual sync frequency.

### How to reproduce

1. create a blueprint and set sync frequency to manual
2. try to edit this blueprint and you'll find it

### Version

main

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by klesh** [comment]
@Startrekzky Please review this

**Comment by likyh** [comment]
> @Startrekzky Please review this

That is a bug and not a feature. This blueprint is manual when it created.

**Comment by klesh** [comment]
I see
