### ISSUE TITLE
[Bug][gitee] gitee connection migrations bug

### ISSUE THREAD

**Issue by likyh** [apache/incubator-devlake#3549]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

![67f4f0cd-9f52-4c79-ad24-aef19fcc39bd](https://user-images.githubusercontent.com/3294100/197401403-babb90a7-376d-4311-a267-7adcd7834bf4.jpeg)

I haven't set git env vars. But now the migration script will create an empty connection for me.

### What you expected to happen

Create new connection only when env exists and not empty 

### How to reproduce

1. start devlake
2. look at config-ui

### Version

main

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by warren830** [comment]
@mappjzc <img width="667" alt="image" src="https://user-images.githubusercontent.com/39366025/197452690-b61fcaf9-cf31-4579-8521-6c9e38fd7541.png">
