### ISSUE TITLE
[Question][CI] Yaml lint action not working

### ISSUE THREAD

**Issue by matrixji** [apache/incubator-devlake#3560]
## Question
Yaml lint action not started due to the action name 'karancode/yamllint-github-action@master' not matching the Action Permissions settings, so any maintainer could help to check it?

Ref: https://github.com/apache/incubator-devlake/actions/runs/3310620618 

## Screenshots
![image](https://user-images.githubusercontent.com/183388/197466375-78ba8b1f-6dfd-494d-8c41-06700adc9c1f.png)

## Additional context
N/A

**Comment by mindlesscloud** [comment]
As the error message suggested, could we replace the action with one verified in the GitHub Marketplace?

**Comment by matrixji** [comment]
It seems https://github.com/marketplace/actions/super-linter is an alternative, I'll try it.
