### ISSUE TITLE
[Bug][config-ui] `Next Run Date` degrade to UTC timezone

### ISSUE THREAD

**Issue by klesh** [apache/incubator-devlake#3587]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

Previously, we display the `Next Run Date` based on **BROWSER TIMEZONE**, so users may know exactly what to expect.
![image](https://user-images.githubusercontent.com/61080/197991468-7c3be641-db27-41a5-8ebe-6202523cd27e.png)

The latest version shows it in **UTC+0 TIMEZONE** without description, this is quite confusing for most if not all users:
![image](https://user-images.githubusercontent.com/61080/197992651-88202b41-433a-40d4-b6d3-add632454301.png)

Related to #3567 

### What you expected to happen

Being able to see "Next Run Date" based on **BROWSER TIMEZONE**

### How to reproduce

1. setup latest version
2. go to config-ui create a blueprint
3. see error

### Version

main

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by e2corporation** [comment]
Local Time is currently displayed on the **Blueprints List** and **Blueprint Status** sections.
<img width="1113" alt="Screen Shot 2022-10-26 at 12 09 03 PM" src="https://user-images.githubusercontent.com/1742233/198078737-82e8d170-14f5-4f71-86cc-969319741ac5.png">
<img width="1192" alt="Screen Shot 2022-10-26 at 12 09 19 PM" src="https://user-images.githubusercontent.com/1742233/198078764-1a4bbd7c-43d9-496b-83b1-7ee162674700.png">

**Comment by yumengwang03** [comment]
In both creating and editing blueprints, there should be an indication to tell users that we are using UTC time. @hehehe will work on the prototype first.
<img width="634" alt="Screen Shot 2022-10-27 at 10 26 31 AM" src="https://user-images.githubusercontent.com/9535430/198177476-98bbcb19-de9a-49a1-8bd3-8400fe3d1934.png">
<img width="824" alt="Screen Shot 2022-10-27 at 10 28 46 AM" src="https://user-images.githubusercontent.com/9535430/198177480-6f2944c6-c38d-48b4-b383-9e1f40c644ac.png">

**Comment by yumengwang03** [comment]
@e2corporation @klesh 
<img width="856" alt="Screen Shot 2022-10-27 at 4 29 51 PM" src="https://user-images.githubusercontent.com/9535430/198232942-0b9ccc59-057f-46d6-a466-7a6bffe2c684.png">

The prototype is here (from the linked screen to the right to see how it should be shown in different states): https://www.figma.com/file/Eux4Dhorxp7M0TwzOnL6Yh/Config-UI-for-V1.0?node-id=291%3A7914

**Comment by klesh** [comment]
@e2corporation @yumengwang03 However, why the text on the right of **Weekly** is **00:00**, while the Next Run Time is **8:00AM**? It is confusing. Should we make them display the same text or label it with TIMEZONE?

- Weekly ( Monday at 00:00 AM UTC )

Next Run Time

10/27/2022 8:00 AM (in 14 hours your LOCAL TIME)

**Comment by yumengwang03** [comment]
New figma prototype: https://www.figma.com/file/Eux4Dhorxp7M0TwzOnL6Yh/Config-UI-for-V1.0?node-id=2610%3A22925
