### ISSUE TITLE
[Feature][config-ui] display version information

### ISSUE THREAD

**Issue by asterix314** [apache/incubator-devlake#3607]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Previously, the version information was displayed at the page's lower-left corner, like this:

![image](https://user-images.githubusercontent.com/10952409/198491962-f073f086-127e-4a5f-b745-2a1c883c5b9d.png)

But not anymore in v0.14. The version info is either removed or hard to find. Please make it reappear. It is handy for issue/bug reporting among other things.

### Use case

Devlake version easily accessible in config-ui page.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by abeizn** [comment]
@asterix314  thanks for your contribution.

**Comment by Startrekzky** [comment]
![image](https://user-images.githubusercontent.com/14050754/205082460-d7c29aa4-a02f-4e32-9782-38ae26d207b2.png)
