### ISSUE TITLE
[Feature][DORA] Allow users to configure the environment of deployments by other attributes rather than 'job/build name'

### ISSUE THREAD

**Issue by Startrekzky** [apache/incubator-devlake#3609]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

The existing ways for users to configure the environment of deployments in GitHub/GitLab/Jenkins blueprint are like the screenshots below.

- GitHub 
![image](https://user-images.githubusercontent.com/14050754/198500762-ad4a9f46-2741-4276-81ff-0a14ad1d6c7a.png)

- GitLab
![image](https://user-images.githubusercontent.com/14050754/198500293-18a744ae-2de5-4dff-8fdc-f9c393f82b01.png)

- Jenkins
![image](https://user-images.githubusercontent.com/14050754/198500353-18ae0890-e9f0-4cd5-8aba-51b9734728e6.png)

### Use case

The problem is that for many projects, the `environment` of deployment cannot be recognized from a CI job/build's name. 

As a result, users can't tell DevLake which deployment is a 'production deployment'. Hence, the data integrity for DORA metrics, such as deployment frequency and change lead time, might not be accurate, as the deployments in non-production environments are counted. 

Take this project "apache/devlake-incubator" for example, we can't tell which GitHub action jobs are running in the `production` or in `staging/test` environment by job names. 

![image](https://user-images.githubusercontent.com/61080/205795035-53eacf44-a9ea-4456-8ea9-31be6310a0d4.png)

### Proposed Solution
Provide more features(deployment attributes) to users to configure "what is a production deployment".
![image](https://user-images.githubusercontent.com/14050754/198502583-76dc1f7a-ca5d-4c27-be24-d3db05bef89c.png)

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by klesh** [comment]
bump

**Comment by Startrekzky** [comment]
Duplicated with #5178
