### ISSUE TITLE
[Bug][Jira] "subtask collectAccounts ended unexpectedly"

### ISSUE THREAD

**Issue by Roberdvs** [apache/incubator-devlake#3614]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

When running a pipeline against a Jira board, it errors out with the following log:

```
time="2022-10-28 09:57:40" level=warning msg=" [pipeline service] [pipeline #3] [task #6] [jira] retry #2 calling api/2/user
	caused by: Http DoAsync error: %!!(MISSING)s(<nil>) (400)"
time="2022-10-28 09:57:41" level=info msg=" [pipeline service] [pipeline #3] [task #6] [jira] [collectAccounts] finished records: 34"
time="2022-10-28 09:57:44" level=info msg=" [pipeline service] [pipeline #3] [task #6] [jira] [collectAccounts] finished records: 43"
time="2022-10-28 09:57:46" level=error msg=" [pipeline service] [pipeline #3] [task #6] [jira] retry exceeded 3 times calling api/2/user (400)
	Wraps: (2) Http DoAsync error: %!!(MISSING)s(<nil>) (400)
	Error types: (1) *hintdetail.withDetail (2) *errors.errorString"
time="2022-10-28 09:57:47" level=info msg=" [pipeline service] [pipeline #3] [task #6] [jira] [collectAccounts] finished records: 51"
time="2022-10-28 09:57:50" level=error msg=" [task service] task failed
	caused by: Error running task 6.
	Wraps: (2) subtask collectAccounts ended unexpectedly
	Wraps: (3) retry exceeded 3 times calling api/2/user (400)
	Error types: (1) *hintdetail.withDetail (2) *hintdetail.withDetail (3) *errors.errorString"
time="2022-10-28 09:57:50" level=error msg=" [pipeline service] [pipeline #3] run tasks failed
	caused by: Error running task 6."
```

### What do you expect to happen

The pipeline to run successfully.

### How to reproduce

Not exactly sure, I added a Jira Cloud data connection and configured a Blueprint to scan a Jira board but it seems to be something wrong when it calls the `/rest/api/2/user` endpoint.

Tried with 2 different Jira boards and got the same error on both.

Happy to provide any extra info to help debug the issue.

### Version

v0.14.2

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by klesh** [comment]
@Roberdvs Sorry for your inconvenience, the Jira Cloud server endpoint should be `https://xxx.atlassian.net/rest/`

**Comment by Roberdvs** [comment]
Hi!

Yes, that's properly configured and actually other subtasks like `collectProjects` or `collectIssues` complete successfully, it's just this one that fails.

**Comment by klesh** [comment]
I see, will look into that

**Comment by klesh** [comment]
@abeizn please help identifying the problem

**Comment by abeizn** [comment]
@Roberdvs  Can you see if there are any account_id = "" data in _tool_jira_accounts table?

sql: 

```
select
*
from
_tool_jira_accounts
where account_id = ""
```
