### ISSUE TITLE
[Feature][Travis] Add travis as a CI/CD tool to devlake

### ISSUE THREAD

**Issue by robbybbb** [apache/incubator-devlake#3615]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Currently Travis is neither supported nor is it on the roadmap.  It's a popular CI/CD tool in the open source community and support is going to be appreciated by many in that community including where I work.

### Use case

Travis supports an API with the services that can provide data needed to a CI/CD dashboard plugin.  The proposal would be to use the standard plug-in format and normalized CI/CD data model.  Please let me know if this is not detailed enough I plan to start working on this myself for my organization's own purposes in any case.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Startrekzky** [comment]
Happy coding!
