### ISSUE TITLE
[Refactor][Framework] Refactor Extractors and Converters to use Generics

### ISSUE THREAD

**Issue by keon94** [apache/incubator-devlake#3616]
## What and why to refactor
Extract functions use raw objects which they manually have to json-deserialize into predefined structs. This is needless boilerplate now that Go supports generics. Refactor the api_extractor.go (and other relevant framework files) to performs these deserializations under the hood and send the resulting Go structs to the user (Extract) functions.
The Converters suffer from this as well, although there's less boilerplate there. Refactor accordingly.

## Describe the solution you'd like
Example:
currently we have:
```go
Extract: func(row *helper.RawData) ([]interface{}, errors.Error) {
	apiAccountOrgs := &[]GithubAccountOrgsResponse{}
	err := json.Unmarshal(row.Data, apiAccountOrgs)
	if err != nil {
		return nil, errors.Convert(err)
	}
	simpleAccount := &SimpleAccountWithId{}
	err = json.Unmarshal(row.Input, simpleAccount)
	if err != nil {
		return nil, errors.Convert(err)
	}
	// more logic...
}
```
it should become like:
```go
Extract: func(orgs []GithubAccountOrgsResponse, input *SimpleAccountWithId) ([]interface{}, errors.Error) {
	// more logic...
}
```
The API extractor will need to take two generic parameters: for the row data and the row input - initialization will look like this:
 
```go 
helper.NewApiExtractor[[]GithubAccountOrgsResponse, SimpleAccountWithId](...)
```

## Related issues
n/a

## Additional context
n/a

**Comment by Startrekzky** [comment]
Bump

**Comment by coldgust** [comment]
Hello, I would like to finish this task，could you assign this to me?

**Comment by keon94** [comment]
@coldgust Thanks for your interest. I've assigned this to you.

**Comment by coldgust** [comment]
It seems that most extractors just need to json-deserialize `row.Data` field, such as `backend/plugins/github/tasks/account_extractor.go`.


I want to define like this
```go
type ApiExtractorArgs[T any] struct {
	RawDataSubTaskArgs
	Params    interface{}
	Extract   func(data *T, row *RawData) ([]interface{}, errors.Error)
	BatchSize int
}
```
It still pass `*RawData` parameter, and the user dicide to whether json-deserialize `row.Input`.

**Comment by safeoy** [comment]
Hello, I will take it

**Comment by Dev79844** [comment]
Hey @keon94 ! Is anyone working on this issue? If not can you assign it to me

**Comment by keon94** [comment]
@Dev79844 I don't believe so. Sure, you can have it. Thanks for taking it on.
