### ISSUE TITLE
[Feature][framework] Task-level concurrency control

### ISSUE THREAD

**Issue by klesh** [apache/incubator-devlake#3618]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

to be filled

### Use case

to be filled

### Related issues

to be filled

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by likyh** [comment]
related with: https://github.com/apache/incubator-devlake/issues/3234

**Comment by klesh** [comment]
replaced by #3234
