### ISSUE TITLE
[Refactor][config-ui] Confusion in IntegrationsContext

### ISSUE THREAD

**Issue by likyh** [apache/incubator-devlake#3625]
## What and why to refactor
https://github.com/apache/incubator-devlake/blob/c215d73fba30c1c0114ab5be871f15b3645d6a53/config-ui/src/store/integrations-context.jsx#L22-L24

Here 3 vars defined but export as other name.

https://github.com/apache/incubator-devlake/blob/c215d73fba30c1c0114ab5be871f15b3645d6a53/config-ui/src/store/integrations-context.jsx#L51-L54

## Describe the solution you'd like
Change to the same.

**Comment by e2corporation** [comment]
@likyh These exports are aliased, it's not confusing... the context props are Capitalized intentionally to signify Priority (Integrations vs integrations. Please close this ticket. It's clearly indicated the props are aliased with the context value.

<img width="676" alt="Screen Shot 2022-10-31 at 9 58 55 AM" src="https://user-images.githubusercontent.com/1742233/199025514-5f18b495-4d75-4332-b4a3-b722bcdafe17.png">

**Comment by e2corporation** [comment]
@likyh  I think I see the confusion you are referring to now, the initial context shape on `Ln 22-24` needs to be updated to Uppercase `Registry`, `Plugins` and `Integration`.

**Comment by likyh** [comment]
https://github.com/apache/incubator-devlake/blob/c215d73fba30c1c0114ab5be871f15b3645d6a53/config-ui/src/store/integrations-context.jsx#L21-L33

Yes, I think `React.createContext` is what this plugin is.

**Comment by e2corporation** [comment]
@likyh Fixed w/ #3626.
