### ISSUE TITLE
[Bug][plugin] raise exception when no input to the argument selectedModels for dbt plugin options

### ISSUE THREAD

**Issue by usharerose** [apache/incubator-devlake#3637]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

According to the implementation of `dbt` plugin, `selectedModels` is an optional argument.

Currently, the task would fail when triggered according to the plan without this argument.

### What do you expect to happen

The task would run successfully under the condition that no specific models selected via this argument.

### How to reproduce

Trigger the pipeline with the following plan,
```
[
    [
        {
            "plugin": "dbt",
            "subtasks": null,
            "options": {
                "projectName": "demo_project",
                "projectPath": "/home/ubuntu/demo_project",
                "projectTarget": "dev"
            }
        }
    ]
]
```

and log shows that,
```
time="2022-11-01 04:42:24" level=info msg=" [pipeline service] [pipeline #61] [task #69] [dbt] [DbtConverter] dbt run script: %!(EXTRA *exec.Cmd=/usr/bin/dbt run --project-dir /home/ubuntu/demo_project --select)"
time="2022-11-01 04:42:29" level=error msg=" [task service] task failed
	caused by: Error running task 69.
	Wraps: (2) subtask DbtConverter ended unexpectedly
	Wraps: (3) exit status 2
	Wraps: (4) exit status 2
	Error types: (1) *hintdetail.withDetail (2) *hintdetail.withDetail (3) *hintdetail.withDetail (4) *exec.ExitError"
time="2022-11-01 04:42:29" level=error msg=" [pipeline service] [pipeline #61] run tasks failed
	caused by: Error running task 69."
```
which we can see that there is an extra `--select` without relative values

### Version

main

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by klesh** [comment]
@abeizn please take a look at this
