### ISSUE TITLE
[Bug][config-ui] getPipeline request didn't stop when I leave blueprint detail page.

### ISSUE THREAD

**Issue by likyh** [apache/incubator-devlake#3640]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

![image](https://user-images.githubusercontent.com/3294100/199253943-89d64ec2-043c-4a59-8c0a-15fd596b1f46.png)
getPipeline request not stop when I leave blueprint detail page.
![image](https://user-images.githubusercontent.com/3294100/199254124-380f37d2-c1e7-4026-be25-66570e24bdba.png)

### What do you expect to happen

Stop when I leave blueprint detail page.

### How to reproduce

1. open a blueprint
2. run it
3. go to other page and don't refresh page
4. look at network.

### Version

main

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by klesh** [comment]
Why shouldn't it be stopped?
I think it should be stopped, and restart when users went back to detail page.

**Comment by likyh** [comment]
> Why shouldn't it be stopped? I think it should be stopped, and restart when users went back to detail page.

I think so. So it is a bug.
