### ISSUE TITLE
[Refactor][dbt] export all args for dbt run and remove args from option

### ISSUE THREAD

**Issue by long2ice** [apache/incubator-devlake#3646]
## What and why to refactor
Now dbt plugin accept args and append to `dbt run` command, which may cause security issue, because I can add some dangerous commands such as `|| rm -rf /*`

## Describe the solution you'd like
Remove args option and export dbt run args explicitly

## Related issues
Please link any other

**Comment by abeizn** [comment]
I'm in favor of doing it too: Remove args option and export dbt run args explicitly
