### ISSUE TITLE
[Bug][config-ui] creation of concurrent runs of the same blueprint job

### ISSUE THREAD

**Issue by asterix314** [apache/incubator-devlake#3654]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

<img width="236" alt="image" src="https://user-images.githubusercontent.com/10952409/199636302-dcab39d2-0eb5-41ea-bcaa-57f4e978cb79.png">

In config-ui's blueprint status page, if you click on the "Run Now" button fast enough, it is possible to create two blueprint runs at the same time:

<img width="587" alt="image" src="https://user-images.githubusercontent.com/10952409/199635655-53f50fe7-63e4-4c6e-b7aa-5d0583b1e56f.png">

I inadvertently triggered this unfortunate event thanks to my jittery fingers. What will happen to the back-end tables in this case?

### What do you expect to happen

As soon as the "Run Now" button is clicked, it should be disabled until the plan finishes.

### How to reproduce

Just keep hitting on the button like crazy.

### Version

v0.14.1

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by e2corporation** [comment]
We do have backend plans to prevent this, Under normal scenario however The Button should be disabled once the run routine is engaged, there maybe some other component delay or some other issue that would be allowing this to happen. What Browser and Version was this produced with @asterix314?

**Comment by asterix314** [comment]
@e2corporation Thanks for the prompt reply. I used Firefox 105.0.3 (64-bit) on macOS Monterey.

**Comment by klesh** [comment]
related to #3286 , this kind of problem should be handled by the Be. @mindlesscloud is working on it
