### ISSUE TITLE
[Bug][StarRocks] starrocks plugin not close db connections

### ISSUE THREAD

**Issue by long2ice** [apache/incubator-devlake#3667]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

starrocks plugin not close db connections

### What do you expect to happen

starrocks plugin will close db connections after data sycn finish

### How to reproduce

sync data from pg to starrocks

### Version

main

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by abeizn** [comment]
closed
