### ISSUE TITLE
[Feature][Config UI] Change the layout of Set Data Scope from tabs to a table

### ISSUE THREAD

**Issue by yumengwang03** [apache/incubator-devlake#3671]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

We have received many complaints on how users may skip the tabs on the Set Data Scope and Set Transformations page, and therefore we want to update this layout to be a table.

Figma link: https://www.figma.com/file/Eux4Dhorxp7M0TwzOnL6Yh/Config-UI-for-V1.0?node-id=2372%3A16637

Current:
<img width="840" alt="Screen Shot 2022-11-04 at 11 09 36 AM" src="https://user-images.githubusercontent.com/9535430/199876764-b4430149-908d-4764-835a-56a77444f0b2.png">

The new layout:
<img width="625" alt="Screen Shot 2022-11-04 at 11 10 01 AM" src="https://user-images.githubusercontent.com/9535430/199876807-bd337e39-1faf-4aad-9df4-45e31b9fc538.png">

### Related issues

https://github.com/apache/incubator-devlake/issues/2271
https://github.com/apache/incubator-devlake/issues/3670

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Startrekzky** [comment]
@mintsweet Is this issue also included in v0.15?

**Comment by mintsweet** [comment]
Already done.
