### ISSUE TITLE
[Refactor][Config UI] Update the wording of the Transformation page

### ISSUE THREAD

**Issue by yumengwang03** [apache/incubator-devlake#3672]
Please follow all the comments on this page to update the wording of Transformations: https://www.figma.com/file/Eux4Dhorxp7M0TwzOnL6Yh/Config-UI-for-V1.0?node-id=2029%3A10488

<img width="1030" alt="Screen Shot 2022-11-04 at 11 35 00 AM" src="https://user-images.githubusercontent.com/9535430/199879755-1014e701-e915-43c8-9ba4-bdcbc314e2e7.png">

Note: GitHub is an example, and we need to update the wording in the same places of all data sources.

**Comment by Startrekzky** [comment]
To be tracked in #3634
