### ISSUE TITLE
[Feature][Config UI] Add the Pipeline list back

### ISSUE THREAD

**Issue by yumengwang03** [apache/incubator-devlake#3673]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

<img width="235" alt="Screen Shot 2022-11-04 at 11 41 25 AM" src="https://user-images.githubusercontent.com/9535430/199880628-219fdf18-bb72-4e34-b0f6-047f675c26f5.png">

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Startrekzky** [comment]
Bump
