### ISSUE TITLE
[Bug][Config-ui] Manual blueprint still has some info that should be in daily mode 

### ISSUE THREAD

**Issue by warren830** [apache/incubator-devlake#3678]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

![image](https://user-images.githubusercontent.com/39366025/199940623-8b6ea736-3bea-49f6-834e-abf1d320ec0a.png)
This is a manual blueprint, but it showed daily run

### What do you expect to happen

none

### How to reproduce

none

### Version

main

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Startrekzky** [comment]
Is it related to #3546?

**Comment by warren830** [comment]
> Is it related to #3546?

No, this issue mainly talked about display errors. #3546 mainly talked about default selection

**Comment by mintsweet** [comment]
#4047 fixed the issue.
