### ISSUE TITLE
[Feature][GitHub] Provide a time filter to limit the GitHub/GitLab data to collect

### ISSUE THREAD

**Issue by Startrekzky** [apache/incubator-devlake#3688]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar feature requirement.

### Use case

As an OSS project maintainer, I want to collect GitHub data with DevLake. It takes ages to finish the collection of all historical data; while I'm not going to use the data before 6 months.

The description below will be centered around GitHub, but the situation is similar for GitLab, jira, and other plugins.

### Description

Similar to #3642, the core idea is to limit the data to collect by selecting a time range. As a result, the collection speed of GitHub data will be shortened evidently.

DevLake will collect the last six months of GitHub data by default. Users can modify the date range. 

#### Affected entities
This time filter will affect the following entities by the corresponding time field:
- issues: `created_date`. All related entities such as issue_comments will be affected as well.
- PRs: `created_date`. All related entities such as pull_request_comments will be affected as well.
- commits: `authored_date`. All related entities such as commit_files will be affected as well.
- workflow runs: `started_at`
- jobs: `started_at`

Non-affected entities:
- tags: as they have no `created_date`
- accounts: it's fine to collect the full account list

Once this approach is proven effective, this `time filter` could be added to other plugins such as GitLab, Jira, etc.

#### Prototype
![Interaction Plan 2 - Time filter - default](https://user-images.githubusercontent.com/14050754/203966697-2227a452-1d9e-4d6e-afe0-7ae43d09c408.png)

<br/>

![image](https://user-images.githubusercontent.com/14050754/203965873-ad9cfbe5-4438-46a6-90a0-385135c92a8a.png)

Figma link: https://www.figma.com/file/Eux4Dhorxp7M0TwzOnL6Yh/Config-UI-for-V1.0?node-id=2601%3A18715

### Related issues

#3642

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by likyh** [comment]
closed by https://github.com/apache/incubator-devlake/pull/3916
