### ISSUE TITLE
[Feature][Dora] Use project_issue_metrics to store issue deployment_id

### ISSUE THREAD

**Issue by warren830** [apache/incubator-devlake#3689]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

As we have project now, we need to use project_name as our data scope to filter issues, also we need to save issue deploymentId to project_issue_metrics

### Use case

1. use project_name to filter data
2. add project_issue_metrics
3. remove relevant fields from issues

### Related issues

#3468 

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by yumengwang03** [comment]
@warren830 is this issue already resolved by the PR above?

**Comment by warren830** [comment]
fixed by #3768

**Comment by warren830** [comment]
> @warren830 is this issue already resolved by the PR above?

Yes, this was resolved
