### ISSUE TITLE
[Feature][Python plugin SDK] Support plugin development in Python

### ISSUE THREAD

**Issue by keon94** [apache/incubator-devlake#3701]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Extend the backend framework to support plugins developed in Python. Create an SDK that developers can use to easily code plugin components in Python, and which hooks itself to the main Go framework.

### Use case

This will allow developers create plugins in Python if they prefer.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Startrekzky** [comment]
Is this one done or not? @keon94

**Comment by keon94** [comment]
> Is this one done or not? @keon94

It's not. Still in progess by @CamilleTeruel
