### ISSUE TITLE
[Bug][github_graphql] 502 when collecting pull requests

### ISSUE THREAD

**Issue by likyh** [apache/incubator-devlake#3708]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

![image](https://user-images.githubusercontent.com/3294100/200982345-a8991341-97b2-42b5-a3ea-c155bf21d129.png)

sometimes PrCollector in graphql will raise 502.

### What do you expect to happen

collect success.

### How to reproduce

1. use graphql_github to collect `https://github.com/apache/jackrabbit-oak`
2. it will raise 502.

### Anything else

The reason is too much data on each page. Now 30 pr, 30 * most 100 commits will bind to one graphql query. But I think it will be too slow if set to less than 30 pr per page. In past, the number is 100 pr per page.

Maybe we need a dynamic page size. It could request 100 per page and reduce less if 502 got.

### Version

main

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by yumengwang03** [comment]
@likyh Do we want to put this bug in v0.15? cc @klesh

**Comment by likyh** [comment]
> @likyh Do we want to put this bug in v0.15? cc @klesh

No, I don't think so.

**Comment by Startrekzky** [comment]
This is solved.
