### ISSUE TITLE
[Bug][Git Extractor] Git Extractor task failed in a GitHub blueprint

### ISSUE THREAD

**Issue by hezyin** [apache/incubator-devlake#3719]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

I created a GitHub blueprint to collect all 54 public repos under merico-dev organization using this python script: https://gist.github.com/hezyin/f34a46288470ab029d2ae3d30de9e698

I successfully created the blueprint and manually triggered it. The pipeline failed at stage 2 because of a failed git extractor task. 

<img width="1509" alt="Screen Shot 2022-11-10 at 4 13 01 PM" src="https://user-images.githubusercontent.com/2908155/201240105-8d04dc5b-f41f-42b8-b682-1795946ad55f.png">

To pinpoint the issue, I created a new blueprint via Config UI to only collect the repo (https://github.com/merico-dev/tree-sitter-kotlin) failed in the previous pipeline. And I was able to reproduce the failure:

<img width="1247" alt="Screen Shot 2022-11-10 at 5 17 01 PM" src="https://user-images.githubusercontent.com/2908155/201240222-4432d926-3a38-4d56-9245-504a6c90236c.png">

Please see below for the log of the failed git extractor task:

>time="2022-11-11 01:13:38" level=info msg=" [pipeline service] [pipeline #4] [task #491] start executing task: 491"
time="2022-11-11 01:13:38" level=info msg=" [pipeline service] [pipeline #4] [task #491] [gitextractor] start plugin"
time="2022-11-11 01:15:25" level=info msg=" [pipeline service] [pipeline #4] [task #491] [gitextractor] total step: 3"
time="2022-11-11 01:15:26" level=info msg=" [pipeline service] [pipeline #4] [task #491] [gitextractor] executing subtask collectGitCommits"
time="2022-11-11 01:15:48" level=info msg=" [pipeline service] [pipeline #4] [task #491] [gitextractor] [collectGitCommits] total jobs: 217"
time="2022-11-11 01:15:52" level=info msg=" [pipeline service] [pipeline #4] [task #491] [gitextractor] [collectGitCommits] finished records: 1"

### What do you expect to happen

I expect the git extractor task to succeed.

### How to reproduce

Please see above.

### Version

v0.14.2

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by likyh** [comment]
Can it appear now? @hezyin

**Comment by mindlesscloud** [comment]
fixed by changing the docker base image

**Comment by moreinhardt** [comment]
We're running into this error with a self-hosted Gitlab server and version v0.19.0.

The [troubleshooting docs](https://devlake.apache.org/docs/v0.19/Troubleshooting/Configuration#gitextractor-task-failed-in-a-githubgitlabbitbucket-blueprint) are pointing to this issue...

I don't remember enabling this plugin manually and I see no way to configure it in the UI. Is it automatically enabled when creating a Gitlab connection?

Any help how this can be fixed?

**Comment by klesh** [comment]
@moreinhardt are you using a self-signed certificate? You may like to take a look at https://devlake.apache.org/docs/Troubleshooting/Configuration#failed-to-collect-data-from-the-server-with-a-self-signed-certificate if so
