### ISSUE TITLE
[Bug][Pipeline] GitHub pipeline failed when only CODE entities were specified

### ISSUE THREAD

**Issue by hezyin** [apache/incubator-devlake#3720]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

I created a GitHub blueprint to collect all 54 public repos under merico-dev organization using this python script: https://gist.github.com/hezyin/f34a46288470ab029d2ae3d30de9e698. I commented out lines 48 - 51 in the script so only CODE entities would be collected.

When I manually triggered the blueprint, the pipeline failed:

<img width="1238" alt="Screen Shot 2022-11-10 at 5 28 16 PM" src="https://user-images.githubusercontent.com/2908155/201243892-4a675244-0350-4777-a5cc-8465efba703e.png">

Please see the log of the failed task below:

> time="2022-11-10 07:31:38" level=info msg=" [pipeline service] [pipeline #1] [task #1] start executing task: 1"
time="2022-11-10 07:31:38" level=info msg=" [pipeline service] [pipeline #1] [task #1] [github] start plugin"
time="2022-11-10 07:31:38" level=info msg=" [pipeline service] [pipeline #1] [task #1] [github] scheduler for api https://api.github.com/ worker: 26, request: 19000, duration: 1h0m0s"
time="2022-11-10 07:31:38" level=info msg=" [pipeline service] [pipeline #1] [task #1] [github] total step: 5"
time="2022-11-10 07:31:38" level=info msg=" [pipeline service] [pipeline #1] [task #1] [github] executing subtask collectApiRepo"
time="2022-11-10 07:31:38" level=info msg=" [pipeline service] [pipeline #1] [task #1] [github] [collectApiRepo] start api collection"
time="2022-11-10 07:31:39" level=info msg=" [pipeline service] [pipeline #1] [task #1] [github] [collectApiRepo] finished records: 1"
time="2022-11-10 07:31:39" level=info msg=" [pipeline service] [pipeline #1] [task #1] [github] [collectApiRepo] end api collection without error"
time="2022-11-10 07:31:39" level=info msg=" [pipeline service] [pipeline #1] [task #1] [github] finished step: 1 / 5"
time="2022-11-10 07:31:39" level=info msg=" [pipeline service] [pipeline #1] [task #1] [github] executing subtask extractApiRepo"
time="2022-11-10 07:31:39" level=info msg=" [pipeline service] [pipeline #1] [task #1] [github] [extractApiRepo] get data from _raw_github_api_repositories where params={"ConnectionId":1,"Owner":"merico-dev","Repo":"tree-sitter-objc"} and got 1"
time="2022-11-10 07:31:39" level=info msg=" [pipeline service] [pipeline #1] [task #1] [github] [extractApiRepo] finished records: 1"
time="2022-11-10 07:31:39" level=info msg=" [pipeline service] [pipeline #1] [task #1] [github] finished step: 2 / 5"
time="2022-11-10 07:31:39" level=info msg=" [pipeline service] [pipeline #1] [task #1] [github] executing subtask CollectApiPrReviewCommentsMeta"
time="2022-11-10 07:31:39" level=info msg=" [pipeline service] [pipeline #1] [task #1] [github] [CollectApiPrReviewCommentsMeta] start api collection"
time="2022-11-10 07:31:40" level=info msg=" [pipeline service] [pipeline #1] [task #1] [github] [CollectApiPrReviewCommentsMeta] finished records: 1"
time="2022-11-10 07:31:40" level=info msg=" [pipeline service] [pipeline #1] [task #1] [github] [CollectApiPrReviewCommentsMeta] end api collection without error"
time="2022-11-10 07:31:40" level=info msg=" [pipeline service] [pipeline #1] [task #1] [github] finished step: 3 / 5"
time="2022-11-10 07:31:40" level=info msg=" [pipeline service] [pipeline #1] [task #1] [github] executing subtask extractApiPrReviewComments"
time="2022-11-10 07:31:40" level=info msg=" [pipeline service] [pipeline #1] [task #1] [github] [extractApiPrReviewComments] get data from _raw_github_api_pull_request_review_comments where params={"ConnectionId":1,"Owner":"merico-dev","Repo":"tree-sitter-objc"} and got 16"

### What do you expect to happen

I expect the failed github task to succeed.

### How to reproduce

Please see above

### Version

v0.14.2

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by mindlesscloud** [comment]
The error was caused by the missing records in the table `_tool_github_pull_requests` during extracting PR review comments. To be more accurate, the error `gorm.ErrRecordNotFound` in line 125 is the root problem.
https://github.com/apache/incubator-devlake/blob/v0.14.2/plugins/github/tasks/pr_review_comment_extractor.go#L125

**Comment by klesh** [comment]
similar to #3804
