### ISSUE TITLE
[Feature][OSS Community Metrics] Create a new dashboard for OSS Community Metrics

### ISSUE THREAD

**Issue by warren830** [apache/incubator-devlake#3721]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar feature requirement.

### Use case

As an open-source project maintainer, I want to measure the community growth with a dashboard that shows metrics such as:
1. stars (total number, number of new stars per month)
2. clones (total number, number of new clones per month)
3. forks (total number, number of new forks per month)
4. watches (total number, number of new watches per month)
5. cloners (total number of distinct cloners, number of new distinct cloners per month)
-------- Below are the metrics that are already been supported by DevLake -----------
6. contributors (total number, number per month)
7. commits (total number, number per month)
8. PRs (total number, merged number, number per month)
9. issues (total number, closed number, bug number, number per month)

#### Todo List: 
1. Investigate [GitHub GraphQL APIs](https://docs.github.com/en/graphql), [GitHub REST APIs](https://docs.github.com/en/rest) and [GHArchive APIs](https://www.gharchive.org/) to find all APIs related to `stars`, `clones`, `forks`, `watch`, `cloner` and other data required by the use case above.
2. Based on step 1, decide if we should create a **new plugin** or update the existing [GitHub-graphQL](https://github.com/apache/incubator-devlake/tree/main/plugins/github_graphql) plugin to accomplish this.
3. Coding on collection&extraction&conversion of data through APIs found in step 1
4. In Grafana, create a dashboard to show the metrics in the use cases based on the data collected in step 3
5. Write relevant docs in [apache/incubator-devlake-website](https://api.github.com/repos/apache/incubator-devlake-website)

#### Deliverables: 
1. A GitHub comment under this issue for the API investigation result
2. A new **plugin**(or an updated GraphQL plugin) that can collect data for `OSS Community Metrics` dashboard
3. A plugin **doc** if we decide to create a new plugin for this feature. Similar to other [plugin docs](https://devlake.apache.org/docs/next/Plugins), we need to tell users how to run this plugin
4. A new **dashboard** called `OSS Community Metrics` on grafana
5. A **doc** to introduce the dashboard to users

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Palanikannan1437** [comment]
Hey @warren830, @henit-chobisa and I would like to work on this issue...could you please assign it to us?

**Comment by warren830** [comment]
> Hey @warren830, @henit-chobisa and I would like to work on this issue...could you please assign it to us?

Assigned, happy coding!

**Comment by henit-chobisa** [comment]
Hey Warren, could you assign this to me as well, I'd be collaborating with @Palanikannan1437 on the same and we'd be dividing the subtasks amongst ourselves. Thank you!

**Comment by warren830** [comment]
> Hey Warren, could you assign this to me as well, I'd be collaborating with @Palanikannan1437 on the same and we'd be dividing the subtasks amongst ourselves. Thank you!

Thanks for your enthusiasm! Happy coding!

**Comment by yumengwang03** [comment]
Hi, @henit-chobisa and @Palanikannan1437 how's the progress of this issue?

**Comment by Palanikannan1437** [comment]
Hey @yumengwang03, we're still working on it while documenting our entire journey to help new contributors as a better guide to implement plugins in general...hence the delay! Thank you!

**Comment by Palanikannan1437** [comment]
> Hey @yumengwang03, we're still working on it while documenting our entire journey to help new contributors as a better guide to implement plugins in general...hence the delay! Thank you!

Yet to work on this according to our OKRs of the JDE program! Currently working on the task of setting up Automated dev environments for DevLake

https://github.com/Palanikannan1437/incubator-devlake/tree/gitpod-script
