### ISSUE TITLE
[Bug][Blueprint] The options of blueprint and pipeline should be encrypted in database

### ISSUE THREAD

**Issue by liangjingyang** [apache/incubator-devlake#3722]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

The options of blueprint and pipeline are unencrypted in database.
<img width="1524" alt="image" src="https://user-images.githubusercontent.com/2056705/201266950-592455f5-9ac4-463b-a705-0dbd439d5f58.png">

### What do you expect to happen

The options of blueprint and pipeline should be encrypted in database.

### How to reproduce

Create a blueprint.

### Version

v0.14.2

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by abeizn** [comment]
same to #3709

**Comment by klesh** [comment]
fixed by #4005
