### ISSUE TITLE
[Bug][e2e] nil support in csv

### ISSUE THREAD

**Issue by narrowizard** [apache/incubator-devlake#3749]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

I have wrote some e2e test with e2ehelper.DataFlowTester, it's a great experience.  
But it reports error when my snapshot data is with nil column value.  
![3e425cc3-529d-4ffd-bb7e-43b708ffa81d](https://user-images.githubusercontent.com/11383928/202332278-8d3d2592-4e0d-43de-91d4-aae8d14e3684.jpeg)

### What do you expect to happen

As a helper, `DataFlowTester` should support nil value properly.   
I noticed that `ImportCsvIntoTabler` will convert empty string to nil value before write to db. It is not a perfect solution as it confused empty string and nil value.  
https://github.com/apache/incubator-devlake/blob/fb6c5e2e6131cd8c868183430b57a84e9c89c827/helpers/e2ehelper/data_flow_tester.go#L145-L147

> we always have columns with nil value, and requrement to validate these data.

### How to reproduce

Refer to `What happened` section

### Anything else

The problem is that csv file cannot distinct empty string and nil value.  
A solution is that we can use a placeholder string to represent nil value. (maybe a `<nil value>`)  
When read from csv file, convert the `<nil value>` to nil. And write a `<nil value>` when writing a nil value.

### Version

main

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by mappjzc** [comment]
Thanks for you issue, are you willing to submit PR?

**Comment by klesh** [comment]
Found an practical solution from https://docs.snowflake.com/en/user-guide/data-unload-considerations.html#:~:text=Empty%20Strings%20and%20NULL%20Values,-An%20empty%20string&text=In%20CSV%20files%2C%20a%20NULL,null%20)%20or%20any%20unique%20string.


That is to quote all string with double quote, and empty string without quote represents `nil`
![image](https://user-images.githubusercontent.com/61080/203507520-8afc3e11-08a2-4b44-8266-b154454b8823.png)
![image](https://user-images.githubusercontent.com/61080/203507541-d6698f0b-8fd6-455f-b731-3c4f5d2fd229.png)
![image](https://user-images.githubusercontent.com/61080/203507569-aca826c8-5cc0-4481-a32d-02240bc932d6.png)

**Comment by Startrekzky** [comment]
@mindlesscloud What's the progress of this bug?
