### ISSUE TITLE
[Bug][Pipeline] Download logs but dbt folder got 

### ISSUE THREAD

**Issue by liangjingyang** [apache/incubator-devlake#3800]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

Download logs but dbt folder got 

<img width="1366" alt="image" src="https://user-images.githubusercontent.com/2056705/203564497-575e3186-e1ce-47fa-a075-e0d5ce1b0663.png">

### What do you expect to happen

Download pipeline logs correctly.

### How to reproduce

Click the "Download Full Log" button of a failed pipeline.

### Version

v0.14.2

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by klesh** [comment]
@keon94 Would you take a look at this? thanks.

**Comment by keon94** [comment]
@liangjingyang What's happening exactly when you try to download them?

**Comment by keon94** [comment]
I tested this on a couple of plugins that errored out midway and did not run into any issues. The logs downloaded normally.

**Comment by keon94** [comment]
@liangjingyang please share your full blueprint setup with me so I can replicate this.

**Comment by keon94** [comment]
Also please check your LOGGING_DIR env. I suspect you might be sharing it with another directory that has all your dbt stuff.

**Comment by liangjingyang** [comment]
Hi @keon94 thanks for your investigating and reply.

I didn't set LOGGING_DIR, so it is the default working directory I guess: `/app`. 

Yes, I mount a `dbt` folder on `/app/dbt`, but the downloaded folder is not the `/app/dbt`, it's `/app/dbt/dbt/proejcts/datacenter`.

After some debuging on `release-0.14`, I found that [here](https://github.com/apache/incubator-devlake/blob/release-v0.14/plugins/dbt/tasks/convertor.go#L58) changed the working directory which maybe made the logging directory changed.

I have some suggestions for discussing:

1. The dbt plugin shouldn't change the working directory @long2ice. (It's better not change the working directory in runtime ). 
2. The core should give a unified base path for relative path.
3. Consider to give a specific relative logging path as default LOGGING_DIR in .env, something like `logs`, since [here](https://github.com/apache/incubator-devlake/blob/release-v0.14/services/pipeline.go#L333) downloads the whole logging directory.

**Comment by klesh** [comment]
1. fixed by #3976 
2. fixed by #3863 
3. will put up an pr for that
