### ISSUE TITLE
[Bug][framework] An error occurred while trying to disable the blueprint

### ISSUE THREAD

**Issue by mindlesscloud** [apache/incubator-devlake#3802]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

An error occurred while trying to disable the blueprint, the following is the screenshot.
![image](https://user-images.githubusercontent.com/8455907/203768787-ad2f9f17-6487-435c-8ad7-821c0405f252.png)

### What do you expect to happen

No error should be raised

### How to reproduce

1. create a gitlab project
2. create a blueprint to collect data of the project
3. delete the project
4. disable the blueprint

### Version

main

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by klesh** [comment]
project deletion is not supported.
close the issue for now.
