### ISSUE TITLE
[Feature][Jira] Provide a time filter to limit the Jira data to collect

### ISSUE THREAD

**Issue by Startrekzky** [apache/incubator-devlake#3805]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar feature requirement.

### Use case

As an product owner, I want to collect Jira data with DevLake to measure issue-tracking metrics. It takes ages to finish the collection of all historical data; while I'm not going to use the data before 6 months.

### Description

Similar to #3688, the core idea is to limit the data to collect by selecting a time range. As a result, the collection speed of Jira data will be shortened evidently.

DevLake will collect the last six months of Jira data by default. Users can modify the date range. 

#### Affected entities
This time filter will affect the following entities by the corresponding time field:
- issues: `created_date`. All comments, changelogs, and worklogs under these issues will be collected.
- sprints: `started_date`.

Non-affected entities:
- boards
- accounts: it's fine to collect the full Jira account list

#### Prototype
Figma: https://www.figma.com/file/Eux4Dhorxp7M0TwzOnL6Yh/Config-UI-for-V1.0?node-id=2610%3A22925
<img width="910" alt="Screen Shot 2022-11-28 at 5 23 55 PM" src="https://user-images.githubusercontent.com/9535430/204241023-3fdfa958-ca86-4c3d-8b84-5dabb6990c10.png">

### Related issues

#3688
#3492 

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by klesh** [comment]
Seems like the BE part is ready, @mintsweet please pick it up for the config-ui

**Comment by likyh** [comment]
closed by https://github.com/apache/incubator-devlake/pull/3916

**Comment by mdapke-insight** [comment]
Is there a way the time Range is always set to 'last 6 months'? So, at any given point in time, the data that devlake is collecting is the last 6 months without us needed to manually set it again and again

**Comment by d4x1** [comment]
@mdapke-insight Your advice makes sense. You can submit a new feature request issue where we can discuss it in detail.
