### ISSUE TITLE
[Bug] Bluepint should be Blueprint on Dashboard page

### ISSUE THREAD

**Issue by MarcViola** [apache/incubator-devlake#3814]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

Dashboard typo.
Maybe somebody had too many pints :-)
![image](https://user-images.githubusercontent.com/31352762/204335345-666cb817-b3fc-4fab-8b84-fe8624327aef.png)

### What do you expect to happen

Should be Blueprint?

### How to reproduce

Load the page: http://localhost:4000/

### Version

main

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by mindlesscloud** [comment]
Thanks for the feedback, we will fix it in the next release. Wish you have a nice day!🍺
