### ISSUE TITLE
[Bug][core] cannot cancel pipelines with status 'TASK_CREATED'

### ISSUE THREAD

**Issue by narrowizard** [apache/incubator-devlake#3825]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

I use api `DELETE /pipelines/:id` to cancal pipelines with status 'TASK_CREATED'. But it not works.

### What do you expect to happen

The target pipeline should be cancelled.

### How to reproduce

Create some pipelines, the latter ones will be put in queue (with status 'TASK_CREATED'. Then call api `DELETE /pipelines/:id` to cancel it, but it not works.

### Version

v0.14.2

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by mappjzc** [comment]
Thank you for your suggestion, we will discuss this issue.Are you willing to submit PR for this?
