### ISSUE TITLE
Error 1206: The total number of locks exceeds the lock table size

### ISSUE THREAD

**Issue by pplam** [apache/incubator-devlake#3849]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

Subtask `collectApiPullRequestReviews` ended unexpectedly when running a `gitee` pipeline.
<img width="1491" alt="Screenshot 2022-12-05 at 09 40 23" src="https://user-images.githubusercontent.com/12783579/205530919-afa8226e-1f7a-4dc7-9d50-e420fcb53442.png">

### What do you expect to happen

Expect the task to complete successfully.

### How to reproduce

Create a pipeline with the following plan:
~~~
{
  "name": "openharmony",
  "plan": [[
      {
        "plugin": "gitee",
        "options": {
          "connectionId": 1,
          "repo": "arkui_ace_engine",
          "owner": "openharmony"
        }
      }
    ]]
}
~~~
And `POST` to the api path `/pipelines`. 

The task fails after running for about `1.5h` with the error message "subtask collectApiPullRequestReviews ended unexpectedly\ncaused by: error deleting data from collector\ncaused by: Error 1206: The total number of locks exceeds the lock table size".

### Version

main

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by klesh** [comment]
Thanks for the report.
Seems like the MySQL InnoDb engine would create a row lock for each and every row that met the condition which would cause memory to exceed when targeting a large number of rows.
In this case, deleting huge amount pr reviews belongs to a specific repo.
![image](https://user-images.githubusercontent.com/61080/205576918-eb3cc021-daec-4559-9c70-765029502e3c.png)
