### ISSUE TITLE
[Doc][gitextractor] Add troubleshooting for GitExtractor

### ISSUE THREAD

**Issue by klesh** [apache/incubator-devlake#3878]
## Documentation Scope
https://devlake.apache.org/docs/next/Plugins/gitextractor

Make sure this plugin doc's format is consistent with other plugin docs, such as [GitHub](https://devlake.apache.org/docs/Plugins/github)

**Comment by lavakush07** [comment]
Hey @klesh , Can you please assign me this issue ?

**Comment by likyh** [comment]
@lavakush07 Hi, Are you still doing this for issue?

**Comment by Startrekzky** [comment]
Hi @lavakush07 , any updates about this issue?
