### ISSUE TITLE
[Refactor][PipelinePlanV200] better to use ID but not transformationRule.

### ISSUE THREAD

**Issue by mappjzc** [apache/incubator-devlake#3887]
## What and why to refactor
In GitHub, Jenkins, Jira, and so on.
Plugins use the transformationRule to makeDataSourcePipelinePlanV200, but not ID as follows:
![107c0978-f033-4470-bd89-70dd1563cf53](https://user-images.githubusercontent.com/2921251/206353449-b5a0ba70-461b-4bcc-83bc-ee9626e2501a.jpeg)
![7987f9de-741a-49da-a4d4-f4361ea8765a](https://user-images.githubusercontent.com/2921251/206353456-e5701b14-683c-4dd4-93a3-3782cdc3804b.jpeg)
![83152c9a-7892-40fe-acea-0b347d15bc29](https://user-images.githubusercontent.com/2921251/206353461-807237cf-560c-4c16-a93a-3e4cf8f30d8b.jpeg)

And now  we can get the TransformationRules by ID from the database on PrepareTaskData
![image](https://user-images.githubusercontent.com/2921251/206353708-08400da7-4d66-40d9-92c8-c18f5befcb43.png)

so it is better to use ID.

## Describe the solution you'd like
change it to save TransformationRuleId but not TransformationRules in Options.

## Related issues
#3468

**Comment by abeizn** [comment]
fixed by v0.15.0
