### ISSUE TITLE
Error 1060: Duplicate column name 'settings' - proceed-db-migration failed

### ISSUE THREAD

**Issue by doronshai** [apache/incubator-devlake#3888]
## Question
I have a new DevLake instance, installed on K8S.

devlake@sha256:dee395b4d273fefce341c6d9963a005a0f6e019cd3a453e7062302f39d9e0c14

when i try to browse i get an error about migration required but when i run it - it fails.

## Screenshots
![Screen Shot 2022-12-08 at 12 15 02](https://user-images.githubusercontent.com/2786709/206420870-ac1f5ddb-b9fb-46ef-99b5-8aeb4eac9c9d.png)

## Additional context
Here are the Error messages from the log
[devlake-log-errors.txt](https://github.com/apache/incubator-devlake/files/10184368/devlake-log-errors.txt)

Please tell me what I am doing wrong

**Comment by keon94** [comment]
Hi @doronshai. Could you add details to the issue title?

**Comment by doronshai** [comment]
@keon94 Done - thanks for notice :)

**Comment by keon94** [comment]
@doronshai Which version of Devlake are you running?

**Comment by doronshai** [comment]
when set to true the pod is restarting endlessly. but anyway the migration fails.
why do i need to do migration? this is a new installation - what do i have to migrate??
if i will take older version will it ask also for migration?

**Comment by keon94** [comment]
Migration just means the DDL statements to set up the SQL tables. No data gets moved around. Anyway, FORCE_MIGRATION should be false, just wanted to make sure. @klesh do you have any ideas what could cause this? We already ruled out race conditions. There is only one pod running.

**Comment by klesh** [comment]
@doronshai Which version is it?
You may try the following step for new installation:
1. stop devlake container
2. recreate the database or delete everything in the database (the `lake` database, not the entire server)
3. start devlake contianer

**Comment by liuxiaomingg** [comment]
> 

@doronshai Did you follow this method on your end

**Comment by liuxiaomingg** [comment]
On my side because mysql5.7 and  0.14.2  incompatible

**Comment by doronshai** [comment]
I am still stuck - not wokring

**Comment by hezyin** [comment]
Hi @doronshai, please let us know if you still need help, thanks!

**Comment by hezyin** [comment]
Hi @doronshai, I'm closing this issue now due to inactivity. Feel free to reopen or reach out if you need further assistance.
