### ISSUE TITLE
[Question][Azure Devops] Azure Devops plugin

### ISSUE THREAD

**Issue by Sarakanerva** [apache/incubator-devlake#3890]
## Question
Hi! Our Team is using Azure Devops and would like to use Apache DevLake for collecting DORA metrics data. On the comments of feature issue #2604 you stated that the plugin is missing a lot of entities and not ready for end users yet, and that it currently collects only Repo and Build data.

Would you have some rough time estimate on when the plugin would be ready for end user use? 

Our use cases for the plugin would be having reporting from all of our ADO repositories on each of the four the DORA metrics and having the reports be visible on a dashboard. 

Thanks!

**Comment by KasperSJensen** [comment]
We have started the DevOps journey in our organization and have five teams eager to use DORA-metrics. DevLake seems like an obvious choice for gathering the data. We use Azure DevOps for development and would  like to upvote this ticket.

**Comment by klesh** [comment]
@Sarakanerva @KasperSJensen Thanks for your input, I'll try to get it into milestone v0.16. The  release date for v0.16 is somewhere between the end of Jan or Mid-Feb, it is not quite decided yet since New  year Holiday is comming. Will leave comment if any development. 😊😊😊

FYI @Startrekzky @hezyin

**Comment by KasperSJensen** [comment]
That is really awesome. Thank you very much!

**Comment by klesh** [comment]
@Sarakanerva @KasperSJensen Hi, we discussed and listed this feature in our v0.16 milestone. Feel free to check out "Phase 2 - Integrate Azure Repos (v0.16)" from #2604.
Since this is a "Question", I consider it is answered 😊. I'm closing it now, feel free to re-open it if I am mistaken. Thanks😁

**Comment by KasperSJensen** [comment]
Thank you @klesh. We are so much looking forward to this feature.
