### ISSUE TITLE
[Refactor][plugins] do not use gorm in any plugins

### ISSUE THREAD

**Issue by mappjzc** [apache/incubator-devlake#3896]
## What and why to refactor
We have developed `dal` and basically use dal in all plugins
But there are still very few parts in the plugin, there are still uses and references to `gorm`.
We should remove all references to `gorm` in the plugin.

## Describe the solution you'd like
![image](https://user-images.githubusercontent.com/2921251/206649163-d8480f28-800e-499e-ada3-a560943bdfde.png)
![image](https://user-images.githubusercontent.com/2921251/206649366-98ff286a-d63d-413c-aa35-c5ebf497ba38.png)

remove all gorm on plugins.

**Comment by deepto98** [comment]
Hi, I'm new to this project, can I pick this up?

**Comment by mappjzc** [comment]
> Hi, I'm new to this project, can I pick this up?
Thanks for your asking.
But, I'm sorry because I had already working on this.
