### ISSUE TITLE
[Bug][GitExtractor] gitextractor reporting error

### ISSUE THREAD

**Issue by klesh** [apache/incubator-devlake#3936]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

When collecting `apache/incubator-devlake` with default settings. the following error reported in the terminal and the task failed.

![image](https://user-images.githubusercontent.com/61080/207791595-64e99542-65ce-42d2-916a-ea62752b335c.png)

### What do you expect to happen

gitext succeed without error

### How to reproduce

collector our repo with default settings

### Version

main

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by klesh** [comment]
maybe related to #4001

**Comment by warren830** [comment]
Seems like this issue no longer exist?

**Comment by klesh** [comment]
> Seems like this issue no longer exist?

No, I don't think so. Closing it.
