### ISSUE TITLE
[Bug][config-ui] "invalid" need to be updated when test

### ISSUE THREAD

**Issue by likyh** [apache/incubator-devlake#3942]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

![image](https://user-images.githubusercontent.com/3294100/207798707-829106f1-86dd-443d-b2b0-452f3bc07e91.png)

### What do you expect to happen

show token is correct

### How to reproduce

1. fill token but keep endpoint empty
![image](https://user-images.githubusercontent.com/3294100/207798390-9f56ee1f-aab5-40b4-9b9c-9c889e059aca.png)
2. fill endpoint and test it
![image](https://user-images.githubusercontent.com/3294100/207798669-c1f6dc98-a989-4ae7-9b0e-5db70742bf4d.png)

3. look at the token, it's still invalid.
![image](https://user-images.githubusercontent.com/3294100/207798707-829106f1-86dd-443d-b2b0-452f3bc07e91.png)

### Version

main

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by klesh** [comment]
@likyh Please add `bug` to the current milestone next time.
