### ISSUE TITLE
[Bug][devops] log can not download

### ISSUE THREAD

**Issue by likyh** [apache/incubator-devlake#3948]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

![image](https://user-images.githubusercontent.com/3294100/207804832-fc49508b-0986-41db-834e-0ea1ada3b1fe.png)
log can not download

### What do you expect to happen

download successfully.

### How to reproduce

1. create bp
2. start bp
3. download log

### Version

main

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by abeizn** [comment]
Fixed and verified.
