### ISSUE TITLE
[Bug][config-ui] choose another transformationRule, the left column can not update reactively.

### ISSUE THREAD

**Issue by likyh** [apache/incubator-devlake#3951]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

![image](https://user-images.githubusercontent.com/3294100/207811290-4d70db25-329b-4f24-92d4-fb8fda0348fb.png)
choose another transformationRule, the left column can not update reactively.

### Version

main

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by mintsweet** [comment]
@likyh  does this issue still exist?

**Comment by likyh** [comment]
> @likyh does this issue still exist?

yes， bp edit page
