### ISSUE TITLE
[Doc][Installation] Encourage users to use helm instead of our k8s template

### ISSUE THREAD

**Issue by hezyin** [apache/incubator-devlake#3954]
## Documentation Scope

DevLake's Getting Started guide provides two approaches for k8s installation:

1. a k8s template for users to customize: https://devlake.apache.org/docs/next/GettingStarted/KubernetesSetup/
2. with helm: https://devlake.apache.org/docs/next/GettingStarted/HelmSetup/

Since users may customize the k8s template file in many ways, it becomes very challenging when something goes wrong and users ask for help debugging the deployment. We should consider recommend helm approach over the k8s template.

## Describe the Change

1. List Helm on top of K8s template in the nav bar on the left of the page so users discover helm first
2. In k8s template doc page, mention that we highly recommend the helm approach and this page is for advanced installation only

**Comment by Palanikannan1437** [comment]
Hey @hezyin , I'd like to work on this issue
...would we be moving this issue to the devlake website repository?

**Comment by warren830** [comment]
Hi @Palanikannan1437 , are you still willing to contribute to this issue? We can keep this issue here, but will create doc issue in website repo next time. Thank you!

**Comment by Palanikannan1437** [comment]
> Hi @Palanikannan1437 , are you still willing to contribute to this issue? We can keep this issue here, but will create doc issue in website repo next time. Thank you!

Hey, yes... was just waiting for the confirmation... these changes should be rather quick! 🚀

**Comment by Palanikannan1437** [comment]
@warren830 I've opened up a [PR](https://github.com/apache/incubator-devlake-website/pull/384) for these minor changes, please review it..thank you!
