### ISSUE TITLE
[Doc][Use Cases] Improve Navigation to discover Use-cases

### ISSUE THREAD

**Issue by JoshuaPoddoku** [apache/incubator-devlake#3960]
## Documentation Scope
The Navigation to the Use-cases in [official docs ](https://devlake.apache.org/docs/next/Overview/Introduction) can be simplified for improving discoverability. 

## Describe the Change
The Use-cases of DevLake can be also mentioned in main [ /docs ](https://devlake.apache.org/docs/next/Overview/Introduction) page along with [/LiveDemo](https://devlake.apache.org/livedemo)

### Proposed Improvement / Fix
<img width="1426" alt="Screenshot 2022-12-17 at 2 27 27 AM" src="https://user-images.githubusercontent.com/31725457/208189056-06280639-8c54-4cc6-a46f-40f47f0088a2.png">

- A New section as shown above can be created additionally to improve User experience 
- This hierarchy can also help to prioritise "Engineering Leads" over the rest

### Current Issue
<img width="1437" alt="Screenshot 2022-12-17 at 2 47 53 AM" src="https://user-images.githubusercontent.com/31725457/208191012-9b6f10ab-5d12-4163-a7d2-012dafe471a6.png">

-  At the moment, the Use-cases of DevLake can be found only on Live Demo Page after multiple steps

## Additional context
(P.S. It took me more than 5 mins to find DevLake use-cases via main page (and later realised they're documented in [Live Demo Page](https://devlake.apache.org/livedemo/EngineeringLeads/DORA))

**Comment by Palanikannan1437** [comment]
Hey @JoshuaPoddoku , would love to make these quick changes! Thank you!

**Comment by Palanikannan1437** [comment]
How should I move forward with this @Startrekzky @JoshuaPoddoku ?

**Comment by Startrekzky** [comment]
> How should I move forward with this @Startrekzky @JoshuaPoddoku ?

Hi @Palanikannan1437 @JoshuaPoddoku, my preference is as described as above, I prefer no changes or renaming `live demo` to `use cases`. It's not that hard

**Comment by JoshuaPoddoku** [comment]
Hi @Startrekzky apologies for delayed response. I think that completely makes sense. CC: @Palanikannan1437
