### ISSUE TITLE
[Bug][Module Name] run task failed with panic (github.com/apache/incubator-devlake/plugins/github/tasks.ExtractApiPrReviewComments.func1:81)Bug title 

### ISSUE THREAD

**Issue by julianolsdominguesTW** [apache/incubator-devlake#3973]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

When running a pipeline configured with just the GIt plugin and a Source Control Management Data Entities, on reaching task 15 of 41 it gives the following error:
run task failed with panic (github.com/apache/incubator-devlake/plugins/github/tasks.ExtractApiPrReviewComments.func1:81)

### What do you expect to happen

That it completes the execution of all tasks.

### How to reproduce

Create a pipeline with Github plugin
Select Source Control Management data entities
Save the pipeline and run.

### Anything else

Whenever I run old repositories with a lot of change history.

### Version

v0.14.2

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by mindlesscloud** [comment]
Could you please share more logs or the console's output with us?

**Comment by julianolsdominguesTW** [comment]
[pipeline.log](https://github.com/apache/incubator-devlake/files/10273877/pipeline.log)
[task-10-1-1-github.log](https://github.com/apache/incubator-devlake/files/10273878/task-10-1-1-github.log)
[task-11-1-2-gitextractor.log](https://github.com/apache/incubator-devlake/files/10273879/task-11-1-2-gitextractor.log)

the following are the execution logs

**Comment by mindlesscloud** [comment]
It was fixed in the PR https://github.com/apache/incubator-devlake/pull/3493, the upcoming v0.15.0 will ship with the fix.
