### ISSUE TITLE
[Bug][Refdiff] calculateIssuesDiff reported error

### ISSUE THREAD

**Issue by warren830** [apache/incubator-devlake#3977]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

Obviously, we didn't test after we finish coding:

time="2022-12-20 14:27:59" level=info msg="/opt/homebrew/Cellar/go/1.19.1/pkg/mod/gorm.io/gorm@v1.24.1-0.20221019064659-5dd2bb482755/callbacks.go:134 Error 1241: Operand should contain 2 column(s)
[2.746ms] [rows:-] SELECT commits_diffs.new_commit_sha as new_ref_commit_sha, commits_diffs.old_commit_sha as old_ref_commit_sha, 
                        pull_request_issues.issue_id as issue_id, pull_request_issues.issue_key as issue_number, 
                        new_refs.id as new_ref_id, old_refs.id as old_ref_id FROM `commits_diffs` left join (  
        select pull_request_id as id, commit_sha from pull_request_commits 
                        left join pull_requests p on pull_request_commits.pull_request_id = p.id
                        where p.base_repo_id = ''
                         union  
                        select id, merge_commit_sha as commit_sha from pull_requests where base_repo_id = '') _combine_pr 
                        on _combine_pr.commit_sha = commits_diffs.commit_sha left join pull_request_issues on pull_request_issues.pull_request_id = _combine_pr.id left join refs new_refs on new_refs.commit_sha = commits_diffs.new_commit_sha left join refs old_refs on old_refs.commit_sha = commits_diffs.old_commit_sha WHERE new_refs.repo_id = '' and pull_request_issues.issue_key > 0 and (new_refs.id, old_refs.id) in (NULL) ORDER BY new_refs.id ASC"
time="2022-12-20 14:27:59" level=error msg=" [pipeline service] [pipeline #1] [task #3] subtask calculateIssuesDiff ended unexpectedly
        Wraps: (2) Error 1241: Operand should contain 2 column(s)
        Wraps: (3) Error 1241: Operand should contain 2 column(s)
        Error types: (1) *hintdetail.withDetail (2) *hintdetail.withDetail (3) *mysql.MySQLError"
time="2022-12-20 14:27:59" level=error msg=" [task service] task failed
        caused by: Error running task 3.
        Wraps: (2) subtask calculateIssuesDiff ended unexpectedly
        Wraps: (3) Error 1241: Operand should contain 2 column(s)
        Wraps: (4) Error 1241: Operand should contain 2 column(s)
        Error types: (1) *hintdetail.withDetail (2) *hintdetail.withDetail (3) *hintdetail.withDetail (4) *mysql.MySQLError"
time="2022-12-20 14:27:59" level=error msg=" [pipeline service] [pipeline #1] run tasks failed
        caused by: Error running task 3."
time="2022-12-20 14:27:59" level=info msg=" [pipeline service] finish pipeline #1, now runningParallelLabels is []"

### What do you expect to happen

should run successfully.

### How to reproduce

trigger a github bp 1.0.0

### Version

main

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by abeizn** [comment]
The Tags Pattern input is not standardized, resulting in the program not getting the corresponding ref pair, but the error should be improved.

**Comment by warren830** [comment]
fixed by #4026
