### ISSUE TITLE
[Bug][framework] PIPELINE_MAX_PARALLEL is not working

### ISSUE THREAD

**Issue by klesh** [apache/incubator-devlake#3978]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

The total number of running pipelines stays at 1 not matter what value is given by `PIPELINE_MAX_PARALLEL`

![image](https://user-images.githubusercontent.com/61080/208603414-505948bc-2a8e-4959-a579-b8059c055ec7.png)

![image](https://user-images.githubusercontent.com/61080/208603348-19116fcd-333f-4f7b-8181-51a135f61270.png)

### What do you expect to happen

total number of running pipelines can reach up to the given `PIPELINE_MAX_PARALLEL`

### How to reproduce

1. set PIPELINE_MAX_PARALLEL in `.env` file or by EnvVar
2. create multiple pipelines
3. observe pipelines statuses from the database

### Version

main

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by likyh** [comment]
It looks cause by #3986 and fixed.
