### ISSUE TITLE
[Bug][config-ui] github token showing "Invalid" even if "Test Connection" succeeded

### ISSUE THREAD

**Issue by klesh** [apache/incubator-devlake#3980]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

![image](https://user-images.githubusercontent.com/61080/208610930-17a99603-278a-4b19-a551-dfdbb5a7112d.png)

### What do you expect to happen

my token should be showing my name

### How to reproduce

no sure

### Version

main

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by likyh** [comment]
duplicate to https://github.com/apache/incubator-devlake/issues/3942
