### ISSUE TITLE
[Bug][config-ui] Blueprint/Pipeline labels is missing from config-ui

### ISSUE THREAD

**Issue by klesh** [apache/incubator-devlake#3983]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

The API returns bp/pl with `labels`
![image](https://user-images.githubusercontent.com/61080/208619380-5bfeddcd-caa3-4ac8-9517-a9aa171487f8.png)

However it is nowhere to see these `labels` on UI except inspecting the JSON

### What do you expect to happen

being able to see `labels` on the config-ui

### How to reproduce

create bp/pl with labels

### Version

main

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by mintsweet** [comment]
How is the label created on bp and how to display it?

**Comment by klesh** [comment]
@mintsweet It is a field of the bp/pl from API.
![image](https://user-images.githubusercontent.com/61080/209032754-e4ee8e73-3bb5-4044-bd80-9ecc14e53fd5.png)
