### ISSUE TITLE
[Doc][GitHub] Explain to users the pros and cons of fine-grained tokens

### ISSUE THREAD

**Issue by hezyin** [apache/incubator-devlake#3998]
## Documentation Scope

GitHub recently introduced new [fine-grained tokens](https://github.blog/2022-10-18-introducing-fine-grained-personal-access-tokens-for-github) to enable granular control over permissions for developers. However, it's still in beta and doesn't support GraphQL API yet. As we're offering both the GraphQL and REST implementations of GitHub plugin, we need to explain to users that fine-grained tokens are only compatible with REST implementation. Once fine-grained tokens support GraphQL API, we'll completely switch over to GraphQL solution.

## Describe the Change

1. In Config-UI, when creating a new GitHub data connection, explain to users that GraphQL implementation is faster but not yet compatible with fine-grained tokens. If users want to use fine-grained tokens, they'll have to go with REST implementation for now.
2. In the documentation, explain the compatibility issue of fine-grained tokens and how to decide whether to use fine-grained tokens.

**Comment by Startrekzky** [comment]
Duplicated with #3869
