### ISSUE TITLE
[Bug][framework] Download log is not working

### ISSUE THREAD

**Issue by klesh** [apache/incubator-devlake#4011]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

![image](https://user-images.githubusercontent.com/61080/209052562-44842f7b-72c0-4dd6-a75e-4aea927bbc47.png)

### What do you expect to happen

being able to download log file

### How to reproduce

ui-my-svr02

### Version

main

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by likyh** [comment]
Same to #3948
