### ISSUE TITLE
[Bug][Jenkins] FullName,FullDisplayName,JobPath too long to save db

### ISSUE THREAD

**Issue by mappjzc** [apache/incubator-devlake#4053]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

A user triggered the error as follows:
`subtask extractApiBuilds ended unexpectedly caused by: error adding the result to batch caused by: Error 1406: Data too long for column 'full_display_name' at row 138`
![8483dd7a-4b7f-4c17-9279-b0f1867b06a1](https://user-images.githubusercontent.com/2921251/209782491-231c251d-8cc6-4b17-9e31-2d9945ff6743.jpeg)
As we see in the code, full_display_name has come from Jenkins API. and it limits by 255 in the tool layer.
![ea7b6b02-ed5b-4bcd-8a09-35d84f66ffc6](https://user-images.githubusercontent.com/2921251/209782497-e0331b6e-2e08-429a-966c-c0acc0ca82ba.jpeg)
in the domain layer. it will convert to the CICD name and limit by 255.
![c34fe7ae-6a33-45d8-86e0-f98dcb887e82](https://user-images.githubusercontent.com/2921251/209782504-3d0ea49d-16d2-4328-bbb5-9f85dc2e5802.jpeg)

Since `fullname` and `jobpath` have a high probability of being too long when FullDisplayName is too long, the above fields may also have the same problem and need to be dealt with.

### What do you expect to happen

Jenkins can get data success.

### How to reproduce

With a very deep and long path to save Jenkins jobs.

### Version

main

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by warren830** [comment]
After check, we can just drop fullDisplayName, this is resolved by #4066 4066
