### ISSUE TITLE
[Doc][Blog Page] The Blog Page can have a button linked to Submission Guideline

### ISSUE THREAD

**Issue by JoshuaPoddoku** [apache/incubator-devlake#4055]
## Documentation Scope
Currently there is only one way to find [contribution guideline](https://devlake.apache.org/community/MakingContributions/)  via the Call to Action / button in the [Team Page](https://devlake.apache.org/team). [Refer 1st Screenshot]

## Describe the Change
Now, there can a button added as showed in 2nd screenshot to make it more discoverable and easier to find [submission guidelines](https://devlake.apache.org/community/make-contribution/BlogSubmission) for contributing blogs. 

### Team Page
<img width="1058" alt="Screenshot 2022-12-29 at 12 14 35 AM" src="https://user-images.githubusercontent.com/31725457/209858531-47b9749e-6122-40ee-bea9-cd5530f92a56.png">

### Changes proposed in Blog Page
<img width="1169" alt="Screenshot 2022-12-29 at 12 20 23 AM" src="https://user-images.githubusercontent.com/31725457/209859221-e2b73a39-0824-48ab-b8d5-50b219c30be8.png">

- Button URL: https://devlake.apache.org/community/make-contribution/BlogSubmission

## Additional context
Nil

**Comment by khanjasir90** [comment]
@JoshuaPoddoku can i work on this!

**Comment by yumengwang03** [comment]
> @JoshuaPoddoku can i work on this!

Hi @khanjasir90, I have assigned this issue to you.

**Comment by kelvinparmar** [comment]
@yumengwang03 
Anyone work on this issue ? If not then please describe what I have to do in this issue?

**Comment by bhavyastar** [comment]
Hey @yumengwang03 , this is done on my side . Should I make pull request as I guess no one is working on this.

**Comment by bhavyastar** [comment]
> Hey @yumengwang03 , this is almost done on my side . Should I make pull request if no one is working on this?

**Comment by JoshuaPoddoku** [comment]
@bhavyastar you can make a PR!

**Comment by kelvinparmar** [comment]
@JoshuaPoddoku anyone working in this issue or not? 
I am interested in this issue

**Comment by JoshuaPoddoku** [comment]
@kelvinparmar we have made some changes to [Blog Page](https://devlake.apache.org/blogOverview)

Here's something you may work on:

1. Add a Contribute CTA Button and link it to[ Blog Submission Guidelines](https://devlake.apache.org/community/make-contribution/BlogSubmission) which is currently accessed in Community Page.
<img width="1435" alt="Screenshot 2023-01-31 at 1 09 39 PM" src="https://user-images.githubusercontent.com/31725457/215696621-0ccab2c3-9e0c-45be-abc5-8d04331c2069.png">

2. Suggested Improvement / Change in Blog Page:
a. Blog Submission can be made more accessible by adding CTA in [Blog Page](https://devlake.apache.org/blogOverview)
<img width="1436" alt="Screenshot 2023-01-31 at 12 45 02 PM" src="https://user-images.githubusercontent.com/31725457/215692537-1c0e2f4f-53f7-4e5c-8938-2dcd69b7349e.png">

cc: @Startrekzky

**Comment by kelvinparmar** [comment]
Hey @JoshuaPoddoku 
what are the changes i have to do in this please explain me in brief

**Comment by JoshuaPoddoku** [comment]
@yumengwang03 any thoughts on this?

**Comment by yumengwang03** [comment]
> @yumengwang03 any thoughts on this?

The PR has been merged but it didn't link to this issue. That's why this issue is not closed. The easiest way is just to check the website and see if the CTA is there. Thanks for the interest though.
