### ISSUE TITLE
[Bug][Plugin] Display the actual default API rate limit instead of 0 on the data connection page

### ISSUE THREAD

**Issue by Startrekzky** [apache/incubator-devlake#4068]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

When enabling the Rate Limit configuration in the connection page of any data source, the default value shows 0; while it's not.

![image](https://user-images.githubusercontent.com/14050754/209960614-7252d31c-9ebc-4739-bae1-d0203ba96a8c.png)

### What do you expect to happen

- [ ] Change the field name from `Rate Limit (per hour)` to `Fixed Rate Limit (per hour)`
- [ ] When the state of the toggle is `disabled`, show text `Use dynamic rate limit` on the right side
- [ ] When the state of the toggle is `enabled`, show default value in the input for each data source as below:
    - [ ] GitHub: default rate limit 4500 (Maximum 5000 per hour, see [details](https://docs.github.com/en/rest/overview/resources-in-the-rest-api?apiVersion=2022-11-28#rate-limiting))
    - [ ] GitLab: default rate limit 5,000 (Maximum 120,000 per hour, but many users encountered 429, see [details](https://docs.gitlab.com/ee/user/gitlab_com/index.html#gitlabcom-specific-rate-limits))
    - [ ] Jira: default rate limit 3,000 (Jira cloud uses dynamic rate limit, but someone tested out that currently, if calls from same IP address exceed 600 requests per 60 seconds, calls are blocked for 60 seconds. See [details](https://help.jiraalign.com/hc/en-us/articles/360045371954-Getting-started-with-the-REST-API-2-0))
    - [ ] Jenkins: can't find any doc, let's use the fallback option 10,000
    - [ ] TAPD: default rate limit 3,000 (max: 60req/1min, see [detail](https://o.tapd.cn/document/api-doc/API%E6%96%87%E6%A1%A3/API%E9%94%99%E8%AF%AF%E7%A0%81_cloud.html))
    - [ ] Zentao: can't find any doc, let's use the fallback option 10,000 

### How to reproduce

1. Go to the `connection` page
2. Click `add a connection`
3. Enable 'Rate Limit'

### Version

v0.14.2

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by mintsweet** [comment]
You should try with the latest code.

**Comment by Startrekzky** [comment]
> You should try with the latest code.

It's a bug found in v0.14.2 by a user. If it doesn't exist in the latest version, I'll close it after verification.

**Comment by likyh** [comment]
Some wording will changed. And a hardcode rateLimit will be added.
