### ISSUE TITLE
[Bug][GitLab] Error when running `collectGitCommits`

### ISSUE THREAD

**Issue by ZouLuDaiFeng** [apache/incubator-devlake#4102]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

<img width="1358" alt="img" src="https://user-images.githubusercontent.com/34237535/210522058-079f9567-c12f-4480-8935-723793cbc6c9.png">

This error occurred while collecting GitLab data.

### What do you expect to happen

Get the GitLab data.

### How to reproduce

Every time.

### Version

main

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Startrekzky** [comment]
Hi @ZouLuDaiFeng , what's your GitLab version? Which way did you install DevLake, Docker Compose, or Helm?
