### ISSUE TITLE
[Feature][Config UI] Allow users to customize the Grafana URL on the side bar of Config-UI 

### ISSUE THREAD

**Issue by felipesbs** [apache/incubator-devlake#4121]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

The link is hardcoded and i think that is a good idea  exported as env var,  for allow customize  the url path for another external instances of Grafana

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Startrekzky** [comment]
Thanks @felipesbs

**Comment by Startrekzky** [comment]
If so, 
- [ ] the BE should provide the config in `.env` and 
- [ ] the configuration needs to be added to doc(s)
