### ISSUE TITLE
[Feature][org] add api to query accounts data

### ISSUE THREAD

**Issue by leric** [apache/incubator-devlake#4130]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar feature requirement.

### Use case

To integrate with third-party system, and manage mapping of devlake accounts to users in third-party system.
Need an API to sync devlake accounts to third-party system.

### Description

Add an API to fetch all accounts incrementally, for third-party system to keep it's copy of accounts in sync with devlake.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by abeizn** [comment]
@leric @klesh look at this issue.

**Comment by Startrekzky** [comment]
Hi @leric , DevLake provides a [team configuration](https://devlake.apache.org/docs/next/UserManuals/TeamConfiguration) to unify accounts from different tools. Please let me know if it can meet your needs.
