### ISSUE TITLE
[Feature][UI] More robust validation of endpoint URL

### ISSUE THREAD

**Issue by keon94** [apache/incubator-devlake#4199]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar feature requirement.

### Use case

The "Endpoint URL" of plugins is something the users specify on the UI. The issue is, any working URL can be entered there as long as it is accessible via a GET request with the specified credentials; however, the same URL is used as the base endpoint for all queries made by blueprint executions. These can conflict with each other. For example, a user recently tried out _jenkins.mydomain.com/api/_ which passes validation but fails at execution. _jenkins.mydomain.com_ by itself works though.

### Description

The simplest solution will be to enforce no appendment of extra paths, e.g. /api/. This may have drawbacks though depending on the server's networking configuration. Feel free to suggest alternatives.

I think we furthermore should normalize the URL paths so that regardless of a "trailing slash" in the URL, the backend connections work. Right now, some connections will fail (despite passing the test) in the presence or absence of a /, which is a trival thing that can cause errors or strange behavior in the backend.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by hezyin** [comment]
Another case reported by a user in the Slack:  the user forgot to the trailing slash behind `https://api.github.com`, the connection test and git extractor handled this, but graphql plugin didn't and threw an error.

**Comment by keon94** [comment]
bump
