### ISSUE TITLE
[Bug][Dashboard] There're duplicated panels in the component and file-level metrics

### ISSUE THREAD

**Issue by ZouLuDaiFeng** [apache/incubator-devlake#4201]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened
The data of these two are exactly the same. One of the metrics should be the total number of modifications, which will not be affected by the time and file-path filters.
<img width="1379" alt="pic" src="https://user-images.githubusercontent.com/34237535/211974652-e31af8bb-5701-48bd-8bc2-82f61cc923f6.png">

### What do you expect to happen

I want to see the total number of modifications of all time and all files.

### How to reproduce

Go to the 'component and file-level metrics' dashboard.

### Version

main

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Startrekzky** [comment]
@ZouLuDaiFeng Thanks for raising this issue. I translated it into English according to the community rules. You can try firing issues in English next time with the help of translators.
