### ISSUE TITLE
[Feature][JIRA/DORA] Incident mapping

### ISSUE THREAD

**Issue by GSoul-hub** [apache/incubator-devlake#4217]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar feature requirement.

### Use case

As a QA lead, I want to be able to compare the Scrum team's efficiency using DORA.

### Description

At the moment, devlake allows mapping only issue type (e.g. "Incident" maps to the "Bug" of JIRA issue type).

Our current configuration of JIRA:
"**Bug sub-task**" (a.k.a. Sprint bug) - a bug is caught during the testing of a new feature (sprint), we can clearly associate it with the feature, so we create it as a sub-task under the feature's main task.
"**Bug**" (a.k.a. Regression/Release bug) - a bug is caught during regression testing before release to a production environment. Since it is not unequivocally clear which feature influenced the appearance of this bug - it is registered as a separate issue (not a sub-task).
"**Bug** with **JIRA label "production**" - a bug is caught in the production environment (by the team, clients, or customers).

As I understand, DORA should include only "production bugs", but devlake configuration supports only issue type and can't be separated by labels. In our cases - regression and production issues will be treated as DORA incidents which will not be correct (shouldn't include regression bugs).

We have multiple teams in our company and as a result, changing/agreeing to the jira configuration setup is quite a long process (e.g. introducing separate issue type only for production bugs).

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Startrekzky** [comment]
Thanks @GSoul-hub , I agree that the definition of BUG/INCIDENT needs to be more flexible. I'll think about it.

**Comment by GSoul-hub** [comment]
Any update?

**Comment by Startrekzky** [comment]
Hi @GSoul-hub , I'll give you an update by the end of this week.

**Comment by Startrekzky** [comment]
Hi @GSoul-hub , I haven't thought of a general solution for this. However, we started collecting Jira issue labels in v0.16, which will be released soon. This version brings a workaround for you by changing the SQL in the DORA dashboard. Please follow the steps below:

1. Go to the DORA dashboard, `Edit` the Median time to restore service
![image](https://user-images.githubusercontent.com/14050754/220827059-e4106476-0f9c-4a66-9dec-3e671a2201c1.png)


2. As you can see, the existing SQL to get incidents looks like below. See other examples SQL in [this doc](https://devlake.apache.org/zh/docs/next/Metrics/MTTR#how-is-it-calculated)

```
-- Metric 3: Median time to restore service 
with _incidents as (
-- get the incidents created within the selected time period in the top-right corner
	SELECT
	  cast(lead_time_minutes as signed) as lead_time_minutes
	FROM
	  issues i
	  join board_issues bi on [i.id](http://i.id/) = bi.issue_id
	  join boards b on bi.board_id = [b.id](http://b.id/)
	  join project_mapping pm on [b.id](http://b.id/) = pm.row_id
	WHERE
	  pm.project_name in ($project)
	  and i.type = 'INCIDENT'
	  and $__timeFilter(i.created_date)
),

...
```

You can update it based on your own definition by joining table [issue_labels](https://devlake.apache.org/zh/docs/DataModels/DevLakeDomainLayerSchema#issue_labels). For example,

```
-- Metric 3: Median time to restore service 
with _incidents as (
-- get the incidents created within the selected time period in the top-right corner
	SELECT
          -- please add a distinct here
          distinct [i.id](http://i.id/),
	  cast(lead_time_minutes as signed) as lead_time_minutes
	FROM
	  issues i
	  join board_issues bi on [i.id](http://i.id/) = bi.issue_id
	  join boards b on bi.board_id = [b.id](http://b.id/)
	  join project_mapping pm on [b.id](http://b.id/) = pm.row_id
          -- add a new join here
          left join issue_labels il on [i.id](http://i.id/) = il.issue_id
	WHERE
	  pm.project_name in ($project)
          -- change the definitions of incidents 
	  and i.type = 'bug'
          and il.name = 'production'
	  and $__timeFilter(i.created_date)
),

...
```

I hope it helps.

**Comment by GSoul-hub** [comment]
Hi @Startrekzky ,

I tried to replace SQL with your example, but getting "No data".

I searched for an issue (**Bug**) with the label **Production** in our jira project and tried to filter it in the issues table - exist.

As I understand, labels should be listed in the issue_labels table (yes?), but this table is empty.
![image](https://user-images.githubusercontent.com/3878492/221559549-dcc64241-7337-4dd8-ae10-0cb84763fac4.png)


So maybe we have a problem with jira import?

**Comment by Startrekzky** [comment]
Hi @GSoul-hub , the latest beta version [v0.16.0-beta2](https://github.com/apache/incubator-devlake/releases/tag/v0.16.0-beta2) is coming out. You can try it out.

**Comment by GSoul-hub** [comment]
Hi @Startrekzky.
I tried this one (slightly different than yours) and it seems to be working:
```
-- Metric 3: Median time to restore service 
with _incidents as (
-- get the incidents created within the selected time period in the top-right corner
	SELECT
	  distinct i.id,
		cast(lead_time_minutes as signed) as lead_time_minutes
	FROM
		issues i
	  join board_issues bi on i.id = bi.issue_id
	  join boards b on bi.board_id = b.id
	  join project_mapping pm on b.id = pm.row_id
	    left join issue_labels il on i.id = il.issue_id
	WHERE
	  pm.project_name in ($project)
		and i.type = 'INCIDENT'
		and il.label_name = 'Production'
		and $__timeFilter(i.created_date)
),
```
but I faced another problem - any panel related with deployments do not show any data (Gitlab). 

I looked through the queries (grafana->DORA) and database records and noticed that the queries expects the type to be "deployment".
```
and type = 'DEPLOYMENT'
and result = 'SUCCESS'
and environment = 'PRODUCTION'
```
in database records (in my case) this value is empty for production (do not know why)

I tried to comment/delete this line in queries, but it fixed only "Monthly deployments" panel. Other panel still doesn't work.

e.g. "Deployment Frequence" shows result as "Fewer than once per six months".


![image](https://user-images.githubusercontent.com/3878492/225845723-7385e8ec-e675-4f01-b41f-826cf89f993e.png)

**Comment by Startrekzky** [comment]
Hey @GSoul-hub , where did you get the deployment data from? You have to configure the transformation rule to extract production values from your CI job titles via RegEx.

This is a screenshot of the GitHub transformation page, I hope it makes sense.
![image](https://user-images.githubusercontent.com/14050754/227068694-bbd1a026-caf3-475f-a947-cc2f5db1a737.png)

**Comment by GSoul-hub** [comment]
@Startrekzky my configuration looks like this:
![image](https://user-images.githubusercontent.com/3878492/227147367-3313afa0-3e9a-420b-a9d2-36e0f525d0d6.png)

Database records for "deploy-production":
![image](https://user-images.githubusercontent.com/3878492/227147551-4568cacd-c211-4320-a318-f57fd9afbb12.png)

and for some reason, "deploy-staging" is marked:
![image](https://user-images.githubusercontent.com/3878492/227147870-0f25ae6d-4f05-47db-bf9f-394fb1049df5.png)

**Comment by Startrekzky** [comment]
@GSoul-hub  I see. This seems like a bug in GitLab's transformation logic. I'll take a look.

**Comment by klesh** [comment]
I believe that the `Deployment` regex should be `^deploy-`

**Comment by GSoul-hub** [comment]
Guys (@Startrekzky , @klesh ), I confused a bit.

In sum, our project has around ~17 jobs in the pipeline.
Some of them:
- deploy-staging
- deploy-production
- build-composer-tests
- phpunit
- behat
- phpstan
- phpcs
and so on

Production indicates - "deploy-production"
Staging indicates - "deploy-staging".

What's wrong here?

Job "deploy-production" - exist.
If I change to ^deploy- - it will pick up a lot of other stuff (like db migration, messenger workers and so on.) + not all of them will be deployments to production.

**Comment by Startrekzky** [comment]
Sorry @GSoul-hub , I made a mistake. Based on your job names, the 

- configuration for the `Deployment` field can be `(deploy-staging|deploy-production)`
- configuration for the `Production` field can be `deploy-production` or `production`

The two configurations extracted the values of fields `type` and `environment` separately in the table cicd_tasks. I hope I've made it clear this time.

**Comment by GSoul-hub** [comment]
@Startrekzky seems good now (at least in DB)! Thanks @klesh @Startrekzky!

But DORA dashboard still shows "Deployment Frequency" as "Fewer than once per month" :/

![image](https://user-images.githubusercontent.com/3878492/228456232-cb8e9962-af7a-44b9-a862-a06b27ba9728.png)

But in DB we have records
![image](https://user-images.githubusercontent.com/3878492/228457816-70c4fb4b-5341-4752-a727-209c2d353b38.png)

Any ideas?

**Comment by Startrekzky** [comment]
Hi @GSoul-hub , these are the filters to query `DEPLOYMENTs in a selected project`

![image](https://user-images.githubusercontent.com/14050754/228511284-a2dd8522-169d-49ab-b2eb-8676c0752343.png)

Based on your given screenshot of the DB, my guess is that many cicd_tasks(deployments) are filtered out by this condition
```
pm.project_name in ($project)
```
Maybe there aren't many cicd_tasks(deployments) in the project 'shipping-project-test' you selected in Grafana?

**Comment by GSoul-hub** [comment]
@Startrekzky 
There are 64 (production):
![image](https://user-images.githubusercontent.com/3878492/228751025-cf4822bb-a062-40d4-9685-be440a12ab32.png)

and look to the monthly deployments diagram (it shows some data):
![image](https://user-images.githubusercontent.com/3878492/228751279-99ac92dd-fc55-4565-81aa-0ed675487066.png)

**Comment by abeizn** [comment]
@GSoul-hub 
It is mainly to obtain a median by querying the records deployed within a specified time period, and then judge how often the deployment frequency is based on this median. 
From the data you provided, I think there are a lot of deployments in March, but few or no deployments in other months, so it leads to this result

**Comment by GSoul-hub** [comment]
@abeizn you are right!
I changed default value (last 6 month) to 3 month and it started to show.

Just Median Time To Restore service showing different stuff - one show less than one hour, another shows 0.
![image](https://user-images.githubusercontent.com/3878492/229053552-14e9f0b3-9ddd-4152-99cb-16656c45e49c.png)

First one:
```
-- Metric 3: Median time to restore service 
with _incidents as (
-- get the incidents created within the selected time period in the top-right corner
	SELECT
	  distinct i.id,
		cast(lead_time_minutes as signed) as lead_time_minutes
	FROM
		issues i
	  join board_issues bi on i.id = bi.issue_id
	  join boards b on bi.board_id = b.id
	  join project_mapping pm on b.id = pm.row_id
	    left join issue_labels il on i.id = il.issue_id
	WHERE
	  pm.project_name in ($project)
		and i.type = 'INCIDENT'
		and il.label_name = 'Production'
		and $__timeFilter(i.created_date)
),

_median_mttr_ranks as(
	SELECT *, percent_rank() over(order by lead_time_minutes) as ranks
	FROM _incidents
),

_median_mttr as(
	SELECT max(lead_time_minutes) as med_time_to_resolve
	FROM _median_mttr_ranks
	WHERE ranks <= 0.5
)

SELECT 
	case
		WHEN med_time_to_resolve < 60  then "Less than one hour"
    WHEN med_time_to_resolve < 24 * 60 then "Less than one Day"
    WHEN med_time_to_resolve < 7 * 24 * 60  then "Between one day and one week"
    WHEN med_time_to_resolve >= 7 * 24 * 60 then "More than one week"
    ELSE "N/A.Please check if you have collected deployments/incidents."
    END as med_time_to_resolve
FROM 
	_median_mttr
```

Another one (0 values):
```
-- Metric 3: median time to restore service - MTTR
with _incidents as (
-- get the incident count each month
	SELECT
	  distinct i.id,
		date_format(i.created_date,'%y/%m') as month,
		cast(lead_time_minutes as signed) as lead_time_minutes
	FROM
		issues i
	  join board_issues bi on i.id = bi.issue_id
	  join boards b on bi.board_id = b.id
	  join project_mapping pm on b.id = pm.row_id
	  	    left join issue_labels il on i.id = il.issue_id
	WHERE
	  pm.project_name in ($project)
		and i.type = 'INCIDENT'
		and il.label_name = 'Production'
		and i.lead_time_minutes is not null
),

_find_median_mttr_each_month_ranks as(
	SELECT *, percent_rank() over(PARTITION BY month order by lead_time_minutes) as ranks
	FROM _incidents
),

_find_median_mttr_each_month as(
	SELECT month, max(lead_time_minutes) as lead_time_minutes
	FROM _find_median_mttr_each_month_ranks
	WHERE ranks <= 0.5
	GROUP BY month
),

_find_mttr_rank_each_month as (
	SELECT
		*,
		rank() over(PARTITION BY month ORDER BY lead_time_minutes) as _rank 
	FROM
		_find_median_mttr_each_month
),

_mttr as (
	SELECT
		month,
		lead_time_minutes as med_time_to_resolve
	from _find_mttr_rank_each_month
	WHERE _rank = 1
),

_calendar_months as(
-- deal with the month with no incidents
	SELECT date_format(CAST((SYSDATE()-INTERVAL (month_index) MONTH) AS date), '%y/%m') as month
	FROM ( SELECT 0 month_index
			UNION ALL SELECT   1  UNION ALL SELECT   2 UNION ALL SELECT   3
			UNION ALL SELECT   4  UNION ALL SELECT   5 UNION ALL SELECT   6
			UNION ALL SELECT   7  UNION ALL SELECT   8 UNION ALL SELECT   9
			UNION ALL SELECT   10 UNION ALL SELECT  11
		) month_index
	WHERE (SYSDATE()-INTERVAL (month_index) MONTH) > SYSDATE()-INTERVAL 6 MONTH	
)

SELECT 
	cm.month,
	case 
		when m.med_time_to_resolve is null then 0 
		else m.med_time_to_resolve/60 end as med_time_to_resolve_in_hour
FROM 
	_calendar_months cm
	left join _mttr m on cm.month = m.month
ORDER BY 1
```

**Comment by abeizn** [comment]
Get, I will close this issue, any other questions are welcome.
