### ISSUE TITLE
[Feature][PagerDuty] Replace tap-pagerduty dependency as it's licensed under AGPLv3

### ISSUE THREAD

**Issue by hezyin** [apache/incubator-devlake#4220]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar feature requirement.

### Use case

Previously, our PagerDuty plugin used [singer-io/tap-pagerduty](https://github.com/singer-io/tap-pagerduty) for the collection step. However, we found out that tap is licensed under AGPLv3 from the recent release process of v0.15, which is incompatible with Apache 2.0. Due to that, we have removed the tap from v0.15 release and will need to fix our PagerDuty plugin in v0.16 release.

I'll open a pull request to update our doc site regarding PagerDuty plugin status.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by keon94** [comment]
The collector will have to be rewritten to use the raw pagerduty API to fetch data, like our other plugins.

**Comment by Startrekzky** [comment]
Hi @keon94, is PagerDuty already rewritten in v0.16 or not? You can close the issue if it doesn't exist.

**Comment by keon94** [comment]
> Hi @keon94, is PagerDuty already rewritten in v0.16 or not? You can close the issue if it doesn't exist.

It has, but it's outdated now as it's not compatible with v200. Here's the PR: https://github.com/apache/incubator-devlake/pull/4248
