### ISSUE TITLE
[Feature][Plugin] Support ServiceNow  as an incident management system

### ISSUE THREAD

**Issue by Startrekzky** [apache/incubator-devlake#4234]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar feature requirement.

### Use case

A ServiceNow plugin is most useful for DevLake's support for DORA metrics.

[ServiceNow](https://www.servicenow.com/) is one of the most popular issue management tools in the industry. DevLake would help more teams implement the DORA framework if it has a plugin that can pull incident data from ServiceNow.

![image](https://user-images.githubusercontent.com/14050754/213149001-f5a8bc5b-ae04-4e3e-b198-e1615dc62f8e.png)

### Description

The most important entity from ServiceNow is `incident`. A ServiceNow incident can be triggered automatically via integration with monitoring service and API, or manually via web app and mobile app. See below for an incomprehensive list of incident attributes we're interested in:

- Number: Unique system-generated incident number.
- State: see [possible values](https://docs.servicenow.com/bundle/tokyo-it-service-management/page/product/incident-management/concept/c_IncidentManagementStateModel.html)
- Service
- Caller: User who contacted you with an issue.
- Assigned to
- Title
- Urgency
- Priority
- Short Description
- When an incident is triggered, when it's acknowledged, and when it's resolved
- See ServiceNow doc on incidents for details: https://docs.servicenow.com/en-US/bundle/tokyo-it-service-management/page/product/incident-management/task/create-an-incident.html

### DORA Support
IIRC, DevLake's DORA plugin uses issues of incident type to calculate DORA metrics, so let's see if we can map ServiceNow 's incident to the issue entity in DevLake's domain layer.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Suhasr76** [comment]
Yeah, it would be very helpful as many organizations your ServiceNow for incident management

**Comment by FaizanSh** [comment]
Yeah, it would be very helpful as many organizations have ServiceNow for incident management. We get tons of insight about the issues an organization is facing.

**Comment by dc-seena** [comment]
Noticed ServiceNow support was listed as Planned on the docs below, but this thread seems dead, any ideas if there will be integration options in future? https://devlake.apache.org/docs/Overview/Roadmap#feature-breakdown

**Comment by klesh** [comment]
Seems like the page has not been updated for quite a while 😂

**Comment by JACONDE** [comment]
Does anybody now the status for this plugin?

**Comment by klesh** [comment]
@JACONDE no one is working on it so far.

**Comment by albusshirazi** [comment]
Noticed ServiceNow support was listed as Planned on the docs below, but this thread seems dead, any ideas if there will be integration options in future? https://devlake.apache.org/docs/Overview/Roadmap#feature-breakdown

THIS ISSUE SHOULD NOT BE STALED!
