### ISSUE TITLE
Helm Chart Grafana Issue

### ISSUE THREAD

**Issue by shreysway** [apache/incubator-devlake#4235]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

Hello I have commented grafana in helm chart then also grafana is getting installed

### What do you expect to happen

Grafana should not get installed

### How to reproduce

you can comment grafana dashboard values
<img width="502" alt="image" src="https://user-images.githubusercontent.com/64957429/213166314-3fb6e72f-499a-438e-9e34-e3cfa63ce554.png">
<img width="1021" alt="image" src="https://user-images.githubusercontent.com/64957429/213166384-ee489eff-b80a-4559-b8e9-c36ff27b16ca.png">

### Version

main

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by shreysway** [comment]
Hey any updates for the same.

**Comment by keon94** [comment]
Hello @shreysway. What if you just completely remove the lines for grafana? Does it still get installed?

**Comment by shreysway** [comment]
Yaa thats the issue only.

**Comment by keon94** [comment]
Can you check in your editor that those lines don't have any hidden characters?

**Comment by shreysway** [comment]
yaa they don't have any

**Comment by Startrekzky** [comment]
Hi @matrixji , can you help look at this problem?

**Comment by matrixji** [comment]
@shreysway do you want to ignore the installation of bundled grafana dashboard from helm?

Comment out the grafana's config sections in values.yaml will **NOT** stop delpoy grafana, it just removes the configurations.

I think we need to wait for https://github.com/apache/incubator-devlake-helm-chart/issues/57

For that delivery, if you want to remove grafana installation from the helm, currently you may try removing the grafana-related Kubernetes resource (services, configmaps, deployments, etc.) from the template directory. As we organize resources by type, so comment out the grafana is not an easy job.

**Comment by matrixji** [comment]
https://github.com/apache/incubator-devlake-helm-chart/pull/94 almost merged, 0.16.0 will have `optional grafana` feature.

**Comment by Startrekzky** [comment]
What's the status of this issue, can I close it? @matrixji

**Comment by matrixji** [comment]
As we now have provided an external Grafana option by https://github.com/apache/incubator-devlake-helm-chart/issues/57
I think we could close this issue.
