### ISSUE TITLE
[Feature][Framework] Allow extractor and convertor to support incremental update

### ISSUE THREAD

**Issue by warren830** [apache/incubator-devlake#4247]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar feature requirement.

### Use case

As we have `_devlake_collector_latest_state` to indicate the newest updated data, we can also use this to let extractor and convertor to support incremental updates

### Description

before we executing extractor and convertor, we can use `_devlake_collector_latest_state.latest_success_start` to filter data

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by klesh** [comment]
I think this is a good idea!

**Comment by klesh** [comment]
However, simply depending on the `_devlake_collector_latest_state.latest_success_start` is not reliable.

## The following factors must be considered:

1. The `extractors` and `converters` are working under the `delete and insert` principle without any knowledge of its preceding `subtasks`
2. Users might collect data multiple times without `extraction` or `conversion` with the current design.
3. The relationship between `collectors`, `extractors`, and `converters` are **NOT** 1:1:1. remember that some `subtasks` might produce multiple kinds of records, for example, the `jira issue extractor` produces `issues` and `changelog` and others. vice-verse, a set of records of a specific scope might come from multiple upstream `subtasks`, for example, `changelog` could come from `issue collector` or `changelog collector`. The dependency could be quite messy if we depend only on the `_devlake_collector_latest_state`

In summary, it is hard and unreliable to distinguish `Incremental` and `FullRefresh` by examining the state of the preceding `collector`.

## Proposal

I think it would easier for us to track the state of  `subtasks` (`extractors` and `converters`) without introducing dependency.

1. Each `extractor` or `converter` should have its own state
2. The `ExtractorHelper` and `ConverterHelper` should support the `IsIncremental` option and determine whether to delete the existing records or not, just like the `CollectorHelper`. However, the `IsIncremental` conditions are different.
3. The `IsIncremental` for  `ExtractorHelper` and `ConverterHelper`  can be done by simply comparing its `latest_success_start` with the `max(created_at)` (the `created_at` represents the time of the record being created in the database)
