### ISSUE TITLE
[Refactor][Framework] Remove redundant collector state table

### ISSUE THREAD

**Issue by keon94** [apache/incubator-devlake#4249]
We have two tables for the sake of tracking collector state: **_devlake_collector_state** and **_devlake_collector_latest_state**. This is redundant and confusing. 

![image](https://user-images.githubusercontent.com/25063936/214175378-5d4e70b7-2379-420d-885b-9c3ba85fb383.png)
![image](https://user-images.githubusercontent.com/25063936/214175427-39fb6c6b-19e4-4aab-b89e-5e18d9ddbf40.png)

We should just have one table. I vote for **_devlake_collector_latest_state** as it's being actively used, however add a column to store JSON values for any data that doesn't fit the other columns (think singer-tap states), as we do in **_devlake_collector_state**.

**Comment by klesh** [comment]
@keon94 Alright, I agree with you except for the JSON column, I would prefer the "Ockham's Razor".
Why there is a `_devlake_collector_state` table and nowhere is using it? Did we create it because we thought "Someday we gonna need it"?

**Comment by keon94** [comment]
@klesh I added that table when I worked on the singer spec ticket. That code uses it to store and retrieve state values during collection. The values are arbitrary JSONs (because that's what the spec uses) which is why I kept it generic like that.

**Comment by klesh** [comment]
@keon94 I see, will it still be used in v0.16?

**Comment by keon94** [comment]
@klesh No, because only Pagerduty was using it which I am reworking in https://github.com/apache/incubator-devlake/pull/4248 because of the licensing problem. But the existing singer-tap framework relies on this table nonetheless.

**Comment by klesh** [comment]
> @klesh Not actively, because only Pagerduty was technically using it, but I am reworking it in #4248 because of the licensing problem. But the existing singer-tap framework relies on this table nonetheless.

I see, ok, I agree that we should add the column.

**Comment by keon94** [comment]
I can probably take this one later this week.

**Comment by keon94** [comment]
After rethinking this, considering how largely the framework has changed since I initially logged this issue, I don't think it makes sense to try to use the same table for Singer taps. I think the better thing to do will be to simply rename this table to something more specific, like _devlake_collector_tap_state, and leave the other one alone
