### ISSUE TITLE
[Bug][Config-UI] Vulnerabilities in Image 

### ISSUE THREAD

**Issue by lavakush07** [apache/incubator-devlake#4250]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

- While I'm trying to **setup the Config-UI**. I am facing the vulnerabilities in the image. 
![image](https://user-images.githubusercontent.com/70131581/214232219-a545bfc6-b33c-487b-98a0-1acbcb1efdd7.png)
![image](https://user-images.githubusercontent.com/70131581/214232281-01388a7e-be79-4c24-944c-952ba48488c5.png)

### What do you expect to happen

Ease in setting up of config-UI.

### How to reproduce

While I'm running it on localhost:4000. It is showing me the following error.

### Version

main

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by keon94** [comment]
The vulnerabilities and the error 500 are two different issues. I suggest you file another issue for the error you're seeing and attaching container logs to it.

**Comment by lavakush07** [comment]
Okay , Surely Will do it.

**Comment by matrixji** [comment]
For the security issue, currently, we're using nginxinc/nginx-unprivileged:1.21 as base image for config-ui, as nginx is stable enough, I guess we could use nginxinc/nginx-unprivileged:latest for get latest security updates from the upstream.

**Comment by matrixji** [comment]
> For the security issue, currently, we're using nginxinc/nginx-unprivileged:1.21 as base image for config-ui, as nginx is stable enough, I guess we could use nginxinc/nginx-unprivileged:latest for get latest security updates from the upstream.

Still, use nginxinc/nginx-unprivileged:latest tag in code repo is not a good practice, maybe we could introducing a checklist in release stage to ensure we're including the latest security updates from upstream at that moment.

**Comment by lavakush07** [comment]
> > For the security issue, currently, we're using nginxinc/nginx-unprivileged:1.21 as base image for config-ui, as nginx is stable enough, I guess we could use nginxinc/nginx-unprivileged:latest for get latest security updates from the upstream.
> 
> Still, use nginxinc/nginx-unprivileged:latest tag in code repo is not a good practice, maybe we could introducing a checklist in release stage to ensure we're including the latest security updates from upstream at that moment.

Got it 👍

**Comment by hezyin** [comment]
Hi @lavakush07, I tried v0.15.0-rc4 with docker-compose and everything works fine. Do you think you could provide details steps for reproducing the  Config-UI issue? Thanks!

**Comment by hezyin** [comment]
Hi @lavakush07, I'm gonna close this issue due to inactivity. But feel free to open a new issue if you need help.
