### ISSUE TITLE
[Doc][Config UI] Improve End-point URL description

### ISSUE THREAD

**Issue by SuperAayush** [apache/incubator-devlake#4251]
## Documentation Scope
When a new user tries to create a dashboard using DevLake, the user has to add a connection that asks an Endpoint URL to be mentioned as shown in the below image:
<img width="957" alt="Screenshot 2023-01-21 at 2 33 13 PM" src="https://user-images.githubusercontent.com/78820926/214392391-7d0c53bd-b5f5-4820-b232-980b52898429.png">

This URL value is misunderstood by new users with that of the project repository URL of which they want to create a dashboard.

## Describe the Change
A single-line description can be added to clarify the type of input required as mentioned in the docs here: https://devlake.apache.org/docs/UserManuals/ConfigUI/GitHub

The description that can be added: "This should be a valid REST API endpoint, eg. https://api.github.com/. The URL should end with /."

## Additional context
The same things can be done for every connection such as Jenkins, GitLab, JIRA, etc.

**Comment by kelvinparmar** [comment]
Hey @SuperAayush what changes have to do please explain me this so I will try to change it

**Comment by Startrekzky** [comment]
This place has been refined in v0.16
