### ISSUE TITLE
[Bug][Grafana] Dashboard charts bug out with "No Data" and SQL errors when there's no data

### ISSUE THREAD

**Issue by keon94** [apache/incubator-devlake#4252]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

![image](https://user-images.githubusercontent.com/25063936/214647303-2314ebfe-bf32-447c-b5f5-605ae7948b6f.png)

When no data is collected it is expected that we have "No Data" for the charts, but with current behavior the queries seem to rely on existing data in the tables, and so they error out with SQL (e.g. code 1064) errors when they're absent. This gives the end user a false-positive alarm.

### What do you expect to happen

Queries need to be written defensively and handle situations when data is absent so that we don't end up with a crashing query. Think defensive programming vs. throwing exceptions.

### How to reproduce

Without running any blueprints for a dashboard, access that dashboard and you'll see this happening assuming that dashboard has a problematic query. (e.g. Github, Gitlab, Dora, etc). Some of the demo ones are okay on the other hand.

### Version

v0.15.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Startrekzky** [comment]
This is due to the 'All' filter on the top left corner. I haven't thought of a perfect solution to address this problem.

**Comment by Startrekzky** [comment]
It's Grafana's design, I cannot fix it unless Grafana has updates.

**Comment by Startrekzky** [comment]
@keon94  I just found out Grafana 9+ has solved this problem, changing the display from `no data` to `no value`. https://github.com/grafana/grafana/pull/47675
