### ISSUE TITLE
[Feature][Plugins] Add a plugin for Redmine.

### ISSUE THREAD

**Issue by Akitata** [apache/incubator-devlake#4278]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar feature requirement.

### Use case

I want developing a plugin for [Radmine](https://github.com/redmine/redmine), which is similar to Jira.

The feature include data analysis of issue, project and account.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by warren830** [comment]
Hi Akitata, can you join our slack: https://join.slack.com/t/devlake-io/shared_invite/zt-17b6vuvps-x98pqseoUagM7EAmKC82xQ
Then we can discuss how to implement this feature

**Comment by Startrekzky** [comment]
Hi @Akitata , what's the progress of this issue?

**Comment by zhangsm2020** [comment]
I also need the redmine plugin.

**Comment by realmyy** [comment]
I also need the redmine plugin
