### ISSUE TITLE
[Refactor][backend/core] Show direct error message for users.

### ISSUE THREAD

**Issue by likyh** [apache/incubator-devlake#4282]
## What and why to refactor
```
caused by: Error running task 16998. (400)
        Wraps: (2) error preparing task data for jenkins (400)
        Wraps: (3) fail to get transformationRule (400)
        Wraps: (4) record not found
```
Now error messages are not readable for users. Because it's difficult to write more user-friendly tips in the backend. The detail message have been wrapped.

## Describe the solution you'd like
show the inner message to users.
```
caused by: fail to get transformationRule  ← show for users
        Calls: (1) Error running task 16998. (400)
        Calls: (2) error preparing task data for jenkins (400)
        Calls: (3) -
        Calls: (4) record not found
```
Split `wrap` to 2 functions `wrap` and `as`. use `as` to recognize which error is. use `wrap` to record where errors pass by.

**Comment by Startrekzky** [comment]
> This sounds like the "user error" vs "developer error" feature I proposely several months ago.

Do you mean this one https://github.com/apache/incubator-devlake/issues/3068? Maybe we can close one.

**Comment by keon94** [comment]
@Startrekzky No, we only discussed it verbally. In the original design of the current error handling framework I was distinguishing between "user-errors" (which would make it to the UI and backend logs) and "dev-errors" (only in backend logs). It sounds like this is a use case for that.

**Comment by Startrekzky** [comment]
This is a long-existing issue that needs to be tackled in the future.
