### ISSUE TITLE
[Bug][Bitbucket] Error when running `collectApiPullRequestCommits`

### ISSUE THREAD

**Issue by jrflga** [apache/incubator-devlake#4285]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

When I run `collectApiPullRequestCommits` with Bitbucket plugin the API that throws an error (Bad Request) when start to fetching the PR API.
![image](https://user-images.githubusercontent.com/3507471/215853537-54ad5b45-cc2a-4b41-8c88-cc8bd2913bb6.png)
![image](https://user-images.githubusercontent.com/3507471/215853723-c0a34056-8611-4274-825d-cdf59c6cbb23.png)

### What do you expect to happen

Fetching on Bitbucket need to run without throwing an error.

### How to reproduce

Configure a Bitbucket connection and run a pipeline with any repo.

### Anything else

I think it's a problem with params that Bitbucket API expect to do pagination. 

### Version

main

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by klesh** [comment]
@jrflga thanks for the reporting. Will look into it ASAP
