### ISSUE TITLE
[Doc][Deployment] How to deploy DevLake in a production setting?

### ISSUE THREAD

**Issue by hezyin** [apache/incubator-devlake#4286]
## Documentation Scope

Users have been asking if we can provide some guidance in deploying DevLake in the production setting, e.g., what practices do we recommend?

1. Replace the MySQL container with a cloud-hosted database like AWS RDS
2. Replace the Grafana container with user's own Grafana instance

**Comment by hezyin** [comment]
Bump

**Comment by Startrekzky** [comment]
Hi @warren830 , can you help add this part to the following docs?
- https://devlake.apache.org/docs/next/GettingStarted/DockerComposeSetup#prerequisites
- https://devlake.apache.org/docs/next/GettingStarted/HelmSetup

**Comment by matrixji** [comment]
for the helm part: attach [incubator-devlake-helm-chart#57](https://github.com/apache/incubator-devlake-helm-chart/issues/57)
I'll do the PR to "support optional grafana with helm install" recently.

**Comment by Startrekzky** [comment]
Hi @matrixji , can you add the doc of using external Grafana in the [HelmSetup doc](https://devlake.apache.org/docs/GettingStarted/HelmSetup/#faq) in the next/v0.17/v0.16 versions? Please refer to the docs here https://devlake.apache.org/docs/GettingStarted/DockerComposeSetup/#can-i-use-an-external-grafana-instead-of-running-grafana-in-docker

**Comment by matrixji** [comment]
> Hi @matrixji , can you add the doc of using external Grafana in the [HelmSetup doc](https://devlake.apache.org/docs/GettingStarted/HelmSetup/#faq) in the next/v0.17/v0.16 versions? Please refer to [this doc](https://devlake.apache.org/docs/GettingStarted/DockerComposeSetup/#can-i-use-an-external-grafana-instead-of-running-grafana-in-docker)

Sure, I'll provide PR on the website repo.

**Comment by joshuabezaleel** [comment]
Hi @matrixji @Startrekzky is there anything that needs to be setup again for using external Grafana?

I've put `grafana.enabled` to `false` and `grafana.external.url` to the external Grafana and while the redirection from the UI is there, the Dashboard that should be created and populated (it's working if I don't use external Grafana) can't be found. 

How is Devlake being able to be authenticated to the Grafana? Currently it's behind Google SSO.

Thank you!
