### ISSUE TITLE
[Doc][Getting Started] Install via Docker Compose

### ISSUE THREAD

**Issue by BaoBaoGitHub** [apache/incubator-devlake#4290]
## Documentation Scope 
I am installing Devlake via  《Getting Started》->《Install via Docker Compose》.
I installed latested Docker Compose and wished to lauch Devlake.

## Describe the Change
The lauch command should be `docker compose up -d` rather than `docker compose up -d`.

## Screenshots
![image](https://user-images.githubusercontent.com/68647811/216094237-96afb797-6ebd-4cc5-9afd-c144727d77f6.png)

**Comment by BaoBaoGitHub** [comment]
> 

Of course.
Should lauch command be `docker compose up -d` rather than `docker-compose up -d` when using latested Docker Compose?
Thank you!

**Comment by JoshuaPoddoku** [comment]
@lavakush07 https://github.com/apache/incubator-devlake-website/blob/main/docs/GettingStarted/DockerComposeSetup.md

Here's the page!
