### ISSUE TITLE
Getting stream timeout error in most dashboards and huge time in querying.

### ISSUE THREAD

**Issue by ibrahimejaz** [apache/incubator-devlake#4291]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

Hi,
We've tried using this and happen to see a huge latency in querying the results especially under DORA dashboard and as result ended up in stream timeout error, we've increased the limits in the grafana.ini file.
Also able to see huge spike in the mysql process which kills the intances, so de-coupled the Database source to Cloud SQL and connected while querying from there as well there is huge spike in latency and also mysql instances received 100 CPU usage and stop responding we've even increased our mysql size to 12 core CPU but still there is 100% CPU usage, is there any known issue for the same? it would be really great if we could get any help for the same. Thanks much.

### What do you expect to happen

Well it's a query from sql and it supposed be getting it response but its taking delay and going into stream timeout in almost all cases.

### How to reproduce

While running DORA metrics dashboard mostly. 

### Version

v0.15.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by klesh** [comment]
@ibrahimejaz thank you very much for reporting the issue, this is indeed a problem.
Do you have any clue which Charts/SQLs might cause the problem?

**Comment by ibrahimejaz** [comment]
@klesh Can see happening in "Overall DORA Metrics" and "Deployment Frequency" Charts, if thats specific you're asking about. Also using 16 Core machine with 64GB Memory and mostly seeing the same.

**Comment by ibrahimejaz** [comment]
Also getting more error with 504 Gateway Time-out.https://share.anysnap.app/fXbw9qrSGh3B

**Comment by abeizn** [comment]
> Also getting more error with 504 Gateway Time-out.https://share.anysnap.app/fXbw9qrSGh3B
@ibrahimejaz 
The v0.15.0-rc5 version will alleviate, you can try. In next version, we will consider how to further optimize.

**Comment by klesh** [comment]
> @klesh Can see happening in "Overall DORA Metrics" and "Deployment Frequency" Charts, if thats specific you're asking about. Also using 16 Core machine with 64GB Memory and mostly seeing the same.

I see, please try replacing the dashboard with the one from @abeizn 's pr #4311 and see if the problem solved, thanks in advanced. 😊

**Comment by ibrahimejaz** [comment]
It's now working like a charm. Thanks.
