### ISSUE TITLE
Adding the 2min demo video on DevLake main website

### ISSUE THREAD

**Issue by lavakush07** [apache/incubator-devlake#4293]
## What and why to refactor
What are you trying to refactor? Why should it be refactored now?
- We can have the **setting up of DevLake with in 2 minutes (Video)** just like this one on the main website. This would make easy for many of the beginners who are looking to contribute.
Because Ease in setting up of project is directly proportional to gaining more community members and active contributors to the project.
![image](https://user-images.githubusercontent.com/70131581/216236828-0398961a-083b-4e81-8f85-0964122268c6.png)

## Describe the solution you'd like
How to refactor?
- By adding up a demo video 

## Related issues
Please link any other

**Comment by klesh** [comment]
+1

**Comment by Startrekzky** [comment]
What's the difference between this and Gitpod?
