### ISSUE TITLE
[Feature][PagerDuty] Upgrade plugin to support blueprint API v2

### ISSUE THREAD

**Issue by hezyin** [apache/incubator-devlake#4303]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar feature requirement.

### Use case

We'd like to upgrade the PagerDuty plugin to support blueprint API v2 so it can be used together with `project` for DORA calculation.

We want to be able to invoke PagerDuty plugin and DORA plugin via API before its Config-UI support is ready.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Startrekzky** [comment]
Hi @hezyin . Who is working on this issue by the way? I don't think it's planned in v0.16?

**Comment by hezyin** [comment]
@Startrekzky I just moved it to v0.17

**Comment by keon94** [comment]
PR: https://github.com/apache/incubator-devlake/issues/4220
