### ISSUE TITLE
[Feature][Jira] Collect data in jira development panel

### ISSUE THREAD

**Issue by narrowizard** [apache/incubator-devlake#4304]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar feature requirement.

### Use case

In our jira use case, we are not link commit to issue by remotelinks, but link it by development panel with a jira plugin.  
We want data in development panel, can you collect it?  
The most useful data is the related commits. And it's better if collecting branches, pull requests and builds.

### data in development panel
![image](https://user-images.githubusercontent.com/11383928/216491656-8b289581-4d97-46d2-acf4-984bfcf3ef54.png)  
![image](https://user-images.githubusercontent.com/11383928/216491503-fb2fa025-3766-4654-a5a7-038f919b58aa.png)

### Description

Now we can get commits related to issue in `issue_commits` entity.  
In jira data source, `issue_commits` is resolved by `_tool_jira_remotelinks` with a configuration of `remotelinkCommitShaPattern`.  
We have another way to link issue commits, can you support it?

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by narrowizard** [comment]
I find a non-public api for development data. But I'm not sure if all versions support it.  

## reference
- https://community.atlassian.com/t5/Jira-questions/Jira-REST-API-documentation-for-rest-dev-status-latest/qaq-p/1158692
- [api docs](https://jira.atlassian.com/browse/JSWCLOUD-16901)
- https://jira.atlassian.com/browse/JSWSERVER-15768

**Comment by abeizn** [comment]
@Startrekzky @klesh take a look at it?

**Comment by klesh** [comment]
Keep in mind, both  Cloud and Server/DataCenter(7.17.13) must be supported if we are to support the collection
