### ISSUE TITLE
[Bug][Customize] Cannot resolve RawDataTable and RawDataParams to TaskData

### ISSUE THREAD

**Issue by narrowizard** [apache/incubator-devlake#4315]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

Lack of mapstructure tag for `RawDataTable` and `RawDataParams` in `MappingRules` of customize.tasks, these two fields cannot be decoded when calling `mapstructure.Decode`

## Code snippets
https://github.com/apache/incubator-devlake/blob/25c68b456d0f89038b9ab70cb336156e70fff982/backend/plugins/customize/tasks/task_data.go#L20-L25
https://github.com/apache/incubator-devlake/blob/25c68b456d0f89038b9ab70cb336156e70fff982/backend/plugins/customize/impl/impl.go#L62

### What do you expect to happen

Nope

### How to reproduce

Nope

### Version

main

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by mindlesscloud** [comment]
There is no need to add the `mapstructure` struct tag, however, the json tags should be changed to `json:"rawDataTable"` and `json:"rawDataParams"`

**Comment by narrowizard** [comment]
Finally, It becauses a document bug. According https://devlake.apache.org/docs/Plugins/customize/ , the implement is satisfaied with it.
