### ISSUE TITLE
[Bug][JIRA] connection refused 

### ISSUE THREAD

**Issue by bsownda** [apache/incubator-devlake#4327]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

I am getting connection issue while connecting my organization JIRA account using config-ui portal. The status of Jira config indicates in portal "disconnected"  Is there any way to disable ssl verify in devlake and config-ui container?

### What do you expect to happen

I want JIRA metrics from Apache devlake platform in Mac.

### How to reproduce

Yes. I can

### Version

main

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Startrekzky** [comment]
What's the DevLake and Jira version you're on? Can you share your connection page with the error message with us?

**Comment by mindlesscloud** [comment]
@bsownda  By setting `IN_SECURE_SKIP_VERIFY=true` in the `.env` file, you cloud disable the SSL certificate verification

**Comment by klesh** [comment]
This is documented as well https://devlake.apache.org/docs/Troubleshooting/Configuration#failed-to-collect-data-from-the-server-with-a-self-signed-certificate

**Comment by bsownda** [comment]
> What's the DevLake and Jira version you're on? Can you share your connection page with the error message with us?

I'm using jira version - v8.22.6#822006 and devlake version - latest docker-compose image 

Error: connection test Failed. error requesting https://dns.com/rest/


Devlake log:
Wraps: (4) context deadline exceeded (Client.Timeout exceeded while awiting headers)
Error types: (1) *hintdetail.withDetail (2) *.hintdetail (3) * url.Error (4) *http.httpError

**Comment by bsownda** [comment]
> @bsownda By setting `IN_SECURE_SKIP_VERIFY=true` in the `.env` file, you cloud disable the SSL certificate verification

I tried with this option also. Still I'm not able to connect.

**Comment by mindlesscloud** [comment]
@bsownda Could you access the Jira server from the server where DevLake was deployed

**Comment by FaizanSh** [comment]
@bsownda @mindlesscloud 
I am having the similar issue. By following the [documentation](https://devlake.apache.org/docs/next/Troubleshooting/Configuration/#failed-to-collect-data-from-the-server-with-a-self-signed-certificate) I was able to add the Certificate in the docker and my curl command works directly from the image and the instance as well.

Adding snippet for reference:
![image](https://user-images.githubusercontent.com/23335607/217797094-6cec5155-4dc5-473e-84ca-38ed3efe7845.png)

Although when I am trying to create a connection I get following issues.
Using the Token
![image](https://user-images.githubusercontent.com/23335607/217797622-6f13f348-22a9-468f-8a2a-e46df9a3ad63.png)

Using the basic Authentication
![image](https://user-images.githubusercontent.com/23335607/217798119-8af3c5e1-afea-4231-a0ac-94c9a852b34a.png)


I have created a [question issue](https://github.com/apache/incubator-devlake/issues/4362) for this as well

**Comment by klesh** [comment]
Jira PAT will be supported in v0.16 by https://github.com/apache/incubator-devlake/pull/4260

**Comment by klesh** [comment]
FYI. ETA of v0.16 is Mar
