### ISSUE TITLE
Bitbucket - getting 404 not found when test a connection

### ISSUE THREAD

**Issue by batchenr** [apache/incubator-devlake#4334]
I have set a bitbucket connection to our local bitbucket - Atlassian Bitbucket v6.8.0
I see that in the docs you say to add the "app password" but i don't have something like that in my bitbucket.
and I didn't find any docs on which versions of bitbucket is supported by devlake.

![image](https://user-images.githubusercontent.com/49156185/216937582-db5297f0-1c36-42cc-af39-4ee473f1e875.png)

I have installed dev lake with helm chart version 0.15.0-rc5
i put my bitbucket URL  with admin user or password, also tried User's access token but i get the response : 
POST http://$KUB_NODE_IP:PORT/api/plugins/bitbucket/test 404 (Not Found)

**Comment by likyh** [comment]
We just test Bitbucket Cloud. Please wait some days, I'll test local bitbucket.

**Comment by likyh** [comment]
Sorry, I have tested the local bitbucket. But actually we not support it now.
The endpoint for the local bitbucket is like `http://ip:7990/rest/api/1.0/`. But the rest api is different from the cloud `https://api.bitbucket.org/2.0/`. They are different versions. 

We haven't supported the local version, Although the are similar. Would you like to join this?

**Comment by batchenr** [comment]
> Sorry, I have tested the local bitbucket. But actually we not support it now. The endpoint for the local bitbucket is like `http://ip:7990/rest/api/1.0/`. But the rest api is different from the cloud `https://api.bitbucket.org/2.0/`. They are different versions.
> 
> We haven't supported the local version, Although the are similar. Would you like to join this?

Im building now a promtheus exporter manually based on python that collect the data and it seems to work for me like this, thank you
