### ISSUE TITLE
[Bug][gitextractor] the url of gitlab has errors under certain circumstances

### ISSUE THREAD

**Issue by mappjzc** [apache/incubator-devlake#4335]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

![image](https://user-images.githubusercontent.com/2921251/216970072-02e544b6-8c22-4cdf-8124-9b2e9e21fca9.png)

Under some settings of GitLab, the URL actually accessed may be inconsistent with the URL configured by GitLab.

It made the gitextractor fail.

### What do you expect to happen

Gitextractor runs success.

### How to reproduce

Use a different URL than the GitLab setting to request.

### Version

main

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by likyh** [comment]
It looks like be a GitLab deploy issue. Please update your GitLab config.
