### ISSUE TITLE
Median Time to Restore Service not working

### ISSUE THREAD

**Issue by ibrahimejaz** [apache/incubator-devlake#4338]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

Median Time to Restore Service
 This metrics in DORA not working, we've integrated with our JIRA  and Github, but not working only for some projects it's showing but most time it wasn't it would be great if we could get help for the same.
Using v0.15.0-rc5@2fa3892.. 

### What do you expect to happen

Median Time to Restore Service
 This data not coming up.

### How to reproduce

In DORA metrics page.

### Version

v0.15.0

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by mindlesscloud** [comment]
@ibrahimejaz I noticed that you checked the `Yes I am willing to submit a PR!` box, I have assigned it to you, let me know if you need any help.

**Comment by abeizn** [comment]
@ibrahimejaz We modified the calculation logic of sql, you can use v0.15.1-beta3 version. Or you can import the new dora.json(https://github.com/apache/incubator-devlake/blob/release-v0.15/grafana/dashboards/DORA.json) to grafana.

**Comment by ibrahimejaz** [comment]
Thanks @abeizn will try that out.

**Comment by ibrahimejaz** [comment]
Hi,
Have updated the DORA dashboard but still happens to some random values under that chart though I've mentioned anything it still pulls up some random values and displays. it does shows random values for months for the newly created repos as well.

**Comment by KlemenDanfoss** [comment]
Hi

we use Azure Devops (board, pipelines) and Azure Repos. We also use trunk based development.

I integrated devlake (latest beta version of 0.17) with our account and I get metrics for 'deployment frequency' and 'Change failure rate' but nothing for 'Median time to restore services'.

Any advice how I can start debuging this?

**Comment by klesh** [comment]
@Startrekzky Can u take a look at this?

**Comment by Startrekzky** [comment]
Hi @KlemenDanfoss , can you go to 'DORA Dashboard validation' in Grafana and take a screenshot of the 'Check Median Lead Time for Changes' section?
![image](https://github.com/apache/incubator-devlake/assets/14050754/0018b4b2-8f3e-497b-baaa-78c885a81204)

This dashboard is designed to debug DORA dashboard.

**Comment by KlemenDanfoss** [comment]
Hi @Startrekzky - I have sent some screenshots to you email.

**Comment by KlemenDanfoss** [comment]
Hi @Startrekzky some screenshosts here as well

![image](https://github.com/apache/incubator-devlake/assets/93664973/85ebe5e0-00a6-400a-b29e-ee4c5593345a)
![image](https://github.com/apache/incubator-devlake/assets/93664973/5ec0a529-9948-491b-839e-6c67325af631)

**Comment by Startrekzky** [comment]
Hi @KlemenDanfoss , we just released the latest [v0.18.0-beta6](https://github.com/apache/incubator-devlake/releases/tag/v0.18.0-beta6) and fixed some bugs in this dashboard. Can you try it out and see if the above problem has been solved?

**Comment by KlemenDanfoss** [comment]
Upgraded, nothing improved.

Could it be because of us using Trunk besed development?


Poslano iz Outlook za Android<https://aka.ms/AAb9ysg>


Classified as Public

________________________________

**Comment by Startrekzky** [comment]
@KlemenDanfoss Trunk-based? That might be the root cause. May I ask

1. Do you use PR or MR to push commits?
2. What Git tool and merge mode do you use? 
3. How do you do deployments? When is a deployment triggered in your workflow?

**Comment by KlemenDanfoss** [comment]
@Startrekzky , sure!

Through a PR in azure devops. We create a PR and usually do squash commit (merged branch is deleted). Deployment pipeline is automatically triggered when a certain (sub)folder (in the main branch) changes after a successful PR.
