### ISSUE TITLE
collectApicomments failing after long run

### ISSUE THREAD

**Issue by ibrahimejaz** [apache/incubator-devlake#4349]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

collectApicomments from graphql is failing after running for sometime, Would be really great if we could fix this thanks and Im using 15-rc5 version. Thanks.

Attaching screenshot --> https://share.anysnap.app/fDjkmEPUMwFD

### What do you expect to happen

ime="2023-02-07 14:51:13" level=warning msg=" [pipeline service] [pipeline #22] [task #348] retry #1 graphql calling after 600s
        caused by: non-200 OK status code: 502 Bad Gateway body: "{\n   \"data\": null,\n   \"errors\":[\n      {\n         \"message\":\"Something went wrong while executing your query. This may be the result of a timeout, or it could be a GitHub bug. Please include `89A2:06E1:2CCCAA:33870F:63E26554` when reporting this issue.\"\n      }\n   ]\n}\n""
^C

### How to reproduce

It just runs for more time and fails has seen the logs after long time.
ime="2023-02-07 14:51:13" level=warning msg=" [pipeline service] [pipeline #22] [task #348] retry #1 graphql calling after 600s
        caused by: non-200 OK status code: 502 Bad Gateway body: "{\n   \"data\": null,\n   \"errors\":[\n      {\n         \"message\":\"Something went wrong while executing your query. This may be the result of a timeout, or it could be a GitHub bug. Please include `89A2:06E1:2CCCAA:33870F:63E26554` when reporting this issue.\"\n      }\n   ]\n}\n""
^C

### Version

v0.15.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by mindlesscloud** [comment]
The 502 error indicates it's a GitHub problem, please try again after a while.

**Comment by ibrahimejaz** [comment]
Yes, but at most times it wasn't later after few hours it started.. Thanks for checking it for us.
