### ISSUE TITLE
[Question] [Jira] Jira Server connection using bearer token instead of Basic Authentication

### ISSUE THREAD

**Issue by FaizanSh** [apache/incubator-devlake#4362]
## Question
I am trying to connect DevLake with Jira Server. The given fields, and documentation suggest to use basic authentication when connecting with Jira server. I am asking if there is any way I can give only (bearer) API token instead of basic authentication credentials?

## Screenshots
Documentation Suggest to use basic authentication.
![image](https://user-images.githubusercontent.com/23335607/217638357-53d41b66-b847-4a61-ace5-5a883aec9747.png)

## Additional context
Documentation: https://devlake.apache.org/docs/UserManuals/ConfigUI/Jira

**Comment by mappjzc** [comment]
We will automatically generate a token, but we cannot provide a token directly at present.

**Comment by klesh** [comment]
Jira PAT will be supported in v0.16 by https://github.com/apache/incubator-devlake/pull/4260

**Comment by klesh** [comment]
Hi, @FaizanSh , the v0.16 is ready for `beta` , please join our slack and reach out to "Hezheng Yin" if you would like to try it out.
