### ISSUE TITLE
[Doc][Troubleshooting] Proposing to add Swagger API info 

### ISSUE THREAD

**Issue by JoshuaPoddoku** [apache/incubator-devlake#4374]
## Documentation Scope
Proposing to add Swagger API info in Troubleshooting Docs: https://devlake.apache.org/docs/Troubleshooting/Configuration

## Describe the Change
Need to update that DevLake has Swagger API (http://localhost:4000/api/swagger/index.html#/) to support Blueprint API and others. This also helps devs to locate easily as it is asked in our slack community several times. 

## Screenshots
We may add the info of Swagger API in [Configuration and Blueprint Troubleshooting](https://devlake.apache.org/docs/Troubleshooting/Configuration)
<img width="1440" alt="Screenshot 2023-02-10 at 1 06 27 AM" src="https://user-images.githubusercontent.com/31725457/217919225-9e40a0e9-2cec-42ce-9184-c4c01eb34f22.png">

## Additional context
- [Slack discussion thread #1](https://devlake-io.slack.com/archives/C03APJ20VM4/p1669774594375629?thread_ts=1669739595.405099&cid=C03APJ20VM4)
- [Slack discussion thread #2](https://devlake-io.slack.com/archives/C03APJ20VM4/p1675942841997909?thread_ts=1675941825.603859&cid=C03APJ20VM4)
<img width="513" alt="Screenshot 2023-02-10 at 1 02 39 AM" src="https://user-images.githubusercontent.com/31725457/217918519-7e1a2182-bd3f-4a34-832c-6929b81c7717.png">

**Comment by mappjzc** [comment]
Thanks for your issue. can you have a look  @klesh

**Comment by Startrekzky** [comment]
Hi @JoshuaPoddoku , this issue has been solved by 
1. adding a doc: https://devlake.apache.org/docs/Overview/References
2. adding an entry to the API docs in the Config UI in v0.17 
   ![image](https://github.com/apache/incubator-devlake/assets/14050754/41232c68-1457-4e08-86e6-a3a7c41ff05d)
