### ISSUE TITLE
[Bug][Task] Task in pipeline is blocked by something for 30+ mins

### ISSUE THREAD

**Issue by narrowizard** [apache/incubator-devlake#4376]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

I have run a pipeline that contains 4 tasks (not in parallels). They are
- jira plugin
- a private plugin to do some data transform
- starrocks plugin
- dbt plugin

The last dbt task is started at 18:19 while the previous starrocks task is finished at 17:44. I dont know what happened in this 30+ mins. 

### What do you expect to happen

The dbt tasks should run as soon as the starrocks task finished.

### How to reproduce

Dont known, seems it is occurred randomly(under some unknown conditions).

### Anything else

I queried the data from `_devlake_tasks` table, it seems there was not other tasks in that 30+ mins.  
![image](https://user-images.githubusercontent.com/11383928/217977971-13be48d5-3f48-4e72-a173-560a481b6dc4.png).  
Tell me if you need any further informations, I will provide it in my best.

### Version

v0.15.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by klesh** [comment]
It is likely caused by `starrocks` not releasing database cursors correctly, please remove unnecessary cursors @abeizn

**Comment by abeizn** [comment]
it will be repaired by #4418.
