### ISSUE TITLE
[Doc][Installation] Provide docs on how to set up HTTPS for Config-UI

### ISSUE THREAD

**Issue by hezyin** [apache/incubator-devlake#4380]
For production deployment, users would like to set up HTTPS for Config-UI. We should consider providing documentation on this topic for both dock-compose and helm users.

**Comment by matrixji** [comment]
For helm with HTTPS deployment, a short description is available here: https://devlake.apache.org/docs/next/GettingStarted/HelmSetup#deploy-with-ingress-https

For the compose deployment, it seems we need to do some code changes to support HTTPS.

**Comment by hezyin** [comment]
Bump
