### ISSUE TITLE
[Doc][Advanced Mode] Provide docs on how to set up subtasks and more configurations for advanced mode 

### ISSUE THREAD

**Issue by chenggui53** [apache/incubator-devlake#4381]
Some subtasks and configurations can only be set in advanced mode, but there is no documentation on how to set subtasks and more other configurations in advanced mode. Please provide documentation on how to set up subtasks and other configurations that are only supported in advanced mode.

**Comment by Startrekzky** [comment]
Can you add it when you're available? @abeizn

**Comment by Startrekzky** [comment]
Hi @chenggui53 , I think this doc can solve your problem, feel free to reopen the issue if it doesn't. https://devlake.apache.org/docs/Configuration/AdvancedMode#examples
