### ISSUE TITLE
error running blueprint on github enterprise.

### ISSUE THREAD

**Issue by vifulnirala** [apache/incubator-devlake#4387]
### Search before asking

- [x] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

If we run the blueprint without manually speciying the fixed rate limit in the github connection the blueprint gives the following error. However the issue fixes if we specify the fixed rate in the connection.
<img width="1792" alt="Screenshot 2023-02-10 at 1 53 23 PM" src="https://user-images.githubusercontent.com/33188781/218048101-68d0981a-205a-477a-8a44-29f92029aca5.png">

### What do you expect to happen

While creating a simple github connection we do not need to specify the fixed rate limit. Similarily when creating the github enterprise connection we should also not need to specify the fixed rate limit

### How to reproduce

Create a github enterprise connection without specifying the Fixed rate limit .
Create a blueprint with the same connection.
Then run the blueprint.

### Version

main

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by abeizn** [comment]
@vifulnirala  main branch? main is the development branch, there may be some unexpected problems. It is recommended that you use the latest tag v0.15.1-beta3.

**Comment by klesh** [comment]
@warren830 Please take a look at this bug.

**Comment by klesh** [comment]
@warren830 FYI, the github enterprise does not return the `X-RateLimit-Limit` header

**Comment by warren830** [comment]
Hi @vifulnirala , are you using enterprise server?
