### ISSUE TITLE
[Feature][Config UI] Support Blueprint, Project and Scope deletion

### ISSUE THREAD

**Issue by moteng** [apache/incubator-devlake#4388]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar feature requirement.

### Use case

Support Blueprint, Project and Scope deletion on UI

### Description

Backend APIs:

1. Sample GET request to get all the scopes with the blueprints:
`GET /plugins/pagerduty/connections/25/scopes?blueprints=true`
May omit blueprints query param or set to false and the blueprints field will not come back in the payload.
You can extract the blueprints from the returned payload by accessing the `blueprints` field on the JSON. It'll be an array of full blueprint objects. You can access the `project_name` on each blueprint as usual.

2. Sample Delete request to delete a scope (delete_data_only=true -> data removed but not scope; data_data_only=false -> scope and data are removed):
`DELETE   "/plugins/pagerduty/connections/26/scopes/PIKL83L?delete_data_only=true"`
Returns nothing.

3. `DELETE   "/blueprints/1` -> deletes this blueprint

4.  `DELETE   "/projects/1` -> deletes this project and all of its metric related data

### Related issues

#4864 

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by abeizn** [comment]
Thanks for reporting the issue.

**Comment by Startrekzky** [comment]
@moteng Please follow the community guidelines for reporting issues https://devlake.apache.org/community/make-contribution/fix-or-create-issues

**Comment by Startrekzky** [comment]
Hi @moteng , we created another issue with more detailed description to track 'bp deletion'. Please check #4864

**Comment by keon94** [comment]
@Startrekzky Let's use this ticket for the required UI work of this feature since the title is already scoped to "config-ui".

**Comment by keon94** [comment]
Designs:

![image](https://github.com/apache/incubator-devlake/assets/25063936/6aa2657b-3d15-4bac-9b7f-3d2b10ba5c46)
![image](https://github.com/apache/incubator-devlake/assets/25063936/d1d38c98-ff06-474e-a2ad-9a8198bc84ac)
![image](https://github.com/apache/incubator-devlake/assets/25063936/f817de9c-4791-4fdd-9ddc-b1296371116f)

**Comment by Startrekzky** [comment]
@keon94 Cool. Should I assign it to @mintsweet?
