### ISSUE TITLE
[Feature][SonarQube] Collect `complexity` from SonarQube

### ISSUE THREAD

**Issue by moteng** [apache/incubator-devlake#4389]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar feature requirement.

### Use case

Collect `complexity` from SonarQube

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by abeizn** [comment]
Thanks for reporting the issue.

**Comment by Startrekzky** [comment]
@moteng Please follow the community guidelines for reporting issues https://devlake.apache.org/community/make-contribution/fix-or-create-issues

**Comment by Startrekzky** [comment]
This issue is duplicated with issue #2305
