### ISSUE TITLE
[Feature][gitextractor] solution needed for https disabled orgs

### ISSUE THREAD

**Issue by JoshuaPoddoku** [apache/incubator-devlake#4392]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar feature requirement.

### Use case

This was raised by DevLake user in [Slack](https://devlake-io.slack.com/archives/C03APJ20VM4/p1675925131880519), the https was disabled at the org level and it works only with ssh. The user had to go through temporary solution via Advanced Blueprint.

[Slack thread](https://devlake-io.slack.com/archives/C03APJ20VM4/p1675925131880519)
![Screenshot 02-11-2023 04 15 36](https://user-images.githubusercontent.com/31725457/218215036-0336fc54-bef5-4df6-ae61-986e5a3ac9fb.png)
Error Logs: [logging.tar-2.gz](https://github.com/apache/incubator-devlake/files/10711656/logging.tar-2.gz)

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by klesh** [comment]
@Startrekzky @yumengwang03 need prototype for the support
