### ISSUE TITLE
[Bug][Jira] The behaviour of createdDateAfter option does not fit the user scenario

### ISSUE THREAD

**Issue by narrowizard** [apache/incubator-devlake#4403]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

In our situation, we do need the limited history sync feature introduced by 0.15.  
With solution implemented in 0.15, we lost issues which is created before but updated after `CreatedDateAfter` time.  
Those issues (created before but updated after) are useful when analysing, because the updating operation means it is picked up again recently.

### What do you expect to happen

We need all data which has updation after the time we specified.

### How to reproduce

No

### Version

v0.15.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by klesh** [comment]
# Plan of attack for v0.16

1. Add `TimeAfter` support alongside `CreatedDateAfter` for JIRA ( including framework modification), review, and merge.
2. Update all plugins one by one in terms of multiple PRs
3. Cleanup: Rename `CreatedDateAfter` to `TimeAfter` in the database and remove all deprecated code
4. Update config-ui  @mintsweet
