### ISSUE TITLE
[Bug][Dashboard] largest files with lowest number of authors--> Dashboard throwing upstream error!

### ISSUE THREAD

**Issue by ibrahimejaz** [apache/incubator-devlake#4406]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

largest files with lowest number of authors -->
This dashboard throwing upstream error after several seconds running the query, can this be optimised and serve better which would be really helpful. Thanks.

### What do you expect to happen

largest files with lowest number of authors --> We've increased the query time for 30 seconds by default it's 10 seconds, it just queries for 30 seconds and fails over.. throwing upstream error. 

### How to reproduce

largest files with lowest number of authors-- not working

### Anything else

That's all I've pls help fixing this.

### Version

main

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by likyh** [comment]
Would you like to tell me which chart is slow than 10s? We will improve these chart

**Comment by ibrahimejaz** [comment]
[Component and File-level Metrics] --> In there this one --> Specific to this dashboard. --> largest files with lowest number of authors

**Comment by Startrekzky** [comment]
Hey @ibrahimejaz I noticed that you clicked this. If you are not going to work on this issue, I'll assign to someone else.
![image](https://user-images.githubusercontent.com/14050754/220133867-743784d8-269e-42ff-8441-7cd5f5304ac5.png)

**Comment by ibrahimejaz** [comment]
Im sorry you may help someone to take this.

**Comment by abeizn** [comment]
We optimized the SQL and added indexes（by #4483）, and passed the test on the apache/hadoop repo. When using it, it is recommended that repo try not to choose all. At the same time, for a large amount of data, you can change the timeout configuration of mysql and grafana to increase the success rate.
