### ISSUE TITLE
[Doc][Grafana] Add doc on how to import JSON dashboard

### ISSUE THREAD

**Issue by hezyin** [apache/incubator-devlake#4410]
Multiple users have asked in the Slack how to import JSON dashboard, especially when the to-be-imported dashboard is an upgrade of an existing built-in dashboard. We should add the following doc somewhere:

1. Click the “+” button on your Grafana’s left side bar and select “Import”

<img width="1312" alt="Screen Shot 2023-02-06 at 2 09 32 PM" src="https://user-images.githubusercontent.com/2908155/218666236-4e9e51ee-ba48-4f6e-9085-f8426b649039.png">

2. Paste the JSON of the fixed dashboard into the text field highlighted and click “Load”. 

<img width="703" alt="Screen Shot 2023-02-06 at 2 14 12 PM" src="https://user-images.githubusercontent.com/2908155/218666279-f1b51a82-275b-49aa-8aab-c6ad1a0c1513.png">

3. Grafana will complain there’s already a dashboard named “DORA”, so consider renaming it to something else like “DORA v2", and also change its uid by clicking “Change UID” and making some random changes to the original UID string. Then go ahead and import.

<img width="711" alt="Screen Shot 2023-02-06 at 2 09 50 PM" src="https://user-images.githubusercontent.com/2908155/218666325-662e51e3-2589-4e9d-aab9-d6040f261c81.png">

**Comment by Amishakumari544** [comment]
Hi @hezyin I would like to work on this issue. can you please assign me?

**Comment by hezyin** [comment]
@Amishakumari544 Thanks for picking this up! Looking forward to your PR!

**Comment by Startrekzky** [comment]
Hi @Amishakumari544 , any updates about this issue? If not, I can take over.
