### ISSUE TITLE
JIRA --> Need to pull all the task types.

### ISSUE THREAD

**Issue by ibrahimejaz** [apache/incubator-devlake#4417]
I may need to pull all the issue types in JIRA dashboard, initially I was using different transformation and I  was able to pull all the issue type involved in our end, have the same replica for our prod env. where I can't able to pull the issue types it's same as old setup and there is no change in our our JIRA end nor our credentials been used, I'm aware I may be missing something I've checked all the possibilities that I've did in the past setup all seems to be same.. So just wondering if any of you can help guide me to see how I can get all the issue type in JIRA while showing.

**Comment by mindlesscloud** [comment]
Which version of DevLake are you using? Have you upgraded it recently?

**Comment by klesh** [comment]
Need to be verified in v0.16

**Comment by ibrahimejaz** [comment]
Have used v0.15 on both which was working on staging will try using v0.16 to see if that helps, thanks.

**Comment by ibrahimejaz** [comment]
The version which I'm using is v0.15.0-rc5. hope v0.16 will launch shortly. Thanks.

**Comment by likyh** [comment]
Hi, @ibrahimejaz . Sorry I haven't understand what you mean. You means you want to create one transformationRule and use it everywhere, or you want to know how to select issue type in the dashboard?

**Comment by likyh** [comment]
0.16 will start beta testing tomorrow. Would you like join testing?

**Comment by likyh** [comment]
Hello, v0.16.0-beta4 has been released and can be tested with the latest version. Link: https://github.com/apache/incubator-devlake/releases/tag/v0.16.0-beta4. It is recommended to backup the previously created Dashboard before updating to avoid being overwritten.

**Comment by ibrahimejaz** [comment]
Hi @likyh have checked in our production env. and see it's working, also wondering if you could help me with this query like while transforming github for DORA, there are two places mentioned in devlake dashboard i.e., deployments and production 
when we mention input value for deployments it does captures per our Github action job, but let's say I might have multiple deployments and would classify with production when I put that action job name it's not considering in the DORA dashboard, so wondering where you be able to help me on this which would be really a great help. Thanks.

**Comment by ibrahimejaz** [comment]
Hi @likyh Yes, have used the same way but when I used production job name under DORA dashboard its not coming up. DORA dashboard does only calculate the deployments (job name mentioned under deployment) and doesn't take it for production (job name). That's where got a confusion where DORA needs production github action name to make it work? using the beta build of 0.16. Also have tried the same with older versions was still facing the same issue..

**Comment by likyh** [comment]
> Hi @likyh Yes, have used the same way but when I used production job name under DORA dashboard its not coming up. DORA dashboard does only calculate the deployments (job name mentioned under deployment) and doesn't take it for production (job name). That's where got a confusion where DORA needs production github action name to make it work? using the beta build of 0.16. Also have tried the same with older versions was still facing the same issue..

@ibrahimejaz Have you recognize production as deployments? I think maybe you should match both deployments and production in `deployment regex` and match production in `production regex`.
