### ISSUE TITLE
Deep exploration on Gitlab CI

### ISSUE THREAD

**Issue by leglars** [apache/incubator-devlake#442]
## Description
I see you guys plan to support Gitlab CI as a data source. I have some ideas want to share with you and wish you can add into your early feature evaluation and consideration.
When EE integrates with Jira, we want to know which commits are linked with an issue. _Gitlab CI for Jira integration_ and _bitbucket_ support this idea:
**_Both of them can monitor new commit across all repositories with the license, scan commit message, and link the commit with target issue by finding the issue key in the commit message._**

However, in reality, many EE clients didn't set up those integrations even if they already use Gitlab and require apply issue key in commit messages.

## Describe the solution you'd like
When you guys explore technical solution for integrating with Gitlab CI, please pay an attention on how Gitlab CI for Jira integration works, and if Gitlab CI supports this commit-link feature originally. So, we can apply a similar feature in our Gitlab CI integration which may be a separate feature outside of Gitlab CI integration or collector. 
When client implement Dev Lake and integrate with a code hosting platform and an issue system, Dev Lake can link validate commits with related issues.

## Describe alternatives you've considered
If we want to keep Gitlab CI simple which is just a machine syncing Gitlab CI data, then, maybe consider an independent feature which can help client link issues with validate commit.

> P.S. @jaxzhou has coded a feature in EE to help EMC link existing validate commits with issues in Jira 

## Additional context
![image](https://user-images.githubusercontent.com/10903437/134845104-2f7f5167-bf5b-431a-b61d-ccda8b4e57f1.png)

**Comment by klesh** [comment]
@leglars It looks like "building issue/commits relationship" to me, correct me if  I'm wrong.]

**Comment by klesh** [comment]
Hi, I think this is already implemented, I'm closing it, feel free to reopen if any misunderstanding.
