### ISSUE TITLE
[Bug][Team] The `users.csv` template downloaded is not encoded in UTF-8

### ISSUE THREAD

**Issue by Startrekzky** [apache/incubator-devlake#4428]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

A user wanted to use the team feature. He followed the [guide](https://devlake.apache.org/docs/UserManuals/TeamConfiguration) and uploaded `users.csv`, and it turned out that the table.users in MySQL was empty. The data was not successfully imported.

The user then found out it was due to the CSV encoding format, the `users.csv` template he downloaded was not encoded in UTF-8.

![image](https://user-images.githubusercontent.com/14050754/219035302-a0240160-7e44-44b1-aea2-877bfae6a119.png)

### What do you expect to happen

- [ ] The templates should be in encoded in UTF-8 by default.
- [ ] Add a line to the [team doc](https://devlake.apache.org/docs/UserManuals/TeamConfiguration#step-1---create-the-teams-table) to tell users that the CSV should be encoded in UTF-8. 

### How to reproduce

Follow the team doc to import team data.

### Version

main

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by klesh** [comment]
CSVs are plain-text files, it is up to applications (likely Excel in this case) to determine which encoding to use.

1. Use libre office instead: it would offer a dialog to choose the encoding
2. Manual choose encoding in Excel, you may google "how to" based on the version you are using

**Comment by klesh** [comment]
And I totally agree with the second point, we should update our document to stress the encoding is UTF-8 and what actions they should take.
