### ISSUE TITLE
[Feature][pydevlake] Add support for transformation rules and scope APIs for python plugins

### ISSUE THREAD

**Issue by CamilleTeruel** [apache/incubator-devlake#4437]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Provide generic implementation of the transformationRules and scope APIs for python plugins.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by keon94** [comment]
PR: #4438

**Comment by hezyin** [comment]
This should have been closed by #4438.
