### ISSUE TITLE
[Feature][Config UI] Error Messages and Warnings in Blueprint creation

### ISSUE THREAD

**Issue by JoshuaPoddoku** [apache/incubator-devlake#4449]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar feature requirement.

### Use case

I have observed a few cases where a user either forgets or doesn't know to add a connection while creating blueprint. For instance "Next Step" button is disabled and the user doesn't know why. ([Slack thread](https://devlake-io.slack.com/archives/C03APJ20VM4/p1676372057717779))

### Description

We can add user friendly error messaging or communicate effectively on config UI itself as shown in the image below
![image](https://user-images.githubusercontent.com/31725457/219836707-726cf959-92a1-44a6-817c-fcfc2c526ad4.png)

### Related issues

Nope

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Startrekzky** [comment]
Thanks @JoshuaPoddoku , can you take a look? @yumengwang03

**Comment by JoshuaPoddoku** [comment]
Hey @Startrekzky , there were quite a few I noticed earlier, especially the user groups who are new to DevLake, beginners and who may miss reading docs. 

Here is a recent [slack thread](https://devlake-io.slack.com/archives/C03APJ20VM4/p1676372057717779) for reference

**Comment by yumengwang03** [comment]
> Hey @Startrekzky , there were quite a few I noticed earlier, especially the user groups who are new to DevLake, beginners and who may miss reading docs.
> 
> Here is a recent [slack thread](https://devlake-io.slack.com/archives/C03APJ20VM4/p1676372057717779) for reference

This a valid potential improvement, but it's probably not at high priority at the moment. We have added more help information, including links to docs, in v0.16's config UI. Let's see how that works first. Is that OK?

**Comment by JoshuaPoddoku** [comment]
I completely agree. We can try including links to docs that should help at the moment!
