### ISSUE TITLE
[Bug][Github] Github Connection not working, PAT is not being validated

### ISSUE THREAD

**Issue by Suhasr76** [apache/incubator-devlake#4499]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

I work in a organisation, and when I tried to add a github connection by following the docs, the PAT is not validated

<img width="274" alt="Screenshot 2023-02-20 at 9 01 10 AM" src="https://user-images.githubusercontent.com/56556749/220816125-a4702cb2-6f9a-4191-a0a3-f665c9083f2c.png">

The `devlake.log` file shows this error

![Screenshot](https://user-images.githubusercontent.com/56556749/220832228-1069d4a4-e836-41aa-8b4e-84093867cc0a.png)
What is the reason for this error?
This bug might be because, the org uses few https certificates for https requests, so is there a way to upload these certificates during initiating a connection.
Or is it something else?

### What do you expect to happen

- Able to use above mentioned https certificates for required connection (this is applicable for Bitbucket also)
- Or any other fix

### How to reproduce

- Initiate the github connection
- Generate and Use PAT to authenticate 
- But for our organisation, PAT is not being validated

### Version

main

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by mappjzc** [comment]
Thanks for your valuable feedback and suggestion.

Make sure the endpoint of the GitHub connection was `https://api.github.com/`
Make sure you can use  `curl` or `postman` to access the URL `https://api.github.com/user` success with your token.

**Comment by Suhasr76** [comment]
Hi @mappjzc, since we are using github enterprise and my github account is from the same enterprise, I used `https://hostname/api/v3/` and it seems to be working now, but before I used different endpoint.

And also, `https://api.github.com` didn't work for a PAT generated from personal github account. What might be the reason for that?

Thanks for your help!!

**Comment by mappjzc** [comment]
> Hi @mappjzc, since we are using github enterprise and my github account is from the same enterprise, I used `https://hostname/api/v3/` and it seems to be working now, but before I used different endpoint.
> 
> And also, `https://api.github.com` didn't work for a PAT generated from personal github account. What might be the reason for that?
> 
> Thanks for your help!!

I don't know what is your meaning about `didn't work for a PAT generated from personal GitHub account`. Can you show more details?

**Comment by Suhasr76** [comment]
In the sense, initially I tried to add 2 github connections
- One with my personal github account, with endpoint `https://api.github.com/` and PAT generated from this account, and this one  didnt work in the `config-ui`, but I was able to use `curl` to access this token
- Second one was with my enterprise given github account and their endpoint `https://hostname/api/v3/` and PAT generated from that account. This worked with both the `config-ui` and `curl`.

The first connection showed this error
<img width="274" alt="Screenshot 2023-02-20 at 9 01 10 AM" src="https://user-images.githubusercontent.com/56556749/221340074-dbcffd1f-0f23-4e80-8eb8-ff84ce2d4b3b.png">

And this was the log in `devlake.log`
![Screenshot](https://user-images.githubusercontent.com/56556749/221340087-bc5bc6c5-fb5d-45ec-8dea-e7406d5ab384.png)

**Comment by klesh** [comment]
Hi, @Suhasr76 , Would you mind sharing your `curl` command? Thanks.
