### ISSUE TITLE
[Doc][Getting Started] Add docs on how to use external database for production deployment

### ISSUE THREAD

**Issue by hezyin** [apache/incubator-devlake#4501]
For production deployment, many users would like to replace MySQL container/pod with an external instance like AWS RDS. We should provide step-by-step documentation on how to do that for both helm and docker-compose installation methods.

We used to document this for k8s installation in an FAQ: https://devlake.apache.org/docs/v0.14/GettingStarted/KubernetesSetup#faq (can be used as a reference)

This applies to Grafana as well, but it's not as urgent.

**Comment by warren830** [comment]
resolved by #https://github.com/apache/incubator-devlake-website/pull/448 and https://github.com/apache/incubator-devlake-website/pull/463
