### ISSUE TITLE
[Bug][config-ui] poroject name caontains '/'

### ISSUE THREAD

**Issue by BaoBaoGitHub** [apache/incubator-devlake#4506]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

# Description

I created a project named `apache/incubator-devlake`.
After that, I create a blueprint including add data connections, set data scope, add transformation (Optional) and set sync policy.
When I click `save BluePrint` button, the error occured.

![73c0c1c9ccbcfd2d9eb2ebbf2b3be27](https://user-images.githubusercontent.com/68647811/220858993-9f5f9bf1-8bfa-42de-9df8-aff53a0f0f7f.png)
![afc0bdbfb998f4b1bc93b81539d7259](https://user-images.githubusercontent.com/68647811/220859046-cf6d29a0-f789-4318-811e-4b5187887314.png)

# Error Response

The response code in browser network tab is 
```
{"success":false,"message":"error creating blueprint (404)\nWraps: (2) invalid projectName: [apache%2Fincubator-devlake] for the blueprint [apache/Fincubator-devlake-BLUEPRINT] (404)\nWraps: (3) could not find project [apache%2Fincubator-devlake] in DB (404)\nWraps: (4) record not found\nWraps: (5) record not found\nError types: (1) *hintdetail.withDetail (2) *hintdetail.withDetail (3) *hintdetail.withDetail (4) *hintdetail.withDetail (5) *errors.errorString","causes":["invalid projectName: [apache%2Fincubator-devlake] for the blueprint [apache/Fincubator-devlake-BLUEPRINT] (404)","could not find project [apache%2Fincubator-devlake] in DB (404)","record not found"]}
```

# Possible Reasons
I guess the problem may be the char `/` is replaced by `%2F` where the latter is escape character in URL.
Besides, the row was inserted into mysql table `projects` successfully.

### What do you expect to happen

Successfully save and runBluePrint when the project name include especial URL character
or
you should give naming rule and check project name.

### How to reproduce

Create a project whose name include `/` character.
Maybe other especial URL characters could trigger the error.

### Anything else

I have described it in detail in part `What happened`.

### Version

v0.15.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by BaoBaoGitHub** [comment]
Version of Devlake is `0.15`.

**Comment by mappjzc** [comment]
Thanks for your valuable feedback and suggestion.

I have checked it
![image](https://user-images.githubusercontent.com/2921251/220871228-9b8527ef-a09e-4fd7-83c5-6658f1e16ada.png)

it happend because the front endpoint send a url encode data in request json, but the json data do not need url encode.

@mintsweet  can you have a look to check if it can be fixed on the front endpoint?
