### ISSUE TITLE
[Question][Git Extractor] Git Extractor takes too long?

### ISSUE THREAD

**Issue by hezyin** [apache/incubator-devlake#4511]
On v0.15.1-beta5, when I create a blueprint to collect `cncf/landscape` (time filter sets to 6 months), I noticed that the Git Extractor task takes much longer than GitHub GraphQL task, see screenshot below. When I examine the subtask/task data, I found that collectGitCommits subtask took 723s while the entire Git Extractor task took 839s, so it's not due to slow clone. This is not an urgent issue, but when we have some cycles, we should research if there's room for improvement.

<img width="932" alt="Screen Shot 2023-02-23 at 8 37 45 PM" src="https://user-images.githubusercontent.com/2908155/221092976-6b183772-eea7-48cf-83ea-01b3ef1378ac.png">

As a comparison, Git Extractor only took 1 min for our own repo:]

<img width="928" alt="Screen Shot 2023-02-23 at 9 18 42 PM" src="https://user-images.githubusercontent.com/2908155/221098353-af81b3ce-2200-465c-bc9c-4fef5772c3e0.png">

**Comment by klesh** [comment]
Judging by the sizes of the repos, the `cncf/landscape` is 10x larger than `apache/incubator-devlake` , I think it is expected to have such a time difference.

![image](https://user-images.githubusercontent.com/61080/221779277-919362d0-dd7e-48d0-bc53-be2c2a07a080.png)
![image](https://user-images.githubusercontent.com/61080/221779299-ee5b367d-3eb2-44e0-b942-f6680f5772c7.png)
