### ISSUE TITLE
[Bug][backend] Docker build failure on amd64 platform

### ISSUE THREAD

**Issue by amanpatel** [apache/incubator-devlake#4525]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

I checked out the repo and attempted to build it via docker-compose. Followed instructions from the documentation. It fails because for some reason my machine is trying to execute stuff in the arm64 image. Even though my machine is amd64.

```
(snip)
 => => sha256:06124234fb3bce48fbef33f31b26bdd22923eeb52bdc6b8a374ee0edb1a78bce 7.11kB / 7.11kB                                                             0.0s
 => => sha256:aa54add66b3a47555c8b761f60b15f818236cc928109a30032111efc98c6fcd4 1.05MB / 54.59MB                                                            0.6s
 => CANCELED [base 2/6] RUN apt-get update &&     apt-get install -y python3-dev python3-pip tar curl libssh2-1 zlib1g &&     apt-get clean &&     rm -fr  0.6s
 => ERROR [debian-arm64 2/3] RUN apt-get update                                                                                                            0.4s
 => CANCELED [debian-amd64 2/3] RUN apt-get update                                                                                                         0.5s
------                                                                                                                                                          
 > [debian-arm64 2/3] RUN apt-get update:                                                                                                                       
#31 0.392 exec /bin/sh: exec format error
------
process "/bin/sh -c apt-get update" did not complete successfully: exit code: 1
ERROR: Service 'devlake' failed to build : Build failed
```

I looked at the `backend/Dockerfile` and I see arguments like TARGETPLATFORM and BUILDPLATFORM, but neither seems to control whether I can opt out of building a arm64 image.

Any help is appreciated :)

### What do you expect to happen

The build would finish properly.

### How to reproduce

- check out repo (on an intel machine, or otherwise amd64 platform)
- cp .env.example .env
- docker compose up

### Anything else

My platform:
```
Linux server 5.4.0-135-generic #152-Ubuntu SMP Wed Nov 23 20:19:22 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

Docker version
```
Docker version 20.10.21, build baeda1f
docker-compose version 1.29.2, build 5becea4c
```

### Version

main

### Are you willing to submit PR?

- [x ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by klesh** [comment]
@warren830 @matrixji please take a look at this

**Comment by amanpatel** [comment]
As I posted my docker-compose version is fairly old 1.29 vs 2.2.3 as mentioned by the documentation.

After I upgraded my docker-compose plugin to the latest version, I am no longer seeing this.

I will close the bug for now.
