### ISSUE TITLE
[Feature][infra] Refresh data in non-incremental manner to mitigate records being deleted in DataSource

### ISSUE THREAD

**Issue by klesh** [apache/incubator-devlake#4529]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar feature requirement.

### Use case

Records were deleted from the data source side and users want them gone in DevLake while keeping the time filter unchanged

### Description

Currently, we have `diffSync` activated by default without any user intervention, it works fine in most scenarios, however, records might be deleted from the Data Source but still exist in the DevLake database no matter how many times they try to recollect data due to the limitation of the `diffSync`.

To force a data refresh to remove those records, one would have to push the time filter to an earlier time to trigger a Data Purge Procedure to make things right, this is unintuitive and ugly.

We should design a Flow to allow users to Refresh Data explicitly.

### Related issues

#4864 #4762 

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by klesh** [comment]
@Startrekzky @yumengwang03 need prototype for user flow design.

**Comment by klesh** [comment]
API: add option to SyncPolicy
config-ui: adopts the option

**Comment by keon94** [comment]
Refreshing Data can now be accomplished by deleting a scope and re-adding it. So closing this.
