### ISSUE TITLE
[Bug][Framework] Removed data scopes are still in effect in sync tasks

### ISSUE THREAD

**Issue by hezyin** [apache/incubator-devlake#4538]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

Reported by a user in Slack: 

> When one edits the scopes attached to a blueprint and removes a data scope, the associated sync tasks, don't get removed/disabled. They keep running on the next sync

I haven't tried reproducing this issue locally, whoever picks this up please reproduce the issue first, thanks!

The user is on v0.15.1-beta5

### What do you expect to happen

See above

### How to reproduce

See above

### Version

v0.15.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by likyh** [comment]
![image](https://user-images.githubusercontent.com/3294100/223474589-f58393ec-a949-42b7-9bc4-44897c071d76.png)
![image](https://user-images.githubusercontent.com/3294100/223474826-e83f4a1c-ca86-47d1-bff3-ac3d264ff5a1.png)
I try these steps but haven't reproduced this issue:
1. add a new repo / delete a repo / replace a repo in gitlab
2. wait for the next cron run or run it manually
All these pipelines run with new repos(scopes). Do you mean the scope hasn't updated when clicking "rerun failed tasks"?
![image](https://user-images.githubusercontent.com/3294100/223475926-8f20941e-46e4-4eef-a27e-cced0c8beeba.png)
Or maybe you can add some more informations.

**Comment by klesh** [comment]
Closed by #4787
