### ISSUE TITLE
[Bug][plugins/bitbucket] Importing pr commits fails

### ISSUE THREAD

**Issue by kwaikul** [apache/incubator-devlake#4539]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

Importing Commits is failing for every PR for all repos. Verified token has all the read scopes as mentioned in the docs.

time="2023-02-28 02:04:05" level=info msg=" [pipeline service] [pipeline #1] [task #6] [collectApiPullRequestCommits] start api collection"
time="2023-02-28 02:58:49" level=warning msg=" [pipeline service] [pipeline #1] [task #6] retry #1 
calling repositories/{workspace}/{repository-slug}/pullrequests/<id>/commits
caused by: Http DoAsync error calling [GET repositories/{workspace}/{repository-slug}/pullrequests/{id}/commits]. Response: {"type": "error", "error": {"message": "Invalid page"}} (400)"

### What do you expect to happen

Task for pr comment collection is failing for all PRs, it should be able to pull commits for a PR. 

### How to reproduce

Use advanced mode with bitbucket and add a repo. 

### Anything else

When running bitbucket importer comments on PR successfully imported but commits step is failing. Stuck at tasks 6 of 25.

### Version

v0.15.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by mindlesscloud** [comment]
Thanks for your valuable feedback. It will be fixed in the incoming version

**Comment by mindlesscloud** [comment]
The bug is fixed by #4292, which will be cherry-picked to `relaese-v0.15` soon

**Comment by mindlesscloud** [comment]
After discussing it with the dev team, cherry-picking is nontrivial and may introduce new bugs. We decided to not cherry-pick it back to release-v0.15. Upon the v0.16.0 is releasing, you could resolve this problem by upgrading. 

I will close this ticket. Please feel free to reopen this ticket or start a new one if you need any further assistance.
