### ISSUE TITLE
[Bug][Jira] Jira Tickets with Epic as original type is not being loaded in the issue table. 

### ISSUE THREAD

**Issue by FaizanSh** [apache/incubator-devlake#4549]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

The **EPIC** type is not populating in domain layer from tool layer.

As can be seen in the tool layer table of '_tool_jira_issues' Epic type exists.
![image](https://user-images.githubusercontent.com/23335607/221868946-9761eb0d-fc37-4288-816d-9acf4d2e155a.png)

When the data gets loaded to the the domain layer table 'Issues', the EPIC type gets missed.
![image](https://user-images.githubusercontent.com/23335607/221869373-88c470de-926d-4996-92be-4c9ee2dccfee.png)

### What do you expect to happen

The Epic type should exist in the Issues domain layer table

### How to reproduce

Do the following queries to verify,

To Check if epic exist in the tool layer
select type from lake._tool_jira_issues group by type;

To Check if EPIC exist in the domain layer
select original_type from lake.issues group by original_type;

### Anything else

I have loaded data from 3 Boards and I couldn't get a single entry of epic in the domain layer.

### Version

v0.15.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by klesh** [comment]
Thanks for your report.

**Comment by klesh** [comment]
To be investigated after 6th Mar 2023
