### ISSUE TITLE
[Feature][BitBucket] Support BitBucket server version

### ISSUE THREAD

**Issue by Startrekzky** [apache/incubator-devlake#4568]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar feature requirement.

### Use case

I'm using a BitBucket self-hosted version and want to integrate BitBucket data with DevLake.

### Description

TODO:

- [ ] Research Auth differences between BitBucket server and cloud
- [ ] Research API differences between BitBucket server and cloud
- [ ] Determine the version to be supported
- [ ] Implementation

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by tim-goto** [comment]
I also would like to use bitbucket server. Do you have any hints on how to get started besides the plugin implementation in the developer manuals?

**Comment by batchenr** [comment]
> I also would like to use bitbucket server. Do you have any hints on how to get started besides the plugin implementation in the developer manuals?

I made an exporter using python bitbucket so you don't dont have to use plugin and you use the api instead

**Comment by tim-goto** [comment]
Do you have a repo link to your implementation? I couldn't find it on your profile.

**Comment by tim-goto** [comment]
Sorry @Startrekzky , this is low prio for me at the moment. I might pick it up at a later date if devlake is deemed useful by the devs in my team

**Comment by Startrekzky** [comment]
> Sorry @Startrekzky , this is low prio for me at the moment. I might pick it up at a later date if devlake is deemed useful by the devs in my team

No problem.

**Comment by tim-goto** [comment]
still an open issue

**Comment by tim-goto** [comment]
still important to me

**Comment by seumassoltysik** [comment]
Would love to see a plugin which supports BB server. At this point this is a blocker for us from being able to fully utilize DevLake as our company uses BB server.
Is there any work-around for not having a plugin based  solution?
For instance, I was wondering if one could write some custom code to populate some db tables with data from BB server and then point DevLake at the data directly.
Someone above mentioned something about an "exporter".
What exactly would that entail?

**Comment by tim-goto** [comment]
> > I also would like to use bitbucket server. Do you have any hints on how to get started besides the plugin implementation in the developer manuals?
> 
> I made an exporter using python bitbucket so you don't dont have to use plugin and you use the api instead

@seumassoltysik this might be easier than creating a plugin for bb server

**Comment by Startrekzky** [comment]
Hi @seumassoltysik @tim-goto You can look at how [bitbucket plugin](https://github.com/apache/incubator-devlake/tree/main/backend/plugins/bitbucket) is implemented. 

One of the major tasks for supporting a new version of BitBucket server is to check if the existing APIs used in the BitBucket (cloud) collectors also support the corresponding BitBucket Server version you use. May I ask what BitBucket Server version are you on?

**Comment by Startrekzky** [comment]
Hi @tim-goto , any updates about this issue? Let me know if you have any plan of attack.

**Comment by tim-goto** [comment]
Hey, sorry this has lost priority for my org (the managers have decided..). We are on `v7.21.14`.

**Comment by Startrekzky** [comment]
@tim-goto Got it. No problem👌

**Comment by seumassoltysik** [comment]
> > > I also would like to use bitbucket server. Do you have any hints on how to get started besides the plugin implementation in the developer manuals?
> > 
> > 
> > I made an exporter using python bitbucket so you don't dont have to use plugin and you use the api instead
> 
> @seumassoltysik this might be easier than creating a plugin for bb server



> Hi @seumassoltysik @tim-goto You can look at how [bitbucket plugin](https://github.com/apache/incubator-devlake/tree/main/backend/plugins/bitbucket) is implemented.
> 
> One of the major tasks for supporting a new version of BitBucket server is to check if the existing APIs used in the BitBucket (cloud) collectors also support the corresponding BitBucket Server version you use. May I ask what BitBucket Server version are you on?

We are using BB server version: 7.10.1

**Comment by seumassoltysik** [comment]
> > > I also would like to use bitbucket server. Do you have any hints on how to get started besides the plugin implementation in the developer manuals?
> > 
> > 
> > I made an exporter using python bitbucket so you don't dont have to use plugin and you use the api instead
> 
> @seumassoltysik this might be easier than creating a plugin for bb server

@tim-goto 
At a high level what would this exporter look like. 
Would it involve an out of band process for populating DevLake db/tables with BB data?
Relatively new to DevLake so have not had opportunity to fully dig into source code.

**Comment by tim-goto** [comment]
I am not quite sure about that, there are some python files in the devlake repo that do just that but for other services, those should get you started

**Comment by Startrekzky** [comment]
23.9.21 Updates: @tim-goto is integrating the BitBucket Server v7.21.14 and we're collaborating in Slack

**Comment by harshadapshankar** [comment]
Using BitBucket Server version v7.21.4.  Hope the work underway to integrate with BitBucket Server can support this version.  Will be happy to try out Beta version as well.

**Comment by leehoawki** [comment]
Using BitBucket Server version  v5.14.1. Hope the work underway to integrate with BitBucket Server can support this version as well.  Will be happy to try out Beta version as well. Thanks

**Comment by hmilkovi** [comment]
I'm also interested in this feature.

**Comment by ilian-cleverpine** [comment]
Hello @Startrekzky, we are willing and ready to take over the BitBucket server integration, please contact me.

**Comment by Startrekzky** [comment]
> Hello @Startrekzky, we are willing and ready to take over the BitBucket server integration, please contact me.

Hi @ilian-cleverpine , thanks for volunteering. We have a community member working on this issue now. Can you DM me in Slack so I can add you to the channel for BitBucket-server development?

**Comment by Startrekzky** [comment]
Nov 6th, 2023 Updates: 

1. Marais is working on this issue.
2. Since we have a variety of BitBucket Server versions, Marais's plan is to support the latest BitBucket v8.9 first, and then keep supporting the previous v8+ and v7+ versions (May be implemented by other contributors).
3. Please reach out to me in [DevLake's Slack community](https://join.slack.com/t/devlake-io/shared_invite/zt-18uayb6ut-cHOjiYcBwERQ8VVPZ9cQQw), I can add you to the BitBucket dev channel if you want to get first-hand updates about this issue.
