### ISSUE TITLE
[Bug][generator] incorrect import path in plugin template

### ISSUE THREAD

**Issue by jakezhu9** [apache/incubator-devlake#4584]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

I tried to create a new plugin following the instructions in the [docs](https://devlake.apache.org/docs/DeveloperManuals/PluginImplementation), but some of the code generated using the template had incorrect import paths. For example, the following import path was wrong:
```go
package main

import (
	"github.com/apache/incubator-devlake/plugins/trello/impl"
	"github.com/apache/incubator-devlake/runner" // incorrect
	"github.com/spf13/cobra"
)
```

I also discovered that this issue was caused by #3884.

### What do you expect to happen

correct import path, for example

```go
package main

import (
	"github.com/apache/incubator-devlake/plugins/trello/impl"
	"github.com/apache/incubator-devlake/core/runner"  // correct
	"github.com/spf13/cobra"
)
```

### How to reproduce

```
go run generator/main.go create-plugin test
```

### Version

main

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by klesh** [comment]
Yup, we had a quite huge directory relocation recently, #2078 , the plugin templates are yet to be updated.
Besides, the current implementation doesn't utilize the `text/template` package from the golang stdlib which should be taken care of as well  #4284
