### ISSUE TITLE
[Doc][README] some links in readme are outdated

### ISSUE THREAD

**Issue by jakezhu9** [apache/incubator-devlake#4605]
## Documentation Scope
the main README

## Describe the Change
Some links in Readme are no longer accessible, we should update or delete them

For example: https://github.com/apache/incubator-devlake/blob/4c91af298d83b772e35c06a3cd6b2e1188ce2a0f/README.md?plain=1#L37

I will submit a PR to fix it soon

**Comment by klesh** [comment]
Thanks for your contribution
