### ISSUE TITLE
[Doc][Community] Add more details to Development Workflow

### ISSUE THREAD

**Issue by magnusp** [apache/incubator-devlake#4609]
## Documentation Scope
The "Development workflow" is rather thin in regard to how a development environment should be set up. I was not able immediately build Devlake (via the Makefile) due to an unsatisfied library dependency.

## Describe the Change
Instructions on how to build and what external dependencies might be required.

## Additional context
Contribution depends on a great first experience.

**Comment by klesh** [comment]
Thanks for your report.
Would you like to share the specific problem you ran into?
Or It would be nice if you'd like to submit PR to the [apache/incubator-devlake-website: Apache Devlake Website](https://github.com/apache/incubator-devlake-website) 😊.
Thanks in advance.
