### ISSUE TITLE
[Feature][Pagerduty] Domain layer handling of Incident management data

### ISSUE THREAD

**Issue by keon94** [apache/incubator-devlake#4613]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar feature requirement.

### Use case

With added support for Pagerduty, an incident management system, we need to decide how to handle incidents at the domain layer for the calculation of DORA metrics. The current design directly maps an incident to a domain issue but this may not be desirable because issues are a source-control-management concept (Code entity).

### Description
Scope:
- Should incidents get their own table at the domain layer? Or should we expand the Issues table to contain extra fields for incidents? What should these fields be? How will the Dora plugin handle these new fields, and what will the Dashboard queries for them look like? These are the questions to answer for this ticket.
- Adapt Pagerduty's converter to this new design.

### Related issues

Blocked by #4220 and #4248 

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by keon94** [comment]
cc @klesh @Startrekzky

**Comment by Startrekzky** [comment]
@keon94 I sent a vote to the community, no one voted... Will send it again to collect more feedback today.

**Comment by Startrekzky** [comment]
We should create a `incidents` table in the domain layer according to the votes from the Slack community.  See https://devlake-io.slack.com/archives/C03APJ20VM4/p1679536502206839

**Comment by Startrekzky** [comment]
I'll close this issue as we've reached a consensus on this discussion. The following to-dos will be tracked in #4769.
