### ISSUE TITLE
[Feature][Infra] Data Retention/Size Limit

### ISSUE THREAD

**Issue by Startrekzky** [apache/incubator-devlake#4621]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar feature requirement.

### Use case

The old data accumulates and exceeds my DB size. I want DevLake to have the ability to (automatically) remove the old data (regularly).

### Description

Questions:
1. DB Size limit, what if I collect a lot of commits/issues, etc.
2. Time to store DB (time to collect or time that records get updated in the data source?)
3. What's the backup plan if DevLake accidentally deletes data due to bugs?
4. What's the backup plan if users accidentally delete data?

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Feggah** [comment]
This issue would be awesome.

I believe we could have some type of "Job" to delete data older than 6 months? Were there any discussion of this in the past?

**Comment by klesh** [comment]
@Feggah  Not really, just some rough ideas.

**Comment by keon94** [comment]
For (3), we could perform soft deletes instead of hard deletes from our code. And just have a cron job to hard delete the entries once in a while. This way if data is accidentally deleted, it's still in the DB for a while and it can be restored.
