### ISSUE TITLE
[Feature][CircleCI] Support CircleCI as a data source for the CI/CD domain

### ISSUE THREAD

**Issue by hezyin** [apache/incubator-devlake#4633]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar feature requirement.

### Use case

Multiple users requested CircleCI plugin for CI/CD domain and for calculating DORA metrics.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by keon94** [comment]
@Startrekzky Should we push this a future milestone?

**Comment by coldgust** [comment]
Hi, I want to try to finish it, pls assigin to me.

**Comment by klesh** [comment]
PR is pending , to be merged in v0.19
