### ISSUE TITLE
[Question][Grafana] Dora Performance Levels

### ISSUE THREAD

**Issue by julianolsdominguesTW** [apache/incubator-devlake#4634]
## Question
We would like to understand why the deployment frequency elite level is reached with 3 or more days with deployments according to the query, and not with 5 or more as we interpret it should be to be considered a daily deployment.

We attached a screenshot of the query and another one of the DORA table

<img width="1354" alt="image (6)" src="https://user-images.githubusercontent.com/117674056/224187352-d8425f9d-cf0b-4470-96fc-5df1b5a9bad8.png">
<img width="1073" alt="image (5)" src="https://user-images.githubusercontent.com/117674056/224187361-fc84ceef-5dff-4942-b338-8f55e4ce81e5.png">

**Comment by abeizn** [comment]
@Startrekzky help answer?

**Comment by julianolsdominguesTW** [comment]
> @Startrekzky help answer?
Any news on the question?

**Comment by Startrekzky** [comment]
Hi @julianolsdominguesTW 

There's no strict definition for daily in DORA's report. When I investigated into this, I found that the four keys project (maintained by the DORA team) uses '>3d per week' as daily, so I use this as the default value. But I guess you can modify it slightly based on your own workflow.
