### ISSUE TITLE
[Bug][Jenkins Plugin] Error when setting a data scope for Jenkins

### ISSUE THREAD

**Issue by smulhall** [apache/incubator-devlake#4647]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

When creating a Jenkins Blueprint, when adding a new data scope, the UI just hangs and the error in the console is:

REQ: http://localhost:4000/api/plugins/jenkins/connections/1/proxy/rest/api/json?tree=jobs[name,jobs]{0,10000}

RESP: {"success":false,"message":"invalid character '\u003c' looking for beginning of value\nWraps: (2) invalid character '\u003c' looking for beginning of value\nError types: (1) *hintdetail.withDetail (2) *json.SyntaxError","causes":null}

### What do you expect to happen

A list of Jenkins jobs to choose from should be displayed on screen.

### How to reproduce

- Create Jenkins Connection
- Create Jenkins Blueprint
- Set data scope
- Page contains a spinner

### Anything else

{"success":false,"message":"invalid character '\u003c' looking for beginning of value\nWraps: (2) invalid character '\u003c' looking for beginning of value\nError types: (1) *hintdetail.withDetail (2) *json.SyntaxError","causes":null}

### Version

main

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by klesh** [comment]
Thanks for the report, will look into it ASAP.

**Comment by mindlesscloud** [comment]
hi  @smulhall , tanks for your feedback. The error caused by the HTTP response was an HTML rather than a JSON. For the sake of locating the bug, I'm wondering if you could share with us the output of the following request.  Please replace the `username`, `password`, and `jenkinshost` with the correct values.

```shell
curl -i -u 'username:password' 'https://jenkinshost/api/json\?tree\=jobs\[name,jobs\]\{0,10000\}'
```

**Comment by smulhall** [comment]
Jenkins version: Jenkins 2.289.3
I checked the response and it is a JSON (just very large, over 7k jobs) I am not pasting response here as it contains sensitive info

**Comment by mindlesscloud** [comment]
Will this bug reappear if you create a new connection and use it to create a blueprint?
Please pay special attention to the Endpoint URL. If `https://myhost.com/path/to/jenkins/` was the URL of the Jenkins server, please make sure the Endpoint URL was filled with `https://myhost.com/path/to/jenkins/`
![image](https://user-images.githubusercontent.com/8455907/225641673-7c52df86-8de2-4c53-b0fa-9dbb7784db9b.png)

**Comment by mindlesscloud** [comment]
Let me explain in detail why a new connection should be created. Some users will put a web server in front of Jenkins, and only specific paths will be routed to Jenkins. In this case, In this case, it will pass the test connection step, but a 404 error will be encountered when listing jobs.  A 404 HTML page will be returned from the web server, which can explain the phenomenon observed so far, so we need to create a new connection and make sure the **Endpoint URL is correctly filled in** to rule out or confirm this suspicion.

**Comment by Startrekzky** [comment]
Feel free to reopen the issue if this bug still exists.
