### ISSUE TITLE
[Bug][Pipeline history] Log download fails with gateway timeout

### ISSUE THREAD

**Issue by aubertaa** [apache/incubator-devlake#4656]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

Trying to download log from pipeline history fails with a timeout error. It seems to be linked to a too short timeout configuration.

![image](https://user-images.githubusercontent.com/14087776/224940077-d0d9ecbb-eda3-4006-b9b3-386d8b969bc2.png)

Note: it is not systematic and download could pass sometimes.

### What do you expect to happen

Timeout should not be reached while gathering logs / creating archive so that download could be successful.

### How to reproduce

- trigger a pipeline with a lot of information (wide scopes i assume could be enough) and click on "download log button"
- i had the issue with a 72K log if this information could help

### Version

v0.15.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by klesh** [comment]
@aubertaa Thanks for the report
I think you are right, the default timeouts are 10s https://github.com/apache/incubator-devlake/blob/d11d1cb00d1e8db0491e2b0c3025982a7cd3822d/config-ui/nginx.conf#L17 , we should fix it
