### ISSUE TITLE
[Bug][Jenkins scopes] Trying to add jenkins scopes in a blueprint fails if at least one jenkins job contains URL specific chars

### ISSUE THREAD

**Issue by aubertaa** [apache/incubator-devlake#4657]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

hi
the jenkins scope selector fails when at least 1 job in the whole list contains '/' character. It tries to call jenkins API with non encoded job name which leads to a 404 error (see screen). This makes jenkins scope selection impossible:

![image](https://user-images.githubusercontent.com/14087776/224946562-acc97df4-8596-4c15-9902-27e3073b2714.png)

if i may suggest, var "repoId" should be URL encoded here as job name may contain "either reserved or potentially unsafe when used in URLs"  : https://github.com/apache/incubator-devlake/blob/d708a808c5808be330998c8bbdaf1e02b8d004d8/config-ui/src/plugins/components/data-scope/api.ts#L22

### What do you expect to happen

- URL specific chars should be encoded when repoId is used as a path parameter
- call to jenkins API should success for each existing job (or at least failure should not be a blocker to add other jobs in scope)

### How to reproduce

- link devlake with a jenkins instance containing a job named "test/myjob"
- try to add scope from this jenkins in a new blueprint

### Version

v0.15.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by d4x1** [comment]
Decoding path parameters is not a good idea, I think putting `repoId` in query string is a good way to solve this issue.
This will break the compatibility of API. 

As for the failure blocks following action, It shouldn't happen, because it's just a 404 error. Can you offer more information about  it?

**Comment by aubertaa** [comment]
hi,
thanks for this reply. Indeed letting you fully the choice of how to handle this case of handling URL specific chars in jenkins jobs names.
If this could help, here a recording showing : the 404 errors for job names containing "/" char + no selected scope whereas selection has been made and a message confirmed that changes were successfully saved.

![no scope for jenkins](https://user-images.githubusercontent.com/14087776/225016498-ce92af6d-2661-4b3c-a902-7f25bb02db63.gif)

Thanks

**Comment by d4x1** [comment]
> hi, thanks for this reply. Indeed letting you fully the choice of how to handle this case of handling URL specific chars in jenkins jobs names. If this could help, here a recording showing : the 404 errors for job names containing "/" char + no selected scope whereas selection has been made and a message confirmed that changes were successfully saved.
> 
> ![no scope for jenkins](https://user-images.githubusercontent.com/14087776/225016498-ce92af6d-2661-4b3c-a902-7f25bb02db63.gif) [ ![no scope for jenkins](https://user-images.githubusercontent.com/14087776/225016498-ce92af6d-2661-4b3c-a902-7f25bb02db63.gif) ](https://user-images.githubusercontent.com/14087776/225016498-ce92af6d-2661-4b3c-a902-7f25bb02db63.gif) [ ](https://user-images.githubusercontent.com/14087776/225016498-ce92af6d-2661-4b3c-a902-7f25bb02db63.gif)
> 
> Thanks

The success message is really confusing. It looks like  this message doesn't  depend on API's success(or any other) response, just a wrong state transformation.

**Comment by d4x1** [comment]
I can help to fix the backend API, but we'd better get some advice from the core maintain team.

**Comment by klesh** [comment]
@aubertaa we tried to reproduce the problem and ran into a problem, seems like the jenkins would allow us to do so:
![img_v2_619d8868-8eea-45d9-9ec8-c37a092cc9cg](https://user-images.githubusercontent.com/61080/225274956-5003487e-1c03-483b-af80-6a52c32ec0d8.jpg)
![img_v2_1220bab3-3581-4c51-af75-ac60fb648d1g](https://user-images.githubusercontent.com/61080/225274978-5bda7684-bce3-4acf-8aa8-dc662eb0160d.jpg)

What is your jenkins version and how did you create that specific scope?

**Comment by aubertaa** [comment]
you may create "multibranch pipeline" and create a new branch named with a "/" in your git repository.
Then scan your branches from jenkins, it will create a job named like the branch.
Regards,

**Comment by klesh** [comment]
Hi, @aubertaa , thanks for the quick response, we might have to solve the problem later due to limited bandwidth.
