### ISSUE TITLE
[Bug][Dashboard] Wrong bug title in the Sonarqube dashboard

### ISSUE THREAD

**Issue by ibrahimejaz** [apache/incubator-devlake#4672]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

Happen to see there where mismatch informations on getting data from Reliability and few other metrics using Sonarqube dashboard. 
Also checked with sorting date range and still same. 

### What do you expect to happen

Sonar bug information is not properly displaying on the sonarqube dashboard

### How to reproduce

Sonar bug information is not properly displaying on the sonarqube dashboard

### Version

main

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by klesh** [comment]
Thanks for your report, will look into is ASAP

**Comment by warren830** [comment]
Hi @ibrahimejaz , can you provide more detail? And what is your mysql configuration? Can you check two configs as below?      
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_bin

**Comment by warren830** [comment]
Hi @ibrahimejaz , can you run the following scripts to change collation, then run the sonarqube bp again:
ALTER TABLE _tool_sonarqube_projects CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;
ALTER TABLE _tool_sonarqube_issues CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;
ALTER TABLE _tool_sonarqube_issue_code_blocks CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;
ALTER TABLE _tool_sonarqube_hotspots CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;
ALTER TABLE _tool_sonarqube_file_metrics CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;
ALTER TABLE _tool_sonarqube_accounts CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;
ALTER TABLE cq_projects CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;
ALTER TABLE cq_issues CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;
ALTER TABLE cq_issue_code_blocks CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;
ALTER TABLE cq_file_metrics CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;

**Comment by ibrahimejaz** [comment]
Have updated the DB but still see the data missing when compared it with actual sonarqube dashboard and devlake/sonarqube dashboard.

**Comment by abeizn** [comment]
> @ibrahimejaz 
After updating the database, whether to rerun the blueprint of sonarqube?

**Comment by ibrahimejaz** [comment]
Yes I've rerun transformation again @abeizn

**Comment by abeizn** [comment]
> 
@ibrahimejaz 
Sorry, I missed the news, we are now upgraded to [v0.16.0](https://github.com/apache/incubator-devlake/releases/tag/v0.16.0) official version or [v0.17.0-beta4](https://github.com/apache/incubator-devlake/releases/tag/v0.17.0-beta4), these versions have fixes for sonarqube.

**Comment by Startrekzky** [comment]
This issue has been solved. Feel free to reopen it if it still exists.
