### ISSUE TITLE
[Doc][swagger] api parameter is not accurate

### ISSUE THREAD

**Issue by narrowizard** [apache/incubator-devlake#4699]
## Documentation Scope
This issue is related to the accuracy and correctness of devlake's Swagger documentation, specifically for the "create jira connection" API endpoint.

## Describe the Change
The "create jira connection" API endpoint documentation currently includes three extraneous fields, namely id, createdAt, and updatedAt. These fields should not be included as they are not necessary for creating a new Jira connection.

The Swagger documentation needs to be updated to remove these extra fields and to provide concise and clear instructions on the required parameters and their expected types. This will ensure that users can properly use this endpoint with the correct parameters without any confusion.

## Screenshots
![dd7e12f8-e40b-4eaa-bcd6-1a05bd0d4b4f](https://user-images.githubusercontent.com/11383928/225831357-f9b34141-d455-4d78-aced-997b474897e0.jpeg)

## Additional context
To resolve this issue, it is recommended that someone from the devlake team reviews the API endpoint's Swagger documentation and makes the necessary changes to remove the unnecessary fields.

It would also be helpful to remind users to refer to the updated documentation when creating any new Jira connections through the devlake platform. This can help prevent issues caused by using incorrect or outdated API documentation.

Additionally, similar issues have been found in the Swagger documentation for other data sources, such as Tapd, suggesting that there may be a more general problem with the Swagger documentation.

**Comment by Startrekzky** [comment]
Can we find an automated way to check if the Swagger docs are aligned with DevLake APIs? @klesh 

Not sure if this plugin helps. https://doc.arcgis.com/en/arcgis-earth/automation-api/automation-api-help-page-with-swagger.htm

**Comment by klesh** [comment]
> Can we find an automated way to check if the Swagger docs are aligned with DevLake APIs? @klesh
> 
> Not sure if this plugin helps. https://doc.arcgis.com/en/arcgis-earth/automation-api/automation-api-help-page-with-swagger.htm

No, they are doing the same thing just like us, offering an automatic swagger doc, nothing more.
