### ISSUE TITLE
[Bug][Sonarqube plugin] Error 500 on trying to add too many projects

### ISSUE THREAD

**Issue by aubertaa** [apache/incubator-devlake#4716]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

I checked many projects to add to data scope from sonarqube. (around 150 projects corresponding to different technical components). Then clicking on 'save' button, nothing happens.
the network panel show this error : 

"error on saving SonarqubeProject\nWraps: (2) Error 1406: Data too long for column 'project_key' at row 23\nWraps: (3) Error 1406: Data too long for column 'project_key' at row 23\nError types: (1) *hintdetail.withDetail (2) *hintdetail.withDetail (3) *mysql.MySQLError"

Would it possible to allow inserting more projects ? and/or inform the user about the limitation instead of throwing a 500.
Regards,

### What do you expect to happen

insert in database should be successful.

### How to reproduce

- add sonarqube connection
- try to add a lot of projects in data scope
- click on 'save'

### Version

main

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by likyh** [comment]
It seems like there is a project with `ProjectKey` longer than 64. But I think `ProjectKey` is a uuid like `cedc509c-0000-1111-2222-33335cdf0c22`. Would you like to confirm what happened in the 23rd Project you choosed?
![image](https://user-images.githubusercontent.com/3294100/226386688-3c19bcf8-b7c4-4510-9242-97f38a620fd0.png)

**Comment by aubertaa** [comment]
I checked and max length i have as a prokect key in sonarqube is indeed 77. The key is not a guid, it could be anything.
Here is what is allowed in sonarquber server :

`Up to 400 characters. Allowed characters are alphanumeric, '-' (dash), '_' (underscore), '.' (period) and ':' (colon), with at least one non-digit.`

**Comment by likyh** [comment]
@aubertaa Which version does your Sonar is? 8.X?

**Comment by aubertaa** [comment]
i'm indeed in Version 8.9.2 (build 46101), planning to update to last LTS 9 soon.
Thanks
