### ISSUE TITLE
[Feature][config ui] Add new connection in existing blueprint

### ISSUE THREAD

**Issue by aubertaa** [apache/incubator-devlake#4717]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar feature requirement.

### Use case

It could be nice to be able to add a connection with an external tool in a existing blueprint. For example, you just released sonarqube connection (in 0.16) and there is no possibility to add this in an existing blueprint.
Recreating each blueprint to add a connection is a bit over costy.
Thanks.

### Description

It could be nice to :
- open an existing blueprint to edit it
- add a new connection
- choose data scope for this new connection

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by likyh** [comment]
Yes, we are planing to add new feature 「Blueprint Editing」 in 0.17

**Comment by mintsweet** [comment]
Hi, @aubertaa, this pr #4741 implements this feature and will be applied in 0.17.
