### ISSUE TITLE
[Question][Domain Layer] What does 'time_spent_minutes' mean?

### ISSUE THREAD

**Issue by coldgust** [apache/incubator-devlake#4718]
## Question
I reference the filed `time_spent_minutes` in `issues` table on `Issue Tracking` domain, but it's description  looks wrong. It has the same description as the previous row.

## Screenshots
![image](https://user-images.githubusercontent.com/115207009/226369496-9e886117-f74b-4cdc-b474-92bcd0f36137.png)

## Additional context
Add any other context here.

**Comment by klesh** [comment]
@coldgust you are right, the description is incorrect, it is the ACTUAL time spent
