### ISSUE TITLE
[Feature][Domain] Support multiple assignees for issues in the issue tracking domain

### ISSUE THREAD

**Issue by narrowizard** [apache/incubator-devlake#4738]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar feature requirement.

### Use case

As a DevOps team, we use TAPD as our issue tracking tool, which supports multiple assignees for a single task. However, the current schema of the issue tracking domain in DevLake only supports one assignee per task. We need DevLake to support multiple assignees for issues to better reflect our real-world workflows.

### Description

Currently, when we collect data from TAPD through DevLake, we are not able to properly capture multiple assignees for a single task. This creates ambiguity and can make it difficult to accurately track the ownership and progress of an issue. Therefore, we would like to request that DevLake updates the schema of the issue tracking domain to support multiple assignees for tasks.

We understand that this change may impact other parts of the system and require changes to the data ingestion process. As such, we recommend that this feature request be prioritized as high and are willing to work closely with the DevLake development team to ensure a smooth integration.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by klesh** [comment]
Thanks for volunteering. I think we should add a table named `issue_assignees (issue_id, assignee_id, assignee_name)` and update all plugins according.

What do you guys think? 
@narrowizard  @Startrekzky

**Comment by narrowizard** [comment]
- `issue_assignees` looks good to me. @klesh   
- We expect this feature to be completed in version 0.18 (before 4.30), do you have enough time to develop it? @coldgust
