### ISSUE TITLE
[Bug][Config-UI] Error: Miller-columns-select duplicate ID in items

### ISSUE THREAD

**Issue by amanpatel** [apache/incubator-devlake#4751]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

Received an error message `Error: miller-columns-select: Duplicate ID in items` when trying to setup a new blueprint.

<img width="388" alt="Cursor_and_Notification_Center" src="https://user-images.githubusercontent.com/226976/227046203-dd15963a-b410-4bb4-97c2-49e8fe305217.png">

### What do you expect to happen

Wanted to be able to setup the blueprint by selecting the repositories in the list.

### How to reproduce

I believe this might be a frontend issue that requires unique IDs among groups/projects. Gitlab does shares IDs between groups & repos, which might be causing the issue. Here is how I reproduced it in my local environment:

- Setup Gitlab connection to my self hosted gitlab instance
- The PAT has full access to the group & its repos (api/read_api/write_api and even the read_repo/write_repo)
- Add project
- create Blueprint / add data connection  | Click next step 
- Add scope
- Select the "group", and received the error message.

### Anything else

I've posted a full recreation video via Slack in private channel. It is very likely this is a gitlab specific issue, but should be addressable in the code since the miller select column component can use namespaced-IDs to avoid collisions.

### Version

main

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Startrekzky** [comment]
Hi @amanpatel , may I ask in which version did you find this bug?

**Comment by hezyin** [comment]
@Startrekzky @amanpatel confirmed in Slack that he was on v0.15.x and he has upgraded to v0.16.0-beta10. This issue has already been fixed in v0.16.0-beta10 and thus can be closed.
