### ISSUE TITLE
[Bug][Config-UI] Configuring GitLab data scopes gets error: TypeError Cannot read properties of null (reading 'gitlabId')

### ISSUE THREAD

**Issue by hezyin** [apache/incubator-devlake#4754]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

On v0.16.0-beta9, when selecting certain GitLab data scopes during creating a blueprint, I ran into the following error:

<img width="756" alt="Screen Shot 2023-03-21 at 11 42 45 AM" src="https://user-images.githubusercontent.com/2908155/227093545-158b5f89-8918-464e-b840-a315fdcb5c12.png">

Notice how the checkboxes of the first 3 repos on the 3rd column were grayed out in the following screenshot:

<img width="960" alt="Screen Shot 2023-03-21 at 11 43 11 AM" src="https://user-images.githubusercontent.com/2908155/227093596-6edbae19-13d6-4848-bbd5-e4fe003ea69e.png">

I can select other repos without issue:

<img width="946" alt="Screen Shot 2023-03-21 at 11 43 17 AM" src="https://user-images.githubusercontent.com/2908155/227093779-06b1fc81-c412-41d2-bcb4-12265c0f271e.png">

But when I try to select the ones whose checkboxes were grayed out, I ran into the error above.

### What do you expect to happen

I'm able to select all displayed GitLab data scopes.

### How to reproduce

See above.

### Version

main

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by mintsweet** [comment]
hi, @hezyin
Looks like a previous issue, what version are you using? Have you cleared the cache?

**Comment by hezyin** [comment]
@mintsweet I'm certain it's not due to cache. I was still able to reproduce this exact bug on a fresh instance of v0.16.0-beta14 in Incognito mode.

**Comment by hezyin** [comment]
It turned out this is not a bug. `code-analytics` cannot be directly selected since it's not a repo, but a group.

**Comment by batjko** [comment]
I am getting the exact same error, but pretty sure I'm selecting repos, since groups are always greyed out and not selectable.
`TypeError: Cannot read properties of null (reading 'gitlabId')`

It's particularly frustrating after selecting a few dozen repos already, clicking through the various levels and then having to redo it again every time.

![image](https://user-images.githubusercontent.com/7287076/235089194-5cd988f1-8663-490c-9499-d4237113abca.png)
v0.16.0-beta17
