### ISSUE TITLE
Deployement Frequency to be viewed as Daily or weekly as well

### ISSUE THREAD

**Issue by Afig08** [apache/incubator-devlake#4757]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar feature requirement.

### Use case

As a DevOps Engineer I would like to be able to track my Deployment frequency on a daily or weekly basis

### Description

the proposed solution is to be able to change the DF from monthly to weekly or even daily in Grafana

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by mappjzc** [comment]
@Afig08 Thanks for your issues.
![image](https://user-images.githubusercontent.com/2921251/227404595-14fa1a40-3b80-492d-bec0-acd6dae2a06d.png)
you can edit the board.
![image](https://user-images.githubusercontent.com/2921251/227405178-cbad826d-d346-4d21-9af1-dc60cea1044a.png)
![image](https://user-images.githubusercontent.com/2921251/227405268-d7ce1d95-0d57-4582-9a43-c10a65f57dd2.png)
And rewrite the SQL of it as you like.
