### ISSUE TITLE
[Bug] ldap_access of type string 

### ISSUE THREAD

**Issue by eMurgaNd** [apache/incubator-devlake#4790]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

I receive the following error when trying to "Set Data Scope" in the DevLake UI. Note that I removed the JSON blob due to some sensitive information in it. So you just seen [].
```
time="2023-03-24 23:18:46" level=error msg="HTTP 500 error
caused by: error decoding response from https://gitlab/api/v4/groups?page=1&per_page=100&top_level_only=true: raw response: []
Wraps: (2) json: cannot unmarshal number into Go struct field GroupResponse.ldap_access of type string
Wraps: (3) json: cannot unmarshal number into Go struct field GroupResponse.ldap_access of type string
Error types: (1) *hintdetail.withDetail (2) *hintdetail.withDetail (3) *json.UnmarshalTypeError"
```

The JSON field ldap_access for our installation returns back an integer for example `"ldap_access":50`

### What do you expect to happen

I expect the Set Scope UI to load all the projects I have access to, but instead it just spins and doesn't load anything. Also there is no error in the UI only the log file.

### How to reproduce

Unfortunately, I don't know what makes our GitLab installation unique. It's self hosted and setup with LDAP integration. So for me to reproduce the issue all I have to do it go to the "Set Data Scope" page for a blueprint. 

### Anything else

This is with 0.16.0-beta10. I wasn't able to select that in the version dropdown for this issue.

### Version

main

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by klesh** [comment]
Looks like we have `ldap*` fields defined but nowhere uses them.
I think we should remove them.
