### ISSUE TITLE
[Feature][Plugins] Request for GitHub Integration Using GitHub Apps

### ISSUE THREAD

**Issue by mtahle** [apache/incubator-devlake#4801]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar feature requirement.

### Use case

As an SRE, I am concerned about the security and flexibility of our project's integration with GitHub. With this feature, we can manage permissions more efficiently, reduce security risks, and enhance the integration's functionality.

### Description

Integrating with GitHub using GitHub Apps instead of personal access tokens for better security and more flexibility.

### Related issues

#4537

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Startrekzky** [comment]
Thanks for the proposal, @mtahle
