### ISSUE TITLE
[Refactor][Build] Unify common parts of CI and Prod Dockerfile into base images and automate Prod image builds

### ISSUE THREAD

**Issue by keon94** [apache/incubator-devlake#4805]
## What and why to refactor
The prod Dockerfile (devlake) and CI Dockerfile (lake-builder) share a lot of dependencies, and are built on top of a Go (Alpine) and Python (Debian) base image. This, as a result, leads to quite a bit of duplicate code between these two.

## Describe the solution you'd like
1. Create two Dockerfiles for each of the base images mentioned above to install the common dependencies into each of them. The Prod and CI Dockerfiles should then inherit from these images instead.
2. Move the Prod Dockerfile to the devops directory to be consistent with the other Dockerfiles.
3. Create a Github workflow to trigger pushing it to Dockerhub and support the "latest" tag. , I suggest versioned images be only based on pushed tags similar to CI, and "latest" for both that and main branch builds. Update Readme accordingly.

**Comment by klesh** [comment]
@keon94 we should update the `latest` tag only for `formal` releases, e.g. v0.16.1/0.17.0 those without suffixes.

**Comment by keon94** [comment]
@klesh Should we use a custom tag then? Like `dev`?

**Comment by klesh** [comment]
> @klesh Should we use a custom tag then? Like `dev`?

When will we update the `dev` tag?

**Comment by keon94** [comment]
@klesh I was thinking after every merge to main we run the job on the main branch.

**Comment by klesh** [comment]
@keon94 I see, who would be using this `dev` for what purposes?
