### ISSUE TITLE
[Question][Module Name] Pls help with reg. how production deployment will be calculated

### ISSUE THREAD

**Issue by ibrahimejaz** [apache/incubator-devlake#4810]
Hi,
Just wondering how does production deployments calculated it does calculates all the job names when comes to deployments in DORA dashboard when we mention the job name, but if we mention the same in production field its not calculating, can someone help shed ideas to implement if I want to only show production deployments in DORA dashboard, yes have followed the documentation by devlake.. but not able to view using version v0.16.0-beta4

**Comment by warren830** [comment]
> 

Hi, can you give us more detail? Which tool are you calculating? Github?Gitlab? or Jenkins?

**Comment by ibrahimejaz** [comment]
We're using github.

**Comment by klesh** [comment]
@ibrahimejaz 0.17 beta is out now, please try it out and see if the problem fixed, thanks.
