### ISSUE TITLE
[Feature][Config UI] Provide the new UI for issue-repo-commit configuration in Jira

### ISSUE THREAD

**Issue by Startrekzky** [apache/incubator-devlake#4821]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar feature requirement.

### Use case

Provide the UI for #4463

### Description

To Do:
- [ ] Allow users to type in the pattern of commit urls
- [ ] Allow users to enter multiple commit urls by clicking 'Add a Rule'

![image](https://user-images.githubusercontent.com/14050754/229100326-23f7534f-09b8-49e9-b0b7-c79cc667fc98.png)

![image](https://user-images.githubusercontent.com/14050754/229100374-f364d80e-3db4-475f-8e63-dd06ea722133.png)

### Related issues

#4463 
#4304 

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by mintsweet** [comment]
@yumengwang03 Could you please tell us the prototype link?
