### ISSUE TITLE
[Feature][SonarQube Connection] Add support for SonarCloud

### ISSUE THREAD

**Issue by alexvaccaro** [apache/incubator-devlake#4838]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar feature requirement.

### Use case

Add support SonarCloud along with SonarCube

Hopefully this is not a big ask, SonarCloud is the cloud hosted version of SonarCube and most of the apis are the same.

I have tried setting up a connection but unfortunately the list of projects comes back empty, for what I can see that's becaus efor SonarCloud the `organisation` parameter [is required](https://sonarcloud.io/web_api/api/projects?deprecated=false), yet the SonarCube connection wizard does not capture this parameter.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by klesh** [comment]
Thanks for your suggestion, @Startrekzky @yumengwang03 @hezyin  please take a look at this.

**Comment by Startrekzky** [comment]
Collecting votes

**Comment by alexvaccaro** [comment]
I see the issue has been tagged with 'add-a-plugin', however this could be potentially handled with the existing SonarCube plugin and have an optional 'Organisation' parameter to inject in the URIs if supplied

**Comment by Startrekzky** [comment]
> I see the issue has been tagged with 'add-a-plugin', however this could be potentially handled with the existing SonarCube plugin and have an optional 'Organisation' parameter to inject in the URIs if supplied

I agree and have removed the label.

**Comment by BrookeKatalon** [comment]
We're definitely interested as well - would be easier if the existing plugin could be adapted, or as second one that's sonarcloud-specific.

**Comment by Startrekzky** [comment]
@klesh It seems we got 4 (3+1) votes now. I'll plan it in the next few versions.

**Comment by klesh** [comment]
LGTM

**Comment by Ragavendira1** [comment]
Dear team, we are looking out sonarcloud integration. Therefore kindly provide us update when we will able to see sonarcloud data into devlake

**Comment by lhart-intelycare** [comment]
Another vote from me!

**Comment by sztukamichal** [comment]
Devlake looks great. I also vote on this functionality.

**Comment by rhanton** [comment]
I'm looking at how much devlake could help our org, but SonarCloud integration would make it quite amazing for us! Upvote from me!

**Comment by rhanton** [comment]
Ping! Is this still possible? Anyone with time to look at it? We might have time for someone on the team to investigate in 2024.

**Comment by abeizn** [comment]
@Startrekzky

**Comment by madibaT** [comment]
Upvote from me

**Comment by wanisfahmyDE** [comment]
+1

**Comment by leandrofrs** [comment]
+1

**Comment by jhonjimenezmatrix** [comment]
+1 we need it!

**Comment by gdolfen** [comment]
+1

**Comment by Startrekzky** [comment]
Any volunteers? We don't have the bandwidth to do this, and we don't have an account for SonarCloud either.

**Comment by UncleLeoTheDad** [comment]
I started to explore this as I am a SonarCloud user.  If you have any shortcuts to get started, I'd appreciate it.

I see this is the current plugin: https://github.com/apache/incubator-devlake/tree/main/backend/plugins/sonarqube

And I followed the "Develop a plugin" link on the main page to start:
https://github.com/apache/incubator-devlake

But I ended up at a dead link. :(
https://github.com/apache/incubator-devlake/blob/main/backend/DevelopmentSetup

**Comment by tonyjw** [comment]
Hi @UncleLeoTheDad I believe the right link is this: https://github.com/apache/incubator-devlake/blob/main/backend/DevelopmentManual.md

**Comment by rhanton** [comment]
@Startrekzky I'll see if someone on our team can take a look. We "finally" got a devlake instance running for our teams, so should be easy-er to test whatever we put together.

**Comment by tc-jason-gregory** [comment]
+1

**Comment by HumSeto** [comment]
+1

**Comment by Startrekzky** [comment]
> I started to explore this as I am a SonarCloud user. If you have any shortcuts to get started, I'd appreciate it.
> 
> I see this is the current plugin: https://github.com/apache/incubator-devlake/tree/main/backend/plugins/sonarqube
> 
> And I followed the "Develop a plugin" link on the main page to start: https://github.com/apache/incubator-devlake
> 
> But I ended up at a dead link. :( https://github.com/apache/incubator-devlake/blob/main/backend/DevelopmentSetup

Sorry, I just saw your comment. Could you join the Slack community so that we can work more closely? 
https://join.slack.com/t/devlake-io/shared_invite/zt-18uayb6ut-cHOjiYcBwERQ8VVPZ9cQQw

**Comment by Startrekzky** [comment]
Hi @UncleLeoTheDad . I am sorry. I just saw your comment. Could you join the Slack community so that we can work more closely if you're still looking at it? Thank you.
https://join.slack.com/t/devlake-io/shared_invite/zt-18uayb6ut-cHOjiYcBwERQ8VVPZ9cQQw

**Comment by UncleLeoTheDad** [comment]
Hi @Startrekzky : tried that link, but it looks like it expired:
![image](https://github.com/apache/incubator-devlake/assets/141352/58b0be17-d725-4937-a04b-92ea5d20cb6f)

**Comment by wanisfahmyDE** [comment]
here you go https://join.slack.com/t/devlake-io/shared_invite/zt-20envwfbk-JUTZ4z9jSeRnrvNhBFLg9w

**Comment by jcorremo** [comment]
Upvote from me

**Comment by mintsweet** [comment]
Hi @lhart-intelycare, 

In response to your inquiry about how config-ui handles the implementation of two different SonarQube modes:

Modifying existing fields, such as "endpoint," is not advisable as it may impact other plugins. If a new field is introduced in SonarQube Cloud, the best approach is to create a new component specifically for this field, similar to [the authentication component used in Jira](https://github.com/apache/incubator-devlake/blob/f27c31f3954bb4d5df8c6a4e829acfdedf36174a/config-ui/src/plugins/register/jira/connection-fields/auth.tsx).

Within the new component, you can retrieve the value of the "endpoint" to ascertain whether the "organization" field is required.

**Comment by lezgin-bakircioglu-qred** [comment]
adding a comment to keep this one alive as there is some progress :)

**Comment by justinphelps** [comment]
Any luck? I saw that someone had PR that should enable Sonarcloud.

**Comment by lhart-intelycare** [comment]
That was me.  I paused on that completed work, shared it with devinsight and they are actively working on enabling the feature (either using my code or starting from scratch) now.  Should be coming soon!
