### ISSUE TITLE
[Refactor][Plugins] We need to unify all endpoints

### ISSUE THREAD

**Issue by warren830** [apache/incubator-devlake#4842]
## What and why to refactor

Currently, our API endpoints are not consistent in their structure. Some endpoints have only the domain, while others include common suffixes (such as version numbers) or even additional common prefixes shared by all API endpoints. This inconsistency can lead to confusion and make it harder to maintain and understand the API.

Refactoring the API endpoints to follow a consistent structure would improve readability, maintainability, and make it easier for developers to work with the API.

Here are some examples:
Github: `https://api.github.com/`
Gitlab: `https://gitlab.com/api/v4/`
Although they are different, but within collector tasks, url are similar: `repos/*` or `projects/*`

Jira: `https://your-domain.atlassian.net/rest/`
Jenkins: `https://api.jenkins.io/`
Tapd: `https://api.tapd.cn/`
Zentao: `http://subdomain.domain:port/api.php/v1/`

## Describe the solution you'd like

We should standardize the structure of our API endpoints. 
1. limit all endpoints to the domain 
2. use the longest common substring among all endpoints. 
3. use default endpoint from data source system -- this might be the best way
 
This will make our API more consistent and easier to work with.

For example, if we choose to include nothing in all endpoints, the structure could look like this:

- `http://DOMAIN:PORT/`

if we choose to include the version number in all endpoints, the structure could look like this:

- `http://DOMAIN:PORT/v1/resource1`
- `http://DOMAIN:PORT/v1/resource2`

If we decide to use the longest common substring, it could look like this:

- `http://DOMAIN:PORT/api/v1/resource1`
- `http://DOMAIN:PORT/api/v1/resource2`

Before implementing the changes, we should discuss and agree on a standard that works best for our use case.

## Additional information:
If we want to unify all endpoints, we may need to 
1. perform data migration (modify endpoints) for all existing plugins
6. modify the URLs in all collector tasks, 
7. and as a result, users may be prone to operational errors for a period of time.

**Comment by keon94** [comment]
I think a better title for this would be "We need to standardize all datasource endpoints" based on my understanding of this request.

**Comment by keon94** [comment]
So essentially it'll become the responsiblity of the backend code to append the correct URL base-path when doing TestConnection() and PrepareTaskData()?

**Comment by klesh** [comment]
> So essentially it'll become the responsiblity of the backend code to append the correct URL base-path when doing TestConnection() and PrepareTaskData()?

It is one way to do it, or we could just prepend the "common path" to every subtasks, it would be easier to understand without digging around
