### ISSUE TITLE
[Bug][Config-UI] Refdiff parameter setting error in transformation

### ISSUE THREAD

**Issue by mintsweet** [apache/incubator-devlake#4846]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

`tagsLimit` in refdiff is wrongly set to `tagsOrder`.

### What do you expect to happen

Set wrong `tagsOrder` back to `tagsLimit`.

### How to reproduce

1. Create a transformation for GitHub.
2. Create a blueprint including the above GitHub transformation.

### Version

main

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by JoshuaPoddoku** [comment]
Hey @mintsweet @likyh did we cherry pick this fix?

**Comment by hezyin** [comment]
@JoshuaPoddoku Yes, it's been cherry picked to https://github.com/apache/incubator-devlake/releases/tag/v0.16.0-beta13
