### ISSUE TITLE
[Bug][Backend] Crashed on backend debugging when it loads plugins

### ISSUE THREAD

**Issue by john-deng** [apache/incubator-devlake#4860]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

Crashed on backend debugging, plugin.Open("bin/plugins/ae/ae"): plugin was built with a different version of package runtime/internal/atomic

![image](https://user-images.githubusercontent.com/6748475/229863771-52abc5fb-6fe5-4e92-94fb-a7579c53dbde.png)

### What do you expect to happen

Continue to run backend server

### How to reproduce

1. make all plugins

```bash
make build-plugin
```

2. debug backend server on Goland

### Version

main

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by keon94** [comment]
Hi @john-deng. This might be happening if you compiled *.so plugins without debugging symbols but you start the server in debug mode. Try running `make build-plugin-debug` instead.
