### ISSUE TITLE
[Feature][Framework] Support for Project, Blueprint and Scope deletion

### ISSUE THREAD

**Issue by keon94** [apache/incubator-devlake#4864]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar feature requirement.

### Use case

Deleting projects,  blueprints and scopes is currently unsupported. This ticket will capture the R&D necessary to support this feature.

### Description

There are technical challenges involved with this. The main question is, how can we purge all the domain-level data associated with a blueprint once we delete that blueprint? We need a way to perform that mapping so we know what to delete from the database.

### Child issues

Scope deletion (PagerDuty + AzureDevops): #4762 
UI work: #4388
Blueprint deletion PR: #5227 
Project deletion PR: #5289 
Scope deletion (Other plugins): #5277 

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by keon94** [comment]
I'm assigning this to myself. cc @Startrekzky

**Comment by yumengwang03** [comment]
Hi @keon94 here is some additional info: in v0.18, we will (most likely) move data scope and transformation to be managed at the data connection level, and Blueprints will only retain its association with the data scope, meaning that adding and deleting data scope need to be done in each data connection, not from the Blueprint anymore. Deleting data scope from a Blueprint doesn't delete the data scope, but delete its association with the Blueprint.

**Comment by keon94** [comment]
@yumengwang03 @Startrekzky Will it make more sense to repurpose this ticket to delete data based on scopes instead? Doing so will prevent data from getting tied the blueprint that created them

**Comment by yumengwang03** [comment]
Adding the prototypes here:
<img width="1412" alt="Screen Shot 2023-05-11 at 5 10 02 PM" src="https://github.com/apache/incubator-devlake/assets/9535430/96615030-6af3-462a-86c8-fe36e7f1e20d">
<img width="1603" alt="Screen Shot 2023-05-11 at 5 10 34 PM" src="https://github.com/apache/incubator-devlake/assets/9535430/b95fef22-2e95-4b42-b21f-11e76e65c84c">
