### ISSUE TITLE
[Refactor][dora] Change Lead Time doesn't include Jenkins deployment and other data correctness issues

### ISSUE THREAD

**Issue by klesh** [apache/incubator-devlake#4869]
## What and why to refactor
1. #4825 indicates that deployment might be a `cicd_pipeline` or `cicd_task` from a user's perspective. Therefore, we need to broaden the scope of the "Deployment Regex" to include the `cicd_pipeline`.
2. Jenkins deployments are not included in Change Lead Time calculation. The `cicd_pipeline_commits` consist of the repositories and commit_shas being built or deployed by a `cicd_pipeline`, we currently rely on the `repo_id` field to distinguish different repos, for data sources like github/gitlabe, filling it is not a issue. However, for specialized tool like Jenkins, it may not be possible, reliable, or easy to provide such information. In such cases, the only dependable field would be the `repo_url`. All data source plugins must be updated to populate this field.
3. There are many ways to orchestrate a deployment, making it challenging to identify all possible scenarios. We have determined that a `cicd_deployment_commits` (new table) is a `cicd_pipeline_commit` if the corresponding `cicd_pipeline` satisfies `type=deployment` or includes any `cicd_tasks` with `type=deployment`.
4. Currently, both `refdiff` and `dora` are identifying previous deployments separately and using different methods, which can lead to issues.
5. To determine the deployment_commit of a pull request, we must identify the commits deployed by examining its preceding SUCCESSFUL deployment. To do this, we must group the deployments by `cicd_scope_id`, `env`, and `repo_url`, then sort them by their `started date`.

## Describe the solution you'd like
![Flowchart](https://user-images.githubusercontent.com/61080/233818262-dbd0d56f-0750-421b-bdf3-dd00294aa952.jpg)

## Related issues
#4825 
#4810

**Comment by keon94** [comment]
@klesh Should this not be for the v0.18 milestone and cherry-picked back to v0.17, or are we delaying v0.17 until this gets done?

**Comment by klesh** [comment]
@keon94 It ought to be fixed ASAP

**Comment by hezyin** [comment]
Hi @klesh, I synced up the refactor plan with @keon94 and @CamilleTeruel today. They were on board with the plan and gave the following feedback:

1. It seems a bit unnatural for the refdiff plugin to generate deployments. That sounds more like the responsibility of the DORA plugin. Can you think of a solution that moves that logic out of the refdiff plugin?
2. Since we're going to change the schema of cicd_pipeline_commits table (replacing repo_id with repo_url), shall we coordinate the efforts to migrate all the existing CI/CD plugins? Keon and Camille are happy to take care of Azure DevOps.

**Comment by klesh** [comment]
> Hi @klesh, I synced up the refactor plan with @keon94 and @CamilleTeruel today. They were on board with the plan and gave the following feedback:
> 
>     1. It seems a bit unnatural for the refdiff plugin to generate deployments. That sounds more like the responsibility of the DORA plugin. Can you think of a solution that moves that logic out of the refdiff plugin?
> 
>     2. Since we're going to change the schema of cicd_pipeline_commits table (replacing repo_id with repo_url), shall we coordinate the efforts to migrate all the existing CI/CD plugins? Keon and Camille are happy to take care of Azure DevOps.

1. good one, i will think about it
2. doc sent

**Comment by klesh** [comment]
@hezyin @keon94 @CamilleTeruel Flow chart has been updated.

**Comment by klesh** [comment]
Finished
