### ISSUE TITLE
[Bug][teambition] test connection not work

### ISSUE THREAD

**Issue by likyh** [apache/incubator-devlake#4890]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

test connection fail on list page
![image](https://user-images.githubusercontent.com/3294100/230940723-c722c98b-9ac7-4a44-b16a-1eb5d7edb858.png)

test connection success even though auth is wrong
![image](https://user-images.githubusercontent.com/3294100/230940867-585261ea-9a4d-4d00-bc84-a99812e42fd2.png)

### What do you expect to happen

1. test connection success on list page
2. test connection fail when auth is wrong

### How to reproduce

1. create a teambition connection
2. test connection

### Version

main

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by likyh** [comment]
https://github.com/apache/incubator-devlake/pull/5066 have solved this issues.

**Comment by ningjunwei** [comment]
@likyh  how to config the teambition ？
