### ISSUE TITLE
[Bug][Jira] System Timezone not Respected

### ISSUE THREAD

**Issue by eMurgaNd** [apache/incubator-devlake#4902]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

I am testing the Jira plugin and have found that the incremental differential feature does not take the timezone into account. You can see in the following log line that the Jira plugin is looking in the future for Jira issues:

```
time="2023-04-11 13:51:26" level=debug msg=" [pipeline service] [pipeline #2] [task #2] [collectIssues] fetchAsync >>> done for agile/1.0/board/1302/issue map[expand:[changelog] jql:[updated >= '2023/04/11 20:20' AND updated >= '2022/10/11 00:00' AND created is not null ORDER BY created ASC] maxResults:[100] startAt:[0]] <nil>"
```
The the time of the log line was 2023-04-11 13:51:26 while the previous pipeline was executed at 2023/04/11 20:20 which is in the future. The pod time zone is set to America/Los_Angeles, but the Jira plugin is using UTC.

### What do you expect to happen

I expect the Jira plugin to use the same timezone as the system along with the same time zone of the lake log timestamps.

### How to reproduce

I had to set the logging level to debug to see the Jira queries where the timestamp is given. I set the log level and timezone using the helm chart flags below:

```
--set "lake.loggingLevel=debug" --set "option.localtime=/usr/share/zoneinfo/America/Los_Angeles"
```

The timezone of my Jira instance is America/Los_Angeles so for someone to test they need to set the pod timezone to a different timezone than the Jira instance. In order to find the Jira server time you can use the HTTP API endpoint `/rest/api/2/serverInfo`.

### Anything else

This issue will cause an inconsistency between ticket changes in Jira and the metrics being stored in MySQL. I just happened to run across the issue because I was making ticket changes and they were not showing up.

The version I'm running is 0.16.0-beta11

### Version

main

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by eMurgaNd** [comment]
@klesh the timezone is PDT as intended.

```
# date
Tue Apr 11 18:38:18 PDT 2023
```

**Comment by klesh** [comment]
Hi, @eMurgaNd , Please run the following SQL and see if it showed the correct time:
```
select now();
```

**Comment by eMurgaNd** [comment]
@klesh looks like it properly is matching the system timezone:
```
mysql> select now();
+---------------------+
| now()               |
+---------------------+
| 2023-04-11 20:54:24 |
+---------------------+
1 row in set (0.00 sec)

mysql> ^DBye
bash-4.4# date
Tue Apr 11 20:54:29 PDT 2023
```

**Comment by eMurgaNd** [comment]
Thank you. It will be much easier for me to continue testing my DevLake configuration with this resolved.

**Comment by mindlesscloud** [comment]
@klesh Ok, I'll follow up on this issue
