### ISSUE TITLE
[Question][Jira] Jira custom fields

### ISSUE THREAD

**Issue by ArsKorotaev** [apache/incubator-devlake#4910]
## Question
Hello!

I have a lot of custom filed setup in my Jira's projects. How can use this fields to build dashboards?

**Comment by Startrekzky** [comment]
Can @mindlesscloud help answer this question?

**Comment by mindlesscloud** [comment]
For your usage scenario, I recommend leveraging the `customize` plugin. This plugin enables you to map fields in the raw layer to tables in the domain layer. For more information, please refer to the following link: https://devlake.apache.org/docs/next/Plugins/customize
