### ISSUE TITLE
[Bug][BitBucket] Not able to add Bitbucket connection

### ISSUE THREAD

**Issue by leehoawki** [apache/incubator-devlake#4927]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

I am not able to add Bitbucket connection.

It says : Test Failed.Please check your configuration.

I noticed the BitBucket server's log contains: GET /rest/api/latest/user HTTP/1.1"  ( return 404

<img width="767" alt="1" src="https://user-images.githubusercontent.com/3602079/231921487-b968199b-06ff-4179-99b9-c73d7c2c3785.png">

But according to the BitBucket API doc, it should be  /rest/api/latest/users

FYI : https://developer.atlassian.com/server/bitbucket/rest/v809/api-group-system-maintenance/#api-api-latest-users-get

### What do you expect to happen

Add the Bitbucket connection successfully.

### How to reproduce

Create a Bitbucket connection 
Endpoint URL: http://testdomain.com:port/rest/api/latest

and then click the Test connection button.

### Anything else

https://github.com/apache/incubator-devlake/blob/v0.15.0/plugins/bitbucket/api/connection.go#L61

I think it should be 
res, err := apiClient.Get("users", nil, nil)
in Line 61

### Version

v0.15.0

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by abeizn** [comment]
You can try this Endpoint URL: https://api.bitbucket.org/2.0/

**Comment by leehoawki** [comment]
> You can try this Endpoint URL: https://api.bitbucket.org/2.0/

Hello, we are not using the Bitbucket cloud.
Our Bitbucket version is v5.14.1 and it seems that the 2.0 API is not available. 

Is devlake only able to work with Bitbucket cloud or I should upgrade to a higher version?

**Comment by klesh** [comment]
@leehoawki oh,  i'm sorry. The Bitbucket server is not supported.

**Comment by leehoawki** [comment]
hello is there a plan for bitbucket server support? since I noticed that there is a tab for bitbucket server on the page.

**Comment by klesh** [comment]
Not in the short term, we are short of bandwidth at this point, would like to contribute?

**Comment by tim-goto** [comment]
I am interested in contributing as stated in #4568 Some initial pointers to get me started would be great.

**Comment by klesh** [comment]
@tim-goto That is great. You may want to check out the `Gitlab` plugin, it does support `cloud` and `server` simultaneously. In general:

It detects the API version when preparing the `ApiClient`
https://github.com/apache/incubator-devlake/blob/8262cb3b830fa3e1a141d5408f8e85fabf6d1603/backend/plugins/gitlab/models/connection.go#L90


Then, some subtasks would behavior different based on the `version` information.
https://github.com/apache/incubator-devlake/blob/b4c1d85cf0d41d07233cf5ee3db16f8a23cc8450/backend/plugins/gitlab/tasks/account_collector.go#L50

However, it is `data source` dependent, and may or may not be suitable for Bitbucket.

**Comment by Startrekzky** [comment]
Please follow #4568 for the support of the BitBucket Server.
