### ISSUE TITLE
[Bug][Gitlab scope selection] TypeError: e is null

### ISSUE THREAD

**Issue by aubertaa** [apache/incubator-devlake#4934]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

- create a new blueprint
- checking a specific gitlab project when defining gitlab scope, i get this error
 
![image](https://user-images.githubusercontent.com/14087776/232015654-7c65674c-b38f-43a3-b2d4-16cb7540be10.png)

 using devlake 0.16.0-beta11

### What do you expect to happen

project should be selected successfully

### How to reproduce

i'm sorry, i have not identified what's wrong with this gitlab project in particular, it's a 'like others' project (even though i know that something should indeed differ)

### Version

main

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by mintsweet** [comment]
Hi, @aubertaa Thank you so much for reporting issues for devlake.
I try to reproduce your issue, but I have some difficulties, can you provide me with more information?

**Comment by aubertaa** [comment]
hi @mintsweet , i suspect that error occurs when selecting a gitlab project which has no description set. I tried also on last 0.16-beta14 and the problem persists.
Regards,

**Comment by mintsweet** [comment]
hi @aubertaa , I tried to choose a project without a description, but I didn't reproduce this issue. Can you help me record a gif to see what's going on on your devlake?

**Comment by aubertaa** [comment]
hi @mintsweet ,
here is the recording, selection this specific project 'service-masterproxy-shaper' always shows the error. (selecting the parent also, as shown on the recording).

![error selecting scope](https://user-images.githubusercontent.com/14087776/232986922-fc8a379c-47a7-420b-8ada-2fa48e2871d4.gif)

Here is part of the payload gotten when browsing projects through devlake ui (first project is selectable without issue, second is not):

from `api/plugins/gitlab/connections/1/remote-scopes`
```
{
    "children": [{
            "type": "scope",
            "parentId": "3589",
            "id": "2345",
            "name": "service-request-manager",
            "data": {
                "connectionId": 0,
                "gitlabId": 2345,
                "name": "service-request-manager",
                "description": "Service gérant le statut des requêtes apiv3",
                "defaultBranch": "develop",
                "pathWithNamespace": "AnalyticsAPI/microservices/api/service-request-manager",
                "webUrl": "XXXXX",
                "creatorId": 0,
                "visibility": "internal",
                "openIssuesCount": 0,
                "starCount": 0,
                "forkedFromProjectId": 0,
                "forkedFromProjectWebUrl": "",
                "httpUrlToRepo": "XXXXX",
                "createdDate": "2019-06-12T15:41:16.532Z",
                "updatedDate": "2023-04-18T07:53:17.091Z"
            }
        },
		{
            "type": "scope",
            "parentId": "3589",
            "id": "450",
            "name": "service-masterproxy-shaper",
            "data": {
                "connectionId": 0,
                "gitlabId": 450,
                "name": "service-masterproxy-shaper",
                "description": "",
                "defaultBranch": "develop",
                "pathWithNamespace": "AnalyticsAPI/microservices/api/service-masterproxy-shaper",
                "webUrl": "XXXXX",
                "creatorId": 0,
                "visibility": "internal",
                "openIssuesCount": 0,
                "starCount": 0,
                "forkedFromProjectId": 0,
                "forkedFromProjectWebUrl": "",
                "httpUrlToRepo": "XXXXX",
                "createdDate": "2016-12-09T10:03:48.527Z",
                "updatedDate": "2023-04-18T07:53:04.473Z"
            }
        },
    ],
    "nextPageToken": ""
}
```

**Comment by mintsweet** [comment]
hi @aubertaa, thank you very much for providing these, I will use the data you provided to try to reproduce later, thanks again.

**Comment by amosli** [comment]
I Have similar problem,using devlake 0.16.0-beta15 , add gitlab projects，my email is  1215186706@qq.com, I can help to reproduce  the bug.

```
TypeError: Cannot read properties of null (**reading 'gitlabId'**)
Please try again, if the problem persists include the above error message when filing a bug report on GitHub. You can also message us on Slack to engage with community members for solutions to common issues.
```

**Comment by mintsweet** [comment]
hi @aubertaa, unfortunately, I mocked the data you provided, but I still haven't reproduced this issue, I will continue to try to reproduce it, please be patient.

![demo](https://user-images.githubusercontent.com/37237996/233282757-9b91cafd-749d-475f-a365-8aaffc4dbaab.gif)

**Comment by mintsweet** [comment]
hi, @amosli, Can you please provide steps to reproduce?

**Comment by amosli** [comment]
> hi, @amosli, Can you please provide steps to reproduce?

yes,you can add my qq 1215186706。

**Comment by Startrekzky** [comment]
This issue is caused by the same reason as #4992 , which has already been cherrypicked to release-v0.17. Please use the latest v0.17 beta to test it out.
