### ISSUE TITLE
[Bug][Devops] The python version can not adapt dbt.

### ISSUE THREAD

**Issue by abeizn** [apache/incubator-devlake#4944]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

When I enter the devlake container to execute the `dbt` command through the v0.16.0-beta14  version, an error will be reported. I think it is caused by the python version.

![image](https://user-images.githubusercontent.com/101256042/232458897-fbc23c26-8ffa-4236-bc0f-6f963e5b9e76.png)

### What do you expect to happen

Executing `dbt` command should have such a result：（v0.15.0 version）
![eTCgnpkNQ1](https://user-images.githubusercontent.com/101256042/232459710-64e64dcd-3abb-4c7e-924b-ec43573e7bbe.jpg)

### How to reproduce

1. installed devlake by https://devlake.apache.org/docs/next/GettingStarted/DockerComposeSetup (v0.16.0-beta14)
2. Enter the devlake container and execute `dbt`

### Version

v0.16.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by keon94** [comment]
Seems to be python version compatiblity issue. Neither 3.10 nor 3.11 work with it, but 3.10+ is what we're requiring for the python framework.

**Comment by keon94** [comment]
dbt-mysql is at v0.19, only compatible up to Python 3.9. postgres (v1.4.5) works with 3.11 but its code is broken - it tries to import "Sequence" using "from collections import Sequence" in a few src files (dependencies) but it has to be "from collections.abc import Sequence" to work.

**Comment by keon94** [comment]
Setting the Python base image to 3.9 works, but that means we'll have to downgrade our requirement for the SDK to 3.9. @CamilleTeruel can this be done without consequences or are we relying on 3.10+ features anywhere?

**Comment by CamilleTeruel** [comment]
> Setting the Python base image to 3.9 works, but that means we'll have to downgrade our requirement for the SDK to 3.9. @CamilleTeruel can this be done without consequences or are we relying on 3.10+ features anywhere?

Just a few `match` statements in azuredevops `convert` methods that can be replaced with `if`s.

**Comment by CamilleTeruel** [comment]
The version spec "^3.9" still matches 3.10

PR: #4947
