### ISSUE TITLE
[Doc][Config UI] Documentation title

### ISSUE THREAD

**Issue by aubertaa** [apache/incubator-devlake#4963]
## Documentation Scope
Wording on the "New transformation" (type jenkins) page is not clear. We can't understand from here that pipelines stage names are also considered:

![image](https://user-images.githubusercontent.com/14087776/232988328-f93b8db8-6f8f-40e9-861d-dab14c717dea.png)

## Describe the Change
As mentionned in slack by @hezyin, "The regex does match with stage names" according to this documentation https://devlake.apache.org/docs/next/Configuration/Jenkins#step-3---adding-transformation-rules-optional"

Inline help should be more precise to describe the behavior (or link directly to the documentation)

**Comment by klesh** [comment]
> ## Documentation Scope
> Wording on the "New transformation" (type jenkins) page is not clear. We can't understand from here that pipelines stage names are also considered:
> 
> ![image](https://user-images.githubusercontent.com/14087776/232988328-f93b8db8-6f8f-40e9-861d-dab14c717dea.png)
> 
> ## Describe the Change
> As mentionned in slack by @hezyin, "The regex does match with stage names" according to this documentation https://devlake.apache.org/docs/next/Configuration/Jenkins#step-3---adding-transformation-rules-optional"
> 
> Inline help should be more precise to describe the behavior (or link directly to the documentation)

Thanks for your report, we also notice the problem and are currently working on it. @Startrekzky @mintsweet

**Comment by mintsweet** [comment]
related to #4960
