### ISSUE TITLE
[Bug][Module Name] Bug title cicd_tasks table started_date data inconsistency

### ISSUE THREAD

**Issue by ibrahimejaz** [apache/incubator-devlake#4984]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

Hi,
We happen to see that there is inconsistency in showing up datas, at the first run of the transformation it does shows data fine, but when we try running few times, the correct data is not showing we can see there is some missing data values.. this impacts us when we try to look into the deployment counts. 
https://share.anysnap.app/fFmKTLMoeYix
Per the screen shot it shows until for 2023-04-12 05:16:16.000 but we've records until 20/apr/2023. Initial run it shows up the correct data but after few runs with same transformation it didn't showed up. 

### What do you expect to happen

Data inconsistency 

### How to reproduce

When you run multiple transformations we can see the data inconsistency 

### Version

main

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ibrahimejaz** [comment]
We're tried using v0.16.0-beta14 and v0.16.0-beta13. Both has the same issue

**Comment by mappjzc** [comment]
Thanks for your issues.
Can you show more detail about this problem?
Like comparing data before and after multiple transformations.

**Comment by klesh** [comment]
@ibrahimejaz Thanks for your report, we noticed that the DORA metrics had some issues described in #4869 .
We are now testing the fix and it will be shipped in v0.17, a `beta` version will be released for early access in 2 weeks.

**Comment by klesh** [comment]
Sorry, I overlooked the `cicd_tasks` table, it may not relevant to #4869.
What was the data source? github?gitlab or jenkin?

**Comment by abeizn** [comment]
@ibrahimejaz If you have a problem with the github data source, this [pr ](https://github.com/apache/incubator-devlake/pull/4998)seems to have solved your problem, you can upgrade to the latest **v0.16.0-beta17** version

**Comment by ibrahimejaz** [comment]
Thanks @abeizn Looks it's working now per the expectation in DB. But will work on few more test cases and post you the updates.

**Comment by klesh** [comment]
Seems like problem had been sovled, I'm closing it
