### ISSUE TITLE
[Refactor][pydevlake] Refactor plugin registration

### ISSUE THREAD

**Issue by CamilleTeruel** [apache/incubator-devlake#4986]
## What and why to refactorIssue title:

Currently, the remote plugins are registered this way:
- the route `/plugins/register` is created in `backend/server/api.go`
- `backend/python/plugins/start.sh` is executed
- this executes the `startup` command of each plugin
- the plugin registers itself by POSTing its details to `/plugins/register` 

This is not ideal, because:
- this is more complicated than it needs to be
- this exposes the registration route to the public, which can be a security issue
- the `start.sh` and `build.sh` scripts have to make assumptions about how to build all plugins (e.g. that they use `poetry`)

## Describe the solution you'd like

Instead, we could add a two shell scripts `build.sh` and `run.sh` to each plugin.
The `build` script is executed by `backend/Makefile` to build each plugin.
Then at startup, `loader.go` look for `run.sh` in `REMOTE_PLUGIN_DIR` and registers each plugin with plugin info returned by `run.sh plugin-info`.

**Comment by keon94** [comment]
So basically have the server make a shell call to a script that returns the plugin details, rather than the plugins calling back into the server? This can work but you also have to worry about the custom file descriptor we use and correctly propagating that from Go to Shell to Python. I don't think that's trivial. Also, If we're going to do a mass refactor, I honestly think we should just move away from cmd calls and have python run as a separate RPC service.

**Comment by klesh** [comment]
I'm concerned from the security perspective.
@CamilleTeruel Can you draw a flow-chart or architecture diagram to show how the new mechanism works?
@keon94 Would you like to do the same if you have another approach?
No matter what we opt for in the end, the security of the new approach must be enforced.

**Comment by keon94** [comment]
@klesh sure I can do that, but at a high level I'm thinking of a service based architecture so we can leverage standard protocols and design patterns. Current architecture is too monolithic and all python (and Go code) run in the same container as the API server which is a problem as far as load balancing in a multi-tenant environment (unless we are going for separate deployments per client?). It also uses a custom shell-based protocol that we made up to interface Go and Python, which (IMO) is best if replaced with REST or RPC calls.

**Comment by klesh** [comment]
@keon94 no problem, we are open to all possibilities.
Share your thoughts pls

**Comment by CamilleTeruel** [comment]
> So basically have the server make a shell call to a script that returns the plugin details, rather than the plugins calling back into the server? 

Exactly, python plugins are loaded by walking `REMOTE_PLUGIN_DIR` looking for `run.sh` executables just after loading go plugins in `loader.go`.

> This can work but you also have to worry about the custom file descriptor we use and correctly propagating that from Go to Shell to Python. I don't think that's trivial.

This still uses invoker and bridge abstraction that take care of the extra file descriptor.

> Also, If we're going to do a mass refactor, I honestly think we should just move away from cmd calls and have python run as a separate RPC service.

This is not a mass refactor. This is just changing plugin registration flow. I agree that we should move away from cmd calls. This change is a necessary first step in that direction.
