### ISSUE TITLE
[Feature][plugin/github] Automatically adding a trailing `/` to the GitHub connection endpoint

### ISSUE THREAD

**Issue by aFlyBird0** [apache/incubator-devlake#4996]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar feature requirement.

### Use case

We can automatically add `/` to reduce the burden on users.

![image](https://user-images.githubusercontent.com/36830265/233537643-906bfee6-b0fe-420e-8db1-aca31da226fa.png)

doc link: https://devlake.apache.org/docs/next/Configuration/GitHub#endpoint-url

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Startrekzky** [comment]
Hi @aFlyBird0 Do you still want to do it?

**Comment by aFlyBird0** [comment]
> Hi @aFlyBird0 Do you still want to do it?

Sure, I'm willing to do that. Open-Source is Cool! Is it Okay to open a PR before Friday?

**Comment by mindlesscloud** [comment]
@aFlyBird0 Sure, I'm looking forward to your PR
