### ISSUE TITLE
[Feature][Gitlab] Automatic fetching newly created gitlab projects

### ISSUE THREAD

**Issue by EvanChen1989** [apache/incubator-devlake#5002]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar feature requirement.

### Use case

As a devlake maintainer, I would expect no extra effort for maintaining newly created gitlab projects

### Description

Though data scope for gitlab can now select a subgroup to include all projects underneath it. But with company's fast growth, new gitlab projects would be created frequently and it would be impossible for devlake maintainer to acknowledge and maintain them.

So, I think a certain group should also be accepted as a data scope selection and data fetching should automatically adapt to current project list under that group.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Startrekzky** [comment]
Collecting votes.

It'll be great if you can also tell us more about your use cases of this feature. We'll consider doing it if more users with specific metric needs want this feature.

**Comment by EvanChen1989** [comment]
@Startrekzky our company has many (about 150+) git repos for different micro-services and still growing... and they're under different gitlab groups. We created multiple blueprints for different groups for easier management and quicker sync speed. But, to make sure our git commit analysis accurate we'll always need to make sure that the blueprints have all the matching projects selected, so we need to edit the data-scope and expand groups and groups and check the newly created projects.....  especially when we have a big group that contains about 100 projects... it's a disaster to check and select all the projects.

In my opinion, devlake aims for data analysis, so it would be a common case for maintainer to select 'all projects under a certain group' instead of picking some of them.

**Comment by KelvinVenancio** [comment]
+1

I am currently facing a similar requirement within our company. With a portfolio of over 300 repositories, I am actively exploring the optimal approach to automate the creation process, seeking to eliminate manual intervention wherever possible.

**Comment by Startrekzky** [comment]
Hi @EvanChen1989 @KelvinVenancio , thanks for the feedback. I have several questions about your use cases:

1. Among the new repos created in the configured GitLab groups, will there be repos that you don't want to collect by default? E.g. repos for libraries, images, docs, etc.
2. What's the frequency of adding new repos to existing GitLab groups? Once a week/month/season?
3. How do you manage your 250+ repos in GitLab, do you have nested groups?
4. How do you organize your GitLab repos in DevLake, one DevLake project for all repos under the same GitLab (root/sub) group?

**Comment by EvanChen1989** [comment]
> 

@Startrekzky thank for the attention, per your questions:
1. Newly created repos usually are needed to collect, resources are usually put under other groups. And even when they're put in wrong place, we're happy to filter them out during analysis other than picking the right ones into selection frequently.
2. The frequence could be like 1 repo per-week in average and could be like 4-5 per week when needed, it depends on system requirement. The hard part is that usually we're not awared of all the repo creating operation across teams.
3.  For now we don't have much requirement on nested groups, the current usage depth should be 2.
4. We create different blueprints for different groups, and due to some historical problems certain groups contains a large number of repos. Now I'm splitting them into 4 grouops divided by alphabetic cuz when we found no data for certain repo, it's a nightmare to search through the blueprint and find if it's included...it's not even sorted during display :(

**Comment by EvanChen1989** [comment]
@Startrekzky 
1. I mean if some source repos are wrongly put into project groups, we can fitler them out or let the gitlab maintainer to move them away. And it should be a rare case.
2. We're now on v0.17.0-beta4, and now we have only one project and multiple bludprints under it.

**Comment by Startrekzky** [comment]
@EvanChen1989 Got it. Just let you know that the [stable v0.17.0](https://github.com/apache/incubator-devlake/releases/tag/v0.17.0) has been released too if you are not planning to upgrade to v0.18

**Comment by stepmr** [comment]
+1, trialling DevLake on a GH org with 12k+ repos

**Comment by EvanChen1989** [comment]
@Startrekzky just noticed on v0.19.0-beta2 the edit data scope function seems has been changed, and group hierarchy is gone... this is NOT what I expected :( ... because I don't expect to sync ALL gitlab data in ONE blueprint, it could cost so long time for one run. Please help look into it 

<img width="863" alt="image" src="https://github.com/apache/incubator-devlake/assets/29242240/5fc2aacc-7531-42a9-84c3-219eea715139">

**Comment by Startrekzky** [comment]
> ..., and group hierarchy is gone... this is NOT what I expected :( ... because I don't expect to sync ALL gitlab data in ONE blueprint...

Hi @EvanChen1989 .  I'm a bit confused. The group hierarchy is gone, but it doesn't mean that all repos are selected. The selected repos are still the repos you selected at the first place.
