### ISSUE TITLE
[Bug][Config UI] TypeError: Cannot read properties of undefined (reading 'name')

### ISSUE THREAD

**Issue by arcfree** [apache/incubator-devlake#5019]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

After executing the task, I encounter this error when entering the project. I am using an M1 computer, with Node version v16.13.2. Could you please help me take a look?

### What do you expect to happen

It is possible to jump to the project details page.

### How to reproduce

After initializing the service, setting up the blueprint and triggering automated tasks upon the first connection to the Jira source, entering the project again will result in this.

### Anything else

Every time it happens.

### Version

main

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by klesh** [comment]
hi @arcfree , can you provide a screenshot ?

**Comment by arcfree** [comment]
![image](https://user-images.githubusercontent.com/11928190/234189792-37fe07d0-acb8-44b1-a51b-34baa992b1b4.png)


> hi @arcfree , can you provide a screenshot ?

**Comment by klesh** [comment]
thanks, I suspect that the backend didn't respond expected content, can u open the Developer Tool bar and find out the offending request?

**Comment by pshail** [comment]
I experienced the same but "refresh" of the offending url fixed this issue all around, for all the urls, so wondering if its some browser cache issue

**Comment by Startrekzky** [comment]
I think this has been fixed. Can you link the bugfix PR here, please? @mintsweet

**Comment by mintsweet** [comment]
hi @arcfree , I forgot what the problem is, so I can't find the pr to fix it through the code, can you provide a screenshot of the browser dev tools log?

**Comment by Startrekzky** [comment]
Hi @arcfree , it's a historical problem and should have been fixed. Please update to the latest DevLake version and see if it exists anymore.
