### ISSUE TITLE
[Question][Jira] Excuse me, how can I set the data collection range for Jira projects without application panels?

### ISSUE THREAD

**Issue by arcfree** [apache/incubator-devlake#5038]
## Question
Excuse me, how can I set the data collection range for Jira projects without application panels?

## Screenshots
![image](https://user-images.githubusercontent.com/11928190/234540497-340dcd55-6241-43dc-9b0c-a5084d1f69ab.png)

## Additional context
Add any other context here.

**Comment by klesh** [comment]
Please create a board to include those issues

**Comment by yumengwang03** [comment]
@arcfree Let us know if this question is resolved :)
