### ISSUE TITLE
[Question][Jira] How can DevLake collect the custom fields on the Jira issue? I didn't succeed even though I used customize

### ISSUE THREAD

**Issue by arcfree** [apache/incubator-devlake#5047]
## Question
How can DevLake collect the custom fields on the Jira issue? I didn't succeed even though I used customize。

## Screenshots
If applicable, add screenshots to help explain.

## Additional context
Add any other context here.

**Comment by likyh** [comment]
https://devlake.apache.org/docs/next/Plugins/customize
Yes, customize is designed for custom field on jira issue. you can add custom column in issues or other domainTable, and collect data from rawLayer to fill the custom column.
