### ISSUE TITLE
[Question] [Data Migration] Getting Error after installing the latest version of Devlake

### ISSUE THREAD

**Issue by Sumanth1919** [apache/incubator-devlake#5051]
Getting Error After Installing New Version of DevLake

Error - **New Migration Scripts Detected
If you have already started, please wait for database migrations to complete, do NOT close your browser at this time.

Warning: Performing migration may wipe collected data for consistency and re-collecting data may be required**.

My previous Version - [v0.16.0-beta16]
My Current Version -[v0.16.0-beta17]

## Screenshots
![image](https://user-images.githubusercontent.com/96106917/234834272-f4e028da-1074-44b7-8c77-2c8da0183493.png)

After clicking on procced to Data Migration 

![image](https://user-images.githubusercontent.com/96106917/234834436-7893de2e-77e7-4b39-887e-17ce58c15bca.png)

After running <config-ui-endpoint>/api/proceed-db-migration 

![image](https://user-images.githubusercontent.com/96106917/234845303-69413e31-17ae-467f-8726-138a005ab8e4.png)

My Docker logs 

time="2023-04-27 11:08:54" level=info msg=" [migrator] applying migratin script 20230223200040-remove created_date_after from _devlake_collector_latest_state"
time="2023-04-27 11:08:54" level=error msg="HTTP 500 error
        caused by: error executing migration
        Wraps: (2) invalid encKey
        Error types: (1) *hintdetail.withDetail (2) *errors.errorString"

## Additional context
Anything needs to do on the MYSQL.

**Comment by mappjzc** [comment]
the error `invalid encKey` means your `ENCODE_KEY` at your `.env` file was wrong.
It always happened if you flush your `.env` file.
you should get the `ENCODE_KEY` key from your old `.env` file and input it into your new `.env` file.

**Comment by Sumanth1919** [comment]
Thanks @mappjzc
