### ISSUE TITLE
[Bug][Config-UI] Azure DevOps jumps to localhost:4000/offline when users enter invalid personal access token

### ISSUE THREAD

**Issue by hezyin** [apache/incubator-devlake#5059]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

**Version v0.17.0-alpha7**

When I intentionally enter an invalid personal access token (only 3 letters) and hit "test connection", Config-UI shows operation failed and jumps to localhost:4000/offline.

<img width="833" alt="Screen Shot 2023-04-27 at 3 29 22 PM" src="https://user-images.githubusercontent.com/2908155/235005030-8ce223d6-0b9d-41ad-b903-edde79cb7277.png">
<img width="602" alt="Screen Shot 2023-04-27 at 3 29 31 PM" src="https://user-images.githubusercontent.com/2908155/235005040-b69c7fde-ab14-4235-ace6-53703889e5d3.png">

### What do you expect to happen

When encountering an invalid personal access token when testing the connection, Config-UI should show operation failed but stay on this page instead of jumping to localhost:4000/offline.
 

### How to reproduce

See above

### Version

main

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by mintsweet** [comment]
hi, @hezyin, this is based on the status returned by the API. Theoretically, if the operation fails, it should return a status code of 400. If it returns 500, it will be judged that the service is invalid, so it will jump to the `offline` page and modify the backend not config-ui.
