### ISSUE TITLE
[Bug][Config-UI] Radio button doesn't work for unselecting

### ISSUE THREAD

**Issue by hezyin** [apache/incubator-devlake#5060]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

**Version v0.17.0-alpha7**

When I try to unassociate a transformation rule (azure-trans-1 in the screenshot) from a data scope, I cannot unselect the radio button. 

<img width="1250" alt="Screen Shot 2023-04-27 at 4 31 33 PM" src="https://user-images.githubusercontent.com/2908155/235025094-3351be69-38db-4528-b08b-ca11b30128be.png">

### What do you expect to happen

I can click on the radio button and unselect the transformation rule.

### How to reproduce

See above

### Version

main

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by mintsweet** [comment]
hi, @hezyin, according to the design of the product tr cannot be canceled after being selected.

**Comment by hezyin** [comment]
Ok, thanks for the clarification.
