### ISSUE TITLE
[Bug][azure] config-ui azure connection 404

### ISSUE THREAD

**Issue by mappjzc** [apache/incubator-devlake#5071]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

![image](https://user-images.githubusercontent.com/2921251/235190655-48f2a8ce-e30b-4b33-93d9-176547aa7673.png)
![image](https://user-images.githubusercontent.com/2921251/235191012-ed079197-e712-4266-a7f3-1fe9a4dd617c.png)

As the picture shows.
The config-ui request  `plugins/azuredevops/`
![image](https://user-images.githubusercontent.com/2921251/235191452-b0a579bd-a750-44e0-98dc-dfbe2f03bf08.png)
only config-ui and python tests use the `azuredevops`

but the backend use `azure`
![image](https://user-images.githubusercontent.com/2921251/235191669-34f1e515-fba8-4e89-87f3-c732d12febd1.png)

So it get the 404 status code.

### What do you expect to happen

No 404 status code.

### How to reproduce

visit config-ui azure connection.

### Version

main

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by klesh** [comment]
@CamilleTeruel I believe we should delete `azure` plugin on the golang side

**Comment by klesh** [comment]
cc @hezyin
