### ISSUE TITLE
[Question][GitHub] What's the right issue type when multiple labels match the same regex?

### ISSUE THREAD

**Issue by hezyin** [apache/incubator-devlake#5079]
The following screenshot was taken on stable v0.16.0, but the issue also exists on main and v0.17.

Take issue https://github.com/apache/incubator-devlake/issues/4861 as an example, it has two `type/xxx` labels: `type/docs` and `type/bug`.

However, based on this [code](https://github.com/apache/incubator-devlake/blob/main/backend/plugins/github_graphql/tasks/issue_collector.go#L273), this issue's `original_type` column can only have one value (the exact value would depend on the execution order of the labels in the for loop).

This is what the issue looks like in our database:

<img width="1918" alt="Screen Shot 2023-05-03 at 9 47 28 AM" src="https://user-images.githubusercontent.com/2908155/235987162-4717202d-01aa-4988-8329-6781abf1c7bc.png">

Questions to discuss:

1. Does an issue's `original_type` column support multiple original types?
2. Does an issue's `type` column support multiple types?

**Comment by klesh** [comment]
I don't think the `issue.type` and the `original_type` should support multiple values, it doesn't make sense to me.
We should just state it clearly on the doc or config-ui IMO

**Comment by Startrekzky** [comment]
My thoughts:

1. An issue only has one `type`, "multiples types" is not allowed in most issue tracking tools like Jira, GitLab issues, TAPD, etc.
2. I can accept an issue having only one or multiple `original_type`, in fact, only GitHub issues may have this situation. The domain layer table issues.original_type equals tool layer jira_issues.`type`, gitlab_issues.`type`, or github_issue_labels, etc. A GitHub issue's type (e.g. #4861) can be saved as a string like `type/docs,type/bugs` as it has two "type/xxx" labels that match the regex: type/docs and type/bug.
3. However, the value of this #4861 's `type` should be from only one of the standard type values. We can define an order to check if lables match the regex of these values. if a GitHub issues ($4861) has multiple labels, and it first matches 'type/bug', it should be transformed to `type` = 'BUG'. 
- REQUIREMENT: type/feature-request
- BUG: type/bug
- DOCS: type/docs
I'm fine with the order or using either first/last match, as long as there's only one type.

**Comment by hezyin** [comment]
@Startrekzky @klesh Makes sense to me. So I guess we can all agree on the following:

1. `type` column of the `issues` table can only have one value, one of "REQUIREMENT", "BUG", or "DOCS".
2. In the GitHub case, if an issue has multiple labels matching the type regexes, only one type would be chosen, in the order of REQUIREMENT > BUG > DOCS.

How about the `original_type` column of the `issues` table when a GitHub issue has multiple type labels? Are you ok with Louis' suggestion of `type/docs,type/bugs`? @klesh

**Comment by klesh** [comment]
sure, i think it is greate
