### ISSUE TITLE
[Bug][Azure DevOps] Missing records in cicd_tasks

### ISSUE THREAD

**Issue by hezyin** [apache/incubator-devlake#5081]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

**Version: v0.17.0-beta3**

## Azure DevOps Setup

I have two pipeline runs in Azure DevOps, each with two jobs, "job_1" and "job_2".
<img width="934" alt="Screen Shot 2023-05-03 at 6 50 34 PM" src="https://user-images.githubusercontent.com/2908155/236113487-3e0e2d43-5f2c-4035-ab95-8fdd2d14a076.png">
<img width="853" alt="Screen Shot 2023-05-03 at 6 50 21 PM" src="https://user-images.githubusercontent.com/2908155/236113494-ea206e1b-4b83-47c5-81c7-b4e6805501da.png">

## DevLake Collection Result

I got 2 cicd_pipelines, which was as expected. But I only got cicd_tasks for the second cicd_pipeline, see the pipeline_id column of the cicd_tasks I got. Also, all of their environment was set to "TESTING", which was unexpected.

I also didn't expect to get the "Finalize Build" job, but since it's also displayed as a job in the Azure DevOps pipeline page, so I think it's ok.

<img width="1121" alt="Screen Shot 2023-05-03 at 6 49 17 PM" src="https://user-images.githubusercontent.com/2908155/236113596-1f99fa40-9435-4d75-b316-b79f27535749.png">
<img width="1122" alt="Screen Shot 2023-05-03 at 6 50 03 PM" src="https://user-images.githubusercontent.com/2908155/236113602-55b0290c-bf2b-4d2a-967d-e4381ecaa6ce.png">

### What do you expect to happen

See above

### How to reproduce

See above

### Version

main

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by CamilleTeruel** [comment]
@hezyin Can you add me to that project or send me the `azure-pipelines.yml`?

**Comment by hezyin** [comment]
Hi @CamilleTeruel, I added you as a team member to my test project.

<img width="1528" alt="Screen Shot 2023-05-04 at 7 25 19 AM" src="https://user-images.githubusercontent.com/2908155/236237704-1699f1ee-f9d2-46df-8685-6adb998a6b9f.png">

In case you still can't get access to it, here's the yml file I used: https://github.com/keon94/cicd-playground

And here's how I later fixed the indentation error:

<img width="950" alt="Screen Shot 2023-05-04 at 7 25 54 AM" src="https://user-images.githubusercontent.com/2908155/236238507-f302ee9b-e93c-4b4e-8a12-3ef95de85c1c.png">
