### ISSUE TITLE
[Bug][Azure DevOps] Error when collecting some failed pipeline runs

### ISSUE THREAD

**Issue by hezyin** [apache/incubator-devlake#5083]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

**Version v0.17.0-beta3**

## Azure DevOps Setup

I messed up the indentation of the azure-pipelines.yml file and had two failed pipeline runs. They did not get run at all due to "Mapping values are not allowed in this context" error in the 2nd screenshot.

![Screen Shot 2023-05-03 at 9 27 04 PM](https://user-images.githubusercontent.com/2908155/236115275-f04959c7-6fef-4558-836d-9da35cad694f.png)
![Screen Shot 2023-05-03 at 9 27 12 PM](https://user-images.githubusercontent.com/2908155/236115279-24b261e6-1ee6-4663-b09d-92455b4eb33b.png)

## DevLake Collection Result

When I tried to collect this Azure repo, I got the following error. Seems like it's a HTTP 204 no content error for API call https://dev.azure.com/merico-dev/DevLake/_apis/build/builds/3/timeline?api-version=7.0.
![Screen Shot 2023-05-03 at 9 54 10 PM](https://user-images.githubusercontent.com/2908155/236115387-ef44e3aa-7bab-4998-8baf-414203c921ee.png)
![Screen Shot 2023-05-03 at 9 26 43 PM](https://user-images.githubusercontent.com/2908155/236115393-9790cf06-aa16-4bd1-a144-c86fc3e9db70.png)

### What do you expect to happen

Proper error handling for my failed pipelines.

### How to reproduce

See above

### Version

main

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Startrekzky** [comment]
Hi @CamilleTeruel , what's the status of this bug?

**Comment by andremattosferraz** [comment]
I`m getting build not found:

<img width="1440" alt="image" src="https://github.com/apache/incubator-devlake/assets/133804167/fb25e39f-6641-4e6f-9b58-68f02b2265bc">
[task-293-2-1-azuredevops.log](https://github.com/apache/incubator-devlake/files/11665396/task-293-2-1-azuredevops.log)
