### ISSUE TITLE
[Feature][Config UI/BE] Need to be able to search boards for adding data scope for Jira

### ISSUE THREAD

**Issue by yumengwang03** [apache/incubator-devlake#5089]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar feature requirement.

### Use case

When selecting boards for Jira, sometime the users have too many boards and it would be convenient for them if they can search boards by name.

<img width="1180" alt="Screen Shot 2023-05-04 at 8 51 07 PM" src="https://user-images.githubusercontent.com/9535430/236209808-d3e2141f-d36e-4527-a6a0-94e00a55cfeb.png">

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by yumengwang03** [comment]
<img width="610" alt="Screen Shot 2023-07-06 at 5 16 12 PM" src="https://github.com/apache/incubator-devlake/assets/9535430/0809f30f-cbdc-45ad-b1da-6eb36a924971">

**Comment by mintsweet** [comment]
related to #5640
