### ISSUE TITLE
[Bug][Azure DevOps] Azure DevOps test connection failure due to SSLCertVerificationError

### ISSUE THREAD

**Issue by nd-siouxfan** [apache/incubator-devlake#5098]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

While creating a connection to AzDO, the test failed.  

Log was emitted:

[GIN] 2023/05/04 - 18:56:32 | 200 |     903.792µs |      172.21.0.5 | GET      "/plugins/azuredevops/connections"
time="2023-05-04 18:57:19" level=info msg="DEBUG: Starting new HTTPS connection (1): app.vssps.visualstudio.com:443"
time="2023-05-04 18:57:20" level=error msg="Traceback (most recent call last):"
time="2023-05-04 18:57:20" level=error msg="  File "/root/.cache/pypoetry/virtualenvs/azuredevops-ANnMAkq9-py3.9/lib/python3.9/site-packages/urllib3/connectionpool.py", line 703, in urlopen"
time="2023-05-04 18:57:20" level=error msg="    httplib_response = self._make_request("
time="2023-05-04 18:57:20" level=error msg="  File "/root/.cache/pypoetry/virtualenvs/azuredevops-ANnMAkq9-py3.9/lib/python3.9/site-packages/urllib3/connectionpool.py", line 386, in _make_request"
time="2023-05-04 18:57:20" level=error msg="    self._validate_conn(conn)"
time="2023-05-04 18:57:20" level=error msg="  File "/root/.cache/pypoetry/virtualenvs/azuredevops-ANnMAkq9-py3.9/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn"
time="2023-05-04 18:57:20" level=error msg="    conn.connect()"
time="2023-05-04 18:57:20" level=error msg="  File "/root/.cache/pypoetry/virtualenvs/azuredevops-ANnMAkq9-py3.9/lib/python3.9/site-packages/urllib3/connection.py", line 419, in connect"
time="2023-05-04 18:57:20" level=error msg="    self.sock = ssl_wrap_socket("
time="2023-05-04 18:57:20" level=error msg="  File "/root/.cache/pypoetry/virtualenvs/azuredevops-ANnMAkq9-py3.9/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket"
time="2023-05-04 18:57:20" level=error msg="    ssl_sock = _ssl_wrap_socket_impl("
time="2023-05-04 18:57:20" level=error msg="  File "/root/.cache/pypoetry/virtualenvs/azuredevops-ANnMAkq9-py3.9/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl"
time="2023-05-04 18:57:20" level=error msg="    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)"
time="2023-05-04 18:57:20" level=error msg="  File "/usr/local/lib/python3.9/ssl.py", line 500, in wrap_socket"
time="2023-05-04 18:57:20" level=error msg="    return self.sslsocket_class._create("
time="2023-05-04 18:57:20" level=error msg="  File "/usr/local/lib/python3.9/ssl.py", line 1040, in _create"
time="2023-05-04 18:57:20" level=error msg="    self.do_handshake()"
time="2023-05-04 18:57:20" level=error msg="  File "/usr/local/lib/python3.9/ssl.py", line 1309, in do_handshake"
time="2023-05-04 18:57:20" level=error msg="    self._sslobj.do_handshake()"
time="2023-05-04 18:57:20" level=error msg="ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)"
time="2023-05-04 18:57:20" level=error 
time="2023-05-04 18:57:20" level=error msg="During handling of the above exception, another exception occurred:"
time="2023-05-04 18:57:20" level=error 
time="2023-05-04 18:57:20" level=error msg="Traceback (most recent call last):"
time="2023-05-04 18:57:20" level=error msg="  File "/root/.cache/pypoetry/virtualenvs/azuredevops-ANnMAkq9-py3.9/lib/python3.9/site-packages/requests/adapters.py", line 489, in send"
time="2023-05-04 18:57:20" level=error msg="    resp = conn.urlopen("
time="2023-05-04 18:57:20" level=error msg="  File "/root/.cache/pypoetry/virtualenvs/azuredevops-ANnMAkq9-py3.9/lib/python3.9/site-packages/urllib3/connectionpool.py", line 787, in urlopen"
time="2023-05-04 18:57:20" level=error msg="    retries = retries.increment("
time="2023-05-04 18:57:20" level=error msg="  File "/root/.cache/pypoetry/virtualenvs/azuredevops-ANnMAkq9-py3.9/lib/python3.9/site-packages/urllib3/util/retry.py", line 592, in increment"
time="2023-05-04 18:57:20" level=error msg="    raise MaxRetryError(_pool, url, error or ResponseError(cause))"
time="2023-05-04 18:57:20" level=error msg="urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='app.vssps.visualstudio.com', port=443): Max retries exceeded with url: /_apis/profile/profiles/me?api-version=7.0 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))"
time="2023-05-04 18:57:20" level=error 
time="2023-05-04 18:57:20" level=error msg="During handling of the above exception, another exception occurred:"
time="2023-05-04 18:57:20" level=error 
time="2023-05-04 18:57:20" level=error msg="Traceback (most recent call last):"
time="2023-05-04 18:57:20" level=error msg="  File "/app/python/plugins/azuredevops/azuredevops/main.py", line 132, in <module>"
time="2023-05-04 18:57:20" level=error msg="    AzureDevOpsPlugin.start()"
time="2023-05-04 18:57:20" level=error msg="  File "/app/python/pydevlake/pydevlake/plugin.py", line 257, in start"
time="2023-05-04 18:57:20" level=error msg="    fire.Fire(PluginCommands(plugin))"
time="2023-05-04 18:57:20" level=error msg="  File "/root/.cache/pypoetry/virtualenvs/azuredevops-ANnMAkq9-py3.9/lib/python3.9/site-packages/fire/core.py", line 141, in Fire"
time="2023-05-04 18:57:20" level=error msg="    component_trace = _Fire(component, args, parsed_flag_args, context, name)"
time="2023-05-04 18:57:20" level=error msg="  File "/root/.cache/pypoetry/virtualenvs/azuredevops-ANnMAkq9-py3.9/lib/python3.9/site-packages/fire/core.py", line 466, in _Fire"
time="2023-05-04 18:57:20" level=error msg="    component, remaining_args = _CallAndUpdateTrace("
time="2023-05-04 18:57:20" level=error msg="  File "/root/.cache/pypoetry/virtualenvs/azuredevops-ANnMAkq9-py3.9/lib/python3.9/site-packages/fire/core.py", line 681, in _CallAndUpdateTrace"
time="2023-05-04 18:57:20" level=error msg="    component = fn(*varargs, **kwargs)"
time="2023-05-04 18:57:20" level=error msg="  File "/app/python/pydevlake/pydevlake/ipc.py", line 51, in wrapper"
time="2023-05-04 18:57:20" level=error msg="    ret = func(self, *args)"
time="2023-05-04 18:57:20" level=error msg="  File "/app/python/pydevlake/pydevlake/ipc.py", line 85, in test_connection"
time="2023-05-04 18:57:20" level=error msg="    self._plugin.test_connection(connection)"
time="2023-05-04 18:57:20" level=error msg="  File "/app/python/plugins/azuredevops/azuredevops/main.py", line 98, in test_connection"
time="2023-05-04 18:57:20" level=error msg="    api.my_profile()"
time="2023-05-04 18:57:20" level=error msg="  File "/app/python/plugins/azuredevops/azuredevops/api.py", line 48, in my_profile"
time="2023-05-04 18:57:20" level=error msg="    return self.send(req)"
time="2023-05-04 18:57:20" level=error msg="  File "/app/python/pydevlake/pydevlake/api.py", line 113, in send"
time="2023-05-04 18:57:20" level=error msg="    res = self.session.get("
time="2023-05-04 18:57:20" level=error msg="  File "/root/.cache/pypoetry/virtualenvs/azuredevops-ANnMAkq9-py3.9/lib/python3.9/site-packages/requests/sessions.py", line 600, in get"
time="2023-05-04 18:57:20" level=error msg="    return self.request("GET", url, **kwargs)"
time="2023-05-04 18:57:20" level=error msg="  File "/root/.cache/pypoetry/virtualenvs/azuredevops-ANnMAkq9-py3.9/lib/python3.9/site-packages/requests/sessions.py", line 587, in request"
time="2023-05-04 18:57:20" level=error msg="    resp = self.send(prep, **send_kwargs)"
time="2023-05-04 18:57:20" level=error msg="  File "/root/.cache/pypoetry/virtualenvs/azuredevops-ANnMAkq9-py3.9/lib/python3.9/site-packages/requests/sessions.py", line 701, in send"
time="2023-05-04 18:57:20" level=error msg="    r = adapter.send(request, **kwargs)"
time="2023-05-04 18:57:20" level=error msg="  File "/root/.cache/pypoetry/virtualenvs/azuredevops-ANnMAkq9-py3.9/lib/python3.9/site-packages/requests/adapters.py", line 563, in send"
time="2023-05-04 18:57:20" level=error msg="    raise SSLError(e, request=request)"
time="2023-05-04 18:57:20" level=error msg="requests.exceptions.SSLError: HTTPSConnectionPool(host='app.vssps.visualstudio.com', port=443): Max retries exceeded with url: /_apis/profile/profiles/me?api-version=7.0 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))"
[GIN] 2023/05/04 - 18:57:20 | 500 |  948.826709ms |      172.21.0.5 | POST     "/plugins/azuredevops/test"
[GIN] 2023/05/04 - 18:57:20 | 200 |        1.25µs |      172.21.0.5 | GET      "/ping"

### What do you expect to happen

Connection test to be succesful

### How to reproduce

Attempt to hit AzDo with a PAT that has full access

### Version

v0.16.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by hezyin** [comment]
Hi @nd-siouxfan, I noticed that you chose version v0.16.0 for this issue, but as far as I know v0.16.0 isn't loaded with Azure DevOps support, are you sure you used v0.16.0?

**Comment by nd-siouxfan** [comment]
Oops.  Should have been v0.17.beta2

**Comment by hezyin** [comment]
Hi @nd-siouxfan, how did you install DevLake? Somehow I wasn't able to reproduce this issue via docker-compose.

**Comment by nd-siouxfan** [comment]
docker-compose.  also tried the env setting 

IN_SECURE_SKIP_VERIFY="true"

**Comment by hezyin** [comment]
Thanks for the info. Unfortunately, I'm still unable to reproduce the issue. Maybe it has to do with your docker host's certificates?

**Comment by nd-siouxfan** [comment]
<sigh> Figured it out.  One word.  Zscaler </sigh>
