### ISSUE TITLE
[Bug][Project Mapping] project_mapping table missing records for deployment webhooks

### ISSUE THREAD

**Issue by hezyin** [apache/incubator-devlake#5099]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

**Version v0.17.0-beta3**

I was testing the deployment webhook on v0.17.0-beta3. After I successfully posted to the webhook, I didn't see any deployment on the DORA dashboard so I dug into the SQL queries. It turned out that there's no record in the project_mapping table that associates the mando project with the cicd_scope that corresponds to the webhook.

See the first screenshot below that the mando project has a webhook called hook1. See the second screenshot below that there's no entry in the project_mapping table that associates mando project with the webhook.

![Screen Shot 2023-05-04 at 2 07 51 PM](https://user-images.githubusercontent.com/2908155/236333903-074a5774-b26f-469e-b3b9-04c86f8ffead.png)
![Screen Shot 2023-05-04 at 2 07 34 PM](https://user-images.githubusercontent.com/2908155/236333909-c5ed4655-ba18-4836-8edc-67f88ef5c913.png)

### What do you expect to happen

See above

### How to reproduce

See above

### Version

main

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by hezyin** [comment]
Upon examination, webhook's record in project_mapping table is created when the blueprint of the project is run. But this is counterintuitive for users, we need a better solution than this.

**Comment by klesh** [comment]
Concluded: prompt users that they should rerun the bp after adding webhook to the project in order to see the updated DORA metric

**Comment by mintsweet** [comment]
related to #5117

**Comment by klesh** [comment]
Resolved by #5119
