### ISSUE TITLE
[Bug][GitHub] GitHub repos' url columns are empty

### ISSUE THREAD

**Issue by hezyin** [apache/incubator-devlake#5100]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

**Version: v0.17.0-beta3**

I collected apache/incubator-devlake repo on v0.17.0-beta3 and its URL column in the repos table is empty (1st screenshot below). This is a problem because the repo URL is used to associate repos with deployments from webhook or Jenkins. Note that the html_url column of _tool_github_repos does have the correct value (2nd screenshot below).

![Screen Shot 2023-05-04 at 2 08 43 PM](https://user-images.githubusercontent.com/2908155/236336864-97347a82-a648-4869-8216-7af703fb072d.png)
![Screen Shot 2023-05-04 at 2 09 08 PM](https://user-images.githubusercontent.com/2908155/236336871-6e4b07a9-b443-4342-a01c-755da232e951.png)

### What do you expect to happen

See above

### How to reproduce

See above

### Version

main

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Startrekzky** [comment]
@abeizn Can you take a look at this, and check if repo urls from GitLab and BitBucket are collected?

**Comment by abeizn** [comment]
GitLab is ok, 
BitBucket is not ok.

**Comment by mintsweet** [comment]
hi @abeizn, the frontend cannot get the data that the backend wants.
the backend needs to update the remote API to return what you want.
