### ISSUE TITLE
[Feature][GitLab] Filter out the GitLab repos that users only have the Guest permission when setting data scope

### ISSUE THREAD

**Issue by Startrekzky** [apache/incubator-devlake#5104]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar feature requirement.

### Use case

When I added GitLab repos to a DevLake project, I could add the repos that I only have guest permission. However, when I started collecting, it threw an error. 
![image](https://user-images.githubusercontent.com/14050754/236432363-ce6d9f2d-19a3-4900-a433-dfc1b8d8d73c.png)

### Description

It turns out that a user has no permission to collect a repo with the Guest role. Hence, it's better to just filter these repos out while configuring GitLab repos in the Config UI.

![image](https://user-images.githubusercontent.com/14050754/236433751-dc977e52-484c-4164-b3c9-65569c4e73c2.png)

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by yumengwang03** [comment]
<img width="793" alt="Screen Shot 2023-05-23 at 5 20 02 PM" src="https://github.com/apache/incubator-devlake/assets/9535430/d388a2a1-f0ba-422b-a54e-4c85876af8ec">

**Comment by Startrekzky** [comment]
Can we also filter out the archived repos?
