### ISSUE TITLE
[Bug][Azure DevOps] lastMergeCommit failling

### ISSUE THREAD

**Issue by mfandre** [apache/incubator-devlake#5108]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

At first pipeline run I received the follow error:
<img width="1401" alt="image" src="https://user-images.githubusercontent.com/1164677/236563141-1299f647-fa0e-4362-9938-a242ecdeaa74.png">

[logging.tar.gz](https://github.com/apache/incubator-devlake/files/11409889/logging.tar.gz)

### What do you expect to happen

The pipeline run without error.

### How to reproduce

After configure the datasource, define de first blue print and run the pipeline.

### Anything else

Tested using [v0.17.0-beta3](https://github.com/apache/incubator-devlake/releases/tag/v0.17.0-beta3)

### Version

main

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by mfandre** [comment]
Looks like the application is trying to find "lastMergeCommit" in a JSON and then failing.

`| jsonpointer.JsonPointerException: member 'lastMergeCommit' not found in`

**Comment by mfandre** [comment]
Digging it more, I think the problem are in PRs with status abandoned.

**Comment by mfandre** [comment]
This bug is blocking me to test the dev lake :(

**Comment by KlemenDanfoss** [comment]
I can confirm the same issue.

**Comment by Startrekzky** [comment]
This will be addressed in v0.17.0-beta6

**Comment by andremattosferraz** [comment]
@Startrekzky do you have the release date?

**Comment by Startrekzky** [comment]
> @Startrekzky do you have the release date?

I guess it's today.

**Comment by KlemenDanfoss** [comment]
@Startrekzky , tested the new version, the old error is gone.

But a new one is here :)

`subtask extractAzuredevopsGitpullrequests ended unexpectedly Wraps: (2) remote error response: | ERROR: DataError (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush bluck if this flush is occuring prematurely) | (MySQLdb.DataError) (1406, "Data too long for column 'description' at row 1) | [SQL: INSERT INTO _tool_azuredevops_gitpullrequests (...)]`

**Comment by klesh** [comment]
@KlemenDanfoss Sorry for your inconvenience. Can you create a new issue for that? Thanks.

@CamilleTeruel What is the data type of _tool_azuredevops_gitpullrequests.description? Looks like it is `varchar`

**Comment by KlemenDanfoss** [comment]
Hi, @klesh , #5275

**Comment by CamilleTeruel** [comment]
@klesh It was a varchar, but it has been changed to text in #5191 which was cherry-picked in v0.17.0-beta6.
