### ISSUE TITLE
[Feature][Zentao] Will  Bug/Incident Age,Bug/Incident Count per 1k Lines of Code's calculation use ZenTao's data in the future??

### ISSUE THREAD

**Issue by amosli** [apache/incubator-devlake#5125]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar feature requirement.

### Use case

As a QA engineer, our company uses zentao for bug management, and gitlab for code warehouse management. The current version (v0.17) devlake bug age is calculated by jira. Can we add data based on zentao in the future? Calculate bug age and other indicators.（such as,Bug  Age,Incident Age,Bug  Count per 1k Lines of Code,Incident Count per 1k Lines of Code）

### Description

For now,Bug  Age,Incident Age,Bug  Count per 1k Lines of Code,Incident Count per 1k Lines of Code are calculated by Jira' data.ZenTao also as a bug manegement widely used in many software compnines, Can DevLake add this feature  in the future? Thank you.

### Related issues

no

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by likyh** [comment]
There's an issue here regarding the data source for Zentao, which currently doesn't specify what bugs can be classified as incidents. Do you have any thoughts on this? @amosli
