### ISSUE TITLE
[Feature][Okta] Enable Okta Authentication in DevLake

### ISSUE THREAD

**Issue by mukteshkrmishra** [apache/incubator-devlake#5140]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar feature requirement.

### Use case

As a developer, I want Okta Authentication to be used in the Dev Lake to improve security. 

### Description

Okta client authentication needs to be integrated into the Dev Lake and later, we can also think about enabling SAML SSSO with DevLake RBAC (In turn, Grafana). 

For the current scope, we want Dev Lake to support Okta Authentication. 

cc: @MaximDub @hezyin 

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by klesh** [comment]
Nice, I currently have a PR implemented the AWS Cognito support, you may want to take a look https://github.com/apache/incubator-devlake/pull/5127

**Comment by hezyin** [comment]
A user made a potentially relevant suggestion in the Slack (oauth2-proxy supports okta): 

> Instead of implementing an entire SSO flow it would probably be easier if there was a guide made on how to use https://github.com/oauth2-proxy/oauth2-proxy as the SSO auth frontend to devlake’s UI.

**Comment by klesh** [comment]
Looks good.
@IronCore864 What do you think? should we use it instead?
