### ISSUE TITLE
[Feature][Backstage] Develop a Backstage Plugin for Apache DevLake

### ISSUE THREAD

**Issue by mukteshkrmishra** [apache/incubator-devlake#5141]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar feature requirement.

### Use case

As a developer/engineering owner/leader, I want to see the Apache Dev Lake Data summary into [Backstage](https://backstage.io/). 

### Description

- Decide what all metrics we want to surface backstage from Dev Lake (Basic metrics, grouping criteria, per service metrics, team level metrics, heatmap for comparison) also their use for individual personas (Developers/Managers/Leaders)
- Implement API endpoints in Dev Lake to support these metrics querying (push and pull)
- Write a UI plugin into Backstage to visualize the collected Metrics into Backstage from Apache Dev Lake

cc: @MaximDub  @hezyin 

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by hezyin** [comment]
Hi @mukteshkrmishra, thanks for opening this issue. I was chatting with another community member this afternoon, and he pointed me to Backstage's Grafana plugin: https://github.com/K-Phoen/backstage-plugin-grafana. Do you think you could take a look and see if that's an acceptable solution for you?

**Comment by Marco-De-Stefani** [comment]
Hey @hezyin, I'm not sure if this is the proper time to focus on writing a plugin for backstage, but I'm using the Grafana plugin for something else and it's definitely not a permanent solution. 
Basically, with that, you can only list the graphs or embed them using iframe, which has a lot of drawbacks.

**Comment by jmbowman** [comment]
I haven't tried it yet, but I stumbled across https://github.com/DevoteamNL/opendora which may provide at least part of what's wanted from this.  It's listed on https://backstage.io/plugins/ as "OpenDORA".
