### ISSUE TITLE
[Bug][Azure DevOps] (MySQLdb.DataError) (1406, "Data too long for column 'description' at row 1")

### ISSUE THREAD

**Issue by alexvaccaro** [apache/incubator-devlake#5151]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

Setup a blueprint using an Azure DevOps connection
Running the blueprint gives an error when running Azure DevOps tasks:

![image](https://github.com/apache/incubator-devlake/assets/3834213/7350c1bf-45f6-42a7-ad51-b94d0733ca16)

Log files:
[logging.zip](https://github.com/apache/incubator-devlake/files/11443862/logging.zip)

### What do you expect to happen

The blueprint to complete without errors

### How to reproduce

So far I tried 4 different Azure DevOps projects and all fail with the same error, see log attached

### Anything else

Every time I run a blueprint

### Version

main

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Startrekzky** [comment]
Hi @CamilleTeruel , any updates for this bug?

**Comment by CamilleTeruel** [comment]
> Hi @CamilleTeruel , any updates for this bug?

@Startrekzky #5191
