### ISSUE TITLE
[Question][devlake-config-ui] When using external RDS dB, started seeing warnings related Question title

### ISSUE THREAD

**Issue by rs287** [apache/incubator-devlake#5152]
## Question
When using external RDS dB on AWS, we started seeing these warnings and on config UI, we received this message
## Screenshots
![image](https://github.com/apache/incubator-devlake/assets/124353455/9b7e4275-994f-4328-bee5-3875bd129f48)
![image](https://github.com/apache/incubator-devlake/assets/124353455/3c4d1010-12b2-4aa9-b0d2-2da52defe375)

If applicable, add screenshots to help explain.
How to solve this problem?  Does it relate to MySQL version on RDS as compared to one comes in helm chart image?

5.7.mysql is the version using on external dB.

**Comment by hezyin** [comment]
Hi @rs287, were you upgrading from a previous version of DevLake? This is normal when an upgrade requires data migration, try clicking "Proceed to Database Migration" and see if it resolves the issue for you.

However, I do believe DevLake requires MySQL > 8.0, that may also be the cause of the issue.

**Comment by rs287** [comment]
When I click on "Proceed to Database Migration", it returns an error as "Operation Failed". However, your second tip related to MySQL version, I give a try to that and install higher  MySQL version. I let you know.

**Comment by rs287** [comment]
I confirm after MySQL version upgrade to 8.0, problem was solved.  Thanks for your input
