### ISSUE TITLE
Multi-data connections support for Gitlab

### ISSUE THREAD

**Issue by Startrekzky** [apache/incubator-devlake#636]
## Description
An EE user Qianxin wants to import data from multiple Gitlab repos as the user has multiple keys and EE cannot support it for now.
@leglars suggested using Dev Lake instead of EE to achieve this goal in the future.

## Describe the solution you'd like
--

## Has the Feature been Requested Before?
--

## Describe alternatives you've considered
--

**Comment by klesh** [comment]
We can start working on it due to #455 has been finalized

**Comment by warren830** [comment]
Plan of Attack
1. update gitlab/api/connection to load and save through db not .env
2. update all entities with new field `connection_id`
3. update all tasks

**Comment by klesh** [comment]
I think the most important part, is to update every single Tool Layer Entities to include this very basic field...
And refactor all converter, to include "connectionId" as part of is `id`
Check JIRA implementation, you will see... it's very, very, huge change...

**Comment by warren830** [comment]
closed by #2260
