### ISSUE TITLE
Config-UI: README Update(s) `npm i` references to `npm ci`

### ISSUE THREAD

**Issue by e2corporation** [apache/incubator-devlake#904]
## Documentation Scope
Update our documentation to prefer "npm ci" install method (continuous integration) that will prioritize the `package-lock.json` file deps first when installing dependencies.

**Comment by e2corporation** [comment]
See notes to amend from @hezyin 
> Maybe this is what we should say: use `npm install` if you add a dep to package.json otherwise use `npm ci` to directly install from package-lock.json to ensure consistency

**Comment by klesh** [comment]
@e2corporation Please update the progress

**Comment by Startrekzky** [comment]
Does the issue still exist?

**Comment by klesh** [comment]
Staled issue, feel free to re-open if any new development
