### ISSUE TITLE
Grafana Chart: "Commit Count by Author" change

### ISSUE THREAD

**Issue by kevin-kline** [apache/incubator-devlake#933]
## Description
The final column of "Commit Count by Author" shows the percentage change in commits between **this month** and **last month**. This number seems to be not that helpful because the comparison is not even. For example, **last month** the author might have 30 commits. At the start of **this month** the author may have 0 commits. Then the change of commits in the two months looks really out of balance.

![image](https://user-images.githubusercontent.com/27032263/144615250-1ad6e196-682e-44a6-981c-6143997ba4b7.png)

## Describe the solution you'd like
I think the solution is to compare the **last month** with the **month before last**

## Has the Feature been Requested Before?
No.

## Additional Context
This observation made with @joncodo

**Comment by Startrekzky** [comment]
I'll take it.

**Comment by Startrekzky** [comment]
This has been fixed in https://github.com/apache/incubator-devlake/pull/2590
