### ISSUE TITLE
Extract file-level data from git repository

### ISSUE THREAD

**Issue by Startrekzky** [apache/incubator-devlake#953]
## User story
As a tech lead, I want to see the bug distribution in low-level components (from code files), as a guide for the future framework evolution.

## Goal
The key is to match `bug` to `component`. 
- If we want to find the overall distribution of all bugs, we can do: `issues(bug)` join `prs` join `commits` join `commit_files(component)`;
- If we want to find the overall distribution of bugs fixed in a specific tag, we can do: `ref_diff_issues(bug)` join `prs` join `commits` join `commit_files(component)`;

## Proposed Solution
- [ ] Add a `commit_files` table in the domain layer
    | field                         | type       | length    | description | key  |                                                                                                                                              
    | -------------          | -------- | -------- | ----------- | -----|
    | `commit_sha`        | char       | 40          |                     | FK    |
    | `file_name`            |  varchar | 255        |                     |         |
    | `status`                  |  varchar | 255        |                     |         |
    | `additions`             |  int         |                |                     |         |
    | `deletions`             |  int         |                |                     |         |
    | `changes`              |  int         |                |                     |         |
    | `file_component`  |  varchar | 255        |                     |         |
    
    a. all the columns except `file_component` can be retrieved from [gitExtractor](https://github.com/apache/incubator-devlake/tree/main/plugins/refdiff). **Note: not from [Github API](https://docs.github.com/en/rest/commits/commits#get-a-commit) or Gitlab API.**
    b. how to assign `file_component` value to a commit file? It varies in different programming languages. 
          - In Go, a component can be found by folder names; 
          - while in other languages, it might need user input to define the `file_component`.

- [ ] Allow users to define the `file_component` in `.env` by REGEX

## An example of commit files
For instance, this [commit](https://github.com/apache/incubator-devlake/pull/2039/commits/aeec784efc4c21e9e92a414e3008987cb7f791fa) touches 4 files:
![image](https://user-images.githubusercontent.com/14050754/171377048-59230b96-be40-4168-93d4-775bf9b33a7a.png)

## Belongs to issue
This is a sub-issue of both #949 and #1771

## Additional context
N/A

**Comment by klesh** [comment]
@Startrekzky @hezyin Seems like this one is related to #1771

**Comment by klesh** [comment]
@xgdyp Would you like to take a look at this?

**Comment by xgdyp** [comment]
I see #1771 and it's awesome!

**Comment by Startrekzky** [comment]
> The table commit_files has already exists in domain layer the DDL is
> 
> ```
>     created_at       datetime(3)     null,
>     updated_at       datetime(3)     null,
>     _raw_data_params varchar(255)    null,
>     _raw_data_table  varchar(255)    null,
>     _raw_data_id     bigint unsigned null,
>     _raw_data_remark longtext        null,
>     commit_sha       varchar(40)     not null,
>     file_path        varchar(255)    not null,
>     additions        bigint          null,
>     deletions        bigint          null,
>     primary key (commit_sha, file_path)
> ```
> 
> and this contains changed-files path. So I think we just use GitHub-api and no need to use git-extractor. I think what we need to do is just reconstruct this table by adding a column `file_component` or by creating a new table with a map of `file_path` and `file_component`? This can be finished by parsing the path,I think.
> 
> Is that right?@klesh

Yes. It does exist, just modify it as we're not using it now.
Can you create an attack of plan for 'file_component' value assignment?

**Comment by Startrekzky** [comment]
> I see #1771 and it's awesome!

That's the detailed info for O

> The table commit_files has already exists in domain layer the DDL is
> 
> ```
>     created_at       datetime(3)     null,
>     updated_at       datetime(3)     null,
>     _raw_data_params varchar(255)    null,
>     _raw_data_table  varchar(255)    null,
>     _raw_data_id     bigint unsigned null,
>     _raw_data_remark longtext        null,
>     commit_sha       varchar(40)     not null,
>     file_path        varchar(255)    not null,
>     additions        bigint          null,
>     deletions        bigint          null,
>     primary key (commit_sha, file_path)
> ```
> 
> and this contains changed-files path. So I think we just use GitHub-api and no need to use git-extractor. I think what we need to do is just reconstruct this table by adding a column `file_component` or by creating a new table with a map of `file_path` and `file_component`? This can be finished by parsing the path,I think.
> 
> Is that right?@klesh

1. "So I think we just use GitHub-api and no need to use git-extractor."
I think we should retrieve from [gitExtractor](https://github.com/apache/incubator-devlake/tree/main/plugins/refdiff), rather than from [Github API](https://docs.github.com/en/rest/commits/commits#get-a-commit) or Gitlab API due to API rate limit restrictions.
2. "I think what we need to do is just reconstruct this table by adding a column file_component or by creating a new table with a map of file_path and file_component? "
I think this approach works, then we might have another table called 'file_components'. What do you think? @klesh

**Comment by xgdyp** [comment]
I see. So the main steps:
1. extract the data using gitextractor
2. for each file of git commits, process the data using some functions to get the fields of the `commits_files` table
3. meanwhile, calculate the filed `file_components` by parsing the `file_path` field. (in lake, what we need to do is parse its first-level-directory , for some other projects we need to define the rule of components manually)
4. store the results into `commits_files` table which add a new column `components`

**Comment by klesh** [comment]
@xgdyp Excellent explanation!
But, lately,we found some factors that need to be taken into account:
1. `component` is a vague concept, it is, in most cases, a directory, but not necessarily located at the root directory of the repo.
2. `component` might consist of several directories located in different paths of the repo.
All of the above is true for `DevLake` itself like we would say `api` `services` from the root directory belongs to `server` component.
So, I would suggest we modify the step 3 to:
1. create a table `component(name, path_regex)`. User would enter records like `('server', '^(api/services)/')`
2. set `commit_files.component` to `component.name` whenever `path_regex` matched
3. if multiple `compnents` matched, we produce a comma-seperated value for `commit_files.component`, and user should update the `path_regex` and re-run the task to correct the error, because it makes no sense for a file belonging to multiple components.

**Comment by xgdyp** [comment]
OK,I understand

**Comment by xgdyp** [comment]
OK, I understand.
